'use client';
import {defensiveHref} from '@/lib/soc-expansion-ui';
import LoadingState from '@/components/loading-state';
import SocFilters from '@/components/soc-filters';
import {useEffect,useMemo,useState} from 'react';
import {Activity,ArrowLeft,ShieldCheck,FileWarning,FolderOpen} from 'lucide-react';
import {useProgress} from '@/app/shell';
type Alert={id:string;title:string;severity:string;timestamp:string;user:string;host:string;sourceIp:string;type:string;summary:string;status:string;closedAt:string|null;score:number;bestScore:number;caseId:string|null};
type Queue={alerts:Alert[];cases:{id:string;title:string;severity:string;status:string;updatedAt:string}[];stats:{newAlerts:number;activeCases:number;closedAlerts:number;totalAlerts:number;progress:number}};
const severityLabels:Record<string,string>={Low:'منخفض',Medium:'متوسط',High:'عالٍ',Critical:'حرج'};
const statusLabels:Record<string,string>={New:'جديد',Investigating:'قيد التحقيق',Escalated:'مصعّد',Resolved:'محلول','False Positive':'إنذار كاذب'};
const date=(stamp:string)=>new Date(stamp).toLocaleString('ar-SA',{dateStyle:'short',timeStyle:'short'});
export default function SocConsole(){
 const {user}=useProgress(),[queue,setQueue]=useState<Queue|null>(null),[loading,setLoading]=useState(!!user),[error,setError]=useState(''),[search,setSearch]=useState(''),[severity,setSeverity]=useState('all'),[status,setStatus]=useState('all'),[type,setType]=useState('all'),[loadedFor,setLoadedFor]=useState('');
 const account=user?.email||'guest';
 useEffect(()=>{if(!user)return;let active=true;fetch('/api/soc',{cache:'no-store'}).then(async r=>{const d=await r.json() as Queue&{error?:string};if(!r.ok)throw Error(d.error||'تعذر تحميل SOC.');if(active){setQueue(d);setError('')}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'تعذر التحميل.')}).finally(()=>{if(active){setLoadedFor(account);setLoading(false)}});return()=>{active=false}},[user,account]);
 const nextAlert=queue&&(queue.alerts.find(a=>a.status==='Investigating')||queue.alerts.find(a=>a.status==='New')||queue.alerts[0]);
 const hasFilters=!!search||severity!=='all'||status!=='all'||type!=='all';
 const types=queue?[...new Set(queue.alerts.map(a=>a.type))]:[];
 const filtered=useMemo(()=>queue?.alerts.filter(a=>(severity==='all'||a.severity===severity)&&(status==='all'||a.status===status)&&(type==='all'||a.type===type)&&(!search||[a.id,a.title,a.user,a.host,a.sourceIp,a.type].join(' ').toLowerCase().includes(search.toLowerCase().trim()))).sort((a,b)=>(['Critical','High','Medium','Low'].indexOf(a.severity)-['Critical','High','Medium','Low'].indexOf(b.severity))||b.timestamp.localeCompare(a.timestamp))||[],[queue,search,severity,status,type]);
 return <div className="reading-width soc-page"><div className="soc-intro"><span className="eyebrow"><Activity size={15}/> عمليات NexaCorp</span><h1>تنبيهات SOC</h1><p>افحص التنبيه، اجمع الأدلة، ثم حدد الاستجابة.</p></div>
 {!user?<section className="panel"><h2>ادخل نوبة SOC التدريبية</h2><p>سجّل الدخول لحفظ التحقيقات وملاحظاتك وقضاياك في حسابك.</p><a className="primary-button" href="/signin-with-chatgpt?return_to=%2Fsoc" target="_top">تسجيل الدخول</a></section>:loading||loadedFor!==account?<LoadingState>جارٍ استعادة قائمة التنبيهات…</LoadingState>:error?<div role="alert" className="error"><p>{error}</p><button className="secondary-button" onClick={()=>location.reload()}>إعادة المحاولة</button></div>:queue&&<>
 {nextAlert&&<section className="panel guided-focus"><div><span className="eyebrow">خطوتك في النوبة</span><h2>{queue.alerts.find(a=>a.status==='Investigating')?'أكمل تحقيقًا بدأته':'افحص تنبيهًا تدريبيًا'}</h2><p>ابدأ بالأدلة المتاحة قبل اتخاذ القرار.</p></div><a className="primary-button" href={defensiveHref(nextAlert.id)}>افتح التنبيه</a></section>}<details className="guided-disclosure"><summary>ملخص النوبة</summary><section className="soc-metrics" aria-label="ملخص نوبة SOC"><div><small>NEW TRAINING ALERTS</small><strong>{queue.stats.newAlerts}</strong><span>تحتاج فرزًا</span></div><div><small>ACTIVE CASES</small><strong>{queue.stats.activeCases}</strong><span>تحقيقات مترابطة</span></div><div><small>SOC PROGRESS</small><strong>{queue.stats.progress}%</strong><span>{queue.stats.closedAlerts} من {queue.stats.totalAlerts} تنبيهات أُغلقت</span></div></section></details>
 <section className="panel soc-queue-panel"><div className="soc-section-head"><div><span className="eyebrow">قائمة العمل</span><h2>قائمة التنبيهات</h2></div><span>{filtered.length} نتيجة</span></div><SocFilters search={search} severity={severity} status={status} type={type} types={types} severityLabels={severityLabels} statusLabels={statusLabels} onSearch={setSearch} onSeverity={setSeverity} onStatus={setStatus} onType={setType}/>{hasFilters&&<div className="soc-filter-actions"><span role="status">المرشحات مطبّقة · {filtered.length} نتيجة</span><button type="button" className="secondary-button" onClick={()=>{setSearch('');setSeverity('all');setStatus('all');setType('all')}}>مسح المرشحات</button></div>}

 <div className="soc-table-head" aria-hidden="true"><span>التنبيه</span><span>الخطورة</span><span>المستخدم / الجهاز</span><span>الوقت</span><span>الحالة</span><span/></div><div className="soc-alert-list">{filtered.map(a=><a className="soc-alert-row" href={defensiveHref(a.id)} key={a.id}><span className="soc-alert-identity"><small>{a.id} · {a.type}</small><strong>{a.title}</strong><em>{a.summary}</em></span><span className={'soc-severity '+a.severity.toLowerCase()}>{severityLabels[a.severity]}</span><span className="soc-entity"><b>{a.user}</b><small>{a.host} · <span dir="ltr">{a.sourceIp}</span></small></span><time>{date(a.timestamp)}</time><span className={'soc-status '+a.status.toLowerCase().replace(' ','-')}>{statusLabels[a.status]}</span><ArrowLeft size={17}/></a>)}{!filtered.length&&<div className="soc-empty">لا توجد تنبيهات تطابق هذه المرشحات. غيّر البحث أو المرشح.</div>}</div></section>
 <details className="guided-disclosure"><summary>القضايا المرتبطة · {queue.cases.length}</summary><section className="panel soc-cases-panel"><div className="soc-section-head"><div><span className="eyebrow"><FolderOpen size={14}/> CASE MANAGEMENT</span><h2>القضايا المرتبطة</h2></div><span>{queue.cases.length} قضية</span></div>{queue.cases.length?<div className="soc-case-grid">{queue.cases.map(c=><a href={'/soc/cases/'+c.id} key={c.id}><span className={'soc-severity '+c.severity.toLowerCase()}>{severityLabels[c.severity]}</span><strong>{c.title}</strong><small>{c.status==='Resolved'?'مغلقة':'قيد التحقيق'} · آخر تحديث {date(c.updatedAt)}</small><ArrowLeft size={18}/></a>)}</div>:<div className="soc-empty"><FileWarning size={25}/><p>لا توجد قضية بعد. سيُنشئ التحقيق في تنبيه حقيقي قضية عند إغلاقه، ويمكن ربط تنبيهات أخرى بها.</p></div>}</section></details>
 <div className="safe-banner"><ShieldCheck size={20}/><p>لا تتصل أدوات SOC بأي أجهزة أو عناوين خارجية؛ جميع النتائج ثابتة ومحاكاة ومخصصة للتعلم.</p></div>
 </>}</div>
}
