'use client';
import {useEffect,useState} from 'react';
import {CoreFrame,Knowledge,useSavedCase,useCoreDraft,useCoreStep,CaseAccess} from '@/app/experience/core-ui';
import {CompletionProgressSummary} from '@/app/progression/view';
import {useProgress} from '@/app/shell';
import {defensivePhases,responsePlans,type DefensivePhase} from '@/lib/soc-expansion-ui';
import {relationshipLabels,relationshipTypes} from '@/lib/investigation-relationships';
import type {BoardDecision,RelationshipType} from '@/lib/investigation-board';
import type {readSocAlert} from '@/lib/soc-storage';
import type {readInvestigation} from '@/lib/investigation-storage';
const priorities=[['Low','منخفض'],['Medium','متوسط'],['High','عالٍ'],['Critical','حرج']];
const initial={priority:'',reason:'',field:'',from:'',relation:'RELATED_TO' as RelationshipType,to:'',linkReason:'',hypothesis:'',affected:[] as string[],proof:[] as string[],plan:'',checks:[] as string[],verification:'',next:''};
const toggle=(values:string[],id:string)=>values.includes(id)?values.filter(v=>v!==id):[...values,id];
export default function DefensiveWorkspace({id}:{id:string}){
 const api=useSavedCase<Awaited<ReturnType<typeof readSocAlert>>>('/api/soc/alerts/'+id),locker=useSavedCase<Awaited<ReturnType<typeof readInvestigation>>>('/api/investigations/soc-'+id),{refresh}=useProgress();
 const [draft,setDraft]=useCoreDraft('defensive-'+id,initial),[notice,setNotice]=useState('');
 const saved=api.data?.state?.session.defensive,closed=!!api.data?.state?.closedAt;
 const recover=(wanted:DefensivePhase):DefensivePhase=>closed?'result':!saved?'brief':saved.phase==='evidence'&&['evidence','correlate','assess'].includes(wanted)?wanted:saved.phase;
 const [step,setStep]=useCoreStep('/soc/alerts/'+id,defensivePhases,api.ready,recover);
 const title=id==='SOC-004'?'نشاط غير معتاد على خادم التطبيق':'مهمة مجدولة تحتاج تحققًا';
 const returnTo='/soc/alerts/'+id+'?view=defensive&step='+step;
 useEffect(()=>{if(saved?.feedback)setNotice(saved.feedback)},[saved?.feedback]);
 if(!api.ready||!api.user||!api.data)return <CoreFrame title={title}><CaseAccess ready={api.ready} user={api.user} href={returnTo} error={api.error}/></CoreFrame>;
 if(!api.data.defensiveUnlocked)return <CoreFrame title={title}><section className="pilot-stage"><span className="pilot-kicker">تدريب الاستجابة · مقفل</span><h1>{title}</h1><p>تحتاج هذه القضية ربط الأدلة والتحقق من أثر الاستجابة.</p><p>المتبقي: أكمل تحقيق جلسة ليلى بقرار صحيح.</p><a className="primary-button" href="/soc/alerts/SOC-002?view=guided">افتح تحقيق جلسة ليلى</a></section></CoreFrame>;
 const state=api.data.state,board=locker.data?.board,collected=locker.data?.evidence.filter(e=>e.collectedAt).map(e=>e.evidenceId)||[],links=locker.data?.links||[];
 const selected=board?.evidence.find(e=>e.id===draft.field),reviewed=!!locker.data?.evidence.some(e=>e.evidenceId===draft.field&&e.reviewedAt),busy=api.busy||locker.busy;
 const allProof=board?.evidence.filter(e=>collected.includes(e.id))||[];
 const observations=api.data.responseObservations||[];
 async function send(input:Record<string,unknown>){const data=await api.post(input);if(data){setNotice(data.state?.session.defensive?.feedback||'');if(data.state?.session.defensive)setStep(data.state.session.defensive.phase);if(data.state?.closedAt){await locker.reload();await refresh();setStep('result')}}return data;}
 async function begin(){if(await api.post({action:'start'}))await send({action:'defensive'});}
 const set=(values:Partial<typeof initial>)=>setDraft(d=>({...d,...values}));
 return <CoreFrame title={title} error={api.error||locker.error}><nav className="defensive-phase" aria-label="مرحلة التحقيق"><span>تنبيه</span><span>←</span><strong>{({brief:'التكليف',triage:'الفرز',evidence:'الأدلة',correlate:'الربط',assess:'التقييم',respond:'الاستجابة',verify:'التحقق',report:'التقرير',result:'النتيجة'})[step]}</strong></nav>
 {step==='brief'&&<section className="pilot-stage"><span className="pilot-kicker">تنبيه NexaCorp · <bdi>{id}</bdi></span><h1>{title}</h1><p className="pilot-lead">{id==='SOC-004'?'رُصد تشغيل غير معتاد على APP-02. حدّد نطاقه قبل اختيار الاستجابة.':'شُغلت مهمة على APP-01 خارج الدوام. هل هو نشاط مشروع أم حادث؟'}</p><dl className="defensive-facts"><div><dt>الأصل</dt><dd><bdi>{api.data.alert.host}</bdi></dd></div><div><dt>الهوية في السجل</dt><dd><bdi>{api.data.alert.user}</bdi></dd></div></dl><button className="primary-button" disabled={busy} onClick={()=>void begin()}>ابدأ فرز التنبيه</button></section>}
 {step==='triage'&&<section className="pilot-stage"><h1>ما أولوية الفحص؟</h1><p>{id==='SOC-004'?'تنبيه على خادم التطبيق يرتبط بعملية وجلسة غير معتادتين.':'تنبيه مهمة مجدولة؛ لم يثبت نشاط ضار بعد.'}</p><form onSubmit={e=>{e.preventDefault();void send({action:'triage',priority:draft.priority,reason:draft.reason})}}><label>الأولوية<select value={draft.priority} onChange={e=>set({priority:e.target.value})} required><option value="">اختر الأولوية</option>{priorities.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>سبب موجز<textarea value={draft.reason} onChange={e=>set({reason:e.target.value})} minLength={12} maxLength={500} required/></label><button className="primary-button" disabled={busy}>احفظ الفرز وافحص الأدلة</button></form></section>}
 {step==='evidence'&&<section className="pilot-stage"><h1>افحص أكثر من مصدر</h1><p>اربط ما حدث بالأصل والتوقيت؛ لا يكفي اسم ملف أو وقت تشغيل وحده.</p>{notice&&<p className="pilot-feedback" role="status">{notice}</p>}<label>مصدر الفحص<select value={draft.field} onChange={e=>set({field:e.target.value})}><option value="">اختر دليلًا</option>{board?.evidence.map(e=><option value={e.id} key={e.id}>{e.title}{collected.includes(e.id)?' · جُمع':''}</option>)}</select></label>
 {selected&&reviewed&&<article className="defensive-artifact"><small><bdi>{selected.source}</bdi> · <bdi>{selected.timestamp}</bdi></small><h2>{selected.title}</h2><pre dir="ltr">{selected.raw}</pre>{['flow','socket','process','hash','task','network'].includes(selected.id)&&<Knowledge title={selected.id==='hash'?'ماذا يثبت حجر الملف؟':id==='SOC-004'?'كيف تربط تدفقًا بعملية؟':selected.id==='task'?'هل التوقيع وحده يكفي؟':'ماذا تثبت الوجهة؟'} text={selected.id==='hash'?'الحجر يقيّد الملف المحدد؛ لا يثبت انتهاء جلسة الحساب أو توقف كل اتصال. افحص آثار النشاط أيضًا.':id==='SOC-004'?'قارِن الجهاز والتوقيت بمالك الاتصال في سجل العملية. حجم التدفق لا يكشف محتواه.':selected.id==='task'?'التوقيع يثبت هوية الملف، لكنه لا يثبت أن التشغيل مصرح به. قارِنه بالتغيير والوجهة.':'الوجهة الداخلية لا تثبت المشروعية وحدها. قارِنها بالخدمة المعتمدة وسجل التنفيذ.'} lessonId={selected.id==='hash'?'security-11':selected.id==='task'||selected.id==='process'||selected.id==='socket'?'soc-3':'soc-2'} returnTo={returnTo}/>}</article>}
 {selected&&!reviewed?<button className="primary-button" disabled={busy} onClick={()=>void locker.post({action:'review',evidenceId:selected.id})}>افحص المصدر</button>:selected&&!collected.includes(selected.id)?<button className="primary-button" disabled={busy} onClick={()=>void locker.post({action:'collect',evidenceId:selected.id})}>اجمع الدليل في الخزانة</button>:<button className="primary-button" disabled={busy||collected.length<3||!state?.session.usedTools.length} onClick={()=>setStep('correlate')}>اربط القرائن</button>}
 <p className="defensive-count">الأدلة المجموعة: {collected.length} · {state?.session.usedTools.length? 'أداة الفحص مستخدمة':'استخدم أداة فحص قبل التقييم'}</p><details className="pilot-secondary"><summary>أدوات الفحص المحاكاة</summary>{api.data.alert.tools.map(tool=><div key={tool.id}><button className="secondary-button" disabled={busy} onClick={()=>void api.post({action:'tool',toolId:tool.id})}>{tool.label}</button>{state?.session.transcript.filter(t=>t.toolId===tool.id).slice(-1).map((t,i)=><pre key={i} dir="ltr">{t.output}</pre>)}</div>)}</details></section>}
 {step==='correlate'&&<section className="pilot-stage"><h1>اربط الكيانات بدليل</h1><p>كل علاقة تحتاج سببًا من مصدر فحصته. اربط الهوية أو العملية بالأصل والوجهة أو سجل التغيير.</p><form onSubmit={async e=>{e.preventDefault();if(await locker.post({action:'link',fromId:draft.from,relation:draft.relation,toId:draft.to,reason:draft.linkReason}))set({linkReason:''})}}><div className="defensive-link-fields"><label>من<select dir={draft.from&&board?.nodes.find(n=>n.id===draft.from)?.kind!=='employee'?'ltr':'rtl'} value={draft.from} onChange={e=>set({from:e.target.value})} required><option value="">اختر كيانًا</option>{board?.nodes.filter(n=>!n.id.startsWith('evidence:')||collected.includes(n.id.slice(9))).map(n=><option value={n.id} key={n.id}>{n.label}</option>)}</select></label><label>العلاقة<select value={draft.relation} onChange={e=>set({relation:e.target.value as RelationshipType})}>{relationshipTypes.map(r=><option key={r} value={r}>{relationshipLabels[r]} · {r}</option>)}</select></label><label>إلى<select dir={draft.to&&board?.nodes.find(n=>n.id===draft.to)?.kind!=='employee'?'ltr':'rtl'} value={draft.to} onChange={e=>set({to:e.target.value})} required><option value="">اختر كيانًا أو دليلًا</option>{board?.nodes.filter(n=>!n.id.startsWith('evidence:')||collected.includes(n.id.slice(9))).map(n=><option value={n.id} key={n.id}>{n.label}</option>)}</select></label></div><label>ما الذي يثبت العلاقة؟<input value={draft.linkReason} onChange={e=>set({linkReason:e.target.value})} minLength={8} maxLength={400} required/></label><button className={links.length>=3?'secondary-button':'primary-button'} disabled={busy}>احفظ العلاقة</button></form><ul className="defensive-links">{links.map(l=><li key={l.fromId+l.relation+l.toId}><bdi>{board?.nodes.find(n=>n.id===l.fromId)?.label}</bdi> ← {relationshipLabels[l.relation]} ← <bdi>{board?.nodes.find(n=>n.id===l.toId)?.label}</bdi><small>{l.reason}</small><button className="email-secondary-link" disabled={busy} onClick={()=>void locker.post({action:'unlink',fromId:l.fromId,toId:l.toId,relation:l.relation})}>إزالة العلاقة</button></li>)}</ul>{links.length>=3&&<button className="primary-button" onClick={()=>setStep('assess')}>قيّم ما تثبته الأدلة</button>}<button className="email-secondary-link" onClick={()=>setStep('evidence')}>العودة إلى الأدلة</button></section>}
 {step==='assess'&&<section className="pilot-stage"><h1>ما الذي ثبت؟</h1><form onSubmit={e=>{e.preventDefault();const action=id==='SOC-004'?'contain':'dismiss';void send({action:'assess',decision:{hypothesis:draft.hypothesis,affected:draft.affected,evidenceIds:draft.proof,action} satisfies BoardDecision})}}><label>الاستنتاج<select value={draft.hypothesis} required onChange={e=>set({hypothesis:e.target.value})}><option value="">اختر فرضية</option>{board?.hypotheses.map(h=><option key={h.id} value={h.id}>{h.label}</option>)}</select></label><fieldset><legend>نطاق التقييم</legend>{board?.nodes.filter(n=>n.kind==='account'||n.kind==='server').map(n=><label className="defensive-choice" key={n.id}><input type="checkbox" checked={draft.affected.includes(n.id)} onChange={()=>set({affected:toggle(draft.affected,n.id)})}/><bdi>{n.label}</bdi></label>)}</fieldset><fieldset><legend>الأدلة التي تسند الاستنتاج</legend>{allProof.map(e=><label className="defensive-choice" key={e.id}><input type="checkbox" checked={draft.proof.includes(e.id)} onChange={()=>set({proof:toggle(draft.proof,e.id)})}/>{e.title}</label>)}</fieldset><button className="primary-button" disabled={busy}>اختبر الاستنتاج</button></form><button className="email-secondary-link" onClick={()=>setStep('correlate')}>راجع الروابط</button></section>}
 {step==='respond'&&<section className="pilot-stage"><h1>اختر نطاق الاستجابة</h1>{notice&&<p className="pilot-feedback" role="status">{notice}</p>}<p>الإجراء يغيّر حالة المحاكاة؛ افحص أثره قبل الإغلاق.</p><label>خطة الاستجابة<select value={draft.plan} onChange={e=>set({plan:e.target.value})}><option value="">اختر الإجراء</option>{responsePlans.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><Knowledge title="ماذا يجب حفظه قبل الاستجابة؟" text="احفظ السجلات ومراجع الأدلة. إيقاف التنبيه لا يثبت توقف النشاط؛ تحقّق من الحساب والشبكة أو الخدمة بعد الإجراء." lessonId="security-11" returnTo={returnTo}/><button className="primary-button" disabled={busy||!draft.plan} onClick={()=>{set({checks:[],verification:''});void send({action:'response-test',plan:draft.plan})}}>نفّذ الاستجابة في المحاكاة</button></section>}
 {step==='verify'&&<section className="pilot-stage"><h1>هل حققت الاستجابة هدفها؟</h1><p>افحص نتيجتين مستقلتين، ثم قرر إن كان الإجراء كافيًا ضمن نافذة الرصد.</p>{observations.map(o=><details className="pilot-secondary" key={o.id} onToggle={e=>{if(e.currentTarget.open)setDraft(d=>({...d,checks:d.checks.includes(o.id)?d.checks:[...d.checks,o.id]}))}}><summary>{o.label}</summary><pre dir="ltr">{o.raw}</pre></details>)}<label>نتيجة التحقق<select value={draft.verification} onChange={e=>set({verification:e.target.value})}><option value="">اختر النتيجة</option><option value="effective">الاستجابة متناسبة ونجحت ضمن نافذة الرصد</option><option value="incomplete">الاستجابة غير كافية أو عطلت نشاطًا مشروعًا</option></select></label><button className="primary-button" disabled={busy||draft.checks.length<2||!draft.verification} onClick={()=>void send({action:'verify',checks:draft.checks,verification:draft.verification})}>تحقق من أثر الإجراء</button></section>}
 {step==='report'&&<section className="pilot-stage"><h1>خلاصة الحادث</h1><div className="pilot-summary"><p><strong>التصنيف:</strong> {id==='SOC-004'?'حادث مثبت · True Positive':'إنذار كاذب · False Positive'}</p><p><strong>ما ثبت:</strong> {state?.session.conclusion}</p><p><strong>الإجراء:</strong> {responsePlans.find(p=>p.id===saved?.plan)?.label}</p><p><strong>التحقق:</strong> فُحصت نتيجتان؛ الاستجابة ناجحة ضمن نافذة الرصد.</p><p><strong>مصادر القرار:</strong> {board?.evidence.filter(e=>saved?.assessment?.evidenceIds.includes(e.id)).map(e=>e.title).join('، ')}</p></div><label>الخطوة التالية<select value={draft.next} onChange={e=>set({next:e.target.value})}><option value="">اختر متابعة مناسبة</option><option value="follow-up">متابعة السبب الجذري قبل إعادة الخدمة</option><option value="baseline">إبقاء المراقبة ومراجعة التشغيل التالي</option></select></label><button className="primary-button" disabled={busy||!draft.next} onClick={async()=>{if(await api.post({action:'report',reportNext:draft.next}))await send({action:'close'})}}>احفظ التقرير وأغلق التحقيق</button></section>}
 {step==='result'&&<section className="pilot-stage pilot-result"><span className="pilot-kicker">التحقيق محفوظ</span><h1>{saved?.verified?(id==='SOC-004'?'احتواء موثّق يحتاج متابعة':'إنذار كاذب أُغلق دون تعطيل العمل'):'نتيجتك السابقة محفوظة'}</h1><p>{saved?.verified?state?.session.conclusion:'بقيت نتيجتك القديمة ومكافأتها كما هي. لم يُسجل تحقق جديد من الاستجابة.'}</p><CompletionProgressSummary achievementId="soc-response"/><details className="pilot-secondary"><summary>ملخص القرار والتحقق</summary><p>{state?.session.caseNote?.assessment}</p><p>{state?.session.caseNote?.nextStep}</p>{saved?.verified&&observations.map(o=><pre dir="ltr" key={o.id}>{o.raw}</pre>)}<p>{api.data.skillAwarded?'مكافأة المهارات مسجلة مرة واحدة لهذا التنبيه.':'لا تمنح اللوحة XP إضافيًا.'}</p></details><a className="primary-button" href={id==='SOC-004'?'/soc/alerts/SOC-010?view=defensive':'/progress'}>{id==='SOC-004'?'افحص تنبيه المهمة المجدولة':'راجع تقدمك وهدفك التالي'}</a><details className="pilot-secondary"><summary>مراجعة التحقيق</summary><button className="secondary-button" disabled={busy} onClick={async()=>{if(await api.post({action:'reopen'})){if(locker.data?.workspace.status!=='open')await locker.post({action:'reopen'});await locker.reload();await send({action:'defensive'});set({checks:[],verification:'',next:''})}}}>أعد التحقيق دون مكافأة مكررة</button><a href={'/soc/alerts/'+id+'?view=classic'}>العرض الكامل للتنبيه</a></details></section>}
 </CoreFrame>;
}
