'use client';
import {CompletionProgressSummary} from '@/app/progression/view';
import {useState} from 'react';
import ActivityBrief from '@/components/activity-brief';
import ProgressiveHints from '@/components/progressive-hints';
import type {ResponseAction,Verdict,Severity} from '@/lib/soc-alerts';
import {coreJourney,socSteps} from '@/lib/mission-first-core';
import {CoreFrame,CaseAccess,Knowledge,useCoreDraft,useCoreStep,useSavedCase} from '@/app/experience/core-ui';
import type {CoreBoardData,CoreSocData} from '@/app/experience/core-types';
const initial={field:'',tool:'',priority:'',triageReason:'',verdict:'',conclusion:'',response:'',responseReason:'',observation:'',assessment:'',owner:'',nextStep:'',refs:[] as string[]};
const verdicts=[['true_positive','نشاط غير مشروع تؤيده الأدلة'],['false_positive','إنذار كاذب له تفسير مشروع'],['benign_suspicious','نشاط مريب لكنه مشروع بعد الفحص']];
const responses=[['contain','احتواء الحساب أو الجلسة'],['escalate','تصعيد لفريق الاستجابة'],['monitor','توثيق ومراقبة'],['dismiss','إغلاق كإنذار كاذب']];
export default function FirstSocGuided(){
 const api=useSavedCase<CoreSocData>('/api/soc/alerts/'+coreJourney.socId),boardApi=useSavedCase<CoreBoardData>('/api/investigations/'+coreJourney.boardId);
 const [draft,setDraft]=useCoreDraft('first-soc',initial),[mirrorError,setMirrorError]=useState('');
 const session=api.data?.state?.session,closed=!!api.data?.state?.closedAt,required=boardApi.data?.board.evidence.filter(e=>e.role==='required').map(e=>e.id)||[];
 const evidenceReady=required.length>0&&required.every(id=>session?.collected.includes(id))&&!!session?.usedTools.length;
 const sourcesCollected=required.length>0&&required.every(id=>session?.collected.includes(id));
 const [step,setStep]=useCoreStep(coreJourney.socHref,socSteps,api.ready&&!!api.data&&boardApi.ready&&!!boardApi.data,s=>{
  if(closed)return 'result';if(!api.data?.state)return 'brief';
  if(s==='result')return 'brief';if(s!=='brief'&&s!=='triage'&&!session?.priority)return 'triage';
  if(['investigation','decision','response','document'].includes(s)&&!evidenceReady)return 'evidence';
  if(s==='response'&&!session?.verdict)return 'decision';if(s==='document'&&!session?.response)return 'response';return s;
 });
 const patch=(part:Partial<typeof initial>)=>setDraft(p=>({...p,...part}));
 const returnTo=coreJourney.socHref+'&step='+step+(draft.field?'&field='+draft.field:'');
 async function begin(){const saved=await api.post({action:'start'});if(saved)setStep(saved.state?.closedAt?'result':saved.state?.session.priority?'evidence':'triage')}
 async function inspect(id:string){const d=await api.post({action:'inspect',evidenceId:id});if(!d)return;patch({field:id});setMirrorError('');
  if(boardApi.data?.workspace.status==='open'&&!boardApi.data.evidence.some(e=>e.evidenceId===id&&e.reviewedAt)){if(!await boardApi.post({action:'review',evidenceId:id}))setMirrorError('فحص التنبيه محفوظ. أعد الفحص لاستكمال مراجعة الدليل في الخزانة.');}}
 async function collect(id:string){const d=await api.post({action:'collect',evidenceId:id});if(!d)return;setMirrorError('');
  if(!boardApi.data){setMirrorError('جمع التنبيه محفوظ. افتح خزانة الأدلة لاستكمال جمع النسخة المرتبطة.');return}
  if(boardApi.data.workspace.status!=='open')return;
  if(!boardApi.data.evidence.some(e=>e.evidenceId===id&&e.reviewedAt)&&!await boardApi.post({action:'review',evidenceId:id})){setMirrorError('جمع التنبيه محفوظ؛ لم تكتمل مراجعة الخزانة. أعد جمع الدليل.');return}
  if(!await boardApi.post({action:'collect',evidenceId:id}))setMirrorError('جمع التنبيه محفوظ؛ أعد جمع الدليل لاستكمال حفظه في الخزانة.');
 }
 const selected=api.data?.alert.evidence.find(e=>e.id===draft.field),result=session?.lastResult;
 const remainingSources=required.filter(id=>!session?.collected.includes(id));
 const stageLabels=['افهم التنبيه','حدد الأولوية','افحص واجمع الأدلة','اربط العلاقات','صنّف التنبيه','حدد الاستجابة','وثّق وسلّم التحقيق'];
 return <CoreFrame title="أول تنبيه SOC" error={api.error||mirrorError}>{!api.ready||!api.user||!api.data?<CaseAccess ready={api.ready} user={api.user} href={coreJourney.socHref} error={api.error}/>:<>
 <nav className="pilot-progress" aria-label="مراحل التنبيه"><span aria-current={['brief','triage'].includes(step)?'step':undefined}>التنبيه</span><span aria-current={step==='evidence'?'step':undefined}>الفحص</span><span aria-current={['investigation','decision','response','document'].includes(step)?'step':undefined}>التحقيق</span><span aria-current={step==='result'?'step':undefined}>النتيجة</span></nav>
 {step!=='result'&&<p className="pilot-footnote" role="status">خطوة {socSteps.indexOf(step)+1} من 7 · {stageLabels[socSteps.indexOf(step)]}</p>}
 {step==='brief'&&<section className="pilot-stage"><span className="pilot-kicker">تنبيه هوية · NexaCorp</span><h1>{api.data.alert.title}</h1><p className="pilot-lead">{api.data.alert.summary}</p><div className="pilot-facts"><div><small>الحساب</small><strong dir="ltr">{api.data.alert.user}</strong></div><div><small>خدمة الرصد</small><strong dir="ltr">{api.data.alert.host}</strong></div></div><p>SOC هو مركز العمليات الأمنية. في First Signal ربطت البريد بنشاط الحساب؛ هنا تقيّم تنبيه الرصد، وتقارن الجلسة بالجهاز المعتاد، ثم تسجّل القرار والاستجابة. افحص أدلة هذا التنبيه؛ لا تفترض تطابقها مع كل تفاصيل القضية السابقة.</p><ActivityBrief skill="فرز تنبيه هوية وتوثيق الاستجابة" time="15–25 دقيقة" level="تحقيق موجّه بعد First Signal"/><button className="primary-button" disabled={api.busy} onClick={()=>void begin()}>افتح التنبيه وابدأ الفرز</button></section>}
 {step==='triage'&&<section className="pilot-stage"><h1>ما أولوية هذا التنبيه؟</h1><p>{api.data.alert.scenario}</p><p>أولوية الرصد المقترحة: {api.data.alert.severity}. الأولوية تحدد سرعة الفحص، وليست حكمًا بأن اختراقًا وقع. قيّم الحساب المتأثر، واحتمال استمرار الجلسة، وما يحتاج تحققًا عاجلًا.</p><form onSubmit={async e=>{e.preventDefault();if(await api.post({action:'triage',priority:(draft.priority||session?.priority) as Severity,reason:draft.triageReason||session?.triageReason}))setStep('evidence')}}><label className="core-field">الأولوية<select required value={draft.priority||session?.priority||''} onChange={e=>patch({priority:e.target.value})}><option value="">اختر الأولوية</option>{[['Low','منخفضة'],['Medium','متوسطة'],['High','عالية'],['Critical','حرجة']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="core-field">سبب الأولوية<textarea required minLength={12} maxLength={500} placeholder="ما الأثر المحتمل؟ ولماذا يحتاج الفحص هذه السرعة؟" value={draft.triageReason||session?.triageReason||''} onChange={e=>patch({triageReason:e.target.value})}/></label><button className="primary-button" disabled={api.busy}>احفظ الفرز وافحص الأدلة</button></form></section>}
 {step==='evidence'&&<section className="pilot-stage"><h1>هل الجلسة تخص الجهاز المعتاد؟</h1><p>راجع سجل الجلسات وبيانات الجهاز، ثم احفظ كل مصدر تحتاجه بالضغط على «اجمع الدليل». المراجعة تعرض المحتوى؛ الجمع يضيفه إلى التحقيق. سياق البريد يدعم المقارنة ولا يحل محل المصدرين.</p><label className="core-field">مصدر الدليل<select value={draft.field} disabled={api.busy||boardApi.busy} onChange={e=>void inspect(e.target.value)}><option value="">اختر مصدرًا</option>{api.data.alert.evidence.map(e=><option key={e.id} value={e.id}>{e.title}{session?.collected.includes(e.id)?' · محفوظ':session?.inspected.includes(e.id)?' · تمت المراجعة':''}</option>)}</select></label>
 {selected?.content&&<article className="core-observation"><h2>{selected.title}</h2><pre dir="auto">{selected.content}</pre><button className="secondary-button" disabled={api.busy||boardApi.busy} onClick={()=>void collect(selected.id)}>{session?.collected.includes(selected.id)?'الدليل محفوظ · تأكيد حفظ الخزانة':'اجمع الدليل في التحقيق'}</button>{selected.id==='sessions'&&<Knowledge title="ماذا تثبت الجلسة الناجحة؟" text="سجل النجاح يثبت جلسة للحساب، لكنه لا يحدد هوية من استخدمه. قارن الوقت وبصمة الجهاز؛ اختلاف الموقع وحده غير كافٍ." lessonId="soc-2" returnTo={returnTo}/>} {selected.id==='device'&&<Knowledge title="حساب متأثر أم جهاز مصاب؟" text="متصفح غير مسجل في خدمة الهوية لا يثبت إصابة محطة الموظفة. اربط الدليل بالكيان الذي يصفه قبل اقتراح العزل." lessonId="security-11" returnTo={returnTo}/>}</article>}
 {session&&session.inspected.length>0&&<details className="pilot-secondary" open={sourcesCollected&&!session.usedTools.length}><summary>الفحص الزمني المطلوب قبل الاستنتاج</summary><p>قارن تسلسل الجلسات بعد جمع المصادر؛ حفظ الدليل وحده لا يفسر توقيت النشاط.</p><label className="core-field">أداة المحاكاة<select value={draft.tool} onChange={e=>patch({tool:e.target.value})}><option value="">اختر فحصًا</option>{api.data.alert.tools.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label><button className={sourcesCollected&&!session.usedTools.length?'primary-button':'secondary-button'} disabled={api.busy||!draft.tool} onClick={()=>void api.post({action:'tool',toolId:draft.tool})}>شغّل الفحص المحاكى</button>{session.transcript.map((t,i)=><pre key={i} dir="auto">{t.output}</pre>)}</details>}
 <p className="pilot-footnote" role="status">{remainingSources.length?"مصادر تحتاج جمعًا: "+remainingSources.map(id=>api.data?.alert.evidence.find(e=>e.id===id)?.title).join("، "):!session?.usedTools.length?"جُمعت المصادر؛ شغّل أحد الفحوص لربط النشاط قبل متابعة التحقيق.":"المصادر والفحص محفوظان؛ انتقل إلى تفسير العلاقات."}</p><p className="pilot-footnote">{required.filter(id=>session?.collected.includes(id)).length} من {required.length} مصادر حاسمة محفوظة · قارِن نتائج الفحص قبل الاستنتاج.</p>{(!sourcesCollected||!!session?.usedTools.length)&&<button className="primary-button" disabled={api.busy||boardApi.busy||!evidenceReady} onClick={()=>setStep('investigation')}>اربط الأدلة بالحساب والجلسة</button>}</section>}
 {step==='investigation'&&<section className="pilot-stage"><h1>كوّن العلاقة التي تفسر التنبيه</h1><p>خزانة الأدلة (Evidence Locker) تحفظ المصادر وملاحظاتك. لوحة التحقيق (Investigation Board) تربط كل مصدر بالحساب أو الجلسة أو الجهاز الذي يصفه. افتح التحقيق، دوّن سبب العلاقة، ثم عد إلى التنبيه للتصنيف؛ حفظ المصدر وحده ليس تفسيرًا.</p>{boardApi.error&&<p className="pilot-error" role="alert">{boardApi.error}</p>}{boardApi.data?.workspace.status!=='open'&&boardApi.data&&<p>نتيجة لوحة التحقيق محفوظة سابقًا؛ يمكنك مراجعتها دون إعادة فتحها.</p>}
 <a className="primary-button" href={coreJourney.boardHref}>افتح التحقيق المرتبط</a><button className="email-secondary-link" onClick={()=>setStep('decision')}>لديّ تحليل محفوظ؛ تابع القرار في التنبيه</button><button className="email-secondary-link" onClick={()=>setStep('evidence')}>راجع الأدلة</button></section>}
 {step==='decision'&&<section className="pilot-stage"><h1>استنتاجك المستقل</h1><p>التصنيف يعبّر عن تفسير النشاط بعد الفحص، لا عن شدة التنبيه. اكتب استنتاجًا، ومصدرين يسندانه، وحدًا لما لم تثبته الأدلة.</p><ProgressiveHints hints={["ما الحساب والوقت ونتيجة الدخول في كل جلسة؟ قارِنها قبل الحكم على مصدر مختلف.","هل اختلاف المصدر تدعمه بصمة جهاز أو سياق مستقل؟ تغيير الموقع وحده قد يكون له تفسير مشروع.","افصل أثرًا على الحساب عن إصابة الجهاز. هل الاستنتاج الذي تكتبه أوسع مما يثبته السجل؟"]}/><form onSubmit={async e=>{e.preventDefault();if(await api.post({action:'decide',verdict:(draft.verdict||session?.verdict) as Verdict,conclusion:draft.conclusion||session?.conclusion}))setStep('response')}}><label className="core-field">تصنيف التنبيه<select required value={draft.verdict||session?.verdict||''} onChange={e=>patch({verdict:e.target.value})}><option value="">اختر بعد الربط</option>{verdicts.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="core-field">كيف تسند الأدلة قرارك؟<textarea required minLength={20} maxLength={1000} value={draft.conclusion||session?.conclusion||''} onChange={e=>patch({conclusion:e.target.value})} placeholder="اربط الحساب والوقت وبصمة الجهاز. ما الذي لم يثبت بعد؟"/></label><button className="primary-button" disabled={api.busy}>احفظ الاستنتاج وحدد الاستجابة</button></form><a className="pilot-text-link" href={coreJourney.boardHref}>راجع العلاقات المحفوظة</a></section>}
 {step==='response'&&<section className="pilot-stage"><h1>إجراء متناسب مع الدليل</h1><p>اختر إجراءً للكيان الذي تصفه الأدلة: حساب أو جلسة أو جهاز. فسّر كيف يقلل الخطر، وما الذي تحفظه قبل تنفيذه وفق سياسة المؤسسة.</p><form onSubmit={async e=>{e.preventDefault();if(await api.post({action:'respond',response:(draft.response||session?.response) as ResponseAction,reason:draft.responseReason||session?.responseReason}))setStep('document')}}><label className="core-field">الإجراء<select required value={draft.response||session?.response||''} onChange={e=>patch({response:e.target.value})}><option value="">اختر الإجراء</option>{responses.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="core-field">لماذا يناسب ما وجدته؟<textarea required minLength={20} maxLength={800} value={draft.responseReason||session?.responseReason||''} onChange={e=>patch({responseReason:e.target.value})}/></label><button className="primary-button" disabled={api.busy}>سجّل الاستجابة ووثّق التحقيق</button></form><Knowledge title="احتفظ بالدليل قبل الإغلاق" text="الاستجابة تحمي الحساب أو الجهاز وفق الدليل، والتوثيق يحفظ ما حدث لمن يتابع. لا تمسح السجلات لتبدو القضية منتهية." lessonId="security-11" returnTo={returnTo}/></section>}
 {step==='document'&&<section className="pilot-stage"><h1>سلّم تحقيقًا يمكن مراجعته</h1><p>افصل ما لاحظته عن تفسيرك. اربط التقييم بالمراجع، وسمِّ مسؤول متابعة وخطوة محددة يمكن التحقق منها.</p><details className="pilot-secondary"><summary>كيف أكتب توثيقًا واضحًا؟</summary><p>الملاحظة: حدث ووقت وحساب من السجل. التقييم: تفسير تدعمه مراجع محددة، مع ما بقي مجهولًا. المتابعة: مسؤول وخطوة ونتيجة تنتظر التحقق منها.</p></details><form onSubmit={async e=>{e.preventDefault();const note=session?.caseNote;const saved=await api.post({action:'document',caseNote:{observation:draft.observation||note?.observation,evidenceRefs:draft.refs.length?draft.refs:note?.evidenceRefs||[],assessment:draft.assessment||note?.assessment,actionTaken:session?.response,owner:draft.owner||note?.owner,nextStep:draft.nextStep||note?.nextStep}});if(saved&&await api.post({action:'close'}))setStep('result')}}>
 <label className="core-field">ما الذي لاحظته؟<textarea required minLength={15} maxLength={500} placeholder="ما الحدث المسجل، ومتى، وعلى أي حساب؟" value={draft.observation||session?.caseNote?.observation||''} onChange={e=>patch({observation:e.target.value})}/></label><fieldset className="pilot-choices"><legend>مراجع الأدلة</legend>{api.data.alert.evidence.filter(e=>session?.collected.includes(e.id)).map(e=><label key={e.id}><input type="checkbox" checked={(draft.refs.length?draft.refs:session?.caseNote?.evidenceRefs||[]).includes(e.id)} onChange={event=>patch({refs:event.target.checked?[...draft.refs,e.id]:draft.refs.filter(id=>id!==e.id)})}/>{e.title}</label>)}</fieldset>
 <label className="core-field">تقييمك وحدود ما ثبت<textarea required minLength={15} maxLength={500} placeholder="ما تفسيرك؟ أي دليل يسنده، وما الذي لم يثبت؟" value={draft.assessment||session?.caseNote?.assessment||''} onChange={e=>patch({assessment:e.target.value})}/></label><label className="core-field">مسؤول المتابعة<input required minLength={3} maxLength={100} value={draft.owner||session?.caseNote?.owner||''} onChange={e=>patch({owner:e.target.value})}/></label><label className="core-field">الخطوة التالية<textarea required minLength={12} maxLength={500} placeholder="ما الفحص التالي، وما النتيجة التي تؤكد نجاحه؟" value={draft.nextStep||session?.caseNote?.nextStep||''} onChange={e=>patch({nextStep:e.target.value})}/></label><button className="primary-button" disabled={api.busy||!(draft.refs.length||session?.caseNote?.evidenceRefs.length)}>احفظ التوثيق وأظهر نتيجة التحقيق</button></form></section>}
 {step==='result'&&closed&&<section className="pilot-stage pilot-result"><h1>{result?.correct?'أكملت التحقيق والاستجابة':'القرار محفوظ ويحتاج مراجعة'}</h1>{result?.correct&&<div className="pilot-summary"><p><strong>ما تعلمته:</strong> فرز التنبيه، وربط الجلسات بالجهاز، واختيار استجابة وفق الأدلة.</p><p><strong>حدود الاستنتاج:</strong> دليل على جلسة غير مألوفة لا يثبت وحده إصابة محطة الموظفة؛ اذكر هذا الحد في التوثيق.</p><p><strong>طبّقها عمليًا:</strong> سلّم حدثًا موثقًا ومراجعه وتقييمك والإجراء ومسؤول المتابعة. ثم تحقق من أثر الاستجابة بدل اعتبار إغلاق التنبيه نهاية الفحص.</p></div>}{result&&<><div className="pilot-summary">{result.feedback.map((f,i)=><p key={i}>{f}</p>)}</div><CompletionProgressSummary achievementId="soc-response"/><details className="pilot-secondary"><summary>نتيجة التقدم</summary><p>{result.score} من 100 · أفضل نتيجة {api.data.state?.bestScore} من 100</p><p>{result.skillAwardGranted?'حُفظت مكافأة المهارة الأصلية مرة واحدة.':api.data.skillAwarded?'مكافأة المهارة محفوظة سابقًا ولم تتكرر.':'لم تبلغ هذه المحاولة معيار مكافأة المهارة.'} لا XP عامة إضافية من SOC.</p></details></>}
 <>{result&&!result.correct?<button className="primary-button" disabled={api.busy} onClick={async()=>{if(await api.post({action:'reopen'})){setDraft(initial);setStep('triage')}}}>أعد فحص التنبيه وفق الملاحظات</button>:<a className="primary-button" href="/progress">خطوتك التالية: راجع تقدمك الأمني</a>}</><details className="pilot-secondary"><summary>مراجعة التحقيق</summary><a href={coreJourney.boardHref}>الأدلة والعلاقات المحفوظة</a>{result?.correct&&<button className="secondary-button" disabled={api.busy} onClick={async()=>{if(await api.post({action:'reopen'})){setDraft(initial);setStep('triage')}}}>أعد التحقيق دون مكافأة مكررة</button>}<a href="/soc/alerts/SOC-002">العرض الكامل للتنبيه</a></details></section>}
 </>}</CoreFrame>;
}
