'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,ClipboardList,FileSearch,History,NotebookPen,ShieldCheck,Terminal} from 'lucide-react';
import {useProgress} from '@/app/shell';
import LabBridge from '@/app/labs/v2/lab-bridge';
import CompanyContext from '@/components/company-context';
type Result={score:number;correct:boolean;skillAwardEligible:boolean;skillAwardGranted?:boolean;feedback:string[];missingEvidence:string[];classificationCorrect:boolean;responseCorrect:boolean;priorityCorrect:boolean;documentation?:{met:string[];missing:string[]}};
type Session={priority:string|null;triageReason:string;inspected:string[];collected:string[];usedTools:string[];transcript:{toolId:string;output:string}[];verdict:string|null;conclusion:string;response:string|null;responseReason:string;caseNote?:{observation:string;evidenceRefs:string[];assessment:string;actionTaken:string|null;owner:string;nextStep:string};prematureDecisions:number;timeline:{time:string;label:string}[];lastResult:Result|null};
type State={status:string;startedAt:string;updatedAt:string;closedAt:string|null;score:number;bestScore:number;attempts:number;session:Session};
type Alert={id:string;title:string;severity:string;timestamp:string;user:string;host:string;sourceIp:string;type:string;summary:string;scenario:string;skillRewards:{skill:string;points:number}[];evidence:{id:string;kind:string;time:string;title:string;content:string|null}[];tools:{id:string;label:string;description:string}[]};
type Detail={alert:Alert;state:State|null;notes:{id:number;content:string;createdAt:string}[];skillAwarded:boolean;caseId:string|null;message?:string;newSkillAward?:boolean;error?:string};
const verdicts=[['true_positive','True Positive · تهديد مثبت'],['false_positive','False Positive · إنذار كاذب'],['benign_suspicious','Benign but suspicious · نشاط مريب مشروع']];
const responses=[['contain','Contain · احتواء الحساب أو الجهاز'],['escalate','Escalate · تصعيد لفريق الاستجابة'],['monitor','Monitor · توثيق ومراقبة'],['dismiss','Dismiss · إغلاق كإنذار كاذب']];
const severityLabels:Record<string,string>={Low:'منخفض',Medium:'متوسط',High:'عالٍ',Critical:'حرج'};
const statusLabels:Record<string,string>={New:'جديد',Investigating:'قيد التحقيق',Escalated:'مصعّد',Resolved:'محلول','False Positive':'إنذار كاذب'};
const emptyCaseNote={observation:'',evidenceRefs:[] as string[],assessment:'',actionTaken:'',owner:'',nextStep:''};
const kindLabels:Record<string,string>={auth:'Authentication Logs',endpoint:'Endpoint Events',network:'Network Events',user:'User Activity',email:'Email Information',file:'File / Hash',ip:'IP Information'};
export default function AlertWorkspace({id}:{id:string}){
 const {user}=useProgress(),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(!!user),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[priority,setPriority]=useState(''),[triageReason,setTriageReason]=useState(''),[verdict,setVerdict]=useState(''),[conclusion,setConclusion]=useState(''),[response,setResponse]=useState(''),[responseReason,setResponseReason]=useState(''),[note,setNote]=useState(''),[caseNote,setCaseNote]=useState(emptyCaseNote),[openEvidence,setOpenEvidence]=useState('');
 useEffect(()=>{if(!user)return;let active=true;(async()=>{const r=await fetch('/api/soc/alerts/'+id,{cache:'no-store'});let data=await r.json() as Detail;if(!r.ok)throw Error(data.error||'تعذر تحميل التنبيه.');if(!data.state){const start=await fetch('/api/soc/alerts/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'start'})});data=await start.json() as Detail;if(!start.ok)throw Error(data.error||'تعذر بدء التحقيق.')}if(active){setDetail(data);setPriority(data.state?.session.priority||'');setTriageReason(data.state?.session.triageReason||'');setVerdict(data.state?.session.verdict||'');setConclusion(data.state?.session.conclusion||'');setResponse(data.state?.session.response||'');setResponseReason(data.state?.session.responseReason||'');setCaseNote({...emptyCaseNote,...data.state?.session.caseNote,actionTaken:data.state?.session.caseNote?.actionTaken||''})}})().catch(e=>{if(active)setError(e instanceof Error?e.message:'تعذر الاتصال.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user,id]);
 async function act(action:string,extra:Record<string,unknown>={}){if(busy)return;setBusy(action);setError('');setMessage('');try{const r=await fetch('/api/soc/alerts/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...extra})});const d=await r.json() as Detail;if(!r.ok)throw Error(d.error||'تعذر حفظ التحقيق.');setDetail(d);setMessage(d.message||'حُفظت الخطوة.');if(action==='reopen'){setPriority('');setTriageReason('');setVerdict('');setConclusion('');setResponse('');setResponseReason('');setCaseNote(emptyCaseNote);setOpenEvidence('')}if(action==='close'&&d.newSkillAward)setMessage('أُغلق التنبيه وسُجلت مكافأة المهارات مرة واحدة.')}catch(e){setError(e instanceof Error?e.message:'تعذر الاتصال.')}finally{setBusy('')}}
 async function saveNote(e:React.FormEvent){e.preventDefault();if(busy||!note.trim())return;setBusy('note');setError('');try{const r=await fetch('/api/soc/alerts/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'note',content:note})});const d=await r.json() as {notes:Detail['notes'];error?:string};if(!r.ok)throw Error(d.error||'تعذر حفظ الملاحظة.');setDetail(prev=>prev?{...prev,notes:d.notes}:prev);setNote('');setMessage('حُفظت ملاحظة المحلل في D1.')}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ.')}finally{setBusy('')}}
 if(!user)return <div className="reading-width soc-page"><a className="back-link" href="/soc">← SOC Console</a><section className="panel"><h1>التحقيق في التنبيه</h1><p>سجّل الدخول لتعود إلى التنبيه نفسه.</p><a className="primary-button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/soc/alerts/'+id)} target="_top">تسجيل الدخول</a></section></div>;
 if(loading&&!detail)return <div className="reading-width soc-page"><p role="status">جارٍ استعادة ملف التحقيق…</p></div>;
 if(!detail)return <div className="reading-width soc-page"><p role="alert" className="error">{error}</p><a href="/soc">العودة إلى قائمة التنبيهات</a></div>;
 const {alert,state}=detail,session=state?.session,closed=!!state?.closedAt,steps=[!!session?.priority,!!session?.inspected.length,!!session?.collected.length,!!session?.verdict,!!session?.response,closed];
 return <div className="reading-width soc-page soc-workspace"><a className="back-link" href="/soc">← قائمة تنبيهات SOC</a><CompanyContext kind="soc" id={id}/>{id==='SOC-002'&&<a className="ib-entry" href="/investigations/soc-SOC-002">افتح خزانة الأدلة ولوحة العلاقات لهذا التنبيه <ArrowLeft size={17}/></a>}<header className="soc-investigation-header"><div><span className="eyebrow">NEXACORP / {alert.id} / {alert.type.toUpperCase()}</span><h1>{alert.title}</h1><p>{alert.summary}</p><div className="soc-attributes"><span className={'soc-severity '+alert.severity.toLowerCase()}>{severityLabels[alert.severity]}</span><span className={'soc-status '+(state?.status||'New').toLowerCase().replace(' ','-')}>{statusLabels[state?.status||'New']}</span><span>{new Date(alert.timestamp).toLocaleString('ar-SA',{dateStyle:'medium',timeStyle:'short'})}</span></div></div><div className="soc-asset"><span>IDENTITY / ASSET</span><strong>{alert.user} · {alert.host}</strong><small dir="ltr">{alert.sourceIp}</small></div></header>
 <div className="safe-banner"><ShieldCheck size={19}/><p>هذه بيئة تدريبية بالكامل. أدوات الفحص تعرض بيانات محاكاة ولا تنفذ أوامر أو طلبات إلى شبكة خارجية.</p></div>
 <LabBridge alertId={id}/><nav className="soc-steps" aria-label="مراحل التحقيق">{['فرز','فحص','جمع الأدلة','قرار','استجابة','إغلاق'].map((s,i)=><span className={steps[i]?'done':''} key={s}>{steps[i]?'✓':i+1} {s}</span>)}</nav>
 <div className="soc-workspace-grid"><div className="soc-workspace-main"><section className="panel soc-brief"><span className="eyebrow">ALERT BRIEF</span><h2>ماذا حدث؟</h2><p>{alert.scenario}</p></section>
 <section className="panel soc-triage"><div className="soc-section-head"><div><span className="eyebrow">01 / TRIAGE</span><h2>فرز التنبيه</h2></div>{session?.priority&&<CheckCircle2 size={20}/>}</div><p>حدد أولوية المعالجة واكتب سببها قبل إصدار الاستنتاج.</p><form onSubmit={e=>{e.preventDefault();void act('triage',{priority,reason:triageReason})}}><label>أولوية المعالجة<select value={priority} onChange={e=>setPriority(e.target.value)} disabled={closed||!!busy} required><option value="">اختر الأولوية</option>{['Low','Medium','High','Critical'].map(s=><option value={s} key={s}>{severityLabels[s]}</option>)}</select></label><label>مبرر الفرز<textarea value={triageReason} onChange={e=>setTriageReason(e.target.value)} disabled={closed||!!busy} minLength={12} maxLength={500} required placeholder="لماذا يستحق هذا التنبيه الفحص أو التأجيل؟"/></label><button className="secondary-button" disabled={closed||!!busy} type="submit">حفظ الفرز</button></form></section>
 <section className="panel soc-evidence-viewer"><span className="eyebrow">02 / INVESTIGATE + COLLECT</span><h2>عارض الأدلة</h2><p>افتح السجلات أولًا، ثم اجمع المؤشرات المهمة في ملف التحقيق. الاطلاع على دليل لا يجمعه تلقائيًا؛ الأدلة المجموعة هي ما يدخل التقييم، ويمكنك مراجعة غيرها اختياريًا.</p>{alert.evidence.map(e=><div className="soc-evidence-card" key={e.id}><button type="button" disabled={!!busy&&!session?.inspected.includes(e.id)} onClick={()=>{setOpenEvidence(openEvidence===e.id?'':e.id);if(!session?.inspected.includes(e.id))void act('inspect',{evidenceId:e.id})}} aria-expanded={openEvidence===e.id}><span><small>{kindLabels[e.kind]||e.kind} · {e.time}</small><strong>{e.title}</strong></span><span>{session?.collected.includes(e.id)?'✓ جُمع في الملف':session?.inspected.includes(e.id)?'تمت المراجعة · لم يُجمع':'راجع الدليل ←'}</span></button>{openEvidence===e.id&&<div className="soc-evidence-content"><pre dir="auto">{e.content||'جارٍ تحميل محتوى الدليل…'}</pre><button className="secondary-button" type="button" disabled={closed||!!busy||!session?.inspected.includes(e.id)||session?.collected.includes(e.id)} onClick={()=>void act('collect',{evidenceId:e.id})}>{session?.collected.includes(e.id)?'جُمع في الملف':'جمع الدليل في ملف التحقيق'}</button></div>}</div>)}</section>
 <section className="panel soc-tools"><span className="eyebrow"><Terminal size={14}/> أدوات فحص محاكية</span><h2>أدوات الفحص</h2><div className="soc-tool-list">{alert.tools.map(t=><button type="button" key={t.id} disabled={closed||!!busy} onClick={()=>void act('tool',{toolId:t.id})}><strong>{t.label} {session?.usedTools.includes(t.id)?'✓':''}</strong><small>{t.description}</small></button>)}</div><div className="soc-tool-output" aria-live="polite">{session?.transcript.length?session.transcript.map((t,i)=><div key={i}><small>{alert.tools.find(tool=>tool.id===t.toolId)?.label}</small><pre dir="auto">{t.output}</pre></div>):<p>اختر أداة لتظهر نتائجها المحاكية هنا.</p>}</div></section>
 <section className="panel soc-decision"><span className="eyebrow">04 / DECIDE</span><h2>استنتاج المحلل</h2><p>حدد التصنيف واكتب الأدلة التي تسنده. قد يؤثر اتخاذ قرار قبل جمع المؤشرات المهمة على تقييمك.</p><form onSubmit={e=>{e.preventDefault();void act('decide',{verdict,conclusion})}}><label>تصنيف التنبيه<select value={verdict} onChange={e=>setVerdict(e.target.value)} required disabled={closed||!!busy}><option value="">اختر بعد التحقيق</option>{verdicts.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>استنتاجك المبني على الأدلة<textarea value={conclusion} onChange={e=>setConclusion(e.target.value)} minLength={20} maxLength={1000} required disabled={closed||!!busy} placeholder="اربط السجلات والمستخدم والجهاز والأوقات، ثم اشرح لماذا صنّفت التنبيه هكذا."/></label><button type="submit" className="secondary-button" disabled={closed||!!busy||!session?.priority}>تسجيل الاستنتاج</button></form></section>
 <section className="panel soc-response"><span className="eyebrow">05 / RESPOND</span><h2>الاحتواء أو التصعيد</h2><p>اختر إجراءً مناسبًا واكتب سبب القرار. التنبيه الكاذب لا يحتاج إلى احتواء، والنشاط المريب قد يستحق المراقبة.</p><form onSubmit={e=>{e.preventDefault();void act('respond',{response,reason:responseReason})}}><label>الإجراء<select value={response} onChange={e=>setResponse(e.target.value)} required disabled={closed||!!busy}><option value="">اختر الإجراء</option>{responses.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>سبب الإجراء<textarea value={responseReason} onChange={e=>setResponseReason(e.target.value)} required minLength={20} maxLength={800} disabled={closed||!!busy} placeholder="ما الذي ستطلب تنفيذه، ولماذا يناسب ما وجدته؟"/></label><button className="secondary-button" type="submit" disabled={closed||!!busy||!session?.verdict}>تسجيل الاستجابة</button></form></section>
 {!closed&&<section className="panel soc-case-document"><span className="eyebrow">توثيق القضية</span><h2>ملاحظة قضية منظمة</h2><p>اكتب ملاحظة قابلة للتسليم لمحلل آخر. يُقيَّم وجود الملاحظة والدليل والتقييم والإجراء والمسؤول والخطوة التالية؛ لا تُمنح درجة على طول النص. يمكن حفظ ملاحظات سريعة منفصلة في الجانب.</p><form className="soc-note-structure" onSubmit={e=>{e.preventDefault();void act('document',{caseNote:{...caseNote,actionTaken:response}})}}><label>الملاحظة المباشرة<textarea required minLength={15} maxLength={500} disabled={!!busy||!session?.response} value={caseNote.observation} onChange={e=>setCaseNote({...caseNote,observation:e.target.value})} placeholder="ما الحدث الذي رصدته؟ اذكر الجهاز والوقت، دون الجزم بالسبب."/></label><fieldset><legend>الأدلة التي تستند إليها</legend>{alert.evidence.filter(e=>session?.collected.includes(e.id)).map(e=><label key={e.id}><input type="checkbox" disabled={!!busy} checked={caseNote.evidenceRefs.includes(e.id)} onChange={event=>setCaseNote({...caseNote,evidenceRefs:event.target.checked?[...caseNote.evidenceRefs,e.id]:caseNote.evidenceRefs.filter(id=>id!==e.id)})}/>{e.id} · {e.title}</label>)}{!session?.collected.length&&<p>اجمع دليلًا من العارض أولًا.</p>}</fieldset><label>التقييم / الاستنتاج<textarea required minLength={15} maxLength={500} disabled={!!busy||!session?.response} value={caseNote.assessment} onChange={e=>setCaseNote({...caseNote,assessment:e.target.value})} placeholder="كيف تفسر الأدلة؟ ما الذي لم يثبت بعد؟"/></label><p>الإجراء المسجل: <strong>{responses.find(([key])=>key===session?.response)?.[1]||'سجّل الاستجابة أولًا'}</strong></p><label>المسؤول عن المتابعة<input required minLength={3} maxLength={100} disabled={!!busy||!session?.response} value={caseNote.owner} onChange={e=>setCaseNote({...caseNote,owner:e.target.value})} placeholder="فريق SOC / فريق IT"/></label><label>الخطوة التالية<textarea required minLength={12} maxLength={500} disabled={!!busy||!session?.response} value={caseNote.nextStep} onChange={e=>setCaseNote({...caseNote,nextStep:e.target.value})} placeholder="حدد فحصًا أو متابعةً مع مسؤول ووقت مناسب."/></label><button className="secondary-button" type="submit" disabled={!!busy||!session?.response||!caseNote.evidenceRefs.length}>حفظ ملاحظة القضية</button>{session?.caseNote&&<p role="status">✓ حُفظت الملاحظة المنظمة في ملف التحقيق. عدّلها وأعد الحفظ عند تغير الأدلة.</p>}</form></section>}
 {!closed?<section className="panel soc-close"><span className="eyebrow">06 / إغلاق</span><h2>أغلق التنبيه مع مراجعة قرارك</h2><p>ستُقيّم الأدلة التي جمعتها وتوقيت القرار وإجراء الاستجابة. يمكنك إعادة التحقيق لاحقًا لتحسين النتيجة دون مكافآت مكررة.</p><button type="button" className="primary-button" disabled={!!busy||!session?.response||!session?.inspected.length} onClick={()=>void act('close')}>إغلاق التنبيه وإظهار التقييم</button></section>:session?.lastResult&&<section className="panel soc-result" aria-live="polite"><span className="eyebrow">نتيجة التحقيق</span><h2>{state?.status==='False Positive'?'أُغلق كإنذار كاذب':state?.status==='Escalated'?'صُعّد التنبيه':'أُغلق التحقيق'}</h2><div className="soc-result-score"><strong>{session.lastResult.score} من 100</strong><span>أفضل نتيجة {state?.bestScore} من 100 · {state?.attempts} محاولة</span></div>{session.lastResult.documentation&&<p>معيار التوثيق: {session.lastResult.documentation.met.length} من 6 · {session.lastResult.documentation.missing.length?'يحتاج '+session.lastResult.documentation.missing.join('، '):'مكتمل'}</p>}<ul>{session.lastResult.feedback.map((f,i)=><li key={i}>{f}</li>)}</ul><p className="soc-reward">{session.lastResult.skillAwardEligible?(session.lastResult.skillAwardGranted?'مُنحت مكافأة Skill XP الأساسية في هذه المحاولة مرة واحدة.':detail.skillAwarded?'مكافأة Skill XP الأساسية سبق منحها ولم تتكرر عند الإعادة.':'تعذر عرض مكافأة المهارة.'):'راجع التصنيف والأدلة والإجراء لبلوغ معيار مكافأة المهارة.'} لا تُضاف XP عامة من SOC Console.</p><div className="button-row">{detail.caseId&&<a className="primary-button" href={'/soc/cases/'+detail.caseId}>فتح القضية المرتبطة <ArrowLeft size={17}/></a>}<button className="secondary-button" type="button" disabled={!!busy} onClick={()=>void act('reopen')}>إعادة التحقيق</button><a className="secondary-button" href="/soc">العودة لقائمة التنبيهات</a></div></section>}
 </div><aside className="soc-workspace-side"><section className="panel soc-notes"><span className="eyebrow"><NotebookPen size={14}/> ملاحظات المحلل</span><h2>ملاحظات المحلل</h2><form onSubmit={saveNote}><label htmlFor="soc-note">اكتب ما لاحظته أثناء التحقيق</label><textarea id="soc-note" value={note} onChange={e=>setNote(e.target.value)} minLength={3} maxLength={2000} placeholder="مثال: المصدر ظهر ثلاث مرات، سأقارن ببقية السجلات…" required/><button className="secondary-button" disabled={!!busy||note.trim().length<3} type="submit">حفظ الملاحظة</button></form>{detail.notes.length?<ol>{detail.notes.map(n=><li key={n.id}><small>{new Date(n.createdAt).toLocaleString('ar-SA',{dateStyle:'short',timeStyle:'short'})}</small><p>{n.content}</p></li>)}</ol>:<p>لم تُحفظ ملاحظات بعد.</p>}</section><section className="panel soc-timeline"><span className="eyebrow"><History size={14}/> تسلسل التحقيق</span><h2>سجل خطواتك</h2>{session?.timeline.length?<ol>{session.timeline.map((event,i)=><li key={i}><time>{new Date(event.time).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}</time><span>{event.label}</span></li>)}</ol>:<p>ابدأ بالفحص وستظهر خطواتك هنا.</p>}</section><section className="panel soc-progress-note"><span className="eyebrow"><FileSearch size={14}/> ملف التحقيق</span><h2>تقدم التحقيق</h2><p>{session?.collected.length||0} أدلة أُضيفت · {session?.usedTools.length||0} أدوات استُخدمت</p><div className="mission-meter" role="progressbar" aria-label="مراحل التحقيق" aria-valuenow={steps.filter(Boolean).length} aria-valuemin={0} aria-valuemax={6}><span style={{width:steps.filter(Boolean).length/6*100+'%'}}/></div>{detail.caseId&&<a href={'/soc/cases/'+detail.caseId}>القضية المرتبطة <ArrowLeft size={15}/></a>}</section></aside></div>{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="mission-message">{message}</p>}<footer className="soc-footer"><ClipboardList size={18}/> تعلّم تفسير الأدلة قبل الاستجابة. المؤشرات الواردة هنا خيالية ولا ترتبط بأي هدف حقيقي.</footer></div>;
}
