'use client';
import {useEffect,useState} from 'react';
import {useProgress} from '@/app/shell';
import {incidentTemplates,type Difficulty} from '@/lib/incident-catalog';
type IncidentSummary={instanceId:string;templateId:string;seed:number;difficulty:Difficulty;variantNumber:number;createdAt:string;status:string|null};
type List={instances:IncidentSummary[];active:Record<string,string>;error?:string};
const difficultyLabels={beginner:'مبتدئ',intermediate:'متوسط',advanced:'متقدم'};
export default function IncidentCenter(){
 const {user}=useProgress(),[data,setData]=useState<List|null>(null),[difficulty,setDifficulty]=useState<Record<string,Difficulty>>({}),[busy,setBusy]=useState(''),[error,setError]=useState('');
 useEffect(()=>{if(!user)return;let live=true;fetch('/api/incidents',{cache:'no-store'}).then(async r=>{const result=await r.json() as List;if(!r.ok)throw Error(result.error||'تعذر تحميل الحوادث.');if(live)setData(result)}).catch(e=>{if(live)setError(e instanceof Error?e.message:'تعذر الاتصال.')});return()=>{live=false}},[user]);
 async function begin(templateId:string,mode:'resume'|'new'){
  if(busy)return;setBusy(templateId);setError('');try{const response=await fetch('/api/incidents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({templateId,difficulty:difficulty[templateId]||'beginner',mode})});const result=await response.json() as {instanceId?:string;error?:string};if(!response.ok||!result.instanceId)throw Error(result.error||'تعذر إنشاء الحادث.');window.location.href='/investigations/'+encodeURIComponent('dynamic-'+result.instanceId)}catch(e){setError(e instanceof Error?e.message:'تعذر الاتصال.');setBusy('')}
 }
 return <div className="reading-width ib-page di-center"><a className="back-link" href="/operations">← العودة إلى العمليات</a><header className="ib-header"><span className="eyebrow">تدريب التحقيق</span><h1>حوادث متغيرة</h1><p>ثلاثة أنواع من الحوادث داخل الشركة نفسها. قارن الأدلة واربط الأحداث قبل القرار. إنشاء نسخة جديدة إجراء تختاره أنت؛ التحديث لا يغيّر النسخة الجارية.</p><p><a href="/experience/nexacorp-response">متابعة حادث ليلى: البريد ثم الجهاز وأثر الاستجابة ←</a></p><p className="ib-caption">محاكاة تعليمية فقط. لا تمنح هذه الحوادث XP أو Skill XP، حتى عند إنشاء نسخ إضافية.</p></header>
 {!user?<div className="ib-section"><p>سجّل الدخول لحفظ نسخة الحادث وأدلتها.</p><a className="primary-button" target="_top" href="/signin-with-chatgpt?return_to=%2Fincidents">تسجيل الدخول</a></div>:!data?<p role={error?'alert':'status'}>{error||'جارٍ استعادة نسخ الحوادث…'}</p>:<><div className="di-grid">{incidentTemplates.map(t=>{const active=data.active[t.id],activeStatus=data.instances.find(i=>i.instanceId===active)?.status,selected=difficulty[t.id]||'beginner';return <article className="ib-section di-card" key={t.id}><small className="eyebrow">حادث تدريبي</small><h2>{t.title}</h2><p>{t.description}</p><label>صعوبة النسخة الجديدة<select value={selected} disabled={!!busy} onChange={e=>setDifficulty(p=>({...p,[t.id]:e.target.value as Difficulty}))}><option value="beginner">مبتدئ · توجيه أوضح</option><option value="intermediate">متوسط · مصادر أكثر</option><option value="advanced">متقدم · ربط أوسع</option></select></label><div className="di-actions"><button className={t.id===(incidentTemplates.find(template=>data.active[template.id])?.id||incidentTemplates[0].id)?"primary-button":"secondary-button"} type="button" disabled={!!busy} onClick={()=>void begin(t.id,'resume')}>{active?(activeStatus&&activeStatus!=='open'?'أعد التحقيق في النسخة نفسها':'تابع النسخة المحفوظة'):'ابدأ أول نسخة'}</button>{active&&<button className="secondary-button" type="button" disabled={!!busy} onClick={()=>void begin(t.id,'new')}>ابدأ نسخة جديدة</button>}</div><a href={t.missionHref}>راجع النشاط المرتبط ←</a></article>})}</div><section className="ib-section"><h2>نسخك المحفوظة</h2>{!data.instances.length?<p>لم تبدأ حادثًا بعد.</p>:<ul className="di-history">{data.instances.map(i=><li key={i.instanceId}><a href={'/investigations/'+encodeURIComponent('dynamic-'+i.instanceId)}>{incidentTemplates.find(t=>t.id===i.templateId)?.title} · نسخة {i.variantNumber} · {difficultyLabels[i.difficulty]}</a><span>{i.status&&i.status!=='open'?'قرار محفوظ':'قيد التحقيق'}</span></li>)}</ul>}</section></>}{error&&data&&<p role="alert" className="error">{error}</p>}</div>
}
