import {readJsonInput,reportServerError,isUserError} from '@/lib/request-validation';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {lessons} from '@/lib/curriculum';
import {readLearning,recordActivity,saveNote,setBookmark,savePreferences} from '@/lib/storage';
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'سجّل الدخول لحفظ بياناتك.'},{status:401});try{return Response.json(await readLearning(user.userId),{headers:{'Cache-Control':'private, no-store'}})}catch(e){reportServerError('Learning read failed',e);return Response.json({error:'تعذر تحميل بيانات التعلم.'},{status:503})}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'سجّل الدخول أولًا.'},{status:401});const parsed=await readJsonInput(request,12000,'learning');if(parsed.error)return parsed.error;const b=parsed.data as Record<string,unknown>;
 try{if(b.action==='settings'){if(!Number.isInteger(b.dailyGoal)||Number(b.dailyGoal)<5||Number(b.dailyGoal)>180||!['dark','light'].includes(b.theme as string))throw Error('اختر هدفًا بين 5 و180 دقيقة.');await savePreferences(user.userId,Number(b.dailyGoal),b.theme as string);}
 else{if(typeof b.id!=='string'||!lessons.some(l=>l.id===b.id))throw Error('الدرس غير موجود.');if(b.action==='read'){if(!Number.isInteger(b.seconds)||Number(b.seconds)<0||Number(b.seconds)>30)throw Error('مدة غير صالحة.');await recordActivity(user.userId,b.id,'read',Number(b.seconds));}else if(b.action==='complete')await recordActivity(user.userId,b.id,'complete');else if(b.action==='note'){if(typeof b.content!=='string'||b.content.length>5000)throw Error('الملاحظة طويلة أو غير صالحة.');await saveNote(user.userId,b.id,b.content);}else if(b.action==='bookmark'){if(typeof b.saved!=='boolean')throw Error('حالة الحفظ غير صالحة.');await setBookmark(user.userId,b.id,b.saved);}else throw Error('إجراء غير معروف.');}
 return Response.json({ok:true});}catch(e){if(isUserError(e,/غير|اختر|طويل/))return Response.json({error:e.message},{status:400});reportServerError('Learning save failed',e);return Response.json({error:'تعذر الحفظ. حاول مجددًا.'},{status:503})}}
