'use client';
import {skillTitles} from '@/lib/progression';
import {useEffect,useState} from 'react';
import {ArrowLeft,ChartNoAxesCombined} from 'lucide-react';
import {useProgress} from '@/app/shell';
import {isCyberHref} from '@/lib/content-scope';
import type {MasteryState,PracticeRecommendation} from '@/lib/adaptive-learning';

export type AdaptiveView={mastery:MasteryState[];recommendations:PracticeRecommendation[];needsPractice:{id:string;name:string;mastery:number|null;samples:number}[];strongSkills:{id:string;name:string;mastery:number|null;samples:number}[];observations:number};
const labels={High:'أولوية عالية',Medium:'تدريب مقترح',Review:'مراجعة سريعة',Start:'ابدأ هنا'};
const types={lesson:'درس','mini-lab':'مختبر مصغر','full-lab':'مختبر عملي',mission:'مهمة',review:'مراجعة'};
export const masteryLabels={New:'جديد',Developing:'قيد التطوير',Proficient:'متمكن',Strong:'قوي'};
export function useAdaptive(){const {user,items,loading:progressLoading}=useProgress(),[data,setData]=useState<AdaptiveView|null>(null),[loading,setLoading]=useState(!!user),[error,setError]=useState('');
 useEffect(()=>{if(!user||progressLoading)return;let active=true;fetch('/api/adaptive',{cache:'no-store'}).then(async r=>{const result=await r.json() as AdaptiveView&{error?:string};if(!r.ok)throw Error(result.error||'تعذر حساب الإتقان.');if(active){setData(result);setError('')}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'تعذر الحساب.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user,items,progressLoading]);
 return {data,loading,error};}
export default function AdaptiveOverview(){const {user}=useProgress(),{data,loading,error}=useAdaptive();if(!user)return null;
 return <section className="panel adaptive-overview" aria-label="التدريب المقترح"><div className="between adaptive-heading"><div><span className="eyebrow">اقتراحات من تقدمك</span><h2>تدريب موصى به</h2><p>اختر تدريبًا يناسب نتائجك. سبب كل اقتراح موضح تحته، وإعادة التدريب لا تكرر المكافآت.</p></div><a href="/skills">تفاصيل الإتقان <ArrowLeft size={16}/></a></div>
 {loading?<p role="status">جارٍ تحليل نتائج التدريب…</p>:error?<p role="alert" className="error">{error} <button type="button" onClick={()=>location.reload()}>إعادة المحاولة</button></p>:data&&<><div className="adaptive-practice-list">{data.recommendations.filter(r=>isCyberHref(r.href)).length?data.recommendations.filter(r=>isCyberHref(r.href)).map(r=><a className="adaptive-practice" href={r.href} key={r.id}><div className="between"><span className={'adaptive-priority '+r.priority.toLowerCase()}>{labels[r.priority]}</span><span className="adaptive-type">{types[r.kind]}</span></div><h3>{r.title}</h3><strong>{r.target}{r.mastery!==null?` · إتقان تقديري ${r.mastery}%`:''}</strong><p>{r.why.join(' ')}</p><span className="adaptive-action">ابدأ التدريب <ArrowLeft size={16}/></span></a>):<div className="adaptive-empty"><strong>لا تظهر حاجة تدريب محددة الآن.</strong><p>يمكنك متابعة قضية NexaCorp أو الرجوع إلى المعرفة السيبرانية، وستتغير الاقتراحات مع نتائج جديدة.</p></div>}</div>
 <div className="adaptive-signals"><div><h3>تحتاج ممارسة</h3>{data.needsPractice.length?data.needsPractice.map(s=><p key={s.id}><span>{skillTitles[s.id]||s.name}</span><b>{s.mastery}%</b></p>):<p>لا توجد فجوة مؤكدة في النتائج الحالية.</p>}</div><div><h3>مهارات قوية</h3>{data.strongSkills.length?data.strongSkills.map(s=><p key={s.id}><span>{skillTitles[s.id]||s.name}</span><b>{s.mastery}%</b></p>):<p>ستظهر هنا بعد تنوع الممارسة وتحسن النتائج.</p>}</div></div></>}
 </section>}
export function SkillMastery({skill}:{skill:MasteryState|undefined}){if(!skill)return <p className="adaptive-muted">جارٍ حساب الإتقان من نتائجك…</p>;return <div className="adaptive-skill-mastery"><div className="between"><strong>الإتقان · {skill.mastery===null?'بيانات غير كافية':skill.mastery+'%'}</strong><span>{masteryLabels[skill.band]}</span></div><p>{skill.samples?`أنشطة التقييم المحفوظة: ${skill.samples} · ${skill.confidence==='established'?'ثقة جيدة':'تقدير أولي'}`:'أكمل تقييمًا أو مختبرًا لبدء تقدير الإتقان.'}</p>{skill.mastery!==null&&<div className="mission-meter" role="progressbar" aria-label={'إتقان '+skill.name} aria-valuenow={skill.mastery} aria-valuemin={0} aria-valuemax={100}><span style={{width:skill.mastery+'%'}}/></div>}{skill.subskills.filter(s=>s.samples>0).length>0&&<details><summary>التفصيل حسب المهارات الفرعية</summary><ul>{skill.subskills.filter(s=>s.samples>0).map(s=><li key={s.id}><span>{skillTitles[s.id]||s.name}</span><b>{s.mastery}% · {masteryLabels[s.band]}</b></li>)}</ul></details>}</div>}
export function MasteryIntro(){return <p className="adaptive-intro"><ChartNoAxesCombined size={17}/> الإتقان تقدير مبني على درجات التدريب ومحاولاته والتلميحات والأخطاء؛ يتغير ببيانات جديدة ولا يمثل نقاط المهارات.</p>}
