import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const require=createRequire(import.meta.url),{build}=createRequire(require.resolve('vite/package.json'))('esbuild');
const db=new DatabaseSync(':memory:');
for(const file of ['drizzle/0010_old_blade.sql','drizzle/0011_swift_hiroim.sql'])db.exec((await readFile(file,'utf8')).replaceAll('--> statement-breakpoint',''));
db.exec("CREATE TABLE progress(user_id TEXT,item_id TEXT,kind TEXT,score INTEGER,xp INTEGER,completed_at TEXT,PRIMARY KEY(user_id,item_id)); CREATE TABLE skill_awards(user_id TEXT,source_kind TEXT,source_id TEXT,skill_id TEXT,xp INTEGER,created_at TEXT,PRIMARY KEY(user_id,source_kind,source_id,skill_id));CREATE TABLE soc_investigations(user_id TEXT,alert_id TEXT,status TEXT,closed_at TEXT,PRIMARY KEY(user_id,alert_id));CREATE TABLE mission_progress(user_id TEXT,mission_id TEXT,started_at TEXT,PRIMARY KEY(user_id,mission_id));");
db.prepare('INSERT INTO progress VALUES(?,?,?,?,?,?)').run('legacy','boss:boss-002','boss',100,340,'2026-09-24T00:00:00Z');
db.prepare('INSERT INTO investigation_workspaces(user_id,investigation_id,status,created_at,updated_at) VALUES(?,?,?,?,?)').run('legacy','soc-SOC-002','closed','2026-09-24','2026-09-24');
const fake={prepare(sql){return {bind(...args){const stmt=db.prepare(sql);return {first:async()=>stmt.get(...args)||null,all:async()=>({results:stmt.all(...args)}),run:async()=>stmt.run(...args)}}}},batch:async statements=>{db.exec('BEGIN');try{for(const stmt of statements)await stmt.run();db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}};
globalThis.__dynamicTestDb=fake;
const fixture=`export {generateIncident,difficultyFromSeed} from './lib/dynamic-incidents.ts';export {startDynamicIncident,getDynamicIncident,listDynamicIncidents} from './lib/dynamic-storage.ts';export {readInvestigation,writeInvestigation} from './lib/investigation-storage.ts';`;
const plugin={name:'fixture',setup(b){b.onResolve({filter:/^fixture$/},()=>({path:'fixture',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:fixture,resolveDir:process.cwd(),loader:'ts'}));b.onResolve({filter:/^\.\/storage$/},()=>({path:'test-db',namespace:'test-db'}));b.onLoad({filter:/.*/,namespace:'test-db'},()=>({contents:'export const database=()=>globalThis.__dynamicTestDb;',loader:'js'}))}};
const bundle=await build({entryPoints:['fixture'],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',plugins:[plugin]});
const runtime=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const {generateIncident,startDynamicIncident,getDynamicIncident,listDynamicIncidents,readInvestigation,writeInvestigation}=runtime;
for(const template of ['phishing','endpoint','network-auth'])for(const [tier,difficulty] of ['beginner','intermediate','advanced'].entries())for(let low=0;low<35;low++){
 const seed=((tier<<30)|(low*9176+124))>>>0,incident=generateIncident(template,seed),again=generateIncident(template,seed);
 assert.deepEqual(incident,again,'same template and seed reproduce the same incident');
 assert.equal(incident.difficulty,difficulty);
 assert.equal(incident.board.nodes.find(n=>n.id===incident.affectedEntities[0]).companyRef?.id,incident.affectedEntities[0].slice(8));
 assert.equal(incident.successConditions.requiredEvidenceIds.length,2);
 assert.equal(incident.successConditions.requiredLinks.length,tier===2?3:2);
 assert.ok(incident.evidence.some(e=>e.role==='supporting')&&incident.evidence.some(e=>e.role==='distractor'));
 assert.ok(incident.board.evidence.every(e=>e.entities.every(id=>incident.board.nodes.some(n=>n.id===id))));
 assert.ok(incident.board.nodes.filter(n=>n.companyRef).every(n=>n.companyRef.id===n.id.split(':').slice(1).join(':')));
}
assert.notDeepEqual(generateIncident('phishing',34).evidence,generateIncident('phishing',35).evidence);
const user='legacy',first=await startDynamicIncident(user,'endpoint','beginner','resume'),id='dynamic-'+first.instanceId;
assert.equal(first.created,true);assert.equal((await startDynamicIncident(user,'endpoint','advanced','resume')).instanceId,first.instanceId);
assert.equal(await getDynamicIncident('another-account',first.instanceId),null);
let state=await readInvestigation(user,id),instance=await getDynamicIncident(user,first.instanceId);
assert.equal(state.review,null,'review hidden before decision');assert.equal('expected' in state.board,false);assert.equal('allowedLinks' in state.board,false);
assert.ok(state.board.evidence.every(e=>e.role==='unclassified'),'evidence role hidden before final decision');
assert.equal(state.incident.seed,instance.seed);
await assert.rejects(writeInvestigation('other',id,{action:'review',evidenceId:'process'}),/غير موجود/);
await assert.rejects(writeInvestigation(user,id,{action:'collect',evidenceId:'process'}),/راجع/);
for(const evidenceId of instance.successConditions.requiredEvidenceIds){await writeInvestigation(user,id,{action:'review',evidenceId});await writeInvestigation(user,id,{action:'collect',evidenceId});await writeInvestigation(user,id,{action:'collect',evidenceId})}
state=await readInvestigation(user,id);assert.equal(state.evidence.length,2);
await writeInvestigation(user,id,{action:'annotate',evidenceId:instance.successConditions.requiredEvidenceIds[0],note:'ربط المصدر بالجهاز',classification:'relevant'});
await assert.rejects(writeInvestigation(user,id,{action:'link',fromId:instance.affectedEntities[0],toId:'ip:203.0.113.1',relation:'SPAWNED',reason:'علاقة غير منطقية'}),/غير صالحة/);
for(const l of instance.successConditions.requiredLinks){await writeInvestigation(user,id,{action:'link',...l,reason:'ظهر الربط في سجلي العمليات والشبكة'});await writeInvestigation(user,id,{action:'link',...l,reason:'كرر هذا الدليل بالخطأ'})}
state=await readInvestigation(user,id);assert.equal(state.links.length,2);
const answer={hypothesis:instance.validConclusions[0],affected:[instance.affectedEntities[0]],evidenceIds:instance.successConditions.requiredEvidenceIds,action:'contain'};
state=await writeInvestigation(user,id,{action:'decide',decision:{...answer,hypothesis:'routine'}});assert.equal(state.workspace.status,'open');assert.ok(state.review);
state=await writeInvestigation(user,id,{action:'decide',decision:{...answer,affected:[...answer.affected,`employee:${instance.affectedEntities[0].slice(8)}`]}});assert.equal(state.workspace.status,'open','unrelated affected entity cannot make an answer correct');
state=await writeInvestigation(user,id,{action:'decide',decision:answer});assert.equal(state.workspace.status,'contained');assert.equal(state.review.missedEvidence.length,0);
assert.equal(state.review.missedLinks.length,0);
state=await writeInvestigation(user,id,{action:'reopen'});assert.equal(state.workspace.status,'open');assert.equal(state.incident.seed,instance.seed);assert.equal(state.evidence.length,2);
state=await writeInvestigation(user,id,{action:'decide',decision:answer});assert.equal(state.workspace.status,'contained');
const other=await startDynamicIncident(user,'endpoint','advanced','new');assert.notEqual(other.instanceId,first.instanceId);
assert.equal((await getDynamicIncident(user,first.instanceId)).seed,instance.seed,'old variant immutable after new variant');
assert.equal((await listDynamicIncidents(user)).active.endpoint,other.instanceId);
assert.equal((await readInvestigation('other','soc-SOC-002')).workspace.status,'open');
assert.equal((await readInvestigation(user,'soc-SOC-002')).workspace.status,'closed','v42 workspace preserved');
assert.equal(db.prepare('SELECT xp FROM progress WHERE user_id=?').get(user).xp,340);
assert.equal(db.prepare('SELECT COUNT(*) AS n FROM skill_awards').get().n,0);
console.log('PASS: 315 deterministic valid incidents, three difficulty tiers, immutable instances, board/locker/decision/review, replay/new variant, duplicate rejection, account isolation, old V42 data and unchanged XP.');
