// Deterministic invariants + actual built Worker APIs against disposable local D1.
import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {readFile,readdir,mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare}=await import(wr.resolve('miniflare')),{build}=createRequire(require.resolve('vite/package.json'))('esbuild');
const bundled=await build({stdin:{contents:"export {generateIncident} from './lib/dynamic-incidents';export {assertIncidentIntegrity} from './lib/dynamic-variation';export {validateDecision} from './lib/investigation-storage';export {dynamicReturnPath,dynamicKnowledge} from './lib/dynamic-presentation';export {publicLessons} from './lib/curriculum';",resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',plugins:[{name:'pure-validation',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'cloudflare',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const env={};',loader:'js'}));}}]});
const {generateIncident,assertIncidentIntegrity,validateDecision,dynamicReturnPath,dynamicKnowledge,publicLessons}=await import('data:text/javascript;base64,'+Buffer.from(bundled.outputFiles[0].text).toString('base64'));
const totals={incident:0,approved:0,blocked:0},fixtures=new Map(),people=new Set();
for(const template of ['phishing','endpoint','network-auth'])for(let n=0;n<600;n++){
 const seed=(((n%3)<<30)|(n*9176+124))>>>0,i=generateIncident(template,seed,undefined,2);assert.deepEqual(i,generateIncident(template,seed,undefined,2));assertIncidentIntegrity(i);totals[i.integrity.verdict]++;people.add(i.integrity.employeeId);
 const decision={hypothesis:i.validConclusions[0],affected:i.affectedEntities,evidenceIds:i.successConditions.requiredEvidenceIds,action:i.recommendedActions[0]},links=i.successConditions.requiredLinks.map(l=>({...l,reason:'ربط المصادر والتوقيت',createdAt:'now'}));
 assert.equal(validateDecision(i.board,decision,decision.evidenceIds,links),true);assert.equal(validateDecision(i.board,{...decision,hypothesis:'unrelated'},decision.evidenceIds,links),false);
 if(i.difficulty==='intermediate'&&!fixtures.has(template+':'+i.integrity.verdict))fixtures.set(template+':'+i.integrity.verdict,i);
 for(const mutate of [s=>s.integrity.officeIp='192.0.2.1',s=>s.events[0].time='bad',s=>s.evidence[0].raw+='\nextra=forged',s=>s.board.expected.hypothesis='unrelated',s=>s.successConditions.requiredEvidenceIds=[]]){const bad=structuredClone(i);mutate(bad);assert.throws(()=>assertIncidentIntegrity(bad));}
}
assert.equal(people.size,4);assert.equal(fixtures.size,7);assert(Object.values(totals).every(n=>n>0));assert.equal(dynamicReturnPath('//evil.example'),null);assert.equal(dynamicReturnPath('/investigations/dynamic-endpoint-00000001?step=observe&field=process&bad=1'),'/investigations/dynamic-endpoint-00000001?step=observe&field=process');for(const k of Object.values(dynamicKnowledge))assert(publicLessons().some(l=>l.id===k.lessonId));
const dir=await mkdtemp(join(tmpdir(),'cyberlab-dynamic-v2-')),modules=['index.js',...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js')].map(f=>({type:'ESModule',path:'dist/server/'+f})),options={modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:dir,cf:false};let worker;
async function call(path,user='existing',body){const headers=user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{};if(body)headers['Content-Type']='application/json';const r=await worker.dispatchFetch('http://local.test'+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};}
async function post(id,body,user='existing'){const r=await call('/api/investigations/'+id,user,body);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;}
const at='2026-09-24T12:00:00Z';let restoreState,first;
try{
 worker=new Miniflare(options);let db=await worker.getD1Database('DB');for(const f of (await readdir('drizzle')).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())for(const sql of (await readFile('drizzle/'+f,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 await db.prepare('INSERT INTO progress VALUES(?,?,?,?,?,?)').bind('existing','boss:boss-002','boss',100,340,at).run();
 let ordinal=0;for(const [key,i] of fixtures){await db.prepare('INSERT INTO dynamic_incidents VALUES(?,?,?,?,?,?,?,?)').bind('existing',i.instanceId,i.templateId,++ordinal,i.seed,i.difficulty,JSON.stringify(i),at).run();const id=i.board.id;
  assert.equal((await call('/api/investigations/'+id,null)).status,401);assert.equal((await call('/api/investigations/'+id,'other')).status,404);assert.equal((await call('/api/investigations/'+id,'other',{action:'review',evidenceId:i.evidence[0].id})).status,404);
  let state=(await call('/api/investigations/'+id)).data;assert.equal(state.review,null);assert(!('expected' in state.board));assert(!('integrity' in state.incident));assert(state.board.evidence.every(e=>!e.raw&&e.role==='unclassified'));
  for(const evidenceId of i.successConditions.requiredEvidenceIds){await post(id,{action:'review',evidenceId});await post(id,{action:'collect',evidenceId});await post(id,{action:'collect',evidenceId});}
  state=await post(id,{action:'annotate',evidenceId:i.successConditions.requiredEvidenceIds[0],note:'ملاحظة تربط معرف الحدث بالمصدرين',classification:'relevant'});assert.equal(state.evidence.length,i.successConditions.requiredEvidenceIds.length);
  assert.equal((await call('/api/investigations/'+id,'existing',{action:'link',fromId:i.affectedEntities[0],toId:'ip:203.0.113.1',relation:'SPAWNED',reason:'علاقة غير منطقية'})).status,400);
  for(const l of i.successConditions.requiredLinks){await post(id,{action:'link',...l,reason:'تطابق معرف الحدث والحساب في المصادر.'});await post(id,{action:'link',...l,reason:'محاولة تكرار العلاقة نفسها'});}
  const answer={hypothesis:i.validConclusions[0],affected:i.affectedEntities,evidenceIds:i.successConditions.requiredEvidenceIds,action:i.recommendedActions[0]};
  state=await post(id,{action:'decide',decision:{...answer,hypothesis:'unrelated'}});assert.equal(state.workspace.status,'open');assert.equal(state.review,null);assert(state.feedback.observation);assert.equal(state.links.length,i.successConditions.requiredLinks.length);
  if(!first){first=i;restoreState={...state};delete restoreState.message;await worker.dispose();worker=new Miniflare(options);db=await worker.getD1Database('DB');assert.deepEqual((await call('/api/investigations/'+id)).data,restoreState);}
  const concurrent=await Promise.all([call('/api/investigations/'+id,'existing',{action:'decide',decision:answer}),call('/api/investigations/'+id,'existing',{action:'decide',decision:{...answer,hypothesis:'unrelated'}}),call('/api/investigations/'+id,'existing',{action:'decide',decision:answer})]);assert(concurrent.some(r=>r.status===200));state=(await call('/api/investigations/'+id)).data;assert.notEqual(state.workspace.status,'open');assert(state.review);
  await post(id,{action:'reopen'});state=(await call('/api/investigations/'+id)).data;assert.equal(state.feedback,null);assert.equal(state.review,null);await post(id,{action:'decide',decision:answer});
 }
 // Old immutable snapshot remains usable and receives no v2 interpretation.
 const legacy=generateIncident('endpoint',37);await db.prepare('INSERT INTO dynamic_incidents VALUES(?,?,?,?,?,?,?,?)').bind('existing',legacy.instanceId,legacy.templateId,9,legacy.seed,legacy.difficulty,JSON.stringify(legacy),at).run();assert.equal((await call('/api/investigations/'+legacy.board.id)).data.incident.generationVersion,undefined);
 // Both creation and resume exercise the built API, including simultaneous variants.
 const created=await call('/api/incidents','zero',{templateId:'endpoint',difficulty:'intermediate',mode:'new'});assert.equal(created.status,200);const current=created.data.instanceId;assert.equal((await call('/api/investigations/dynamic-'+current,'zero')).data.incident.generationVersion,2);assert.equal((await call('/api/incidents','zero',{templateId:'endpoint',difficulty:'advanced',mode:'resume'})).data.instanceId,current);
 const concurrent=await Promise.all([call('/api/incidents','zero',{templateId:'endpoint',difficulty:'beginner',mode:'new'}),call('/api/incidents','zero',{templateId:'endpoint',difficulty:'beginner',mode:'new'})]);assert(concurrent.every(r=>r.status===200));assert.notEqual(concurrent[0].data.instanceId,concurrent[1].data.instanceId);const variants=(await call('/api/incidents','zero')).data.instances;assert.equal(new Set(variants.map(r=>r.variantNumber)).size,3);
 assert.equal((await call('/api/investigations/dynamic-'+current,'existing')).status,404);assert.equal((await call('/api/investigations/'+first.board.id,'zero')).status,404);
 const xp=await db.prepare('SELECT xp FROM progress WHERE user_id=?').bind('existing').first();assert.equal(xp.xp,340);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM skill_awards').first()).n,0);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM progress WHERE user_id=?').bind('zero').first()).n,0);
 const p=await call('/api/progression');assert.equal(p.status,200);assert.equal(p.data.xp,340);assert.equal(p.data.achievements.find(a=>a.id==='investigator').value,3,'Variants normalize to templates; no achievement farming');
 console.log('PASS: 1800 deterministic variants / 600 seeds; '+JSON.stringify(totals)+'; 7 real Worker investigations; restart persistence, wrong/correct, concurrent completion, creation, replay, ownership, old data and unchanged XP/Skill XP.');
 console.log('Browser fixtures: '+JSON.stringify([...fixtures].map(([key,i])=>({key,seed:i.seed,id:i.instanceId}))));
}finally{await worker?.dispose();await rm(dir,{recursive:true,force:true});}
