import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import {hasCommit,skipBaseline} from './helpers/git-baseline.mjs';
import {readFile,readdir,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,relative} from 'node:path';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=await import(wranglerRequire.resolve('miniflare'));
const {build}=createRequire(require.resolve('vite/package.json'))('esbuild');
const baseline='8dd247a2ae5c6248f6c86c116156d9e9d42e1acf',hasBaseline=hasCommit(baseline);
async function load(entry,previous=false){const b=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',plugins:previous?[{name:'baseline',setup(b){b.onLoad({filter:/\/lib\/.*\.ts$/},a=>({loader:'ts',contents:execFileSync('git',['show',baseline+':'+relative(process.cwd(),a.path)],{encoding:'utf8'})}))}}]:[]});return import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'))}
const curriculum=await load('lib/curriculum.ts'),previous=hasBaseline?await load('lib/curriculum.ts',true):null,labs=await load('lib/interactive-labs.ts'),previousLabs=hasBaseline?await load('lib/interactive-labs.ts',true):null,scope=await load('lib/content-scope.ts'),core=await load('lib/mission-first-core.ts'),search=await load('lib/site-search.ts');
assert.equal(curriculum.lessons.length,220);assert.deepEqual(scope.scopeCounts(),{CYBER_CORE:135,CYBER_SUPPORTING:60,OUT_OF_SCOPE:25});
const contracts=m=>m.lessons.map(l=>({id:l.id,track:l.track,level:l.level,module:l.module,questions:l.questions,prerequisites:l.prerequisites}));if(hasBaseline){assert.deepEqual(contracts(curriculum),contracts(previous),'no IDs, quiz contract or existing prerequisite changes');assert.deepEqual(curriculum.labs,previous.labs);assert.deepEqual(labs.interactiveLabs,previousLabs.interactiveLabs,'no lab definitions/rewards/unlocks added or changed')}else skipBaseline(baseline,'curriculum/lab contract comparison');
for(const id of ['security-5','security-6','web-7','web-9','web-security-7','web-security-12','network-security-1','web-10','web-security-6']){const l=curriculum.lessons.find(x=>x.id===id);assert(l.sections.length>=3);assert(!l.sections.some(s=>s.text.includes('المفهوم المجاور')));assert(l.code.includes('\n'),'reference adds a concrete comparison beyond the card')}
const directory=await mkdtemp(join(tmpdir(),'cyberlab-final-qa-')),uiDir=await mkdtemp(resolve('.sites-runtime/final-qa-ui-'));
const modules=['index.js',...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js')].map(f=>({type:'ESModule',path:'dist/server/'+f}));const options={modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:directory,cf:false};let worker;
async function call(path,body,user='existing'){const headers={};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}if(body!==undefined)headers['Content-Type']='application/json';const r=await worker.dispatchFetch('http://local.test'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()}}
async function action(path,body,user='existing'){const r=await call(path,body,user);assert.equal(r.status,200,JSON.stringify(r.data));return r.data}
let iconNames=new Set();for(const root of ['app','components'])for(const f of await readdir(root,{recursive:true})){if(!/\.(t|j)sx?$/.test(f))continue;const text=await readFile(join(root,f),'utf8');for(const m of text.matchAll(/import\s*\{([^}]+)\}\s*from\s*['"]lucide-react['"]/g))for(const n of m[1].split(',')){const id=n.trim().replace(/^type /,'').split(/\s+as\s+/)[0];if(/^[A-Za-z]\w*$/.test(id))iconNames.add(id)}}
const components={};const entries={dashboard:'app/dashboard.tsx',progress:'app/progress/page.tsx',soc:'app/soc/alerts/[id]/guided.tsx',lesson:'app/learn/[id]/view.tsx',search:'app/search/results.tsx',catalog:'app/labs/page.tsx',library:'app/learn/cyber-library.tsx',access:'app/labs/v2/[id]/offensive.tsx',track:'app/practice/offensive/page.tsx'};
for(const [id,entry] of Object.entries(entries)){
 const b=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',external:['react/jsx-runtime'],plugins:[{name:'ui-hooks',setup(b){b.onResolve({filter:/^(react|lucide-react|@\/app\/shell|\.\.?\/shell|@\/components\/native-link|@\/components\/ui\/(progress|tabs|radio-group)|\.\/adaptive\/overview|\.\/career\/view|\.\/rank\/experience)$/},a=>({path:a.path,namespace:'harness'}));b.onLoad({filter:/.*/,namespace:'harness'},a=>({loader:'js',contents:
 a.path==='react'?`export const useState=v=>globalThis.qaHooks.useState(v),useEffect=(f,d)=>globalThis.qaHooks.useEffect(f,d),useRef=v=>globalThis.qaHooks.useRef(v);`:
 a.path.endsWith('/shell')?`export const useProgress=()=>globalThis.qaProgress;`:
 a.path==='lucide-react'?[...iconNames].map(n=>`export const ${n}=()=>null;`).join('\n'):
 a.path==='@/components/native-link'?`import {jsx} from 'react/jsx-runtime';export default p=>{const q={...p};const k=q.key;delete q.key;return jsx('a',q,k)};`:
 a.path.endsWith('/progress')?`import {jsx} from 'react/jsx-runtime';export const Progress=p=>jsx('span',{'data-progress':p.value});`:
 a.path.endsWith('/tabs')?`import {jsx} from 'react/jsx-runtime';export const Tabs=p=>{globalThis.qaTabChange=p.onValueChange;return jsx('div',{children:[p.children].flat().filter(x=>!x?.props?.value||x.props.value===(p.value??p.defaultValue))})};export const TabsList=p=>jsx('nav',p),TabsContent=p=>jsx('section',p),TabsTrigger=p=>jsx('button',{children:p.children,onClick:()=>globalThis.qaTabChange(p.value)});`:
 a.path.endsWith('/radio-group')?`import {jsx} from 'react/jsx-runtime';export const RadioGroup=p=>jsx('fieldset',p),RadioGroupItem=p=>jsx('input',{...p,type:'radio'});`:
 `export default ()=>null;export const CareerCard=()=>null,RankSummary=()=>null,RankExperience=()=>null;`}))}}]});const file=join(uiDir,id+'.mjs');await writeFile(file,b.outputFiles[0].text);components[id]=(await import(pathToFileURL(file))).default;
}
// Keyed hook frames emulate component boundaries, not a browser or DOM renderer.
let frames=new Map(),frame,dirty=false,effects=[],tree,Component,props,uiUser,pending=new Set(),seen=new Set();
globalThis.qaHooks={useState(v){const i=frame.index++,f=frame;if(!f.slots[i])f.slots[i]={value:typeof v==='function'?v():v};return [f.slots[i].value,n=>{f.slots[i].value=typeof n==='function'?n(f.slots[i].value):n;dirty=true}]},useRef(v){const i=frame.index++;if(!frame.slots[i])frame.slots[i]={current:v};return frame.slots[i]},useEffect(fn,deps){const i=frame.index++,f=frame;if(!f.slots[i]||!deps||deps.some((d,j)=>d!==f.slots[i].deps?.[j])){f.slots[i]?.cleanup?.();f.slots[i]={deps};effects.push(()=>{f.slots[i].cleanup=fn()})}}};
function execute(fn,p,key){let f=frames.get(key);if(!f){f={slots:[],index:0};frames.set(key,f)}seen.add(key);const parent=frame;frame=f;f.index=0;const result=fn(p);frame=parent;return resolveTree(result,key+'/out')}
function resolveTree(node,path){if(Array.isArray(node))return node.map((n,i)=>resolveTree(n,path+'/'+(n?.key||i)));if(node&&typeof node==='object'&&node.props){if(typeof node.type==='function')return execute(node.type,node.props,path+'/'+(node.type.name||'component'));return {...node,props:{...node.props,children:resolveTree(node.props.children,path+'/children')}}}return node}
function cleanup(){for(const f of frames.values())for(const s of f.slots)s?.cleanup?.();frames=new Map()}
function render(){dirty=false;seen=new Set();tree=execute(Component,props,'root');for(const [key,f] of frames)if(!seen.has(key)){for(const s of f.slots)s?.cleanup?.();frames.delete(key)}for(const e of effects.splice(0))e()}
async function settle(){for(let i=0;i<24;i++){if(pending.size)await Promise.all([...pending]);await new Promise(r=>setImmediate(r));if(dirty)render()}assert.equal(pending.size,0);assert(!dirty)}
function nodes(node,out=[],visible=false){if(arguments.length===0)node=tree;if(Array.isArray(node)){for(const n of node)nodes(n,out,visible)}else if(node&&typeof node==='object'&&node.props){out.push(node);if(visible&&node.type==='details'&&!node.props.open)nodes([node.props.children].flat().filter(n=>n?.type==='summary'),out,visible);else nodes(node.props.children,out,visible)}return out}
function textOf(n){if(n==null||typeof n==='boolean')return '';if(Array.isArray(n))return n.map(textOf).join('');return typeof n==='object'?textOf(n.props?.children):String(n)}
function element(type,label){const e=nodes().find(n=>n.type===type&&textOf(n).includes(label));assert(e,`missing ${type}: ${label}; screen ${textOf(tree)}`);return e}
const primary=()=>nodes(tree,[],true).filter(n=>['a','button'].includes(n.type)&&n.props.className==='primary-button');
async function click(label){const n=element('button',label);assert(!n.props.disabled);n.props.onClick();await settle()}
function locationAt(path){globalThis.location={href:new URL(path,'http://local.test').href,search:new URL(path,'http://local.test').search,reload(){throw Error('unexpected reload')}};globalThis.history={replaceState(_a,_b,p){locationAt(p)}};globalThis.window={location,history}}
const storage=new Map();globalThis.sessionStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};globalThis.document={visibilityState:'hidden',addEventListener(){},removeEventListener(){}};
let deferBoard=false,heldBoard;
const oldFetch=globalThis.fetch;globalThis.fetch=(path,init={})=>{assert(String(path).startsWith('/api/'),'UI must use local APIs only');const headers={...init.headers};if(uiUser){headers['oai-authenticated-user-id']=uiUser;headers['oai-authenticated-user-email']=uiUser+'@example.test'}const p=(async()=>{const r=await worker.dispatchFetch('http://local.test'+path,{...init,headers});return new Response(await r.text(),{status:r.status,headers:r.headers})})();pending.add(p);p.finally(()=>pending.delete(p));return deferBoard&&String(path)==='/api/investigations/soc-SOC-002'?p.then(response=>new Promise(resolve=>{heldBoard=()=>resolve(response)})):p};
async function mount(name,user='existing',p={},path='/'){cleanup();uiUser=user;Component=components[name];props=p;locationAt(path);globalThis.qaProgress={user:user?{email:user+'@example.test'}:null,items:user?(await call('/api/progress',undefined,user)).data.items:[],learning:user?(await call('/api/learning',undefined,user)).data:{activity:[],dailyTime:[],attempts:[],bookmarks:[],notes:[],preferences:{dailyGoal:15}},loading:false,error:'',refresh:async()=>{},update:async()=>{}};render();await settle()}
async function snapshot(user){const db=await worker.getD1Database('DB'),out={};for(const table of ['progress','activity','skill_awards','skill_progress','career_promotions','mission_progress','interactive_lab_progress','soc_investigations','investigation_workspaces','investigation_evidence','investigation_links'])out[table]=(await db.prepare('SELECT * FROM '+table+' WHERE user_id=? ORDER BY rowid').bind(user).all()).results;return out}
async function finishSoc(user,correct=true){const post=(actionName,more={})=>action('/api/soc/alerts/SOC-002',{action:actionName,...more},user);await post('start');await post('triage',{priority:'Critical',reason:'توجد جلسة ناجحة غير مألوفة تحتاج فحص الحساب والجهاز.'});for(const evidenceId of ['sessions','device']){await post('inspect',{evidenceId});await post('collect',{evidenceId})}const definition=await call('/api/soc/alerts/SOC-002',undefined,user);await post('tool',{toolId:definition.data.alert.tools[0].id});await post('decide',{verdict:correct?'true_positive':'false_positive',conclusion:'قارنت الجلسة الناجحة وبصمة الجهاز والمصدر في دليلين مستقلين.'});await post('respond',{response:correct?'contain':'dismiss',reason:'الإجراء المقترح محدد بالحساب والجلسة ويستند إلى المقارنة.'});await post('document',{caseNote:{observation:'ظهر نجاح من متصفح غير مسجل بجانب نشاط الحساب المعتاد.',evidenceRefs:['sessions','device'],assessment:'المصادر تصف الحساب والجلسة؛ لم يثبت اختراق محطة الموظفة.',actionTaken:correct?'contain':'dismiss',owner:'SOC Lead',nextStep:'تحقق مع الموظفة وراجع الجلسات بعد الإجراء المحاكى.'}});return post('close')}
try{
 worker=new Miniflare(options);const db=await worker.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 await mount('dashboard','zero',{lessons:curriculum.publicLessons()});assert.equal(primary().length,1);assert.equal(primary()[0].props.href,'/experience/nexacorp-first');assert(!nodes(tree,[],true).some(n=>n.props.href==='/tracks/it'));
 for(const id of ['it-2','net-1'])await db.prepare('INSERT INTO progress VALUES(?,?,?,?,?,?)').bind('existing',id,'quiz',3,100,'2026-07-01').run();await action('/api/learning',{action:'read',id:'py-1',seconds:30});await action('/api/learning',{action:'read',id:'security-8',seconds:30});await call('/api/skills');await call('/api/career');const before=await snapshot('existing');await mount('dashboard','existing',{lessons:curriculum.publicLessons()});assert.equal(primary().length,1);assert.equal(primary()[0].props.href,'/learn/security-8');assert(!primary().some(n=>n.props.href==='/experience/nexacorp-first'));assert(!primary().some(n=>n.props.href==='/learn/py-1'));assert.deepEqual(await snapshot('existing'),before);await mount('dashboard','existing',{lessons:curriculum.publicLessons()});assert.deepEqual(await snapshot('existing'),before);
 for(const l of curriculum.lessons.filter(l=>scope.isCyberLesson(l.id)))await db.prepare('INSERT INTO activity VALUES(?,?,?,?,?,?)').bind('complete-library',l.id,'2026-07-01','2026-07-01',30,'2026-07-01').run();await mount('dashboard','complete-library',{lessons:curriculum.publicLessons()});assert.equal(primary().length,1);assert.equal(primary()[0].props.href,'/practice');assert(textOf(tree).includes('أكملت المراجع السيبرانية الحالية'));assert(!textOf(primary()[0]).includes('ابدأ الدرس'));
 await action('/api/interactive-labs/v2-http',{action:'start'});await mount('catalog');assert.equal(element('a','تابع المختبر').props.href,'/labs/v2/v2-http');assert(textOf(element('section','تتبّع طلب الويب')).includes('تابع مختبرك'),'in-progress lab is featured as the lab to continue');await mount('search','existing',{results:search.searchResults.filter(r=>r.href==='/labs/v2/v2-http')});assert(textOf(tree).includes('قيد التقدم'));const select=nodes(element('label','الحالة')).find(n=>n.type==='select');select.props.onChange({target:{value:'active'}});await settle();assert(nodes().some(n=>n.type==='a'&&n.props.href==='/labs/v2/v2-http'));
 // All basic locked requirements lead to existing reachable references/activities.
 const list=(await call('/api/interactive-labs',undefined,'zero')).data.labs;for(const lab of list.filter(l=>l.access?.locked)){const d=(await call('/api/interactive-labs/'+lab.id,undefined,'zero')).data;assert(d.access.requirements.some(r=>!r.done));for(const r of d.access.requirements)assert.equal((await worker.dispatchFetch('http://local.test'+r.href)).status,200,r.href);assert.equal((await call('/api/interactive-labs/'+lab.id,{action:'start'},'zero')).status,400)}
 await action('/api/learning',{action:'complete',id:'security-6'},'unlock');for(const body of [{action:'start'},...['H01','H02'].flatMap(key=>['request','response'].map(value=>({action:'inspect',key,value}))),{action:'submit',method:'get',unauthorized:'401',authorized:'200',difference:'Cookie'}])await action('/api/interactive-labs/v2-http',body,'unlock');for(const id of ['v2-attack-surface','v2-access-control'])assert.equal((await call('/api/interactive-labs/'+id,undefined,'unlock')).data.access.locked,false);await mount('search','unlock',{results:search.searchResults.filter(r=>r.href==='/labs/v2/v2-attack-surface')});assert(textOf(tree).includes('متاح'));assert(!textOf(tree).includes('المتبقي للفتح'));
 // Viewing progress with every lab completed is read-only (the old lab counter is no longer part of this page).
 for(const l of [...curriculum.labs,...labs.interactiveLabs])await db.prepare('INSERT INTO progress VALUES(?,?,?,?,?,?)').bind('all-labs',l.id,'lab',100,75,'2026-07-01').run();const labBefore=await snapshot('all-labs');await mount('progress','all-labs');assert.deepEqual(await snapshot('all-labs'),labBefore);
 await mount('library','existing',{lessons:curriculum.publicLessons(),done:new Set()});assert(textOf(tree).includes('ثلاثة تقييمات عملية'));assert(!textOf(tree).includes('لم يُبنَ بعد'));assert(nodes().some(n=>n.type==='a'&&n.props.href==='/practice/offensive'));
 await mount('access',null,{track:true});const auth=new URL(primary()[0].props.href,'http://local.test');assert.equal(auth.searchParams.get('return_to'),'/labs/v2/v2-access-control?track=offensive');assert(textOf(tree).includes('أساسيات التقييم الهجومي'));
 const returnTo='/experience/nexacorp-first?step=inspect',lesson=curriculum.lessons.find(l=>l.id==='network-5');await mount('lesson','reader',{lesson,next:'network-6',returnTo},'/learn/network-5?return_to='+encodeURIComponent(returnTo));assert.equal(primary().length,1);assert.equal(primary()[0].props.href,returnTo);assert(textOf(primary()[0]).includes('طبّق ما تعلمت'));await click('اختبر فهمك اختياريًا');assert.equal(primary().length,1);const radios=nodes().filter(n=>n.type==='input'&&n.props.type==='radio');radios[0].props.onChange();await settle();for(const index of [0,1]){nodes().filter(n=>n.type==='input'&&n.props.type==='checkbox')[index].props.onChange({target:{checked:true}});await settle()}const practical=nodes().find(n=>n.type==='input'&&n.props['aria-label']);practical.props.onChange({target:{value:'/24'}});await settle();element('form','').props.onSubmit({preventDefault(){}});await settle();assert(textOf(tree).includes('اجتزت الاختبار'));assert.equal(primary().length,1);assert.equal(primary()[0].props.href,returnTo);assert(!nodes().some(n=>n.type==='a'&&n.props.href==='/learn/network-6'));const readerRewards=(await call('/api/progress',undefined,'reader')).data.items;assert.equal(readerRewards.reduce((n,r)=>n+r.xp,0),100);await action('/api/submit',{kind:'quiz',id:'network-5',answers:[0,[0,1],'/24']},'reader');assert.deepEqual((await call('/api/progress',undefined,'reader')).data.items,readerRewards);
 await mount('lesson',null,{lesson,next:'network-6',returnTo},'/learn/network-5?return_to='+encodeURIComponent(returnTo));const guestAuth=nodes().filter(n=>n.type==='a'&&String(n.props.href).startsWith('/signin-with-chatgpt'));assert(guestAuth.length);assert(guestAuth.every(n=>new URL(n.props.href,'http://local.test').searchParams.get('return_to')==='/learn/network-5?return_to='+encodeURIComponent(returnTo)));
 // Product audit: preserving context through a reference's optional lab and prerequisites.
 await mount('lesson','reader',{lesson,next:'network-6',returnTo},'/learn/network-5?return_to='+encodeURIComponent(returnTo));
 // Lessons opened from a case no longer offer a side lab (LessonPracticeRoute/LabBridge stay hidden);
 // any lab link that is shown must still carry the case context.
 for(const l of nodes().filter(n=>n.type==='a'&&String(n.props.href).startsWith('/labs/v2/')))assert.equal(new URL(l.props.href,'http://local.test').searchParams.get('return_to'),returnTo);
 const prerequisite=nodes().find(n=>n.type==='a'&&String(n.props.href).startsWith('/learn/network-1'));
 assert.equal(new URL(prerequisite.props.href,'http://local.test').searchParams.get('return_to'),returnTo);
 // Real asynchronous source ordering: SOC arrives before the board. Do not downgrade the return URL.
 const resumeUser='delayed-board';
 await action('/api/soc/alerts/SOC-002',{action:'start'},resumeUser);
 await action('/api/soc/alerts/SOC-002',{action:'triage',priority:'Critical',reason:'فحص جلسة ناجحة غير معتادة يتطلب مقارنة المصادر.'},resumeUser);
 for(const evidenceId of ['sessions','device']){await action('/api/soc/alerts/SOC-002',{action:'inspect',evidenceId},resumeUser);await action('/api/soc/alerts/SOC-002',{action:'collect',evidenceId},resumeUser)}
 const alert=(await call('/api/soc/alerts/SOC-002',undefined,resumeUser)).data.alert;
 await action('/api/soc/alerts/SOC-002',{action:'tool',toolId:alert.tools[0].id},resumeUser);
 deferBoard=true;await mount('soc',resumeUser,{},core.coreJourney.socHref+'&step=decision');
 assert.equal(new URL(location.href).searchParams.get('step'),'decision','wait for both sources before correcting a saved step');
 assert(heldBoard);deferBoard=false;heldBoard();await settle();
 assert(textOf(tree).includes('استنتاجك المستقل'));assert.equal(new URL(location.href).searchParams.get('step'),'decision');
 await mount('soc',resumeUser,{},core.coreJourney.socHref+'&step=decision');assert(textOf(tree).includes('استنتاجك المستقل'));
 // A wrong saved SOC result used to loop through a completed board. Reopen is now the primary action.
 const wrong=await finishSoc('needs-review',false);assert.equal(wrong.state.session.lastResult.correct,false);const wrongBefore=await snapshot('needs-review');await mount('dashboard','needs-review',{lessons:curriculum.publicLessons()});assert.equal(primary().length,1);assert.equal(primary()[0].props.href,core.coreJourney.socHref);assert(textOf(primary()[0]).includes('أعد فحص'));assert.deepEqual(await snapshot('needs-review'),wrongBefore);await mount('soc','needs-review',{},core.coreJourney.socHref);assert.equal(primary().length,1);assert.equal(primary()[0].type,'button');assert(textOf(primary()[0]).includes('أعد فحص'));assert.deepEqual(await snapshot('needs-review'),wrongBefore);await click('أعد فحص التنبيه');assert.equal((await call('/api/soc/alerts/SOC-002',undefined,'needs-review')).data.state.closedAt,null);assert(textOf(tree).includes('ما أولوية'));assert.equal(primary().length,1);await finishSoc('needs-review',true);await mount('soc','needs-review',{},core.coreJourney.socHref);assert.equal(primary()[0].props.href,'/progress');const socDone=await snapshot('needs-review');await action('/api/soc/alerts/SOC-002',{action:'reopen'},'needs-review');await finishSoc('needs-review',true);assert.deepEqual((await snapshot('needs-review')).skill_awards,socDone.skill_awards);assert.equal((await call('/api/progress',undefined,'needs-review')).data.items.length,0);
 await cleanup();const preserved=await snapshot('existing');await worker.dispose();worker=new Miniflare(options);assert.deepEqual(await snapshot('existing'),preserved);await mount('dashboard','existing',{lessons:curriculum.publicLessons()});assert.equal(primary()[0].props.href,'/learn/security-8');assert.equal((await call('/api/progress',undefined,'zero')).data.items.length,0);assert.equal((await call('/api/progress',undefined,null)).status,401);
 for(const href of ['/','/learn','/roadmap','/practice','/operations','/practice/offensive','/experience/nexacorp-first','/experience/nexacorp-email','/campaigns/first-signal','/soc/alerts/SOC-002?view=guided','/investigations/soc-SOC-002?journey=core','/search?q=surface'])assert.equal((await worker.dispatchFetch('http://local.test'+href)).status,200,href);
 console.log('PASS: Version 51 ID/quiz/prerequisite/lab/reward contracts preserved; zero/existing/returning/exhausted Dashboard, read-only old/archived progress, started-lab Search/catalog state, real lock requirements/unlock/URLs, 22-lab counter, existing offensive discovery/auth return, full Knowledge lesson and optional quiz return/replay, wrong SOC primary retry/recovery, persistence/isolation. Compiled UI + isolated local Worker/D1; no real browser/Production OAuth/iPhone/Safari or human-usability study.');
}finally{cleanup();globalThis.fetch=oldFetch;if(worker)await worker.dispose();await rm(directory,{recursive:true,force:true});await rm(uiDir,{recursive:true,force:true})}
