import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=await import(wranglerRequire.resolve('miniflare'));
const {build}=createRequire(require.resolve('vite/package.json'))('esbuild');
const built=await build({entryPoints:['lib/interactive-labs.ts'],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});
const {interactiveLabs}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const modules=['index.js',...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js')].map(f=>({type:'ESModule',path:'dist/server/'+f}));
const directory=await mkdtemp(join(tmpdir(),'cyberlab-interactive-'));
const options={modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:directory,cf:false};let worker;
async function call(path,body,user='learner'){const headers={};if(body!==undefined)headers['Content-Type']='application/json';if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}const r=await worker.dispatchFetch('http://local.test'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()}}
const url=id=>'/api/interactive-labs/'+id;
async function action(id,kind,extra={}){const r=await call(url(id),{action:kind,...extra});assert.equal(r.status,200,JSON.stringify({id,kind,data:r.data}));return r.data.state}
const xp=async()=> (await call('/api/progress')).data.items.reduce((total,item)=>total+item.xp,0);
const skills=async()=>Object.fromEntries((await call('/api/skills')).data.skills.map(s=>[s.id,s.xp]));
async function solveTerminal(){const id='v2-terminal';await action(id,'start');assert.equal((await call(url(id),{action:'submit',path:'/srv/audit/report.txt',owner:'atlas'})).data.state.session.lastResult.passed,false);for(const input of ['pwd','ls','cat README.txt','find /srv -name report.txt','cat /srv/audit/report.txt','ps'])await action(id,'command',{input});const done=await action(id,'submit',{path:'/srv/audit/report.txt',owner:'atlas'});assert(done.session.lastResult.passed);return done}
async function solveLogs(){const id='v2-logs';await action(id,'start');assert.equal((await call(url(id),{action:'mark',key:'L04'})).status,400);await action(id,'filter',{filters:{type:'Authentication',user:'admin',from:'2026-09-24T09:02:00Z',to:'2026-09-24T09:05:00Z'}});for(const key of ['L04','L07','L08'])await action(id,'mark',{key});assert.equal((await action(id,'log-auth',{ip:'198.51.100.25',user:'admin'})).session.logAuthSolved,false);let phase=await action(id,'log-auth',{ip:'198.51.100.24',user:'admin'});assert(phase.session.logAuthSolved);await action(id,'filter',{filters:{type:'Endpoint',host:'APP-02'}});for(const key of ['L14','L15'])await action(id,'mark',{key});assert.equal((await action(id,'correlate',{key:'endpoint-chain',host:'APP-02',indicator:'powershell.exe',value:'dismiss'})).session.logSolved.length,0);phase=await action(id,'correlate',{key:'endpoint-chain',host:'APP-02',indicator:'report-viewer.exe',value:'investigate'});assert.equal(phase.session.logSolved.length,1);await action(id,'filter',{filters:{type:'Firewall',host:'APP-02'}});for(const key of ['L17','L18'])await action(id,'mark',{key});phase=await action(id,'correlate',{key:'network-chain',host:'APP-02',indicator:'203.0.113.77',value:'contain'});assert.equal(phase.session.logSolved.length,2);const done=await action(id,'submit');assert(done.session.lastResult.passed);return done}
async function solveEmail(){const id='v2-email';await action(id,'start');const verdicts={E01:'legitimate',E02:'suspicious',E03:'phishing'};for(const key of Object.keys(verdicts)){for(const value of ['headers','url','replyTo','attachment'])await action(id,'inspect',{key,value});await action(id,'classify',{key,value:verdicts[key]})}for(const value of ['replyTo','headers'])await action(id,'mark',{key:'E03',value});const done=await action(id,'submit');assert(done.session.lastResult.passed);return done}
async function solveNetwork(){const id='v2-network';await action(id,'start');const cases=[['wrong-ip','ip','192.168.50.21'],['wrong-gateway','gateway','192.168.50.1'],['dhcp-failure','dhcp','on'],['dns-error','dns','192.168.50.53'],['isolated-host','port','on']];for(const [key,field,value] of cases){await action(id,'inspect',{key});let state=await action(id,'test',{key});assert(state.session.networkOutput.includes('فشل'));await action(id,'configure',{key,field,value});state=await action(id,'test',{key});assert(state.session.networkOutput.includes('نجاح'))}assert.equal((await call(url(id),{action:'submit'})).data.state.session.lastResult.passed,false);const transports=[['file-transfer','tcp'],['voice-call','udp'],['dns-query','udp'],['web-session','tcp'],['live-stream','udp']];for(const [key,value] of transports){await action(id,'transport-trace',{key});if(key==='voice-call')assert.equal((await action(id,'transport',{key,value:'tcp'})).session.transportSolved.includes(key),false);const state=await action(id,'transport',{key,value});assert(state.session.transportSolved.includes(key))}const flows=[['return-flow','192.168.50.21:51514','translate'],['missing-session','mapping','policy'],['branch-route','route','add-route']];for(const [key,answer,value] of flows){for(const part of ['device','gateway','route'])await action(id,'network-view',{key,value:part});if(key==='missing-session')assert.equal((await action(id,'network-resolve',{key,answer:'gateway',value:'change-gateway'})).session.networkSolved.includes(key),false);const state=await action(id,'network-resolve',{key,answer,value});assert(state.session.networkSolved.includes(key))}const done=await action(id,'submit');assert(done.session.lastResult.passed);return done}
async function solveHttp(){const id='v2-http';await action(id,'start');for(const key of ['H01','H02'])for(const value of ['request','response'])await action(id,'inspect',{key,value});const done=await action(id,'submit',{method:'get',unauthorized:'401',authorized:'200',difference:'Cookie'});assert(done.session.lastResult.passed);return done}
try{worker=new Miniflare(options);const db=await worker.getD1Database('DB');for(const migration of (await readdir('drizzle')).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())for(const sql of (await readFile('drizzle/'+migration,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 assert.equal(interactiveLabs.length,8);assert.equal((await call('/api/interactive-labs')).data.labs.length,8);assert.equal((await call(url('v2-terminal'),undefined,null)).status,401);assert.equal((await call(url('bad-id'))).status,404);
 const prior='2026-09-20T10:00:00Z';await db.prepare('INSERT INTO progress(user_id,item_id,kind,score,xp,completed_at) VALUES(?,?,?,?,?,?)').bind('learner','net-1','quiz',3,100,prior).run();
 const t=await solveTerminal();assert.equal(t.attempts,2);await solveLogs();await solveEmail();await solveNetwork();await solveHttp();assert.equal(await xp(),475);
 const earned=await skills();assert(earned.linux>0&&earned.logs>0&&earned.phishing>0&&earned.networking>0&&earned.cybersecurity>0);
 const contributions=(await call('/api/skills')).data.skills.find(s=>s.id==='linux').contributions;assert(contributions.some(c=>c.kind==='lab'&&c.id==='v2-terminal'));
 let list=(await call('/api/interactive-labs')).data.labs;assert.equal(list.filter(l=>l.state?.completedAt).length,5);assert.equal((await call('/api/interactive-labs',undefined,'other')).data.labs.filter(l=>l.state).length,0);
 await action('v2-terminal','replay');for(const input of ['cat README.txt','find /srv -name report.txt','cat /srv/audit/report.txt','ps'])await action('v2-terminal','command',{input});const replay=await action('v2-terminal','submit',{path:'/srv/audit/report.txt',owner:'atlas'});assert.equal(replay.session.lastResult.xpGranted,false);assert.equal(replay.session.lastResult.skillGranted,false);assert(replay.bestScore>=t.bestScore);assert.equal(await xp(),475);assert.deepEqual(await skills(),earned);
 await action('v2-terminal','replay');await action('v2-terminal','scenario',{key:'dns'});assert.equal((await call(url('v2-terminal'))).data.state.session.terminalScenarioId,'dns');assert.equal((await call(url('v2-terminal'),{action:'scenario',key:'bogus'})).status,400);for(const input of ['cat README.txt','cat /etc/resolv.conf','ip','ping 203.0.113.10','nslookup portal.training'])await action('v2-terminal','command',{input});const dns=await action('v2-terminal','submit',{path:'DNS',owner:'192.168.50.53'});assert(dns.session.lastResult.passed);assert.equal(dns.session.lastResult.xpGranted,false);assert.equal(dns.session.lastResult.skillGranted,false);assert.equal(await xp(),475);assert.deepEqual(await skills(),earned);
 await action('v2-logs','replay');await action('v2-logs','filter',{filters:{type:'Authentication',user:'admin'}});await action('v2-logs','mark',{key:'L04'});assert.equal((await call(url('v2-logs'))).data.state.completedAt!==null,true);
 let fresh=await call(url('v2-http'),{action:'start'},'new-learner');assert.equal(fresh.status,200);assert.equal(fresh.data.state.completedAt,null);assert.equal((await call('/api/progress',undefined,'new-learner')).data.items.length,0);
 const oldMission=(await call('/api/missions')).data;assert.equal(oldMission.states.filter(s=>s.completedAt).length,0);assert.equal((await call('/api/learning')).status,200);assert.equal((await call('/api/campaigns/first-signal')).status,200);assert.equal((await call('/api/soc')).status,200);
 await worker.dispose();worker=new Miniflare(options);list=(await call('/api/interactive-labs')).data.labs;assert.equal(list.filter(l=>l.state?.completedAt).length,5);assert.deepEqual((await call(url('v2-logs'))).data.state.session.evidence,['L04']);assert.equal((await call(url('v2-terminal'))).data.state.session.lastResult.passed,true);assert.equal((await call(url('v2-http'),undefined,'new-learner')).data.state.completedAt,null);assert.equal(await xp(),475);assert.deepEqual(await skills(),earned);
 console.log('PASS: five lab types end-to-end, two independent terminal scenarios, D1 reload/restart, existing 100 XP preserved, 75 XP each first completion, skill awards once, replay, filters/evidence, virtual commands, email comparison, five network faults, five transport decisions, three NAT/routing investigations, endpoint/network correlation, HTTP, auth/isolation and learning/mission/campaign/SOC regressions.');
}finally{if(worker)await worker.dispose();await rm(directory,{recursive:true,force:true})}
