import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const require=createRequire(import.meta.url),{build}=createRequire(require.resolve('vite/package.json'))('esbuild');
const db=new DatabaseSync(':memory:');
db.exec((await readFile('drizzle/0010_old_blade.sql','utf8')).replaceAll('--> statement-breakpoint',''));
db.exec("CREATE TABLE progress(user_id TEXT,item_id TEXT,kind TEXT,score INTEGER,xp INTEGER,completed_at TEXT,PRIMARY KEY(user_id,item_id));CREATE TABLE skill_awards(user_id TEXT,source_kind TEXT,source_id TEXT,skill_id TEXT,xp INTEGER,created_at TEXT,PRIMARY KEY(user_id,source_kind,source_id,skill_id));CREATE TABLE soc_investigations(user_id TEXT,alert_id TEXT,status TEXT,closed_at TEXT,PRIMARY KEY(user_id,alert_id));");
db.prepare('INSERT INTO progress VALUES(?,?,?,?,?,?)').run('existing','boss:boss-002','boss',100,340,'2026-09-24T15:47:57Z');
db.prepare('INSERT INTO soc_investigations VALUES(?,?,?,?)').run('existing','SOC-002','Closed','2026-09-24T15:47:57Z');
const fake={prepare(sql){return {bind(...args){const statement=db.prepare(sql);return {first:async()=>statement.get(...args)||null,all:async()=>({results:statement.all(...args)}),run:async()=>statement.run(...args)}}}},batch:async statements=>{for(const stmt of statements)await stmt.run()}};
globalThis.__investigationTestDb=fake;
const bundle=await build({entryPoints:['lib/investigation-storage.ts'],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',plugins:[{name:'test-db',setup(build){build.onResolve({filter:/^\.\/storage$/},()=>({path:'test-db',namespace:'test-db'}));build.onLoad({filter:/.*/,namespace:'test-db'},()=>({contents:'export const database=()=>globalThis.__investigationTestDb;',loader:'js'}))}}]});
const {readInvestigation,writeInvestigation,validateDecision}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const id='soc-SOC-002',user='existing';
let state=await readInvestigation(user,id);
assert.equal(state.workspace.status,'open');
assert.equal(state.board.evidence.length,3);
assert.equal(state.board.nodes.find(n=>n.id==='device:WKST-02').companyRef.id,'WKST-02');
await assert.rejects(writeInvestigation(user,id,{action:'collect',evidenceId:'sessions'}),/راجع/);
await writeInvestigation(user,id,{action:'review',evidenceId:'sessions'});
await writeInvestigation(user,id,{action:'review',evidenceId:'sessions'});
await writeInvestigation(user,id,{action:'collect',evidenceId:'sessions'});
await writeInvestigation(user,id,{action:'collect',evidenceId:'sessions'});
state=await readInvestigation(user,id);
assert.equal(state.evidence.length,1);
assert.equal(state.evidence[0].evidenceId,'sessions');
await assert.rejects(writeInvestigation(user,id,{action:'link',fromId:'employee:layla',toId:'ip:198.51.100.77',relation:'SPAWNED',reason:'غير ممكن في السجل'}),/غير صالحة/);
await assert.rejects(writeInvestigation(user,id,{action:'link',fromId:'employee:layla',toId:'account:layla',relation:'USES',reason:'قصير'}),/8 أحرف/);
const link={action:'link',fromId:'employee:layla',toId:'account:layla',relation:'USES',reason:'حساب ليلى يعود إلى الموظفة في السجل'};
await writeInvestigation(user,id,link);await writeInvestigation(user,id,link);
state=await readInvestigation(user,id);assert.equal(state.links.length,1);
await writeInvestigation(user,id,{action:'annotate',evidenceId:'sessions',classification:'relevant',note:'جلسة جديدة من مصدر مختلف'});
assert.equal((await readInvestigation(user,id)).board.evidence.find(e=>e.id==='sessions').raw,state.board.evidence.find(e=>e.id==='sessions').raw);
await assert.rejects(writeInvestigation(user,id,{action:'decide',decision:{hypothesis:'compromised',affected:['account:layla'],evidenceIds:['sessions'],action:'contain'}}),/اجمع الأدلة المطلوبة/);
await writeInvestigation(user,id,{action:'review',evidenceId:'device'});await writeInvestigation(user,id,{action:'collect',evidenceId:'device'});
const choice={hypothesis:'compromised',affected:['account:layla'],evidenceIds:['sessions','device'],action:'contain'};
assert.equal('expected' in state.board,false,'answer key must remain server-side');
state=await writeInvestigation(user,id,{action:'decide',decision:{...choice,affected:['device:WKST-02']}});assert.equal(state.workspace.status,'open','unrelated device cannot close investigation');
state=await writeInvestigation(user,id,{action:'decide',decision:choice});assert.equal(state.workspace.status,'contained');
await assert.rejects(writeInvestigation(user,id,{action:'collect',evidenceId:'email'}),/افتح التحقيق/);
state=await readInvestigation(user,id);assert.deepEqual(state.workspace.decision,choice);
state=await writeInvestigation(user,id,{action:'reopen'});assert.equal(state.workspace.status,'open');assert.equal(state.links.length,1);assert.equal(state.evidence.filter(e=>e.collectedAt).length,2);
state=await writeInvestigation(user,id,{action:'decide',decision:choice});assert.equal(state.workspace.status,'contained');
assert.equal((await readInvestigation('another-user',id)).evidence.length,0);
assert.equal(db.prepare('SELECT xp FROM progress WHERE user_id=?').get(user).xp,340);
assert.equal(db.prepare('SELECT COUNT(*) AS n FROM skill_awards').get().n,0);
assert.equal(db.prepare('SELECT closed_at AS closedAt FROM soc_investigations WHERE user_id=?').get(user).closedAt,'2026-09-24T15:47:57Z');
console.log('PASS: three source definitions; durable review/collect/annotations, duplicate and invalid links, structured decision, existing completion, replay, user isolation and unchanged rewards.');
