import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=await import(wranglerRequire.resolve('miniflare'));
const {build}=createRequire(require.resolve('vite/package.json'))('esbuild');
async function load(entry){const b=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});return import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'))}
const core=await load('lib/mission-first-core.ts'),email=await load('lib/mission-first-email.ts'),pilot=await load('lib/mission-first-pilot.ts'),socDefinitions=await load('lib/soc-alerts.ts'),curriculum=await load('lib/curriculum.ts');
const firstSocAlert=socDefinitions.socAlertById(core.coreJourney.socId);
assert.equal(core.signalMission.id,'boss-002');assert.equal(firstSocAlert.id,'SOC-002');
assert(core.isCoreBeginner([{id:'mission:003'},{id:'boss:boss-002'}],[{id:'security-8'}]));assert(!core.isCoreBeginner([{id:'mission:004'}],[]));
assert.equal(core.coreNextStep(false,false,true,false,false).href,core.coreJourney.socHref,'existing completions do not force earlier replay');
for(const path of [core.coreJourney.signalHref+'?step=evidence&field=email',core.coreJourney.socHref+'&step=evidence&field=sessions',core.coreJourney.boardHref+'&step=links'])assert.equal(pilot.pilotReturnPath(path),path);
for(const path of ['//evil.test/campaigns/first-signal','https://evil.test/campaigns/first-signal','/soc/alerts/SOC-002','/campaigns/first-signal?view=full'])assert.equal(core.coreReturnPath(path),null);
const directory=await mkdtemp(join(tmpdir(),'cyberlab-core-')),uiDir=await mkdtemp(resolve('.sites-runtime/core-ui-'));
const modules=['index.js',...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js')].map(f=>({type:'ESModule',path:'dist/server/'+f}));
const options={modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:directory,cf:false};let worker;
async function call(path,body,user='learner'){const headers={};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}if(body!==undefined)headers['Content-Type']='application/json';const r=await worker.dispatchFetch('http://local.test'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()}}
async function action(path,body,user='learner'){const r=await call(path,body,user);assert.equal(r.status,200,JSON.stringify(r.data));return r.data}
const entries={dashboard:'app/dashboard.tsx',network:'app/experience/nexacorp-first/workspace.tsx',email:'app/experience/nexacorp-email/workspace.tsx',signal:'app/campaigns/[id]/guided.tsx',soc:'app/soc/alerts/[id]/guided.tsx',board:'app/investigations/[id]/guided.tsx',start:'app/experience/core-start.tsx'};
const components={};
for(const [id,entry] of Object.entries(entries)){
 const result=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',external:['react/jsx-runtime'],plugins:[{name:'hooks',setup(b){b.onResolve({filter:/^(react|lucide-react|@\/app\/progression\/view|@\/app\/shell|\.\.?\/shell|@\/components\/native-link|@\/components\/ui\/progress|@\/components\/ui\/radio-group|\.\/adaptive\/overview|\.\/career\/view|\.\/rank\/experience)$/},a=>({path:a.path,namespace:'harness'}));b.onLoad({filter:/.*/,namespace:'harness'},a=>({loader:'js',contents:a.path==='@/app/progression/view'?`export const CompletionProgressSummary=()=>null;`:a.path==='react'?`export const useState=(v)=>globalThis.coreHooks.useState(v),useEffect=(f,d)=>globalThis.coreHooks.useEffect(f,d),useRef=(v)=>globalThis.coreHooks.useRef(v);`:a.path.endsWith('/shell')?`export const useProgress=()=>globalThis.coreProgress;`:a.path==='@/components/native-link'?`import {jsx} from 'react/jsx-runtime';export default p=>jsx('a',p);`:a.path==='@/components/ui/radio-group'?`import {jsx} from 'react/jsx-runtime';export const RadioGroup=p=>jsx('div',p),RadioGroupItem=p=>jsx('button',{...p,role:'radio'});`:a.path==='@/components/ui/progress'?`export const Progress=()=>null;`:a.path==='lucide-react'?`export const Clock3=()=>null,Target=()=>null,Signal=()=>null,ArrowLeft=()=>null,ArrowRight=()=>null,CheckCircle2=()=>null,Lightbulb=()=>null,Mail=()=>null,Network=()=>null,ShieldCheck=()=>null,Code2=()=>null,Shield=()=>null,BookOpen=()=>null,Activity=()=>null,TrendingUp=()=>null,Trophy=()=>null,FlaskConical=()=>null;`:`export default ()=>null;export const CareerCard=()=>null,RankSummary=()=>null,RankExperience=()=>null;`}))}}]});
 const file=join(uiDir,id+'.mjs');await writeFile(file,result.outputFiles[0].text);components[id]=(await import(pathToFileURL(file))).default;
}
// These are actual compiled workspace handlers/effects against the real worker,
// with only React hooks/context replaced. This is not browser/visual/OAuth QA.
const storage=new Map();globalThis.sessionStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
const preferences=new Map();globalThis.localStorage={getItem:k=>preferences.get(k)||null,setItem:(k,v)=>preferences.set(k,v),removeItem:k=>preferences.delete(k)};
function locationAt(path){globalThis.location={href:new URL(path,'http://local.test').href,search:new URL(path,'http://local.test').search,reload(){throw Error('unexpected reload')}};globalThis.history={replaceState(_s,_t,p){location.href=new URL(p,'http://local.test').href;location.search=new URL(p,'http://local.test').search}};globalThis.window={location,history}}
let slots=[],index=0,dirty=false,effects=[],tree,pending=new Set(),uiUser=null,Component,advanced=false;
const oldFetch=globalThis.fetch;
globalThis.fetch=(path,init={})=>{const headers={...init.headers};if(uiUser){headers['oai-authenticated-user-id']=uiUser;headers['oai-authenticated-user-email']=uiUser+'@example.test'}const p=(async()=>{const r=await worker.dispatchFetch('http://local.test'+path,{...init,headers});return new Response(await r.text(),{status:r.status,headers:r.headers})})();pending.add(p);p.finally(()=>pending.delete(p));return p};
globalThis.coreHooks={useState(v){const i=index++;if(!slots[i])slots[i]={value:typeof v==='function'?v():v};return [slots[i].value,n=>{slots[i].value=typeof n==='function'?n(slots[i].value):n;dirty=true}]},useRef(v){const i=index++;if(!slots[i])slots[i]={current:v};return slots[i]},useEffect(f,deps){const i=index++;if(!slots[i]||deps.some((d,j)=>d!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>{slots[i].cleanup=f()})}}};
function materialize(node){if(Array.isArray(node))return node.map(materialize);if(node&&typeof node==='object'&&node.props){if(typeof node.type==='function')return materialize(node.type(node.props));return {...node,props:{...node.props,children:materialize(node.props.children)}}}return node}
function render(){index=0;dirty=false;tree=materialize(Component({lessons:curriculum.publicLessons(),onAdvanced:()=>{advanced=true}}));for(const e of effects.splice(0))e()}
async function settle(){for(let i=0;i<16;i++){if(pending.size)await Promise.all([...pending]);await new Promise(r=>setImmediate(r));if(dirty)render()}assert.equal(pending.size,0);assert(!dirty,'hooks must settle')}
function nodes(node,out=[]){if(arguments.length===0)node=tree;if(Array.isArray(node)){for(const child of node)nodes(child,out)}else if(node&&typeof node==='object'&&node.props){if(typeof node.type==='function')nodes(node.type(node.props),out);else{out.push(node);nodes(node.props.children,out)}}return out}
function textOf(node){if(node==null||typeof node==='boolean')return '';if(Array.isArray(node))return node.map(textOf).join('');if(typeof node==='string'||typeof node==='number')return String(node);return typeof node.type==='function'?textOf(node.type(node.props)):textOf(node.props?.children)}
function element(type,label){const node=nodes().find(n=>n.type===type&&textOf(n).includes(label));assert(node,`missing ${type}: ${label}; screen: ${textOf(tree)}`);return node}
async function click(label){const n=element('button',label);assert(!n.props.disabled,`disabled ${label}`);n.props.onClick();await settle()}
async function submit(){const f=element('form','');f.props.onSubmit({preventDefault(){}});await settle()}
async function change(type,label,value){const labelNode=element('label',label),n=nodes(labelNode).find(n=>n.type===type);assert(n,`missing ${type} inside ${label}`);n.props.onChange({target:{value}});await settle()}
async function check(label){const n=nodes(element('label',label)).find(n=>n.type==='input'&&n.props.type==='checkbox');assert(n);if(!n.props.checked){n.props.onChange({target:{checked:true}});await settle()}}
async function mount(id,user='learner',path=({network:pilot.firstPilot.href,email:email.emailExperience.href,signal:core.coreJourney.signalHref,soc:core.coreJourney.socHref,board:core.coreJourney.boardHref,start:'/',dashboard:'/'}[id])){for(const slot of slots)slot?.cleanup?.();slots=[];uiUser=user;Component=components[id];globalThis.coreProgress={items:user?(await call('/api/progress',undefined,user)).data.items:[],learning:user?(await call('/api/learning',undefined,user)).data:{activity:[]},user:user?{email:user+'@example.test',name:user}:null,loading:false,error:'',refresh:async()=>{}};locationAt(path);render();await settle()}
async function followPrimary(){const a=nodes().find(n=>n.type==='a'&&n.props.className==='primary-button');assert(a,'the next action must be a visible link');const route=new URL(a.props.href,'http://local.test');const dest=route.pathname.startsWith('/experience/nexacorp-first')?'network':route.pathname.startsWith('/experience/nexacorp-email')?'email':route.pathname.startsWith('/campaigns/')?'signal':route.pathname.startsWith('/soc/alerts/')?'soc':route.pathname.startsWith('/investigations/')?'board':null;assert(dest,'unexpected journey destination '+a.props.href);await mount(dest,uiUser,a.props.href)}
function onePrimary(){assert.equal(nodes().filter(n=>['a','button'].includes(n.type)&&n.props.className==='primary-button').length,1)}
async function snapshot(user){const db=await worker.getD1Database('DB'),out={};for(const table of ['progress','skill_awards','mission_progress','soc_investigations','investigation_workspaces','investigation_evidence','investigation_links'])out[table]=(await db.prepare('SELECT * FROM '+table+' WHERE user_id=? ORDER BY rowid').bind(user).all()).results;return out}
async function rewardSnapshot(user='learner'){return {items:(await call('/api/progress',undefined,user)).data.items.map(({score,...i})=>i),skills:(await call('/api/skills',undefined,user)).data.skills.map(s=>[s.id,s.xp])}}
async function finishSignal(user='learner'){const post=(actionName,more={})=>action('/api/missions',{id:'boss-002',action:actionName,...more},user);await post('start');for(const evidenceId of ['email','activity','auth-log'])await post('inspect',{evidenceId});for(const toolId of ['domain','auth','ip'])await post('tool',{toolId});await post('decide',{decisionId:'contain',response:'إنهاء جلسات ليلى وإعادة تعيين كلمة المرور'});await post('decide',{decisionId:'preserve',response:'حفظ الرسالة والترويسة والسجلات وإبلاغ فريق الأمن'});return post('solve',{answers:{account:'layla',ip:'198.51.100.77',sequence:'phishing email link credentials unauthorized login'}})}
async function finishSoc(user='learner'){const post=(actionName,more={})=>action('/api/soc/alerts/SOC-002',{action:actionName,...more},user);await post('start');await post('triage',{priority:'Critical',reason:'جلسة غير معتادة تحتاج إلى فحص عاجل لمالك الحساب.'});for(const evidenceId of ['sessions','device']){await post('inspect',{evidenceId});await post('collect',{evidenceId})}await post('tool',{toolId:firstSocAlert.tools[0].id});await post('decide',{verdict:'true_positive',conclusion:'قارنت الحساب ومصدر الجلسة وبصمة الجهاز وزمن النشاط في مصدرين.'});await post('respond',{response:'contain',reason:'احتواء الجلسة غير المألوفة يتناسب مع أدلة الحساب وبصمة الجهاز.'});await post('document',{caseNote:{observation:'ظهرت جلسة ناجحة غير مألوفة بجانب جلسة الجهاز المعتاد.',evidenceRefs:['sessions','device'],assessment:'توافق المصدر وبصمة الجهاز غير المسجلة يدعم اختراق الحساب.',actionTaken:'contain',owner:'SOC Lead',nextStep:'متابعة الجلسات والتحقق مع الموظفة من أثر احتواء الحساب.'}});return post('close')}
try{
 worker=new Miniflare(options);const db=await worker.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 // Optional entry choices personalize only a fresh start, never saved training.
 await mount('start','entry-user');onePrimary();
 for(const [label,value] of [['خبرتك الحالية','foundation'],['هدفك الأول','defense']]){nodes().find(n=>n.props['aria-label']===label).props.onValueChange(value);await settle()}
 const beforePreference=await rewardSnapshot('entry-user');await click('طبّق اقتراح البداية');assert.equal(element('a','افحص الرسالة').props.href,email.emailExperience.href);assert.deepEqual(await rewardSnapshot('entry-user'),beforePreference);
 await mount('start','entry-user');assert.equal(element('a','افحص الرسالة').props.href,email.emailExperience.href,'preference restores on this device');
 await mount('start','entry-other');assert.equal(element('a','افتح البلاغ').props.href,pilot.firstPilot.href,'another account must not inherit the entry choice');
 await action('/api/interactive-labs/'+pilot.firstPilot.labId,{action:'start'},'entry-user');await mount('start','entry-user');assert.equal(element('a','افتح البلاغ').props.href,pilot.firstPilot.href,'started network work overrides preferred email');
 await action('/api/missions',{id:'003',action:'start'},'entry-email');await mount('start','entry-email');assert.equal(element('a','افحص الرسالة').props.href,email.emailExperience.href,'started email must not redirect to network');
 preferences.set('cyberlab-start-preference:entry-other%40example.test','{"experience":["new"],"goal":"defense"}');await mount('start','entry-other');assert.equal(element('a','افتح البلاغ').props.href,pilot.firstPilot.href,'malformed device preference falls back safely');
 await click('تخطَّ التخصيص');assert.equal(preferences.has('cyberlab-start-preference:entry-other%40example.test'),false);
 await mount('dashboard');onePrimary();assert.equal(element('a','افتح البلاغ').props.href,pilot.firstPilot.href);
 await followPrimary();onePrimary();
 const ipLesson=element('a','راجع عنوان IP والقناع').props.href;
 assert.equal(new URL(ipLesson,'http://local.test').pathname,'/learn/network-5');
 assert.equal(new URL(ipLesson,'http://local.test').searchParams.get('return_to'),pilot.firstPilot.href+'?step=brief');
 await click('ابدأ الفحص');await click('افحص إعداد الجهاز');
 await mount('network','learner',pilot.firstPilot.href);
 assert(textOf(tree).includes('عنوان الجهاز والشبكة'),'re-entry must resume the inspected step');
 assert(textOf(tree).includes('255.255.255.0 (/24)'),'the comparison must include the mask, not only two IP addresses');
 storage.delete('cyberlab-network-view:learner%40example.test');
 await mount('network','learner',pilot.firstPilot.href);
 assert(textOf(tree).includes('عنوان الجهاز والشبكة'),'saved lab state resumes on a fresh device without a view draft');
 await click('اختبر الوصول');await click('فسّر ما لاحظته');
 const networkRewards=await rewardSnapshot();
 nodes().filter(n=>n.type==='input'&&n.props.type==='radio')[3].props.onChange();await settle();
 await click('تحقق من فرضيتك');
 assert(textOf(tree).includes('انقطاع الاتصال وحده لا يثبت اختراقًا'));
 assert.equal(nodes().filter(n=>n.type==='table'&&n.props.className==='network-result-compare').length,0,'a hypothesis is not a completed repair');
 nodes().filter(n=>n.type==='input'&&n.props.type==='radio')[0].props.onChange();await settle();
 await click('تحقق من فرضيتك');
 await change('select','أي عنوان',pilot.firstPilotCase.initial.gateway);await click('طبّق داخل المحاكاة');
 assert(textOf(tree).includes('هذا العنوان مستخدم للبوابة'));
 assert.equal(nodes().filter(n=>n.type==='table'&&n.props.className==='network-result-compare').length,0,'an incorrect address must not show success');
 await change('select','أي عنوان',pilot.firstPilotCase.fix.value);await click('طبّق داخل المحاكاة');
 onePrimary();
 const comparison=element('table','ما الذي تغيّر؟'),rows=nodes(comparison).filter(n=>n.type==='tr');
 assert.equal(rows.length,4);
 assert(textOf(rows[1]).includes(pilot.firstPilotCase.initial.ip));
 assert(textOf(rows[1]).includes(pilot.firstPilotCase.fix.value));
 assert.deepEqual(nodes(rows[2]).filter(n=>n.type==='bdi').map(textOf),[pilot.firstPilotCase.initial.gateway,pilot.firstPilotCase.initial.gateway],'repair must not imply a gateway change');
 assert(textOf(rows[3]).includes('فشلنجح'));
 assert(textOf(tree).includes('ليس إكمال المختبر كله'));
 assert.deepEqual(await rewardSnapshot(),networkRewards,'one guided device repair does not grant an extra lab completion or reward');
 assert.equal(element('a','خطوتك التالية').props.href,email.emailExperience.href);
 await mount('network','learner',pilot.firstPilot.href);
 assert(element('table','ما الذي تغيّر؟'),'saved repair must restore the evidence-based result');
 await followPrimary();await click('افحص الرسالة');await change('select','الفحص التالي','headers');await change('select','الفحص التالي','link');await click('ابنِ قرارك');nodes().filter(n=>n.type==='input'&&n.props.type==='radio')[2].props.onChange();await settle();for(let i=0;i<2;i++){nodes().filter(n=>n.type==='input'&&n.props.type==='checkbox')[i].props.onChange({target:{checked:true}});await settle()}await change('select','الإجراء','report');await click('أرسل القرار');assert.equal(element('a','خطوتك التالية').props.href,core.coreJourney.signalHref);
 await mount('dashboard');assert.equal(element('a','تابع القضية').props.href,core.coreJourney.signalHref);
 await followPrimary();onePrimary();assert(!textOf(tree).includes('Return-Path'));await click('افتح ملف القضية');assert(element('button','كوّن استنتاجك').props.disabled);
 await change('select','مصدر الفحص','email');const fullLesson=element('a','اقرأ الشرح الكامل').props.href;let r=await worker.dispatchFetch('http://local.test'+fullLesson);assert.equal(r.status,200);assert((await r.text()).includes('العودة إلى البلاغ'));const returnPath=new URL(fullLesson,'http://local.test').searchParams.get('return_to');await mount('signal','learner',returnPath);assert(textOf(tree).includes('اختلاف النطاق'));await click('عاين النطاق');await change('select','مصدر الفحص','activity');await change('select','مصدر الفحص','auth-log');await click('رشّح جلسات');await click('قارن نشاط');
 await mount('signal','learner',core.coreJourney.signalHref+location.search);assert(textOf(tree).includes('فشل الدخول أم جلسة'));await click('كوّن استنتاجك');await change('select','الحساب المتأثر','layla');await change('select','مصدر الجلسة','198.51.100.77');await change('select','تسلسل','phishing email link credentials unauthorized login');for(let i=0;i<2;i++){nodes().filter(n=>n.type==='input'&&n.props.type==='checkbox')[i].props.onChange({target:{checked:true}});await settle()}await change('select','إجراء الحساب','حظر مرسل البريد فقط مع إبقاء جلسة الحساب');await change('select','التعامل مع الأدلة','حفظ الرسالة والترويسة والسجلات وإبلاغ فريق الأمن');await submit();assert(textOf(tree).includes('راجع السجل'));assert(!(await call('/api/missions')).data.states.find(s=>s.id==='boss-002').completedAt);await click('راجع الدليل المخالف');await click('كوّن استنتاجك');await change('select','إجراء الحساب','إنهاء جلسات ليلى وإعادة تعيين كلمة المرور');await submit();assert(textOf(tree).includes('ربطت الرسالة'));assert.equal(element('a','خطوتك التالية').props.href,core.coreJourney.socHref);
 const campaign=(await call('/api/campaigns/first-signal')).data;assert(campaign.progress<100,'one case must not fake complete the six-chapter campaign');
 await followPrimary();onePrimary();assert(!textOf(tree).includes('Evidence Locker'));await click('افتح التنبيه');await change('select','الأولوية','Critical');await change('textarea','سبب الأولوية','جلسة جديدة على حساب الموظفة تستدعي فحصًا عاجلًا.');await submit();
 for(const id of ['sessions','device']){await change('select','مصدر الدليل',id);await click('اجمع الدليل')}
 let locker=(await call('/api/investigations/'+core.coreJourney.boardId)).data;assert.equal(locker.evidence.filter(e=>e.collectedAt).length,2);assert(locker.evidence.every(e=>e.reviewedAt));await click('الدليل محفوظ');assert.equal((await call('/api/investigations/'+core.coreJourney.boardId)).data.evidence.length,2,'mirrored collection is idempotent');
 onePrimary();assert(nodes().some(n=>n.type==='details'&&n.props.open&&textOf(n).includes('الفحص الزمني المطلوب')));await change('select','أداة المحاكاة',firstSocAlert.tools[0].id);await click('شغّل الفحص');const savedSoc=(await call('/api/soc/alerts/SOC-002')).data.state;await mount('soc','learner',core.coreJourney.socHref+'&step=evidence&field=device');assert.deepEqual((await call('/api/soc/alerts/SOC-002')).data.state,savedSoc);await click('اربط الأدلة');assert.equal(element('a','افتح التحقيق المرتبط').props.href,core.coreJourney.boardHref);
 await followPrimary();onePrimary();await click('اربط الكيانات');await change('select','من','account:layla');await change('select','إلى','evidence:sessions');await change('textarea','ما الملاحظة','ظهر الحساب والمصدر معًا في سجل الجلسة الناجحة.');const boardLesson=element('a','اقرأ الشرح الكامل').props.href;await mount('board','learner',new URL(boardLesson,'http://local.test').searchParams.get('return_to'));await submit();
 await change('select','ماذا حدث','normal');await check('layla');for(let i=0;i<2;i++){const refs=nodes().filter(n=>n.type==='fieldset').find(n=>textOf(n).includes('الأدلة التي تسند'));nodes(refs).filter(n=>n.type==='input')[i].props.onChange();await settle()}await change('select','الإجراء','monitor');await submit();assert(textOf(tree).includes('قارن سجل الجلسات'));assert.equal((await call('/api/investigations/'+core.coreJourney.boardId)).data.workspace.status,'open');await click('أعد مراجعة');await click('اربط الكيانات');await click('تابع فرضية');await change('select','ماذا حدث','compromised');await change('select','الإجراء','contain');await submit();assert.equal((await call('/api/investigations/'+core.coreJourney.boardId)).data.workspace.status,'contained');const socReturn=element('a','عد للتنبيه').props.href;
 await followPrimary();assert(location.href.endsWith(socReturn));await change('select','تصنيف التنبيه','true_positive');await change('textarea','كيف تسند','قارنت الجلسة الناجحة ومصدرها ببصمة الجهاز المعتاد وغير المسجل.');await submit();await change('select','الإجراء','contain');await change('textarea','لماذا يناسب','إنهاء الجلسة غير المعتادة وحماية الحساب يتناسبان مع الأدلة.');await submit();await change('textarea','ما الذي لاحظته','توجد جلسة ناجحة غير مألوفة بجانب الجلسة المعتادة للحساب.');for(let i=0;i<2;i++){nodes().filter(n=>n.type==='input'&&n.props.type==='checkbox')[i].props.onChange({target:{checked:true}});await settle()}await change('textarea','تقييمك','سجل الجلسة وبصمة الجهاز يدعمان وصولًا غير مشروع للحساب دون إثبات إصابة محطة العمل.');await change('input','مسؤول المتابعة','SOC Lead');await change('textarea','الخطوة التالية','التحقق مع الموظفة ومراقبة جلسات الحساب بعد الاحتواء.');await submit();assert(textOf(tree).includes('أكملت التحقيق والاستجابة'));onePrimary();assert((await call('/api/soc/alerts/SOC-002')).data.state.session.lastResult.correct);
 const rewards=await rewardSnapshot();assert.equal(rewards.items.reduce((n,i)=>n+i.xp,0),480);await mount('start');assert.equal(element('a','افتح متابعة ليلى').props.href,'/experience/nexacorp-response');
 const preserved=await snapshot('learner');for(const page of ['signal','soc','board'])await mount(page);assert.deepEqual(await snapshot('learner'),preserved,'opening completed UI must not mutate saved data');
 await action('/api/missions',{id:'boss-002',action:'replay'});assert.equal((await finishSignal()).state.session.lastResult.xpGranted,false);await action('/api/soc/alerts/SOC-002',{action:'reopen'});assert.equal((await finishSoc()).state.session.lastResult.skillAwardGranted,false);await action('/api/investigations/'+core.coreJourney.boardId,{action:'reopen'});await action('/api/investigations/'+core.coreJourney.boardId,{action:'decide',decision:{hypothesis:'compromised',affected:['account:layla'],evidenceIds:['sessions','device'],action:'contain'}});assert.deepEqual(await rewardSnapshot(),rewards,'replaying the new journey cannot farm rewards');
 const beforeRestart=await snapshot('learner');await worker.dispose();worker=new Miniflare(options);assert.deepEqual(await snapshot('learner'),beforeRestart);await mount('soc');assert(textOf(tree).includes('أكملت التحقيق'));await mount('board');assert(textOf(tree).includes('علاقاتك محفوظة'));
 await mount('signal','zero',core.coreJourney.signalHref+'?step=decision');assert(textOf(tree).includes('أكمل المتطلبات التالية ثم عد'));await mount('soc','zero',core.coreJourney.socHref+'&step=document');assert(textOf(tree).includes('افتح التنبيه'));await mount('board','zero',core.coreJourney.boardHref+'&step=decision');assert(textOf(tree).includes('ما الذي جمعته'));assert.equal((await call('/api/investigations/'+core.coreJourney.boardId,undefined,'zero')).data.evidence.length,0);
 await mount('signal',null);assert(textOf(tree).includes('تسجيل الدخول'));assert.equal((await call('/api/missions',{id:'boss-002',action:'start'},null)).status,401);
 await mount('start','learner');assert.equal(advanced,false);await action('/api/missions',{id:'001',action:'start'},'advanced');advanced=false;await mount('start','advanced');assert(advanced,'experienced user keeps existing dashboard');
 for(const path of [core.coreJourney.signalHref,'/campaigns/first-signal?view=full',core.coreJourney.socHref,'/soc/alerts/SOC-002',core.coreJourney.boardHref,'/investigations/soc-SOC-002'])assert.equal((await worker.dispatchFetch('http://local.test'+path)).status,200,path);
 console.log('PASS: full compiled UI journey network→email→First Signal→SOC→Locker/Board→decision; wrong/recheck/correct, real requirements/deep links, lesson returns, evidence mirroring/deduplication, refresh/restart/account isolation, existing completed read-only states, reward idempotence, advanced Dashboard. No browser/OAuth/visual device QA.');
}finally{globalThis.fetch=oldFetch;for(const slot of slots)slot?.cleanup?.();if(worker)await worker.dispose();await rm(directory,{recursive:true,force:true});await rm(uiDir,{recursive:true,force:true})}
