import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const require=createRequire(import.meta.url);
const wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=await import(wranglerRequire.resolve('miniflare'));
const {build}=createRequire(require.resolve('vite/package.json'))('esbuild');
const bundled=await Promise.all(['lib/mission-first-pilot.ts','lib/interactive-lab-engine.ts'].map(entry=>build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'})));
const modules=await Promise.all(bundled.map(async item=>import('data:text/javascript;base64,'+Buffer.from(item.outputFiles[0].text).toString('base64'))));
const pilot=modules.find(m=>m.firstPilot),engine=modules.find(m=>m.applyLabAction);
assert(pilot&&engine);
assert.equal(pilot.firstPilotCase.host,pilot.firstPilotDevice.id);
assert.equal(pilot.firstPilotDevice.segmentId,pilot.firstPilotSegment.id);
assert.equal(pilot.firstPilotCase.fix.value,'192.168.50.21');
assert.equal(pilot.firstPilot.nextMissionId,'003');
assert.deepEqual(Object.values(pilot.firstPilot.knowledge).map(k=>k.lessonId),['network-5','network-9','network-8']);
assert.equal(pilot.isPilotBeginner([],[]),true);
assert.equal(pilot.isPilotBeginner([{id:'network-5'}],[]),false);
assert.equal(pilot.isPilotBeginner([],[{id:'network-5',completedAt:null}]),true);
assert.equal(pilot.isPilotBeginner([],[{id:'network-5',completedAt:'2026-09-27'}]),false);
assert.equal(pilot.isPilotBeginner([],[{id:'other',completedAt:null}]),false);
assert.equal(pilot.pilotReturnPath('/experience/nexacorp-first?step=inspect'),'/experience/nexacorp-first?step=inspect');
for(const input of ['https://evil.test/experience/nexacorp-first','/experience/nexacorp-first-evil','/experience/nexacorp-first?step=../../account'])assert.equal(pilot.pilotReturnPath(input),input.endsWith('account')?pilot.firstPilot.href:null);
let session=engine.newLabSession();
for(const action of [{action:'inspect',key:'wrong-ip'},{action:'test',key:'wrong-ip'},{action:'configure',key:'wrong-ip',field:'ip',value:'192.168.50.21'},{action:'test',key:'wrong-ip'}])session=engine.applyLabAction(pilot.firstPilotLab,session,action).session;
assert(session.networkFixed.includes('wrong-ip'));
assert.equal(session.lastResult,null);
assert.equal(session.networkIndex,1);
assert.equal(engine.progressOf(pilot.firstPilotLab,session),8);
const directory=await mkdtemp(join(tmpdir(),'cyberlab-pilot-'));
const modulesForWorker=['index.js',...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js')].map(f=>({type:'ESModule',path:'dist/server/'+f}));
const options={modules:modulesForWorker,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:directory,cf:false};
let worker;
async function call(path,body,user='existing'){
 const headers={'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'};
 if(body)headers['Content-Type']='application/json';
 const r=await worker.dispatchFetch('http://local.test'+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});
 return {status:r.status,data:await r.json()};
}
try{
 worker=new Miniflare(options);
 const db=await worker.getD1Database('DB');
 for(const migration of (await readdir('drizzle')).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())for(const sql of (await readFile('drizzle/'+migration,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 await db.prepare('INSERT INTO progress(user_id,item_id,kind,score,xp,completed_at) VALUES(?,?,?,?,?,?)').bind('existing','net-1','quiz',3,100,'2026-09-20T10:00:00Z').run();
 const initial=await call('/api/progress');
 const url='/api/interactive-labs/'+pilot.firstPilot.labId;
 for(const action of [{action:'start'},{action:'inspect',key:'wrong-ip'},{action:'test',key:'wrong-ip'},{action:'configure',key:'wrong-ip',field:'ip',value:'192.168.50.21'},{action:'test',key:'wrong-ip'}])assert.equal((await call(url,action)).status,200);
 const saved=(await call(url)).data.state.session;
 assert(saved.networkFixed.includes('wrong-ip'));
 assert.equal(saved.lastResult,null);
 assert.deepEqual((await call('/api/progress')).data.items,initial.data.items);
 assert.equal((await call(url,undefined,'other')).data.state,null);
 await worker.dispose();worker=new Miniflare(options);
 assert.deepEqual((await call(url)).data.state.session,saved);
 assert.deepEqual((await call('/api/progress')).data.items,initial.data.items);
}finally{if(worker)await worker.dispose();await rm(directory,{recursive:true,force:true})}
console.log('PASS: canonical NexaCorp/lab/lesson IDs, first case D1 persistence and restart, existing account progress unchanged, account isolation, no standalone reward, beginner gate and safe return paths.');
