// Actual compiled Pilot handlers with isolated built Worker/D1. No real browser/OAuth QA.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=await import(wranglerRequire.resolve('miniflare'));
const {build}=createRequire(require.resolve('vite/package.json'))('esbuild');
async function source(entry){const b=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});return import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'))}
const pilot=await source('lib/offensive-pilot.ts'),labs=await source('lib/interactive-labs.ts'),company=await source('lib/nexacorp.ts'),scope=await source('lib/content-scope.ts'),search=await source('lib/site-search.ts');
const id=pilot.offensivePilot.id,api='/api/interactive-labs/'+id,href=pilot.offensivePilot.href;
assert.equal(labs.interactiveLabs.length,8);assert.equal(labs.interactiveLabById(id).kind,'http');assert.deepEqual(scope.scopeCounts(),{CYBER_CORE:135,CYBER_SUPPORTING:60,OUT_OF_SCOPE:25});
const asset=company.resolveCompanyEntity({kind:'asset',id:pilot.offensivePilot.assetId});assert(asset);assert.deepEqual(asset.deviceIds,[]);assert.deepEqual(asset.serviceIds,[]);assert.equal(company.resolveCompanyEntity({kind:'account',id:pilot.offensivePilot.accountId}).employeeId,'sara');
for(const knowledge of Object.values(pilot.assessmentKnowledge))assert(scope.isCyberLesson(knowledge.lessonId));
assert.equal(pilot.assessmentReturnPath(href),href);for(const unsafe of ['//evil.test'+href,'https://evil.test'+href,href+'/extra','/experience/nexacorp-first'])assert.equal(pilot.assessmentReturnPath(unsafe),null);
assert(search.searchSite('التفويض').some(r=>r.href===href));
const directory=await mkdtemp(join(tmpdir(),'cyberlab-offensive-')),uiDir=await mkdtemp(resolve('.sites-runtime/offensive-ui-'));
const modules=['index.js',...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js')].map(f=>({type:'ESModule',path:'dist/server/'+f}));
const options={modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:directory,cf:false};let worker;
async function call(path,body,user='learner'){const headers={};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}if(body!==undefined)headers['Content-Type']='application/json';const r=await worker.dispatchFetch('http://local.test'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()}}
async function action(action,extra={},user='learner'){const r=await call(api,{action,...extra},user);assert.equal(r.status,200,JSON.stringify(r.data));return r.data.state}
const components={};
for(const [name,entry] of Object.entries({pilot:'app/labs/v2/[id]/offensive.tsx',catalog:'app/labs/page.tsx',search:'app/search/results.tsx'})){
 const result=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',external:['react/jsx-runtime'],plugins:[{name:'hooks',setup(b){b.onResolve({filter:/^(react|lucide-react|@\/app\/progression\/view|@\/app\/shell|@\/components\/native-link)$/},a=>({path:a.path,namespace:'harness'}));b.onLoad({filter:/.*/,namespace:'harness'},a=>({loader:'js',contents:a.path==='@/app/progression/view'?`export const CompletionProgressSummary=()=>null;`:a.path==='react'?`export const useState=v=>globalThis.pilotHooks.useState(v),useEffect=(f,d)=>globalThis.pilotHooks.useEffect(f,d);`:a.path==='@/app/shell'?`export const useProgress=()=>globalThis.pilotProgress;`:a.path==='lucide-react'?`export const ArrowLeft=()=>null,FlaskConical=()=>null,ShieldCheck=()=>null,Terminal=()=>null;`:`import {jsx} from 'react/jsx-runtime';export default p=>jsx('a',Object.fromEntries(Object.entries(p).filter(([k])=>k!=='key')));`}))}}]});const file=join(uiDir,name+'.mjs');await writeFile(file,result.outputFiles[0].text);components[name]=(await import(pathToFileURL(file))).default;
}
let slots=[],index=0,dirty=false,effects=[],tree,pending=new Set(),uiUser,Component,props;
const oldFetch=globalThis.fetch;
globalThis.fetch=(path,init={})=>{assert(String(path).startsWith('/api/'),'Pilot can only fetch local app APIs');const headers={...init.headers};if(uiUser){headers['oai-authenticated-user-id']=uiUser;headers['oai-authenticated-user-email']=uiUser+'@example.test'}const p=(async()=>{const r=await worker.dispatchFetch('http://local.test'+path,{...init,headers});return new Response(await r.text(),{status:r.status,headers:r.headers})})();pending.add(p);p.finally(()=>pending.delete(p));return p};
globalThis.pilotHooks={useState(v){const i=index++;if(!slots[i])slots[i]={value:typeof v==='function'?v():v};return [slots[i].value,n=>{slots[i].value=typeof n==='function'?n(slots[i].value):n;dirty=true}]},useEffect(f,deps){const i=index++;if(!slots[i]||deps.some((d,j)=>d!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>{slots[i].cleanup=f()})}}};
function render(){index=0;dirty=false;tree=Component(props);for(const e of effects.splice(0))e()}
async function settle(){for(let i=0;i<18;i++){if(pending.size)await Promise.all([...pending]);await new Promise(r=>setImmediate(r));if(dirty)render()}assert.equal(pending.size,0);assert(!dirty)}
function nodes(node,out=[],visible=false){if(arguments.length===0)node=tree;if(Array.isArray(node)){for(const child of node)nodes(child,out,visible)}else if(node&&typeof node==='object'&&node.props){if(typeof node.type==='function')nodes(node.type(node.props),out,visible);else{out.push(node);if(visible&&node.type==='details'&&!node.props.open)nodes([node.props.children].flat().filter(c=>c?.type==='summary'),out,visible);else nodes(node.props.children,out,visible)}}return out}
function textOf(node){if(node==null||typeof node==='boolean')return '';if(Array.isArray(node))return node.map(textOf).join('');if(typeof node==='string'||typeof node==='number')return String(node);return typeof node.type==='function'?textOf(node.type(node.props)):textOf(node.props?.children)}
function element(type,label){const node=nodes().find(n=>n.type===type&&textOf(n).includes(label));assert(node,`missing ${type}: ${label}; ${textOf(tree)}`);return node}
async function click(label){const n=element('button',label);assert(!n.props.disabled,`disabled ${label}`);n.props.onClick();await settle()}
async function change(label,value){const n=nodes(element('label',label)).find(n=>n.type==='select');assert(n,label);n.props.onChange({target:{value}});await settle()}
async function checkbox(label){const n=nodes(element('label',label)).find(n=>n.type==='input');assert(n);n.props.onChange({target:{checked:true}});await settle()}
function onePrimary(){assert.equal(nodes().filter(n=>['button','a'].includes(n.type)&&n.props.className==='primary-button').length,1)}
async function mount(name='pilot',user='learner',p={}){for(const slot of slots)slot?.cleanup?.();slots=[];uiUser=user;Component=components[name];props=p;const items=user?(await call('/api/progress',undefined,user)).data.items:[],learning=user?(await call('/api/learning',undefined,user)).data:{activity:[]};globalThis.pilotProgress={user:user?{email:user+'@example.test'}:null,items,learning,loading:false,error:'',refresh:async()=>{}};render();await settle()}
async function snapshot(user){const db=await worker.getD1Database('DB'),out={};for(const table of ['progress','activity','mission_progress','soc_investigations','interactive_lab_progress','investigation_workspaces','investigation_evidence','investigation_links','career_promotions','skill_awards','skill_progress'])out[table]=(await db.prepare('SELECT * FROM '+table+' WHERE user_id=? ORDER BY rowid').bind(user).all()).results;return out}
async function solve(user='learner',submit=true){
 await action('start',{},user);await action('authorize',{accepted:true},user);for(const key of ['account','reports'])await action('page',{key},user);await action('observe',{},user);await action('hypothesis',{},user);await action('choose',{key:'object'},user);for(const key of ['guest','other'])await action('probe',{key},user);await action('evaluate',{},user);await action('report',{report:{finding:'read',impact:'confidentiality',evidence:['own','guest','other']}},user);await action('patch',{key:'server'},user);for(const key of ['own','guest','other'])await action('retest',{key},user);return submit?action('submit',{},user):null;
}
try{
 worker=new Miniflare(options);const db=await worker.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 assert.equal((await call(api,undefined,null)).status,401);assert.equal((await call(api,{action:'start'},null)).status,401);const zero=await snapshot('zero');await mount('pilot','zero');onePrimary();assert(textOf(tree).includes('مقفل'));assert(textOf(tree).includes('0 من 2'));assert.equal((await call(api,{action:'start'},'zero')).status,400);assert.deepEqual(await snapshot('zero'),zero);assert.equal((await worker.dispatchFetch('http://local.test'+href)).status,200);
 await mount('catalog','zero');assert(!nodes().filter(n=>n.props.className==='primary-button').some(n=>n.props.href===href));assert(nodes().some(n=>n.type==='details'&&textOf(n).includes('تقييم الوصول')));await mount('search',null,{results:search.searchResults.filter(r=>r.href===href)});assert(textOf(tree).includes('مقفل'));assert(textOf(tree).includes('المتبقي للفتح'));assert(textOf(tree).includes('Cyber Core'));
 // Existing user earns no new progress merely by inspecting/authorizing/probing.
 await db.prepare('INSERT INTO progress VALUES(?,?,?,?,?,?)').bind('learner','it-2','quiz',3,100,'2026-07-01').run();await call('/api/learning',{action:'complete',id:'security-6'});

 for(const body of [{action:'start'},...['H01','H02'].flatMap(key=>['request','response'].map(value=>({action:'inspect',key,value}))),{action:'submit',method:'get',unauthorized:'401',authorized:'200',difference:'Cookie'}])assert.equal((await call('/api/interactive-labs/v2-http',body)).status,200);
 await call('/api/skills');await call('/api/career');const before=await snapshot('learner'),previousRewards={items:(await call('/api/progress')).data.items,skills:(await call('/api/skills')).data.skills.map(s=>[s.id,s.xp])};
 assert.equal((await call(api)).data.access.locked,false);await mount();onePrimary();assert(!textOf(tree).includes('IDOR'));assert(!textOf(tree).includes('XP'));await checkbox('قرأت التفويض');await click('ابدأ التقييم');onePrimary();await click('افتح الصفحة');await change('الصفحة التي تريد','reports');await click('افتح الصفحة');await click('افحص طلب');onePrimary();assert(!textOf(tree).includes('R-205\nowner: layla'));
 await click('معرفة عند الحاجة');const lesson=element('a','اقرأ الشرح الكامل').props.href;assert.equal(new URL(lesson,'http://local.test').searchParams.get('return_to'),href);const r=await worker.dispatchFetch('http://local.test'+lesson);assert.equal(r.status,200);assert((await r.text()).includes('العودة إلى التقييم'));
 const observed=(await call(api)).data.state;assert(nodes().some(n=>n.props.dir==='rtl'));assert(nodes().filter(n=>n.type==='pre').every(n=>n.props.dir==='ltr'));await mount('catalog');assert.equal(element('a','تابع المختبر').props.href,href);await mount();assert.equal((await call(api)).data.state.session.assessment.step,'observe');assert.equal(element('h2','الملاحظة').props.id,'assessment-stage');assert.deepEqual((await call(api)).data.state,observed);
 await click('كوّن فرضية');await change('فرضيتك','ui');await click('اختبر هذه');await change('الطلب المحاكى','guest');await click('نفّذ الطلب');await change('الطلب المحاكى','other');await click('نفّذ الطلب');await click('نفّذ الطلب');assert.equal((await call(api)).data.state.session.assessment.observations.length,3,'no duplicate traces');await click('قارن النتائج');assert(textOf(tree).includes('الرابط غير ظاهر'));assert(!textOf(tree).includes('IDOR'));onePrimary();await click('عد للملاحظات');await change('فرضيتك','object');await click('اختبر هذه');assert.equal((await call(api,{action:'probe',key:'https://external.example/'})).status,400);assert.equal((await call(api,{action:'probe',key:'R-999'})).status,400);await click('قارن النتائج');onePrimary();
 assert.equal((await call(api,{action:'probe',key:'https://external.example/'})).status,400);assert.equal((await call(api,{action:'submit'})).status,400,'cannot bypass impact/remediation');
 await change('ما الذي ثبت','admin');await change('الأثر الذي','outage');await checkbox('سارة تطلب تقريرها');await checkbox('زائر دون جلسة');await checkbox('سارة تطلب التقرير R-205');await click('اعتمد الأثر');assert(textOf(tree).includes('لم تختبر تعديلًا'));assert(!textOf(tree).includes('IDOR'));await change('ما الذي ثبت','read');await change('الأثر الذي','confidentiality');await click('اعتمد الأثر');
 await change('الإجراء التصحيحي','hide');await click('طبّق المعالجة');for(const value of ['own','guest','other']){await change('طلب إعادة الاختبار',value);await click('أعد اختبار الطلب')}await click('تحقق من المعالجة');assert(textOf(tree).includes('ما زال الحساب نفسه يقرأ'));assert.equal((await call(api)).data.state.completedAt,null);
 // A failed solution has no completion/reward and does not alter historical records.
 const during=await snapshot('learner');assert.deepEqual(during.progress,before.progress);assert.deepEqual(during.skill_awards,before.skill_awards);assert.deepEqual(during.career_promotions,before.career_promotions);assert.deepEqual(during.activity,before.activity);
 await change('الإجراء التصحيحي','server');await click('غيّر المعالجة');for(const value of ['own','guest','other']){await change('طلب إعادة الاختبار',value);await click('أعد اختبار الطلب');onePrimary()}
 const atFix=(await call(api)).data.state;await mount();assert.equal((await call(api)).data.state.session.assessment.step,'remediation');assert.deepEqual((await call(api)).data.state,atFix);assert(textOf(tree).includes('403'));onePrimary();await click('تحقق من المعالجة');onePrimary();assert(textOf(tree).includes('IDOR'));assert(textOf(tree).includes('+75 XP'));const done=(await call(api)).data.state;assert(done.completedAt);assert(done.session.lastResult.passed);
 const after=await snapshot('learner');assert.deepEqual(after.progress.filter(x=>x.item_id!==id),before.progress);assert.deepEqual(after.interactive_lab_progress.filter(x=>x.lab_id!==id),before.interactive_lab_progress);for(const table of ['activity','career_promotions','mission_progress','soc_investigations','investigation_workspaces','investigation_evidence','investigation_links'])assert.deepEqual(after[table],before[table],table);
 const earned={items:(await call('/api/progress')).data.items,skills:(await call('/api/skills')).data.skills.map(s=>[s.id,s.xp])};assert.equal(earned.items.reduce((n,x)=>n+x.xp,0)-previousRewards.items.reduce((n,x)=>n+x.xp,0),75);for(const [skill,xp] of previousRewards.skills)assert.equal(earned.skills.find(s=>s[0]===skill)[1],xp+(skill==='cybersecurity'?25:skill==='logs'?10:0));
 await mount();assert.deepEqual(await snapshot('learner'),after,'completed viewing must not write records');await click('أعد التقييم نفسه');assert.equal((await call(api)).data.state.session.assessment.step,'authorize');const replay=await solve();assert.equal(replay.session.lastResult.xpGranted,false);assert.equal(replay.session.lastResult.skillGranted,false);assert.deepEqual((await call('/api/progress')).data.items,earned.items);assert.deepEqual((await call('/api/skills')).data.skills.map(s=>[s.id,s.xp]),earned.skills);
 // A completed Pilot is grandfathered even if prerequisite rows are incomplete.
 await db.prepare('INSERT INTO interactive_lab_progress (user_id,lab_id,started_at,updated_at,completed_at,best_score,attempts,hints_used,session_json) VALUES (?,?,?,?,?,?,?,?,?)').bind('completed',id,'2026-07-01','2026-07-01','2026-07-01',100,1,0,JSON.stringify(done.session)).run();assert.equal((await call(api,undefined,'completed')).data.access.locked,false);await mount('pilot','completed');assert(textOf(tree).includes('تقييم مكتمل'));assert.equal((await call('/api/progress',undefined,'completed')).data.items.length,0);
 const saved=await snapshot('learner');await worker.dispose();worker=new Miniflare(options);assert.deepEqual(await snapshot('learner'),saved);await mount();assert(textOf(tree).includes('تقييم مكتمل'));assert.deepEqual((await call(api,undefined,'zero')).data.state,null);assert.equal((await call('/api/progress',undefined,'zero')).data.items.length,0);await mount('search','zero',{results:search.searchResults.filter(r=>r.href===href)});assert(textOf(tree).includes('مقفل'));await mount('pilot',null);onePrimary();assert(textOf(tree).includes('سجّل الدخول'));
 // Repeated/concurrent completion uses the existing unique reward records.
 await action('replay');await action('start');await action('authorize',{accepted:true});for(const key of ['account','reports'])await action('page',{key});await action('observe');await action('hypothesis');await action('choose',{key:'object'});for(const key of ['guest','other'])await action('probe',{key});await action('evaluate');await action('report',{report:{finding:'read',impact:'confidentiality',evidence:['own','guest','other']}});await action('patch',{key:'server'});for(const key of ['own','guest','other'])await action('retest',{key});await Promise.all([call(api,{action:'submit'}),call(api,{action:'submit'}),call(api,{action:'submit'})]);assert.deepEqual((await call('/api/progress')).data.items,earned.items);assert.deepEqual((await call('/api/skills')).data.skills.map(s=>[s.id,s.xp]),earned.skills);
 const restartedDb=await worker.getD1Database('DB');await restartedDb.prepare('INSERT INTO activity VALUES (?,?,?,?,?,?)').bind('concurrent','security-6','2026-07-01','2026-07-01',30,'2026-07-01').run();await restartedDb.prepare('INSERT INTO interactive_lab_progress (user_id,lab_id,started_at,updated_at,completed_at,session_json) VALUES (?,?,?,?,?,?)').bind('concurrent','v2-http','2026-07-01','2026-07-01','2026-07-01','{}').run();await solve('concurrent',false);await Promise.all([call(api,{action:'submit'},'concurrent'),call(api,{action:'submit'},'concurrent'),call(api,{action:'submit'},'concurrent')]);assert.equal((await call('/api/progress',undefined,'concurrent')).data.items.reduce((sum,x)=>sum+x.xp,0),75);const rewardRows=(await worker.getD1Database('DB').then(db=>db.prepare('SELECT * FROM skill_awards WHERE user_id=? AND source_id=?').bind('concurrent',id).all())).results;assert.equal(rewardRows.length,2);assert.equal(rewardRows.reduce((sum,x)=>sum+x.xp,0),35);
 console.log('PASS: actual compiled authorization→recon→observation→knowledge/lesson return→wrong hypothesis/recheck→correlated safe tests→bounded impact→wrong fix/retest→server fix/result; real prerequisites, locked search/catalog/deep link, no bypass, deduplication, reload/restart/account isolation/completed access; 75 XP and 25+10 Skill XP once, replay/concurrent completion, old records and scope classification preserved. No browser/OAuth/iPhone/Safari QA.');
}finally{globalThis.fetch=oldFetch;for(const slot of slots)slot?.cleanup?.();if(worker)await worker.dispose();await rm(directory,{recursive:true,force:true});await rm(uiDir,{recursive:true,force:true})}
