// Actual compiled Pilot handlers with isolated built Worker/D1. No real browser/OAuth QA.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,readdir,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=await import(wranglerRequire.resolve('miniflare'));
const {build}=createRequire(require.resolve('vite/package.json'))('esbuild');
async function source(entry){const b=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});return import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'))}
const minimum=await source('lib/offensive-minimum.ts');
const pilot=await source('lib/offensive-pilot.ts'),labs=await source('lib/interactive-labs.ts'),company=await source('lib/nexacorp.ts'),scope=await source('lib/content-scope.ts'),search=await source('lib/site-search.ts');
const id=pilot.offensivePilot.id,api='/api/interactive-labs/'+id,href=pilot.offensivePilot.href;
assert.equal(labs.interactiveLabs.length,8);assert.equal(labs.interactiveLabById(id).kind,'http');assert.deepEqual(scope.scopeCounts(),{CYBER_CORE:135,CYBER_SUPPORTING:60,OUT_OF_SCOPE:25});
const asset=company.resolveCompanyEntity({kind:'asset',id:pilot.offensivePilot.assetId});assert(asset);assert.deepEqual(asset.deviceIds,[]);assert.deepEqual(asset.serviceIds,[]);assert.equal(company.resolveCompanyEntity({kind:'account',id:pilot.offensivePilot.accountId}).employeeId,'sara');
for(const knowledge of Object.values(pilot.assessmentKnowledge))assert(scope.isCyberLesson(knowledge.lessonId));
assert.equal(pilot.assessmentReturnPath(href),href);for(const unsafe of ['//evil.test'+href,'https://evil.test'+href,href+'/extra','/experience/nexacorp-first'])assert.equal(pilot.assessmentReturnPath(unsafe),null);
assert(search.searchSite('التفويض').some(r=>r.href===href));
const directory=await mkdtemp(join(tmpdir(),'cyberlab-minimum-')),uiDir=await mkdtemp(resolve('.sites-runtime/minimum-ui-'));
const modules=['index.js',...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js')].map(f=>({type:'ESModule',path:'dist/server/'+f}));
const options={modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:directory,cf:false};let worker;
async function call(path,body,user='learner'){const headers={};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@example.test'}if(body!==undefined)headers['Content-Type']='application/json';const r=await worker.dispatchFetch('http://local.test'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()}}
async function action(action,extra={},user='learner'){const r=await call(api,{action,...extra},user);assert.equal(r.status,200,JSON.stringify(r.data));return r.data.state}
const components={};
for(const [name,entry] of Object.entries({minimum:'app/labs/v2/[id]/minimum.tsx',track:'app/practice/offensive/page.tsx',pilot:'app/labs/v2/[id]/offensive.tsx',catalog:'app/labs/page.tsx',search:'app/search/results.tsx'})){
 const result=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',external:['react/jsx-runtime'],plugins:[{name:'hooks',setup(b){b.onResolve({filter:/^(react|lucide-react|@\/app\/progression\/view|@\/app\/shell|@\/components\/native-link)$/},a=>({path:a.path,namespace:'harness'}));b.onLoad({filter:/.*/,namespace:'harness'},a=>({loader:'js',contents:a.path==='@/app/progression/view'?`export const CompletionProgressSummary=()=>null;`:a.path==='react'?`export const useState=v=>globalThis.pilotHooks.useState(v),useEffect=(f,d)=>globalThis.pilotHooks.useEffect(f,d);`:a.path==='@/app/shell'?`export const useProgress=()=>globalThis.pilotProgress;`:a.path==='lucide-react'?`export const ArrowLeft=()=>null,FlaskConical=()=>null,ShieldCheck=()=>null,Terminal=()=>null;`:`import {jsx} from 'react/jsx-runtime';export default p=>jsx('a',Object.fromEntries(Object.entries(p).filter(([k])=>k!=='key')));`}))}}]});const file=join(uiDir,name+'.mjs');await writeFile(file,result.outputFiles[0].text);components[name]=(await import(pathToFileURL(file))).default;
}
let slots=[],index=0,dirty=false,effects=[],tree,pending=new Set(),uiUser,Component,props;
const oldFetch=globalThis.fetch;
globalThis.fetch=(path,init={})=>{assert(String(path).startsWith('/api/'),'Pilot can only fetch local app APIs');const headers={...init.headers};if(uiUser){headers['oai-authenticated-user-id']=uiUser;headers['oai-authenticated-user-email']=uiUser+'@example.test'}const p=(async()=>{const r=await worker.dispatchFetch('http://local.test'+path,{...init,headers});return new Response(await r.text(),{status:r.status,headers:r.headers})})();pending.add(p);p.finally(()=>pending.delete(p));return p};
globalThis.pilotHooks={useState(v){const i=index++;if(!slots[i])slots[i]={value:typeof v==='function'?v():v};return [slots[i].value,n=>{slots[i].value=typeof n==='function'?n(slots[i].value):n;dirty=true}]},useEffect(f,deps){const i=index++;if(!slots[i]||deps.some((d,j)=>d!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>{slots[i].cleanup=f()})}}};
function render(){index=0;dirty=false;tree=Component(props);for(const e of effects.splice(0))e()}
async function settle(){for(let i=0;i<18;i++){if(pending.size)await Promise.all([...pending]);await new Promise(r=>setImmediate(r));if(dirty)render()}assert.equal(pending.size,0);assert(!dirty)}
function nodes(node,out=[],visible=false){if(arguments.length===0)node=tree;if(Array.isArray(node)){for(const child of node)nodes(child,out,visible)}else if(node&&typeof node==='object'&&node.props){if(typeof node.type==='function')nodes(node.type(node.props),out,visible);else{out.push(node);if(visible&&node.type==='details'&&!node.props.open)nodes([node.props.children].flat().filter(c=>c?.type==='summary'),out,visible);else nodes(node.props.children,out,visible)}}return out}
function textOf(node){if(node==null||typeof node==='boolean')return '';if(Array.isArray(node))return node.map(textOf).join('');if(typeof node==='string'||typeof node==='number')return String(node);return typeof node.type==='function'?textOf(node.type(node.props)):textOf(node.props?.children)}
function element(type,label){const node=nodes().find(n=>n.type===type&&textOf(n).includes(label));assert(node,`missing ${type}: ${label}; ${textOf(tree)}`);return node}
async function click(label){const n=element('button',label);assert(!n.props.disabled,`disabled ${label}`);n.props.onClick();await settle()}
async function change(label,value){const n=nodes(element('label',label)).find(n=>n.type==='select');assert(n,label);n.props.onChange({target:{value}});await settle()}
async function checkbox(label){const n=nodes(element('label',label)).find(n=>n.type==='input');assert(n);n.props.onChange({target:{checked:true}});await settle()}
function onePrimary(){assert.equal(nodes().filter(n=>['button','a'].includes(n.type)&&n.props.className==='primary-button').length,1)}
async function mount(name='pilot',user='learner',p={}){for(const slot of slots)slot?.cleanup?.();slots=[];uiUser=user;Component=components[name];props=p;const items=user?(await call('/api/progress',undefined,user)).data.items:[],learning=user?(await call('/api/learning',undefined,user)).data:{activity:[]};globalThis.pilotProgress={user:user?{email:user+'@example.test'}:null,items,learning,loading:false,error:'',refresh:async()=>{}};render();await settle()}
async function snapshot(user){const db=await worker.getD1Database('DB'),out={};for(const table of ['progress','activity','mission_progress','soc_investigations','interactive_lab_progress','investigation_workspaces','investigation_evidence','investigation_links','career_promotions','skill_awards','skill_progress'])out[table]=(await db.prepare('SELECT * FROM '+table+' WHERE user_id=? ORDER BY rowid').bind(user).all()).results;return out}
async function solve(user='learner',submit=true){
 await action('start',{},user);await action('authorize',{accepted:true},user);for(const key of ['account','reports'])await action('page',{key},user);await action('observe',{},user);await action('hypothesis',{},user);await action('choose',{key:'object'},user);for(const key of ['guest','other'])await action('probe',{key},user);await action('evaluate',{},user);await action('report',{report:{finding:'read',impact:'confidentiality',evidence:['own','guest','other']}},user);await action('patch',{key:'server'},user);for(const key of ['own','guest','other'])await action('retest',{key},user);return submit?action('submit',{},user):null;
}

const sid=minimum.surfaceId,aid=minimum.sessionId;
async function minAction(id,action,extra={},user='learner'){const r=await call('/api/interactive-labs/'+id,{action,...extra},user);assert.equal(r.status,200,JSON.stringify(r.data));return r.data.state}
async function state(id,user='learner'){return (await call('/api/interactive-labs/'+id,undefined,user)).data.state}
async function seedReady(user){const db=await worker.getD1Database('DB');await db.prepare('INSERT INTO activity VALUES (?,?,?,?,?,?)').bind(user,'security-6','2026-07-01','2026-07-01',30,'2026-07-01').run();await db.prepare('INSERT INTO interactive_lab_progress (user_id,lab_id,started_at,updated_at,completed_at,session_json) VALUES (?,?,?,?,?,?)').bind(user,'v2-http','2026-07-01','2026-07-01','2026-07-01','{}').run()}
async function surfaceSolve(user='learner',submit=true){
 await minAction(sid,'start',{},user);await minAction(sid,'authorize',{accepted:true},user);for(const key of ['portal','metrics','admin'])await minAction(sid,'inspect',{key},user);await minAction(sid,'classify-start',{},user);for(const [key,value] of [['portal','present'],['metrics','review'],['admin','present']])await minAction(sid,'classify',{key,value},user);await minAction(sid,'prioritize',{},user);await minAction(sid,'priority',{key:'metrics'},user);for(const key of ['policy','external','internal'])await minAction(sid,'probe',{key},user);await minAction(sid,'evaluate',{},user);await minAction(sid,'report',{report:{finding:'config',impact:'metadata',evidence:['policy','external','internal']}},user);await minAction(sid,'patch',{key:'restrict'},user);for(const key of ['external','internal','portal'])await minAction(sid,'retest',{key},user);return submit?minAction(sid,'submit',{},user):null;
}
async function sessionSolve(user='learner',submit=true){
 await minAction(aid,'start',{},user);await minAction(aid,'authorize',{accepted:true},user);await minAction(aid,'login',{},user);await minAction(aid,'logout',{},user);await minAction(aid,'login-again',{},user);await minAction(aid,'hypothesis',{},user);await minAction(aid,'choose',{key:'revocation'},user);for(const key of ['old','current','anonymous'])await minAction(aid,'probe',{key},user);await minAction(aid,'evaluate',{},user);await minAction(aid,'report',{report:{finding:'revocation',impact:'continued',evidence:['old','current','anonymous']}},user);await minAction(aid,'patch',{key:'revoke'},user);for(const key of ['old','current','anonymous'])await minAction(aid,'retest',{key},user);return submit?minAction(aid,'submit',{},user):null;
}
async function unchangedExceptNew(before,after){for(const t of Object.keys(before)){if(['progress','interactive_lab_progress','skill_awards','skill_progress'].includes(t))continue;assert.deepEqual(after[t],before[t],t)}assert.deepEqual(after.progress.filter(r=>![sid,aid,id].includes(r.item_id)),before.progress.filter(r=>![sid,aid,id].includes(r.item_id)));assert.deepEqual(after.interactive_lab_progress.filter(r=>![sid,aid,id].includes(r.lab_id)),before.interactive_lab_progress.filter(r=>![sid,aid,id].includes(r.lab_id)));assert.deepEqual(after.skill_awards.filter(r=>![sid,aid,id].includes(r.source_id)),before.skill_awards.filter(r=>![sid,aid,id].includes(r.source_id)))}
async function minMount(id,user='learner'){await mount('minimum',user,{id});onePrimary();assert(nodes().some(n=>n.props.dir==='rtl'));assert(nodes().filter(n=>n.type==='pre').every(n=>n.props.dir==='ltr'))}
try{
 worker=new Miniflare(options);const db=await worker.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())for(const sql of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 assert.deepEqual(minimum.offensiveOrder,[sid,id,aid]);assert.deepEqual(labs.interactiveLabById(id).unlock,{lessons:['security-6'],labs:['v2-http']});
 for(const id of [sid,aid]){
  const href=minimum.minimumHref(id);assert.equal(minimum.minimumReturnPath(href),href);for(const invalid of ['https://evil.test'+href,'//evil.test'+href,href+'/extra',href+'?target=external'])assert.equal(minimum.minimumReturnPath(invalid),null);
  for(const lesson of labs.interactiveLabById(id).relatedLessons)assert(scope.isCyberLesson(lesson));
  const zero=await snapshot('zero');await minMount(id,'zero');assert(textOf(tree).includes('مقفل'));assert(textOf(tree).includes('0 من 2'));assert.equal((await call('/api/interactive-labs/'+id,{action:'start'},'zero')).status,400);assert.deepEqual(await snapshot('zero'),zero);assert.equal((await worker.dispatchFetch('http://local.test'+href)).status,200);await mount('search','zero',{results:search.searchResults.filter(r=>r.href===href)});assert(textOf(tree).includes('مقفل'));assert(textOf(tree).includes('المتبقي للفتح'));await minMount(id,null);assert(textOf(tree).includes('سجّل الدخول'));
 }
 for(const assetId of ['surface-training','session-training']){const a=company.resolveCompanyEntity({kind:'asset',id:assetId});assert(a);assert.deepEqual(a.deviceIds,[]);assert.deepEqual(a.serviceIds,[])}
 await seedReady('learner');await db.prepare('INSERT INTO progress VALUES(?,?,?,?,?,?)').bind('learner','it-2','quiz',3,100,'2026-07-01').run();await call('/api/skills');await call('/api/career');const before=await snapshot('learner');await minMount(sid);assert(!textOf(tree).includes('XP'));assert(!textOf(tree).includes('allow_zone=all'));assert(!nodes().some(n=>n.type==='input'&&n.props.type!=='checkbox'));
 await checkbox('قرأت التفويض');await click('ابدأ التقييم');onePrimary();for(const key of ['portal','metrics','admin']){await change('الأصل الذي تريد',key);await click('افحص الأصل');onePrimary()}
 await click('معرفة عند الحاجة');const lesson=element('a','اقرأ الشرح الكامل').props.href;assert.equal(new URL(lesson,'http://local.test').searchParams.get('return_to'),minimum.minimumHref(sid));const lessonResponse=await worker.dispatchFetch('http://local.test'+lesson);assert.equal(lessonResponse.status,200);assert((await lessonResponse.text()).includes('العودة إلى التقييم'));const atRecon=await state(sid);await minMount(sid);assert.deepEqual(await state(sid),atRecon);
 await click('ابنِ خريطة');for(const [key,value] of [['portal','vulnerability'],['metrics','misconfiguration'],['admin','vulnerability']]){await change('الأصل المراد',key);await change('التصنيف المبني',value);await click('احفظ التصنيف')}
 await click('راجع الخريطة');assert(textOf(tree).includes('لم تقارنه بعد بالسياسة'));assert.equal((await state(sid)).session.minimum.step,'classify');for(const [key,value] of [['portal','present'],['metrics','review'],['admin','present']]){await change('الأصل المراد',key);await change('التصنيف المبني',value);await click('احفظ التصنيف')}
 await click('راجع الخريطة');await change('أولوية التحقق','admin');await click('تحقق من الأصل');assert(textOf(tree).includes('مرفوضة من المنطقة الخارجية'));await change('أولوية التحقق','metrics');await click('تحقق من الأصل');onePrimary();
 assert.equal((await call('/api/interactive-labs/'+sid,{action:'submit'})).status,400);for(const key of ['https://external.example','192.0.2.1','other'])assert.equal((await call('/api/interactive-labs/'+sid,{action:'probe',key})).status,400);assert.equal((await call('/api/interactive-labs/'+sid,{action:'probe',key:'policy',target:'external'})).status,400);
 for(const value of ['policy','external','internal','external']){await change('الفحص المحاكى',value);await click('نفّذ الفحص');onePrimary()}assert.equal((await state(sid)).session.minimum.observations.length,3);await click('قارن الأدلة');onePrimary();await change('ما الذي ثبت','cve');await change('الأثر الذي','takeover');for(const label of ['سجل الأصول','طلب من منطقة التقييم','طلب من منطقة الإدارة'])await checkbox(label);await click('اعتمد الأثر');assert(textOf(tree).includes('لم تثبت ثغرة برمجية'));await change('ما الذي ثبت','config');await change('الأثر الذي','metadata');await click('اعتمد الأثر');
 await change('الإجراء التصحيحي','close');await click('طبّق المعالجة');for(const value of ['external','internal','portal']){await change('طلب إعادة الاختبار',value);await click('أعد اختبار الحالة');onePrimary()}await click('تحقق من المعالجة');assert.equal((await state(sid)).completedAt,null);assert.deepEqual((await snapshot('learner')).progress,before.progress);assert.deepEqual((await snapshot('learner')).skill_awards,before.skill_awards);
 await change('الإجراء التصحيحي','restrict');await click('غيّر المعالجة');for(const value of ['external','internal','portal']){await change('طلب إعادة الاختبار',value);await click('أعد اختبار الحالة');onePrimary()}const savedFix=await state(sid);await minMount(sid);assert.deepEqual(await state(sid),savedFix);assert(textOf(tree).includes('403'));await click('تحقق من المعالجة');onePrimary();assert((await state(sid)).completedAt);assert.equal(element('a','الخطوة التالية').props.href,href+'?track=offensive');assert.equal((await call('/api/interactive-labs/'+aid)).data.access.locked,true);
 // Existing Access Control remains its original scenario and ledger; track context only changes navigation.
 await solve();await mount('pilot','learner',{track:true});onePrimary();assert.equal(element('a','الخطوة التالية').props.href,minimum.offensiveTrackHref);await mount('track');onePrimary();assert.equal(element('a','تابع التقييم التالي').props.href,minimum.minimumHref(aid));assert.equal((await call('/api/interactive-labs/'+aid)).data.access.locked,false);
 await minMount(aid);assert(!textOf(tree).includes('XP'));await checkbox('قرأت التفويض');await click('ابدأ التقييم');await click('سجّل الدخول إلى التطبيق');onePrimary();assert(!textOf(tree).includes('Session A (logout'));await click('معرفة عند الحاجة');const sessionLesson=element('a','اقرأ الشرح الكامل').props.href;const sr=await worker.dispatchFetch('http://local.test'+sessionLesson);assert.equal(sr.status,200);assert((await sr.text()).includes('العودة إلى التقييم'));const logged=await state(aid);await minMount(aid);assert.deepEqual(await state(aid),logged);
 await click('سجّل الخروج من التطبيق');await click('سجّل الدخول من جديد');await click('كوّن فرضية');await change('فرضيتك','browser');await click('اختبر هذه');assert.equal((await call('/api/interactive-labs/'+aid,{action:'submit'})).status,400);assert.equal((await call('/api/interactive-labs/'+aid,{action:'probe',key:'old',credentials:'real'})).status,400);for(const value of ['old','current','anonymous','old']){await change('الفحص المحاكى',value);await click('نفّذ الفحص');onePrimary()}assert.equal((await state(aid)).session.minimum.observations.length,6);await click('قارن الأدلة');assert(textOf(tree).includes('المتصفح أزال A'));assert.equal((await state(aid)).session.minimum.step,'test');await click('عد للملاحظات');await change('فرضيتك','authorization');await click('اختبر هذه');await click('قارن الأدلة');assert(textOf(tree).includes('لا يوجد طلب لمورد حساب آخر'));await click('عد للملاحظات');await change('فرضيتك','revocation');await click('اختبر هذه');await click('قارن الأدلة');
 await change('ما الذي ثبت','other');await change('الأثر الذي','admin');for(const label of ['الجلسة A','الجلسة B','طلب دون جلسة'])await checkbox(label);await click('اعتمد الأثر');assert(textOf(tree).includes('لا دليل على كلمة مرور'));await change('ما الذي ثبت','revocation');await change('الأثر الذي','continued');await click('اعتمد الأثر');await change('الإجراء التصحيحي','cookie');await click('طبّق المعالجة');for(const value of ['old','current','anonymous']){await change('طلب إعادة الاختبار',value);await click('أعد اختبار الحالة');onePrimary()}await click('تحقق من المعالجة');assert.equal((await state(aid)).completedAt,null);
 await change('الإجراء التصحيحي','revoke');await click('غيّر المعالجة');for(const value of ['old','current','anonymous']){await change('طلب إعادة الاختبار',value);await click('أعد اختبار الحالة');onePrimary()}const atRetest=await state(aid);await minMount(aid);assert.deepEqual(await state(aid),atRetest);await click('تحقق من المعالجة');onePrimary();const complete=await snapshot('learner');await unchangedExceptNew(before,complete);const addedXP=complete.progress.filter(r=>[sid,aid,id].includes(r.item_id)).reduce((n,r)=>n+r.xp,0);assert.equal(addedXP,225);assert.equal(complete.skill_awards.filter(r=>[sid,aid,id].includes(r.source_id)).reduce((n,r)=>n+r.xp,0),105);await mount('track');onePrimary();assert(textOf(tree).includes('Offensive Foundations Completed'));assert(textOf(tree).includes('3 من 3'));assert.deepEqual(await snapshot('learner'),complete,'track completion and viewing grant nothing');
 for(const id of [sid,aid]){await minAction(id,'replay');id===sid?await surfaceSolve():await sessionSolve();assert.equal((await state(id)).session.lastResult.xpGranted,false);assert.equal((await state(id)).session.lastResult.skillGranted,false)}const replayed=await snapshot('learner');assert.deepEqual(replayed.progress,complete.progress);assert.deepEqual(replayed.skill_awards,complete.skill_awards);assert.deepEqual(replayed.skill_progress,complete.skill_progress);
 // Persisted sessions, isolated accounts, guest sign-in UI; not a real OAuth test.
 const stored=await state(aid);await worker.dispose();worker=new Miniflare(options);assert.deepEqual(await state(aid),stored);await minMount(aid);assert(textOf(tree).includes('تقييم مكتمل'));assert.equal(await state(aid,'zero'),null);assert.equal((await call('/api/interactive-labs/'+aid,undefined,null)).status,401);
 const restartedDb=await worker.getD1Database('DB');for(const id of [sid,aid]){const completed=await state(id);await restartedDb.prepare('INSERT INTO interactive_lab_progress (user_id,lab_id,started_at,updated_at,completed_at,best_score,attempts,hints_used,session_json) VALUES (?,?,?,?,?,?,?,?,?)').bind('historical',id,'2026-07-01','2026-07-01','2026-07-01',100,1,0,JSON.stringify(completed.session)).run();assert.equal((await call('/api/interactive-labs/'+id,undefined,'historical')).data.access.locked,false);await minMount(id,'historical');assert(textOf(tree).includes('تقييم مكتمل'));assert.equal((await call('/api/progress',undefined,'historical')).data.items.length,0)}
 // First completion races and replay races must use existing unique reward keys.
 await seedReady('race');await surfaceSolve('race',false);await Promise.all([1,2,3].map(()=>call('/api/interactive-labs/'+sid,{action:'submit'},'race')));await solve('race');await sessionSolve('race',false);await Promise.all([1,2,3].map(()=>call('/api/interactive-labs/'+aid,{action:'submit'},'race')));const raced=await snapshot('race');assert.equal(raced.progress.reduce((n,r)=>n+r.xp,0),225);assert.equal(raced.skill_awards.filter(r=>[sid,aid,id].includes(r.source_id)).length,6);assert.equal(raced.skill_awards.reduce((n,r)=>n+r.xp,0),105);
 for(const id of [sid,aid]){await minAction(id,'replay',{},'race');id===sid?await surfaceSolve('race',false):await sessionSolve('race',false);await Promise.all([1,2,3].map(()=>call('/api/interactive-labs/'+id,{action:'submit'},'race')))}const racedAgain=await snapshot('race');assert.deepEqual(racedAgain.progress,raced.progress);assert.deepEqual(racedAgain.skill_awards,raced.skill_awards);assert.deepEqual(racedAgain.skill_progress,raced.skill_progress);
 const css=await readFile('app/globals.css','utf8');assert(css.includes('@media(max-width:750px){.surface-map{grid-template-columns:minmax(0,1fr)}'));assert(css.includes('.minimum-assessment select{width:100%;min-height:48px}'));assert(css.includes('overflow-wrap:anywhere'));for(const id of [sid,aid])assert.equal((await worker.dispatchFetch('http://local.test'+minimum.minimumHref(id))).status,200);assert.equal((await worker.dispatchFetch('http://local.test'+minimum.offensiveTrackHref)).status,200);
 console.log('PASS: compiled three-assessment journey; real Worker/D1 locks and deep links, scoped surface map/classification/priority/validation, session login/logout/correlation/wrong hypotheses, bounded impact, wrong fixes/correct remediation/retest, knowledge return/refresh/restart, completed-user compatibility, unique first/replay/concurrent XP+Skill XP, RTL nodes and mobile CSS rules. No real browser/Production/OAuth/iPhone/Safari test.');
}finally{globalThis.fetch=oldFetch;for(const slot of slots)slot?.cleanup?.();if(worker)await worker.dispose();await rm(directory,{recursive:true,force:true});await rm(uiDir,{recursive:true,force:true})}
