// Compiled real notification component/effects; no browser or Production claim.
import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {resolve,join} from 'node:path';import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url),{build}=createRequire(require.resolve('vite/package.json'))('esbuild'),dir=await mkdtemp(resolve('.sites-runtime/progression-ui-'));
const output=await build({entryPoints:['app/rank/experience.tsx'],bundle:true,platform:'node',format:'esm',write:false,external:['react/jsx-runtime'],plugins:[{name:'hooks',setup(b){b.onResolve({filter:/^(react|lucide-react)$/},a=>({path:a.path,namespace:'ui'}));b.onLoad({filter:/.*/,namespace:'ui'},a=>({loader:'js',contents:a.path==='react'?`export const useEffect=(f,d)=>globalThis.hooks.useEffect(f,d),useRef=v=>globalThis.hooks.useRef(v),useState=v=>globalThis.hooks.useState(v);`:`export const ArrowLeft=()=>null,Check=()=>null,X=()=>null;`}))}}]});await writeFile(join(dir,'rank.mjs'),output.outputFiles[0].text);const {RankExperience}=await import(pathToFileURL(join(dir,'rank.mjs')));let slots=[],index=0,effects=[],dirty=false,tree;
const timers=new Map();let serial=0;globalThis.window={setTimeout(f){timers.set(++serial,f);return serial},clearTimeout(id){timers.delete(id)}};
globalThis.hooks={useRef(v){const i=index++;slots[i]??={current:v};return slots[i]},useState(v){const i=index++;slots[i]??={value:v};return [slots[i].value,n=>{if(slots[i].value!==n){slots[i].value=n;dirty=true}}]},useEffect(f,deps){const i=index++;if(!slots[i]||deps.some((d,j)=>d!==slots[i].deps[j])){slots[i]?.cleanup?.();slots[i]={deps};effects.push(()=>slots[i].cleanup=f())}}};
function render(props){for(let pass=0;pass<6;pass++){index=0;dirty=false;tree=RankExperience(props);for(const effect of effects.splice(0))effect();if(!dirty)return tree}throw Error('Notification effect did not settle')}
const text=n=>Array.isArray(n)?n.map(text).join(' '):n?.props?text(n.props.children):typeof n==='object'?'':String(n??'');
try{assert.equal(render({xp:195,ready:true,accountKey:'a'}),null,'initial hydration is quiet');render({xp:195,ready:false,accountKey:'a'});assert(text(render({xp:200,ready:true,accountKey:'a'})).includes('تمت الترقية'),'saving and refreshing progress must not swallow a real level-up');assert.equal(tree.props.role,'status');assert(!text(tree).includes('LEVEL'));assert.equal(timers.size,1,'one notification only');assert(text(render({xp:200,ready:true,accountKey:'a'})).includes('المستوى'));render({xp:2595,ready:true,accountKey:'b'});assert.equal(tree,null,'different-account hydration does not inherit notifications');for(const slot of slots)slot?.cleanup?.();slots=[];effects=[];render({xp:0,ready:false,accountKey:'b'});render({xp:3000,ready:true,accountKey:'b'});assert.equal(tree,null,'restore does not announce historical levels');render({xp:3800,ready:true,accountKey:'b'});assert(text(tree).includes('الأفق'));assert.equal(timers.size,1);for(const f of [...timers.values()])f();render({xp:3800,ready:true,accountKey:'b'});assert.equal(tree,null,'timer dismisses');render({xp:3800,ready:true,accountKey:'b'});assert.equal(tree,null,'replay/equal XP does not reannounce');console.log('PASS: real level-up UI, one tier/level status, Arabic copy, initial restore and account change quiet, dismissal, replay without repeated notification.')}finally{await rm(dir,{recursive:true,force:true});delete globalThis.hooks;delete globalThis.window}
