// Actual built Worker and disposable D1; never connects to Production.
import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {readFile,readdir,mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare}=await import(wr.resolve('miniflare')),{build}=createRequire(require.resolve('vite/package.json'))('esbuild');
async function load(entry){const b=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});return import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'))}
const {levelPath,achievementCatalog,achievementStates}=await load('lib/progression.ts'),{rankEvent}=await load('lib/ranks.ts'),{composeResponseIncident}=await load('lib/incident-chain-definition.ts');
assert.equal(levelPath(2595).level,13);assert.equal(levelPath(2595).within,195);assert.equal(levelPath(2595).toNext,5);assert.equal(levelPath(2595).next.minLevel,15);assert.equal(levelPath(2595).remaining,205);assert.equal(levelPath(0).level,1);assert(levelPath(30000).path.length<=4);assert.equal(levelPath(30000).next,null);assert.equal(rankEvent(null,2595),null);assert.equal(rankEvent(195,200).toLevel,2);assert.equal(rankEvent(200,200),null);
assert.equal(achievementCatalog.filter(a=>!a.legacy).length,9);assert.equal(new Set(achievementCatalog.map(a=>a.id)).size,15);assert.equal(achievementStates({},[]).filter(a=>a.earnedTier).length,0);
const dir=await mkdtemp(join(tmpdir(),'cyberlab-progression-')),modules=['index.js',...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js')].map(f=>({type:'ESModule',path:'dist/server/'+f}));const options={modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:dir,cf:false};let worker;
async function call(path='/api/progression',user='existing',body){const headers=user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.test'}:{};if(body)headers['Content-Type']='application/json';const r=await worker.dispatchFetch('http://local.test'+path,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});return {status:r.status,data:r.headers.get('content-type')?.includes('json')?await r.json():await r.text(),headers:r.headers}}
async function view(user='existing'){const r=await call('/api/progression',user);assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.headers.get('cache-control'),'private, no-store');return r.data}
const at='2026-09-24T12:00:00Z';
async function retained(db,user){const tables=(await db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'achievement_unlocks' AND name NOT LIKE '_cf_%'").all()).results,out={};for(const {name} of tables){const columns=(await db.prepare('PRAGMA table_info('+name+')').all()).results;if(columns.some(c=>c.name==='user_id'))out[name]=(await db.prepare('SELECT * FROM '+name+' WHERE user_id=? ORDER BY rowid').bind(user).all()).results}return out}
async function saveChain(db,user,root,ordinal=0){let prior;for(let stage=0;stage<3;stage++){const i=composeResponseIncident(stage,root,prior,prior?{hypothesis:prior.validConclusions[0],action:prior.recommendedActions[0],affected:prior.board.expected.affected,evidenceIds:prior.successConditions.requiredEvidenceIds}:undefined);const answer={hypothesis:i.board.expected.hypothesis,action:i.board.expected.actions[0],affected:i.board.expected.affected,evidenceIds:i.board.expected.requiredEvidenceIds};await db.prepare('INSERT INTO dynamic_incidents VALUES(?,?,?,?,?,?,?,?)').bind(user,i.instanceId,i.templateId,stage+1+ordinal,i.seed,i.difficulty,JSON.stringify(i),at).run();await db.prepare('INSERT INTO investigation_workspaces VALUES(?,?,?,?,?,?,?)').bind(user,i.board.id,'closed',JSON.stringify(answer),at,at,at).run();for(const id of answer.evidenceIds)await db.prepare('INSERT INTO investigation_evidence(user_id,investigation_id,evidence_id,reviewed_at,collected_at) VALUES(?,?,?,?,?)').bind(user,i.board.id,id,at,at).run();for(const l of i.board.expected.requiredLinks)await db.prepare('INSERT INTO investigation_links VALUES(?,?,?,?,?,?,?)').bind(user,i.board.id,l.fromId,l.relation,l.toId,'الربط موثق من المصدرين في بيانات التحقيق.',at).run();prior=i}}
try{
 worker=new Miniflare(options);const db=await worker.getD1Database('DB');for(const f of (await readdir('drizzle')).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())for(const sql of (await readFile('drizzle/'+f,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 assert.equal((await call('/api/progression',null)).status,401);assert.equal((await call('/api/progression?userId=existing','zero')).status,400);assert.equal((await call('/api/progression?achievementId=mastery','zero')).status,400);assert.notEqual((await call('/api/progression','zero',{xp:999999,achievement:'mastery'})).status,200);
 await db.prepare('INSERT INTO skill_progress VALUES(?,?,?,?,?,?)').bind('xp-only','cybersecurity',99999,500,99,at).run();assert.equal((await view('xp-only')).achievements.find(a=>a.id==='mastery').earnedTier,0,'XP alone cannot prove mastery');
 const zero=await view('zero');assert.equal(zero.xp,0);assert.equal(zero.level.level,1);assert.equal(zero.goal.href,'/experience/nexacorp-first');assert(zero.achievements.every(a=>a.earnedTier===0));assert.equal(zero.mastery.filter(s=>s.mastery!==null).length,0);
 await db.prepare('INSERT INTO progress VALUES(?,?,?,?,?,?)').bind('existing','mission:003','mission',100,2595,at).run();await db.prepare('INSERT INTO mission_progress(user_id,mission_id,started_at,updated_at,completed_at,score) VALUES(?,?,?,?,?,?)').bind('existing','003',at,at,at,100).run();
 await db.prepare('INSERT INTO progress VALUES(?,?,?,?,?,?)').bind('existing','linux-1','quiz',100,0,at).run();await db.prepare('INSERT INTO activity(user_id,lesson_id,started_at,last_at,seconds,completed_at) VALUES(?,?,?,?,?,?)').bind('existing','linux-1',at,at,120,at).run();
 for(const id of ['v2-attack-surface','v2-access-control','v2-auth-session'])await db.prepare('INSERT INTO interactive_lab_progress(user_id,lab_id,started_at,updated_at,completed_at,best_score) VALUES(?,?,?,?,?,?)').bind('existing',id,at,at,at,100).run();
 await db.prepare('INSERT INTO skill_progress VALUES(?,?,?,?,?,?)').bind('existing','cybersecurity',425,3,12,at).run();
 await db.prepare('INSERT INTO career_promotions VALUES(?,?,?,?,?)').bind('existing','foundation','cybersecurity-trainee',at,'[]').run();
 await db.prepare('INSERT INTO soc_investigations(user_id,alert_id,started_at,updated_at,closed_at,session_json) VALUES(?,?,?,?,?,?)').bind('existing','SOC-002',at,at,at,JSON.stringify({lastResult:{correct:true}})).run();
 // Progress between achievement tiers survives reopening a later source.
 for(const id of ['SOC-001','SOC-002']){await db.prepare('INSERT INTO soc_investigations(user_id,alert_id,started_at,updated_at,closed_at,session_json) VALUES(?,?,?,?,?,?)').bind('tier-progress',id,at,at,at,JSON.stringify({lastResult:{correct:true}})).run();await view('tier-progress')}
 let tier=(await view('tier-progress')).achievements.find(a=>a.id==='soc-response');assert.equal(tier.value,2);assert.equal(tier.target,3);assert.equal(tier.earnedTier,1);
 await db.prepare('UPDATE soc_investigations SET closed_at=NULL,session_json=? WHERE user_id=? AND alert_id=?').bind('{}','tier-progress','SOC-002').run();tier=(await view('tier-progress')).achievements.find(a=>a.id==='soc-response');assert.equal(tier.value,2,'proven intermediate progress must not disappear on replay');
 // A closure without a decision/evidence is not sufficient proof for a new investigation badge.
 await db.prepare('INSERT INTO investigation_workspaces(user_id,investigation_id,status,created_at,updated_at,closed_at) VALUES(?,?,?,?,?,?)').bind('unproven','soc-SOC-002','closed',at,at,at).run();assert.equal((await view('unproven')).achievements.find(a=>a.id==='investigator').earnedTier,0);
 await saveChain(db,'mixed-chain',17);await saveChain(db,'mixed-chain',18,3);
 for(const row of (await db.prepare('SELECT snapshot_json AS snapshot FROM dynamic_incidents WHERE user_id=?').bind('mixed-chain').all()).results){const i=JSON.parse(row.snapshot);if(i.chain.rootSeed===17&&i.chain.stage>0)await db.prepare("UPDATE investigation_workspaces SET status='open',closed_at=NULL WHERE user_id=? AND investigation_id=?").bind('mixed-chain',i.board.id).run()}
 assert.equal((await view('mixed-chain')).achievements.find(a=>a.id==='incident-chain').earnedTier,1,'a completed connected chain must be recognized even when an earlier variant is incomplete');
 await saveChain(db,'existing',17);await saveChain(db,'existing',18,3);const before=await retained(db,'existing');
 const views=await Promise.all(Array.from({length:4},()=>view()));for(const v of views){assert.equal(v.xp,2595);assert.equal(v.level.level,13);assert.equal(v.career.id,'cybersecurity-trainee');assert.equal(v.mastery.find(s=>s.id==='cybersecurity').xp,425);assert.equal(v.achievements.find(a=>a.id==='phishing').earnedTier,1);assert.equal(v.achievements.find(a=>a.id==='offensive-foundations').earnedTier,2);assert.equal(v.achievements.find(a=>a.id==='incident-chain').earnedTier,1);assert.equal(v.achievements.find(a=>a.id==='investigator').earnedTier,2);assert.equal(v.achievements.find(a=>a.id==='correlation').earnedTier,1);assert(v.mastery.some(s=>s.samples>=2&&['Proficient','Strong'].includes(s.band)), 'earned mastery is backed by performance');}
 assert.equal(views.reduce((n,v)=>n+v.newUnlocks.length,0),(await db.prepare('SELECT COUNT(*) AS n FROM achievement_unlocks WHERE user_id=?').bind('existing').first()).n,'concurrent reads announce each new tier only once');
 const count=(await db.prepare('SELECT COUNT(*) AS n FROM achievement_unlocks WHERE user_id=?').bind('existing').first()).n;assert(count>0);assert.deepEqual(await retained(db,'existing'),before,'all original user tables remain byte-for-byte unchanged');assert.equal((await view('zero')).achievements.filter(a=>a.earnedTier).length,0,'server account isolation');
 await db.prepare("UPDATE investigation_workspaces SET status='open',closed_at=NULL,decision_json=NULL WHERE user_id=?").bind('existing').run();await db.prepare('UPDATE soc_investigations SET closed_at=NULL,session_json=? WHERE user_id=?').bind('{}','existing').run();const replay=await view();assert.equal(replay.achievements.find(a=>a.id==='investigator').earnedTier,2);assert.equal(replay.achievements.find(a=>a.id==='incident-chain').earnedTier,1);assert.equal(replay.achievements.find(a=>a.id==='soc-response').earnedTier,1);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM achievement_unlocks WHERE user_id=?').bind('existing').first()).n,count);assert.equal(replay.newUnlocks.length,0);
 await worker.dispose();worker=new Miniflare(options);const restored=await view();assert.deepEqual(restored.achievements,replay.achievements);assert.equal(restored.xp,2595);
 for(const path of ['/progress','/achievements','/profile','/experience/nexacorp-response'])assert.equal((await call(path)).status,200,path);
 console.log('PASS: new user, preserved level/rank/skillXP/career, nine meaningful achievements and six legacy IDs, valid correlation/chain, rejected unproven closure and XP-only mastery, retroactive awards, concurrent single ledger entries, no original-table mutation, no reward changes, replay and restart persistence, local identity isolation, rejected client claims and IDs.');
}finally{if(worker)await worker.dispose();await rm(dir,{recursive:true,force:true})}
