// Compiled UI/effects + actual local Worker HTML; no browser/viewport/OAuth claim.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import {readFile,readdir,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,relative} from 'node:path';
import {pathToFileURL} from 'node:url';
import {hasCommit,skipBaseline} from './helpers/git-baseline.mjs';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare}=await import(wranglerRequire.resolve('miniflare'));
const {build}=createRequire(require.resolve('vite/package.json'))('esbuild');
const baseline='e8e9509032bd5b663c2b995c7b8a1f876bbe7410',hasBaseline=hasCommit(baseline);
const uiDir=await mkdtemp(resolve('.sites-runtime/ui-polish-')),directory=await mkdtemp(join(tmpdir(),'cyberlab-ui-polish-'));
const icons=new Set();for(const root of ['app','components'])for(const file of await readdir(root,{recursive:true})){if(!/\.(t|j)sx?$/.test(file))continue;for(const m of (await readFile(join(root,file),'utf8')).matchAll(/import\s*\{([^}]+)\}\s*from\s*['"]lucide-react['"]/g))for(const n of m[1].split(',')){const id=n.trim().replace(/^type /,'').split(/\s+as\s+/)[0];if(/^[A-Za-z]\w*$/.test(id))icons.add(id)}}
async function load(entry,previous=false){const b=await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent',external:['react/jsx-runtime'],plugins:[{name:'ui',setup(b){b.onResolve({filter:/^(react|lucide-react|@\/app\/shell|\.\.?\/shell|@\/components\/native-link|@\/components\/ui\/progress)$/},a=>({path:a.path,namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({loader:'js',contents:a.path==='react'?`export const useState=v=>globalThis.uiHooks.useState(v),useEffect=(f,d)=>globalThis.uiHooks.useEffect(f,d),useLayoutEffect=(f,d)=>globalThis.uiHooks.useEffect(f,d),useRef=v=>globalThis.uiHooks.useRef(v),useMemo=f=>f(),useCallback=f=>f,useContext=c=>c?._currentValue,useId=()=>'harness-id',useInsertionEffect=()=>{};export * from ${JSON.stringify(require.resolve('react'))};`:a.path.endsWith('/shell')?`export const useProgress=()=>globalThis.uiProgress;`:a.path==='lucide-react'?[...icons].map(n=>`export const ${n}=()=>null;`).join('\n'):a.path.endsWith('/progress')?`export const Progress=()=>null;`:`import {jsx} from 'react/jsx-runtime';export default p=>jsx('a',{...p});`}));if(previous)b.onLoad({filter:/\/(app|lib)\/.*\.(ts|tsx)$/},a=>({loader:a.path.endsWith('.tsx')?'tsx':'ts',contents:execFileSync('git',['show',baseline+':'+relative(process.cwd(),a.path)],{encoding:'utf8'})}))}}]});const f=join(uiDir,entry.replace(/[^\w]/g,'-')+(previous?'-before':'')+'.mjs');await writeFile(f,b.outputFiles[0].text);return import(pathToFileURL(f))}
const dashboard=await load('app/dashboard.tsx'),oldDashboard=hasBaseline?await load('app/dashboard.tsx',true):null,adaptive=await load('app/adaptive/overview.tsx'),oldAdaptive=hasBaseline?await load('app/adaptive/overview.tsx',true):null,career=await load('app/career/view.tsx'),oldCareer=hasBaseline?await load('app/career/view.tsx',true):null;
const dataBuild=await build({entryPoints:['lib/curriculum.ts'],bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'}),curriculum=await import('data:text/javascript;base64,'+Buffer.from(dataBuild.outputFiles[0].text).toString('base64'));
let frames=new Map(),frame,seen=new Set(),effects=[],dirty=false,tree,Component,props,requests=[],pending=new Set();
globalThis.uiHooks={useState(v){const i=frame.index++,f=frame;if(!f.slots[i])f.slots[i]={value:typeof v==='function'?v():v};return [f.slots[i].value,n=>{f.slots[i].value=typeof n==='function'?n(f.slots[i].value):n;dirty=true}]},useRef(v){const i=frame.index++;if(!frame.slots[i])frame.slots[i]={current:v};return frame.slots[i]},useEffect(fn,deps){const i=frame.index++,f=frame;if(!f.slots[i]||!deps||deps.some((d,j)=>d!==f.slots[i].deps?.[j])){f.slots[i]?.cleanup?.();f.slots[i]={deps};effects.push(()=>{f.slots[i].cleanup=fn()})}}};
function execute(fn,p,key){let f=frames.get(key);if(!f){f={slots:[],index:0};frames.set(key,f)}seen.add(key);const parent=frame;frame=f;f.index=0;const result=fn(p);frame=parent;return materialize(result,key+'/out')}
function materialize(n,path){if(Array.isArray(n))return n.map((c,i)=>materialize(c,path+'/'+(c?.key||i)));if(n&&typeof n==='object'&&n.props){if(typeof n.type==='function')return execute(n.type,n.props,path+'/'+(n.type.name||'component'));return {...n,props:{...n.props,children:materialize(n.props.children,path+'/children')}}}return n}
function cleanup(){for(const f of frames.values())for(const s of f.slots)s?.cleanup?.();frames=new Map()}
function render(){dirty=false;seen=new Set();tree=execute(Component,props,'root');for(const [k,f]of frames)if(!seen.has(k)){for(const s of f.slots)s?.cleanup?.();frames.delete(k)}for(const e of effects.splice(0))e()}
async function settle(){for(let i=0;i<18;i++){if(pending.size)await Promise.all([...pending]);await new Promise(r=>setImmediate(r));if(dirty)render()}assert(!dirty);assert.equal(pending.size,0)}
function nodes(n,out=[]){if(arguments.length===0)n=tree;if(Array.isArray(n))n.forEach(c=>nodes(c,out));else if(n&&typeof n==='object'&&n.props){out.push(n);nodes(n.props.children,out)}return out}
function text(n){if(n==null||typeof n==='boolean')return '';return Array.isArray(n)?n.map(text).join(''):typeof n==='object'?text(n.props?.children):String(n)}
const items=[{id:'net-1',kind:'quiz',score:3,xp:100,completedAt:'2026-07-01'}];
function progress(loading=false){return {user:{name:'Tester',email:'qa@example.test'},items:[...items],loading,error:'',learning:{activity:[],attempts:[],bookmarks:[],notes:[],dailyTime:[],preferences:{dailyGoal:15,theme:'dark'}},refresh:async()=>{},update:async()=>{}}}
async function mount(c,p={},loading=false){cleanup();requests=[];Component=c;props=p;globalThis.uiProgress=progress(loading);render();await settle()}
const oldFetch=globalThis.fetch;globalThis.fetch=(path,init={})=>{requests.push({path:String(path),method:init.method||'GET'});let body;if(path==='/api/adaptive')body={mastery:[],recommendations:[],needsPractice:[],strongSkills:[],observations:0};else if(path==='/api/career')body={current:{title:'Cybersecurity Trainee'},next:null,newlyUnlocked:[],careerPractice:null};else throw Error('Unexpected API '+path);const p=Promise.resolve(new Response(JSON.stringify(body),{status:200}));pending.add(p);p.finally(()=>pending.delete(p));return p};
let worker;
try{
 if(hasBaseline){await mount(oldDashboard.default,{lessons:curriculum.publicLessons()});assert.equal(requests.filter(r=>r.path==='/api/adaptive').length,1);assert.equal(requests.filter(r=>r.path==='/api/career').length,1)}else skipBaseline(baseline,'pre-change dashboard/adaptive/career fetch comparison');
 await mount(dashboard.default,{lessons:curriculum.publicLessons()});assert.equal(requests.length,0,'closed disclosures must not load unused data');assert.equal(nodes().filter(n=>['a','button'].includes(n.type)&&n.props.className==='primary-button').length,1);const outer=nodes().find(n=>n.type==='details'&&text(n).includes('التدريب الموصى'));const ev={open:true};outer.props.onToggle({target:ev,currentTarget:ev});await settle();assert.equal(requests.filter(r=>r.path==='/api/adaptive').length,1);assert.equal(requests.filter(r=>r.path==='/api/career').length,0);const inner=nodes().find(n=>n.type==='details'&&text(n.props.children?.[0]).includes('المراحل المهنية'));inner.props.onToggle({target:ev,currentTarget:ev});await settle();assert.equal(requests.filter(r=>r.path==='/api/career').length,1);assert(requests.every(r=>r.method==='GET'));
 for(const [before,after,name]of [[oldAdaptive?.useAdaptive,adaptive.useAdaptive,'adaptive'],[oldCareer?.useCareer,career.useCareer,'career']]){
  if(before){await mount(()=>{before();return null},{},true);assert.equal(requests.length,1);globalThis.uiProgress=progress(false);render();await settle();assert.equal(requests.length,2,'baseline '+name+' duplicates initial data fetch after progress restores')}
  await mount(()=>{after();return null},{},true);assert.equal(requests.length,0);globalThis.uiProgress=progress(false);render();await settle();assert.equal(requests.length,1,'one initial '+name+' request');globalThis.uiProgress=progress(true);render();await settle();assert.equal(requests.length,1);globalThis.uiProgress=progress(false);render();await settle();assert.equal(requests.length,2,'a later explicit progress refresh must still retrieve current '+name+' data');
 }
 cleanup();globalThis.fetch=oldFetch;
 const modules=['index.js',...(await readdir('dist/server',{recursive:true})).filter(f=>f.endsWith('.js')&&f!=='index.js')].map(f=>({type:'ESModule',path:'dist/server/'+f}));worker=new Miniflare({modules,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:directory,cf:false});const db=await worker.getD1Database('DB');for(const file of(await readdir('drizzle')).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())for(const sql of(await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql.trim()).run();
 for(const path of ['/','/learn','/roadmap','/search?q=NAT','/progress','/skills','/career','/profile','/account','/soc','/soc/alerts/SOC-002','/soc/cases/case-layla','/operations/nexacorp','/investigations/soc-SOC-002','/campaigns/first-signal?view=full','/incidents','/experience/nexacorp-first','/experience/nexacorp-email','/campaigns/first-signal','/soc/alerts/SOC-002?view=guided','/investigations/soc-SOC-002?journey=core','/labs/v2/v2-access-control','/labs/v2/v2-attack-surface','/labs/v2/v2-auth-session']){
  const r=await worker.dispatchFetch('http://local.test'+path);assert.equal(r.status,200,path);const html=await r.text();assert.equal((html.match(/<main(?:\s|>)/g)||[]).length,1,'one main landmark: '+path);assert(html.includes('dir="rtl"'),path);if(path.startsWith('/experience/')||path.includes('view=guided')||path.includes('journey=core')||path.startsWith('/labs/v2/'))assert(!html.includes('class="topbar"'),'Focus must not render navigation '+path);
 }
 const after=await db.prepare('SELECT COUNT(*) AS n FROM progress').first();assert.equal(after.n,0,'opening UI must not award progress');assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM skill_awards').first()).n,0);
 console.log('PASS: actual compiled Dashboard closed/open disclosures (2 unused GETs→0), Adaptive/Career initial restoration (2 GETs→1; later refresh preserved), one primary action, local Worker route availability/one main/RTL/Focus/no rewards. No browser visual, touch, real OAuth, viewport, CLS or device test.');
}finally{cleanup();globalThis.fetch=oldFetch;if(worker)await worker.dispose();await rm(directory,{recursive:true,force:true});await rm(uiDir,{recursive:true,force:true})}
