'use client';
import {useEffect,useState} from 'react';
import Link from '@/components/native-link';
import {useProgress} from '@/app/shell';
import type {PublicLesson} from '@/lib/curriculum';
export default function LessonTools({lesson,next,returnTo}:{lesson:PublicLesson;next?:string;returnTo?:string|null}){
 const {learning,user,loading,error:progressError,update}=useProgress();
 const [note,setNote]=useState(''),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const completed=!!learning.activity.find(a=>a.id===lesson.id)?.completedAt;
 const bookmarked=learning.bookmarks.some(b=>b.id===lesson.id);
 useEffect(()=>{if(!loaded&&learning.notes.some(n=>n.id===lesson.id)){setNote(learning.notes.find(n=>n.id===lesson.id)!.content);setLoaded(true)}},[learning.notes,lesson.id,loaded]);
 useEffect(()=>{if(!user)return;let start=Date.now(),active=document.visibilityState==='visible';const tick=()=>{if(!active)return;const seconds=Math.min(30,Math.floor((Date.now()-start)/1000));start=Date.now();if(seconds>0)void fetch('/api/learning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'read',id:lesson.id,seconds})})};const visibility=()=>{if(document.visibilityState==='hidden'){tick();active=false}else{active=true;start=Date.now()}};void fetch('/api/learning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'read',id:lesson.id,seconds:0})});const timer=setInterval(tick,30000);document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visibility);tick()}},[user,lesson.id]);
 async function save(data:Record<string,unknown>,success:string){setBusy(true);setError('');try{await update({...data,id:lesson.id});setMessage(success)}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ.')}finally{setBusy(false)}}
 return <section className="learning-tools" id="study-tools"><h2>مكتبك الدراسي</h2>{!!lesson.takeaways?.length&&<details className="takeaways"><summary>خلاصة الدرس</summary><ul>{lesson.takeaways.map((t,i)=><li key={i}>{t}</li>)}</ul></details>}
 {user&&<><div className="button-row"><button type="button" className="secondary-button" disabled={busy||loading||!!progressError} onClick={()=>void save({action:'bookmark',saved:!bookmarked},bookmarked?'أزيلت الإشارة.':'حُفظت الإشارة.')}>{bookmarked?'إزالة الإشارة':'حفظ في الإشارات'}</button><button type="button" className="secondary-button" disabled={busy||loading||!!progressError||completed} onClick={()=>void save({action:'complete'},'سُجل إكمال الدرس.')}>{completed?'أكملت الدرس':'أكملت قراءة الدرس'}</button>{completed&&<Link className="secondary-button" href={returnTo||'/tracks/'+lesson.track}>{returnTo?'العودة إلى النشاط':'العودة إلى المسار'}</Link>}{completed&&!returnTo&&next&&<Link className="secondary-button" href={'/learn/'+next}>الدرس التالي</Link>}</div><details className="pilot-secondary lesson-feedback"><summary>ملاحظاتي الخاصة</summary><label htmlFor="lesson-note">ملاحظة لهذا الدرس</label><textarea id="lesson-note" value={note} disabled={busy||loading||!!progressError} onChange={e=>{setNote(e.target.value);setLoaded(true)}} maxLength={5000} placeholder="اكتب فكرة أو سؤالًا تريد مراجعته…"/><small>تُحفظ الملاحظة عند الضغط على حفظ، وتبقى مرتبطة بهذا الدرس.</small><button type="button" className="secondary-button" disabled={busy||loading||!!progressError} onClick={()=>void save({action:'note',content:note},'حُفظت الملاحظة.')}>حفظ الملاحظة</button></details></>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="success">{message}</p>}</section>
}
