'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,FolderOpen,ShieldCheck} from 'lucide-react';
import {useProgress} from '@/app/shell';
type CaseDetail={case:{caseId:string;status:string;severity:string;createdAt:string;updatedAt:string;closedAt:string|null;finalConclusion:string|null;title:string;description:string;relatedAlertIds:string[]};alerts:{id:string;title:string;url:string;linkedAt:string}[];evidence:{alertId:string;evidenceId:string;title:string;content:string;time:string;kind:string;collectedAt:string}[];notes:{id:number;content:string;createdAt:string}[];affectedUsers:string[];affectedHosts:string[];timeline:{time:string;label:string}[];error?:string};
export default function CaseWorkspace({id}:{id:string}){
 const {user}=useProgress(),[detail,setDetail]=useState<CaseDetail|null>(null),[loading,setLoading]=useState(!!user),[busy,setBusy]=useState(''),[error,setError]=useState(''),[note,setNote]=useState(''),[conclusion,setConclusion]=useState('');
 useEffect(()=>{if(!user)return;let active=true;fetch('/api/soc/cases/'+id,{cache:'no-store'}).then(async r=>{const d=await r.json() as CaseDetail;if(!r.ok)throw Error(d.error||'تعذر تحميل القضية.');if(active){setDetail(d);setConclusion(d.case.finalConclusion||'')}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'تعذر الاتصال.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user,id]);
 async function act(action:'note'|'close',payload:Record<string,string>){if(busy)return;setBusy(action);setError('');try{const r=await fetch('/api/soc/cases/'+id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const d=await r.json() as CaseDetail&{notes:CaseDetail['notes']};if(!r.ok)throw Error(d.error||'تعذر الحفظ.');if(action==='note'){setDetail(prev=>prev?{...prev,notes:d.notes}:prev);setNote('')}else setDetail(d)}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ.')}finally{setBusy('')}}
 if(!user)return <div className="reading-width soc-page"><a className="back-link" href="/soc">← SOC Console</a><section className="panel"><h1>ملف القضية</h1><p>سجّل الدخول لاستعادة قضيتك.</p><a className="primary-button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/soc/cases/'+id)} target="_top">تسجيل الدخول</a></section></div>;
 if(loading&&!detail)return <div className="reading-width soc-page"><p role="status">جارٍ استعادة القضية…</p></div>;
 if(!detail)return <div className="reading-width soc-page"><p role="alert" className="error">{error}</p><a href="/soc">العودة إلى SOC Console</a></div>;
 const c=detail.case;
 return <div className="reading-width soc-page soc-case-view"><a className="back-link" href="/soc">← SOC Console</a>{id==='case-layla'&&<a className="ib-entry" href="/investigations/soc-SOC-002">لوحة تحقيق تنبيه ليلى المرتبط بالقضية ←</a>}<header className="soc-investigation-header"><div><span className="eyebrow"><FolderOpen size={15}/> NEXACORP / CASE FILE / {c.caseId.toUpperCase()}</span><h1>{c.title}</h1><p>{c.description}</p><div className="soc-attributes"><span className={'soc-severity '+c.severity.toLowerCase()}>{c.severity}</span><span className="soc-status">{c.status==='Resolved'?'مغلقة':'قيد التحقيق'}</span><span>بدأت {new Date(c.createdAt).toLocaleString('ar-SA',{dateStyle:'medium',timeStyle:'short'})}</span></div></div><div className="soc-asset"><span>RELATED ALERTS</span><strong>{detail.alerts.length}</strong><small>إشارات مرتبطة بهذا الملف</small></div></header>
 <div className="soc-case-layout"><div><section className="panel"><span className="eyebrow">ALERT CORRELATION</span><h2>التنبيهات المرتبطة</h2><p>يمكن ربط أكثر من تنبيه بالقضية نفسها. يظهر التنبيه هنا بعد أن توثّق التحقيق وتغلقه كحادث حقيقي.</p><div className="soc-related-alerts">{detail.alerts.map(a=><a href={a.url} key={a.id}><span>{a.id}</span><strong>{a.title}</strong><ArrowLeft size={16}/></a>)}</div>{c.relatedAlertIds.some(id=>!detail.alerts.some(a=>a.id===id))&&<p className="soc-muted">هناك تنبيهات أخرى في قائمة SOC تستحق المقارنة؛ لن تُربط بالقضية حتى تُحقق فيها.</p>}</section>
 <section className="panel soc-case-evidence"><span className="eyebrow">COLLECTED EVIDENCE</span><h2>الأدلة المحفوظة في القضية</h2>{detail.evidence.length?detail.evidence.map(e=><details key={e.alertId+e.evidenceId}><summary><span>{e.time} · {e.alertId}</span><strong>{e.title}</strong></summary><pre dir="auto">{e.content}</pre></details>):<p>لم تُجمع أدلة بعد.</p>}</section>
 <section className="panel soc-case-close"><span className="eyebrow">FINAL CONCLUSION</span><h2>{c.closedAt?'نتيجة القضية':'إغلاق ملف القضية'}</h2>{c.closedAt?<p>{c.finalConclusion}</p>:<form onSubmit={e=>{e.preventDefault();void act('close',{conclusion})}}><label>اكتب الخلاصة والإجراء بناءً على التنبيهات والأدلة<textarea minLength={25} maxLength={2000} required value={conclusion} onChange={e=>setConclusion(e.target.value)} placeholder="ما الذي حدث؟ ما الحسابات والأجهزة المعنية؟ وما الإجراء الذي اتخذته؟"/></label><button type="submit" className="primary-button" disabled={!!busy||conclusion.trim().length<25}>إغلاق القضية وحفظ الخلاصة</button></form>}</section></div>
 <aside><section className="panel soc-case-facts"><span className="eyebrow">CASE ENTITIES</span><h2>نطاق التأثر</h2><strong>المستخدمون</strong><p>{detail.affectedUsers.join('، ')}</p><strong>الأجهزة</strong><p>{detail.affectedHosts.join('، ')}</p><p className="soc-muted">النطاق يتوسع عندما تُربط تنبيهات أخرى بالقضية.</p></section><section className="panel soc-timeline"><span className="eyebrow">CASE TIMELINE</span><h2>خطوات القضية</h2><ol>{detail.timeline.map((t,i)=><li key={i}><time>{new Date(t.time).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}</time><span>{t.label}</span></li>)}</ol></section><section className="panel soc-notes"><span className="eyebrow">ANALYST NOTES / D1</span><h2>ملاحظات القضية</h2><form onSubmit={e=>{e.preventDefault();void act('note',{content:note})}}><label htmlFor="case-note">ملاحظة مرتبطة بالقضية</label><textarea id="case-note" value={note} onChange={e=>setNote(e.target.value)} minLength={3} maxLength={2000} required/><button type="submit" className="secondary-button" disabled={!!busy||note.trim().length<3}>حفظ الملاحظة</button></form>{detail.notes.length?<ol>{detail.notes.map(n=><li key={n.id}><small>{new Date(n.createdAt).toLocaleString('ar-SA',{dateStyle:'short',timeStyle:'short'})}</small><p>{n.content}</p></li>)}</ol>:<p>لا توجد ملاحظات بعد.</p>}</section></aside></div>{error&&<p role="alert" className="error">{error}</p>}<div className="safe-banner"><ShieldCheck size={18}/><p>هذه قضية تدريبية على بيانات NexaCorp افتراضية، بلا أي وصول إلى بيئة إنتاج أو أجهزة خارجية.</p></div></div>;
}
