'use client';
import {useEffect,useState} from 'react';
import {LockKeyhole,ShieldCheck,ArrowLeft} from 'lucide-react';
import {useProgress} from '@/app/shell';
import {bossMissions} from '@/lib/boss-missions';
import {groupByDisplayState} from '@/lib/display-state';
type State={id:string;completedAt:string|null;score:number;stars:number;progress:number;session:{replaying:boolean}};
type Lock={id:string;reasons:string[]};
export default function BossCenter(){
 const {user}=useProgress(),[states,setStates]=useState<State[]>([]),[locks,setLocks]=useState<Lock[]>([]),[loading,setLoading]=useState(!!user),[error,setError]=useState('');
 useEffect(()=>{if(!user)return;let active=true;fetch('/api/missions',{cache:'no-store'}).then(async r=>{const data=await r.json() as {error?:string;states:State[];locks:Lock[]};if(!r.ok)throw Error(data.error||'تعذر التحميل.');if(active){setStates(data.states);setLocks(data.locks)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'تعذر التحميل.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user]);
 const card=(m:typeof bossMissions[number])=>{const s=states.find(s=>s.id===m.id),reasons=locks.find(l=>l.id===m.id)?.reasons||[],locked=reasons.length>0&&!s;const body=<><div className="mission-card-top"><span>{m.id.toUpperCase()}</span><span className="mission-difficulty">{m.difficulty}</span></div><h3>{m.title}</h3><p>{m.description}</p><div className="mission-tags">{m.requiredSkills.map(skill=><span key={skill}>{skill}</span>)}</div>{locked&&<div className="boss-lock"><LockKeyhole size={17}/><div><strong>متطلبات الفتح</strong><ul>{reasons.map(reason=><li key={reason}>{reason}</li>)}</ul></div></div>}<div className="mission-card-bottom"><span>{s?.completedAt?'مكتملة · أفضل نتيجة '+s.score+' من 100 · '+s.stars+' ★'+(s.session.replaying?' · إعادة جارية':''):s?'التقدم '+s.progress+'%':locked?'مقفلة':'جاهزة للتحقيق'}</span><strong>{s?.completedAt?'المكافأة مُنحت':'+'+m.xpReward+' XP'}</strong>{!locked&&<ArrowLeft size={18}/>}</div>{s&&!s.completedAt&&<div className="mission-meter" role="progressbar" aria-label={'تقدم '+m.title} aria-valuenow={s.progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:s.progress+'%'}}/></div>}</>;
 return <a href={'/bosses/'+m.id} className={'mission-card boss-card'+(locked?' locked':'')} key={m.id} aria-label={locked?m.title+' · مقفل · اعرض المتطلبات':m.title}>{body}</a>};
 const grouped=groupByDisplayState(bossMissions,states),{active,completed}=grouped;
 const available=grouped.available.filter(m=>!locks.some(l=>l.id===m.id&&l.reasons.length));
 const locked=grouped.available.filter(m=>locks.some(l=>l.id===m.id&&l.reasons.length));
 return <div className="reading-width mission-center boss-center"><div className="page-heading"><div><div className="eyebrow">المهمات / تحقيقات متقدمة</div><h1>التحقيقات المتقدمة</h1><p>تحقيقات متعددة المراحل، تعتمد على الأدلة والأدوات وقرارات الاستجابة.</p></div></div><div className="safe-banner"><ShieldCheck size={20}/><p>جميع الشبكات والبريد والسجلات والطرفية محاكاة داخل التطبيق.</p></div>
 {!user?<div className="panel"><p>سجّل الدخول لعرض متطلبات الفتح وحفظ التحقيقات.</p><a className="primary-button" href="/signin-with-chatgpt?return_to=%2Fbosses" target="_top">تسجيل الدخول</a></div>:loading?<p role="status">جارٍ تحميل التحقيقات…</p>:error?<p role="alert" className="error">{error}</p>:<><section className="mission-group"><h2>تحقيقات قيد التقدم</h2>{active.length?<div className="mission-grid">{active.map(card)}</div>:<p className="muted">لا يوجد تحقيق قيد التقدم.</p>}</section><section className="mission-group"><h2>تحقيقات متاحة <small>{available.length}</small></h2>{available.length?<div className="mission-grid">{available.map(card)}</div>:<p className="muted">لا يوجد تحقيق متاح الآن. راجع متطلبات التحقيقات المقفلة.</p>}</section><section className="mission-group"><h2>تحقيقات مقفلة ومتطلباتها <small>{locked.length}</small></h2><div className="mission-grid">{locked.map(card)}</div></section><section className="mission-group"><h2>تحقيقات مكتملة <small>{completed.length}</small></h2>{completed.length?<div className="mission-grid">{completed.map(card)}</div>:<p className="muted">ستظهر النتائج وأفضل النجوم بعد إنجاز أول تحقيق.</p>}</section></>}</div>
}
