'use client';
import {CompletionProgressSummary} from '@/app/progression/view';
import {useState} from 'react';
import ActivityBrief from '@/components/activity-brief';
import ProgressiveHints from '@/components/progressive-hints';
import {useProgress} from '@/app/shell';
import type {MissionSession} from '@/lib/mission-engine';
import {coreJourney,signalMission,signalSteps,recoverSignalStep} from '@/lib/mission-first-core';
import {CoreFrame,CaseAccess,Knowledge,useCoreDraft,useCoreStep,useSavedCase} from '@/app/experience/core-ui';
type State={id:string;completedAt:string|null;session:MissionSession};
type Data={states?:State[];locks?:{id:string;reasons:string[]}[];state?:State};
const initial={field:'',account:'',ip:'',sequence:'',contain:'',preserve:'',evidence:[] as string[]};
const sequenceChoices=[['phishing email link credentials unauthorized login','رسالة تصيد ← فتح رابط ← إدخال بيانات ← دخول غير مصرح'],['failed login only','محاولات فاشلة فقط، دون جلسة ناجحة'],['domain mismatch alone','اختلاف نطاق الرسالة يثبت اختراق الجهاز وحده']];
const containment=['إنهاء جلسات ليلى وإعادة تعيين كلمة المرور','حظر مرسل البريد فقط مع إبقاء جلسة الحساب','مسح الجهاز دون حفظ السجلات'];
const preservation=['حفظ الرسالة والترويسة والسجلات وإبلاغ فريق الأمن','حذف الرسالة والسجلات لإنهاء المشكلة','مراقبة الحساب دون حفظ الأدلة أو إبلاغ'];
export default function FirstSignalGuided(){
 const api=useSavedCase<Data>('/api/missions'),{refresh}=useProgress();
 const state=api.data?.state||api.data?.states?.find(s=>s.id===coreJourney.signalMissionId)||null;
 const session=state?.session,finished=!!state?.completedAt&&!session?.replaying;
 const reasons=!state?api.data?.locks?.find(l=>l.id===coreJourney.signalMissionId)?.reasons||[]:[];
 const [draft,setDraft]=useCoreDraft('first-signal',initial),[feedback,setFeedback]=useState('');
 const [step,setStep]=useCoreStep(coreJourney.signalHref,signalSteps,api.ready&&!!api.data,s=>recoverSignalStep(s,session||null,!!state?.completedAt));
 const readyForDecision=signalMission.successConditions.evidence.every(e=>session?.inspected.includes(e))&&signalMission.successConditions.tools.every(t=>session?.usedTools.includes(t));
 const evidence=signalMission.evidence.find(e=>e.id===draft.field);
 const remainingSources=signalMission.successConditions.evidence.filter(id=>!session?.inspected.includes(id));
 const remainingChecks=signalMission.successConditions.tools.filter(id=>!session?.usedTools.includes(id));
 const returnTo=coreJourney.signalHref+'?step='+step+(draft.field?'&field='+draft.field:'');
 async function act(action:string,more:Record<string,unknown>={}){return api.post({id:coreJourney.signalMissionId,action,...more})}
 async function begin(){const d=await act('start');if(d){setFeedback('');setStep(d.state?.completedAt&&!d.state.session.replaying?'result':'evidence')}}
 async function inspect(id:string){const d=await act('inspect',{evidenceId:id});if(d?.state?.session.inspected.includes(id)){setDraft(p=>({...p,field:id}));setFeedback('')}}
 async function decide(){
  if(!readyForDecision||draft.evidence.length<2)return;
  if(!session?.decisions.includes('contain')){const d=await act('decide',{decisionId:'contain',response:draft.contain});if(!d?.state)return;if(!d.state.session.decisions.includes('contain')){setFeedback('راجع السجل: هل انتهت الجلسة غير المعروفة بمجرد التعامل مع البريد؟ اربط الإجراء بنشاط الحساب نفسه.');return}}
  if(!session?.decisions.includes('preserve')){const d=await act('decide',{decisionId:'preserve',response:draft.preserve});if(!d?.state)return;if(!d.state.session.decisions.includes('preserve')){setFeedback('هل يستطيع المحلل التالي مراجعة ما حدث بعد الإجراء الذي اخترته؟ قارن ذلك بمصدر السجلات قبل المتابعة.');return}}
  const d=await act('solve',{answers:{account:draft.account,ip:draft.ip,sequence:draft.sequence}});if(!d?.state)return;
  if(d.state.completedAt&&!d.state.session.replaying){setStep('result');await refresh()}
  else setFeedback('قارن حساب الجلسة الناجحة ومصدرها ببلاغ الموظفة. لا تساوِ محاولة فاشلة بجلسة ناجحة، ولا اختلاف نطاق باختراق مثبت.');
 }
 const patch=(value:Partial<typeof initial>)=>{setDraft(p=>({...p,...value}));setFeedback('')};
 return <CoreFrame title="First Signal" error={api.error}>{!api.ready||!api.user||!api.data?<CaseAccess ready={api.ready} user={api.user} href={coreJourney.signalHref} error={api.error}/>:reasons.length?<section className="pilot-stage"><h1>قضية ظاهرة، لكنها لم تُفتح بعد</h1><p>تحتاج هذه القضية إلى أساس في فحص البريد قبل ربطه بنشاط الحساب. أكمل المتطلبات التالية ثم عد؛ إنجازك السابق يبقى محفوظًا:</p><ul>{reasons.map(r=><li key={r}>{r}</li>)}</ul><a className="primary-button" href="/experience/nexacorp-email">أكمل تحقيق الرسالة</a></section>:<>
 <nav className="pilot-progress" aria-label="مراحل First Signal">{signalSteps.map((s,i)=><span key={s} aria-current={step===s?'step':undefined}>{['البلاغ','الربط','القرار','النتيجة'][i]}</span>)}</nav>
 {step==='brief'&&<section className="pilot-stage"><span className="pilot-kicker">First Signal · قضية التصيد</span><h1>هل بقي الأمر مجرد رسالة؟</h1><p className="pilot-lead">{signalMission.scenario}</p><p>في تدريب البريد صنّفت الرسالة. هنا ستتحقق مما حدث بعدها: تراجع الرسالة ونشاط الموظفة وسجل الدخول، ثم تربطها بالحساب والوقت. هذه عينة مختلفة؛ لا تنقل استنتاج البلاغ السابق إليها تلقائيًا.</p><ActivityBrief skill="ربط البريد بنشاط الحساب" time="12–18 دقيقة" level="بعد تدريب البريد"/><button className="primary-button" disabled={api.busy} onClick={()=>void begin()}>افتح ملف القضية</button><details className="pilot-secondary"><summary>عن هذه المرحلة</summary><p>هذه قضية واحدة موجودة ضمن First Signal. الحملة الكاملة تضم ستة فصول، وتحتفظ بقواعد فتحها وتقدمها.</p><a href="/campaigns/first-signal?view=full">عرض الحملة الكاملة</a></details></section>}
 {step==='evidence'&&<section className="pilot-stage"><span className="pilot-kicker">اربط أكثر من مصدر</span><h1>الرسالة، الموظفة، ثم الجلسة</h1><p>ابدأ بالرسالة، ثم نشاط الموظفة، ثم سجل المصادقة الذي يسجل محاولات الدخول ونتائجها. شغّل الفحوص المرتبطة بالمصدر؛ قراءة السجل وحدها لا تكمل المقارنة.</p><label className="core-field">مصدر الفحص<select value={draft.field} disabled={api.busy} onChange={e=>void inspect(e.target.value)}><option value="">اختر مصدرًا</option>{signalMission.evidence.map(e=><option key={e.id} value={e.id} disabled={e.id==='auth-log'&&(!session?.inspected.includes('email')||!session.inspected.includes('activity'))}>{e.title}{session?.inspected.includes(e.id)?' · تمت المراجعة':''}</option>)}</select></label>
 {evidence&&session?.inspected.includes(evidence.id)&&<article className="core-observation"><h2>{evidence.title}</h2><pre dir="auto">{evidence.content}</pre>{evidence.id==='email'&&<><button className="secondary-button" disabled={api.busy} onClick={()=>void act('tool',{toolId:'domain'})}>عاين النطاق والوجهة</button><Knowledge title="متى يكون اختلاف النطاق مهمًا؟" text="اختلاف النطاق إشارة. اربطه بطلب الرسالة ونشاط المستخدم ونتيجة الدخول قبل الحكم على الأثر." lessonId="security-8" returnTo={returnTo}/></>}{evidence.id==='activity'&&<Knowledge title="رتّب الملاحظة قبل الاستنتاج" text="فتح رسالة أو رابط ليس وحده دليل فقدان الحساب. ابحث عن تفاعل لاحق وجلسة غير معتادة في مصدر مستقل." lessonId="security-11" returnTo={returnTo}/>} {evidence.id==='auth-log'&&<><div className="core-secondary-actions"><button className="secondary-button" disabled={api.busy} onClick={()=>void act('tool',{toolId:'auth'})}>رشّح جلسات الحساب</button><button className="secondary-button" disabled={api.busy} onClick={()=>void act('tool',{toolId:'ip'})}>قارن نشاط المصدر</button></div><Knowledge title="فشل الدخول أم جلسة ناجحة؟" text="الفشل يسجل محاولة دخول لم تنجح؛ النجاح يسجل دخولًا للحساب ولا يحدد وحده الشخص الذي استخدمه. قارِن الحساب والمصدر والوقت بنشاط الموظفة قبل الاستنتاج." lessonId="soc-2" returnTo={returnTo}/></>}</article>}
 {session&&session.transcript.length>0&&<details className="pilot-secondary"><summary>نتائج الفحوص التي أجريتها</summary>{session.transcript.map((t,i)=><pre key={i} dir="auto">{t.output}</pre>)}</details>}
 <p className="pilot-footnote" role="status">{remainingSources.length?"المصادر المتبقية: "+remainingSources.map(id=>signalMission.evidence.find(e=>e.id===id)?.title).join("، "):remainingChecks.length?"الفحوص المتبقية: "+remainingChecks.map(id=>signalMission.tools.find(t=>t.id===id)?.label).join("، "):"اكتملت مراجعة المصادر والفحوص؛ كوّن الآن استنتاجًا يربطها."}</p><p className="pilot-footnote">{signalMission.successConditions.evidence.filter(e=>session?.inspected.includes(e)).length} من {signalMission.successConditions.evidence.length} مصادر تمت مراجعتها · {signalMission.successConditions.tools.filter(t=>session?.usedTools.includes(t)).length} من {signalMission.successConditions.tools.length} فحوص</p><button className="primary-button" disabled={api.busy||!readyForDecision} onClick={()=>{setFeedback('');setStep('decision')}}>كوّن استنتاجك واتخذ الإجراء</button></section>}
 {step==='decision'&&!finished&&<section className="pilot-stage"><h1>ما أثر الرسالة، وما الإجراء المناسب؟</h1><p>حدد الحساب ومصدر الدخول وتسلسل الأحداث، واختر مصدرين يدعمان ذلك. ثم افصل إجراء حماية الحساب عن إجراء حفظ الأدلة.</p><ProgressiveHints hints={["ابحث عن الحساب المشترك بين نشاط الموظفة وسجل الدخول؛ لا تختَر من اسم الرسالة وحده.","رتّب أوقات الرسالة والتفاعل والدخول. هل السجل يعرض محاولات فاشلة فقط أم دخولًا ناجحًا أيضًا؟","اختبر أثر الإجراء: هل يعالج جلسة الحساب، وهل يترك الرسالة والسجلات متاحة للمراجعة؟"]}/><form onSubmit={e=>{e.preventDefault();void decide()}}><label className="core-field">الحساب المتأثر<select required value={draft.account} onChange={e=>patch({account:e.target.value})}><option value="">اختر من السجلات</option>{['layla','omar','admin'].map(a=><option key={a}>{a}</option>)}</select></label><label className="core-field">مصدر الجلسة غير المصرح بها<select required value={draft.ip} onChange={e=>patch({ip:e.target.value})}><option value="">قارن المصادر</option>{['192.0.2.17','198.51.100.77','192.0.2.18'].map(ip=><option key={ip}>{ip}</option>)}</select></label><label className="core-field">تسلسل ما حدث<select required value={draft.sequence} onChange={e=>patch({sequence:e.target.value})}><option value="">اربط الملاحظات</option>{sequenceChoices.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 <fieldset className="pilot-choices"><legend>الأدلة التي تدعم استنتاجك</legend>{signalMission.evidence.filter(e=>session?.inspected.includes(e.id)&&e.id!=='policy').map(e=><label key={e.id}><input type="checkbox" checked={draft.evidence.includes(e.id)} onChange={event=>patch({evidence:event.target.checked?[...draft.evidence,e.id]:draft.evidence.filter(id=>id!==e.id)})}/>{e.title}</label>)}</fieldset>
 <label className="core-field">إجراء الحساب<select required value={draft.contain} disabled={session?.decisions.includes('contain')} onChange={e=>patch({contain:e.target.value})}><option value="">اختر الإجراء</option>{containment.map(c=><option key={c}>{c}</option>)}</select>{session?.decisions.includes('contain')&&<small>إجراء الحساب محفوظ في التحقيق.</small>}</label><label className="core-field">التعامل مع الأدلة<select required value={draft.preserve} disabled={session?.decisions.includes('preserve')} onChange={e=>patch({preserve:e.target.value})}><option value="">اختر ما ستفعله</option>{preservation.map(c=><option key={c}>{c}</option>)}</select>{session?.decisions.includes('preserve')&&<small>إجراء حفظ الأدلة محفوظ.</small>}</label>
 {!feedback?<button className="primary-button" type="submit" disabled={api.busy||draft.evidence.length<2}>سجّل القرار وأغلق القضية</button>:<div className="pilot-feedback" role="status"><p>{feedback}</p><button className="primary-button" type="button" onClick={()=>{setFeedback('');setStep('evidence')}}>راجع الدليل المخالف</button></div>}<button className="email-secondary-link" type="button" onClick={()=>setStep('evidence')}>العودة للفحص</button></form></section>}
 {step==='result'&&finished&&<section className="pilot-stage pilot-result"><span className="pilot-kicker">قضية التصيد مكتملة</span><h1>ربطت الرسالة بنشاط الحساب</h1><p className="pilot-lead">انتقلت من الاشتباه برسالة إلى تفسير نشاط الحساب باستخدام أكثر من مصدر.</p><div className="pilot-summary"><p><strong>ما تعلمته:</strong> ربط الحساب والوقت ومصدر الدخول بنشاط الموظفة؛ اختلاف نطاق الرسالة وحده لا يثبت الأثر.</p><p><strong>لماذا الإجراء مناسب؟</strong> حماية جلسات الحساب تعالج النشاط المرصود، وحفظ الرسالة والسجلات يتيح مراجعة القرار.</p><p><strong>طبّقها عمليًا:</strong> دوّن خطًا زمنيًا قصيرًا مع مصدر كل حدث، وافصل الملاحظة المسجلة عن استنتاجك.</p><p><strong>في المرحلة التالية:</strong> تفحص تنبيهًا مستقلًا لجلسة ليلى وتقارنها بالجهاز المعتاد، ثم تحدد الأولوية والاستجابة وتوثّق التحقيق.</p></div><p className="pilot-footnote">حُفظ الإنجاز في المهمة الأصلية؛ بقية فصول First Signal لها متطلباتها وتقدمها المستقل.</p><CompletionProgressSummary/><details className="pilot-secondary"><summary>القرار والتقدم المحفوظان</summary><p>حساب layla · مصدر الجلسة 198.51.100.77 · احتواء الحساب وحفظ الأدلة والإبلاغ.</p><p>{session?.lastResult?.xpGranted?'مكافأة المهمة الأصلية محفوظة مرة واحدة.':'الإنجاز محفوظ سابقًا؛ لا مكافأة جديدة للواجهة.'}</p></details><a className="primary-button" href={coreJourney.socHref}>خطوتك التالية: افحص تنبيه جلسة ليلى</a><details className="pilot-secondary"><summary>مراجعة إضافية</summary><a href="/campaigns/first-signal?view=full">الحملة الكاملة وتقدمها</a><button className="secondary-button" disabled={api.busy} onClick={async()=>{if(await act('replay')){setDraft(initial);setFeedback('');setStep('brief')}}}>إعادة القضية دون مكافأة مكررة</button></details></section>}
 </>}</CoreFrame>;
}
