'use client';
import {useCallback,useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,LockKeyhole,Radio,ShieldCheck,BookOpen,BriefcaseBusiness,FileText} from 'lucide-react';
import {useProgress} from '@/app/shell';
import CompanyContext from '@/components/company-context';

type Objective={id:string;title:string;kind:string;url:string;completed:boolean;started:boolean;reasons:string[]};
type Chapter={id:string;number:number;title:string;subtitle:string;briefing:{time:string;label:string;text:string;speaker:string};debrief:string;missionIds:string[];people:string[];unlocked:boolean;complete:boolean;completedCount:number;objectives:Objective[];briefed:boolean;debriefed:boolean};
type State={campaign:{id:string;title:string;description:string;company:string;people:{id:string;name:string;role:string;department:string;initial:string}[]};chapters:Chapter[];currentChapterId:string;completedChapters:number;completed:boolean;progress:number;timeline:{id:string;time:string;title:string;detail:string}[];evidence:{id:string;title:string;detail:string;read:boolean}[];activeObjective:Objective|null;latestEvent:{id:string;time:string;title:string}|null;summary:{casesSolved:number;bossMissionsCompleted:number;evidenceDiscovered:number;skillsDemonstrated:string[];strongestSkills:{name:string;level:number;xp:number}[];skillsNeedingPractice:string[]}|null};

export default function CampaignHub({id}:{id:string}){
 const {user}=useProgress(),[state,setState]=useState<State|null>(null),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(!!user),[busy,setBusy]=useState('');
 const reload=useCallback(async()=>{if(!user)return;setLoading(true);try{const r=await fetch('/api/campaigns/'+encodeURIComponent(id),{cache:'no-store'});const data=await r.json() as State&{error?:string};if(!r.ok)throw Error(data.error||'تعذر تحميل الحملة.');setState(data);setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل الحملة.')}finally{setLoading(false)}},[id,user]);
 useEffect(()=>{void reload()},[reload]);
 async function mark(flagId:string){if(busy)return;setBusy(flagId);setError('');try{const r=await fetch('/api/campaigns/'+encodeURIComponent(id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({flagId})});const data=await r.json() as State&{error?:string};if(!r.ok)throw Error(data.error||'تعذر الحفظ.');setState(data)}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ.')}finally{setBusy('')}}
 if(!user)return <div className="reading-width campaign-hub"><div className="campaign-hero"><span className="eyebrow">حملة CyberLab / القضية الأولى</span><h1>First Signal</h1><p>انضم إلى فريق NexaCorp وتابع القضية مع حفظ تقدمك في حسابك.</p><a className="primary-button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/campaigns/'+id)} target="_top">تسجيل الدخول إلى الحملة</a></div></div>;
 if(loading&&!state)return <div className="reading-width campaign-hub"><p role="status">جارٍ استعادة ملف القضية…</p></div>;
 if(!state)return <div className="reading-width campaign-hub"><p role="alert">{error}</p><button className="secondary-button" onClick={()=>void reload()}>إعادة المحاولة</button></div>;
 const current=state.chapters.find(c=>c.id===state.currentChapterId)!,chapter=state.chapters.find(c=>c.id===(selected||current.id))||current;
 const speaker=state.campaign.people.find(p=>p.id===chapter.briefing.speaker);
 const next=chapter.objectives.find(o=>!o.completed),latest=state.latestEvent;
 return <div className="reading-width campaign-hub">
  <a className="pilot-text-link" href="/campaigns/first-signal">العودة للرحلة الموجّهة</a><CompanyContext kind="campaign" id={id}/>{id==='first-signal'&&<a className="ib-entry" href="/investigations/campaign-first-signal">افتح خزانة الأدلة ولوحة العلاقات للقضية ←</a>}
  <div className="campaign-hero"><div className="campaign-hero-top"><span className="eyebrow"><Radio size={14}/> CyberLab / First Signal / NexaCorp</span><span className="campaign-live">{state.completed?'القضية مغلقة':'القضية جارية'}</span></div><h1>{state.campaign.title}</h1><p>{state.campaign.description}</p><div className="campaign-hero-bottom"><div><span>تقدم القضية</span><strong>{state.progress}%</strong><div className="mission-meter" role="progressbar" aria-label="تقدم الحملة" aria-valuenow={state.progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:state.progress+'%'}}/></div></div><div><span>الفصول المكتملة</span><strong>{state.completedChapters} من {state.chapters.length}</strong></div><div><span>الفصل الحالي</span><strong>{current.number.toString().padStart(2,'0')} · {current.title}</strong></div></div></div>
  <div className="campaign-stat-row"><div><small>آخر حدث</small><strong>{latest?latest.time+' · '+latest.title:'08:42 · بدء ملف القضية'}</strong></div><div><small>الهدف الحالي</small><strong>{state.activeObjective?.title||'أُنجزت أهداف الحملة'}</strong></div><div><small>ملاحظات القضية الاختيارية</small><strong>{state.evidence.length} متاحة · راجعت {state.evidence.filter(e=>e.read).length} منها</strong></div></div>
  {state.completed&&state.summary&&<section className="panel campaign-complete" aria-label="Campaign Complete"><span className="eyebrow">اكتمل التحقيق / NexaCorp</span><h2>أكملت First Signal</h2><p>أغلقت ملف الحادث بعد ربط بلاغات الدعم والأدلة الأمنية. الحملة لا تمنح XP أو Skill XP إضافيًا.</p><div className="campaign-complete-grid"><div><strong>{state.summary.casesSolved}</strong><span>قضايا محلولة</span></div><div><strong>{state.summary.evidenceDiscovered}</strong><span>أدلة مكتشفة</span></div><div><strong>{state.summary.bossMissionsCompleted}</strong><span>Boss Missions</span></div><div><strong>{state.progress}%</strong><span>اكتمال الحملة</span></div></div><div className="campaign-skill-report"><p><b>مهارات أظهرتها:</b> {state.summary.skillsDemonstrated.join(' · ')}</p><p><b>أقوى المهارات:</b> {state.summary.strongestSkills.map(s=>s.name+' · L'+s.level).join('، ')}</p><p><b>تحتاج تدريبًا إضافيًا:</b> {state.summary.skillsNeedingPractice.join('، ')}</p></div></section>}
  <div className="campaign-layout"><div className="campaign-main"><section className="campaign-section"><div className="campaign-section-title"><span className="eyebrow">فصول التحقيق</span><h2>مسار التحقيق</h2><p>تُفتح الفصول حسب إنجازات المهمات الموجودة في حسابك.</p></div><ol className="campaign-chapters">{state.chapters.map(c=><li key={c.id} className={(c.unlocked?'unlocked':'locked')+(chapter.id===c.id?' selected':'')+(c.complete?' complete':'')}><button type="button" disabled={!c.unlocked} onClick={()=>setSelected(c.id)} aria-current={chapter.id===c.id?'step':undefined}><span className="campaign-node">{c.complete?<CheckCircle2 size={20}/>:c.unlocked?c.number.toString().padStart(2,'0'):<LockKeyhole size={17}/>}</span><span className="campaign-chapter-label"><small>الفصل {c.number.toString().padStart(2,'0')} · {c.complete?'مكتمل':c.unlocked?'متاح':'مغلق'}</small><strong>{c.title}</strong><span>{c.subtitle}</span>{!c.unlocked&&<em>أكمل الفصل السابق لفتح هذا الفصل</em>}</span><span className="campaign-count">{c.completedCount} من {c.objectives.length}</span></button></li>)}</ol></section>
   <section className="panel campaign-briefing" aria-live="polite"><div className="campaign-briefing-head"><span className="eyebrow"><BriefcaseBusiness size={14}/> ملخص الفصل {chapter.number.toString().padStart(2,'0')}</span><span>{chapter.briefing.time} · {chapter.briefing.label}</span></div><h2>{chapter.title}</h2><p>{chapter.briefing.text}</p><div className="campaign-speaker"><span className="campaign-avatar">{speaker?.initial}</span><span><strong>{speaker?.name}</strong><small>{speaker?.role} · {speaker?.department}</small></span>{!chapter.briefed&&<button type="button" className="secondary-button" disabled={!!busy} onClick={()=>void mark('brief:'+chapter.id)}>تأكيد قراءة الملخص (اختياري)</button>}</div><div className="campaign-objective-list"><h3>أهداف هذا الفصل</h3>{chapter.objectives.map(o=><div key={o.id} className="campaign-objective"><span>{o.completed?<CheckCircle2 size={18}/>:<span className="campaign-dot"/>}</span><div><strong>{o.title}</strong><small>{o.completed?'مكتملة في حسابك':o.started?'قيد التحقيق':o.kind==='boss'?'تحقيق موسّع':'مهمة متاحة'}</small>{o.reasons.length>0&&!o.completed&&<small>متطلبات المهمة: {o.reasons.join(' · ')}</small>}</div>{o.completed?<a href={o.url}>مراجعة</a>:!o.reasons.length?<a href={o.url}>{o.started?'متابعة':'ابدأ'} <ArrowLeft size={15}/></a>:null}</div>)}</div>{next&&!next.reasons.length&&<a className="primary-button campaign-continue" href={next.url}>متابعة الحملة: {next.title} <ArrowLeft size={17}/></a>}{chapter.complete&&<div className="campaign-debrief"><span className="eyebrow">تحديث القضية</span><p>{chapter.debrief}</p>{!chapter.debriefed&&<button type="button" disabled={!!busy} className="secondary-button" onClick={()=>void mark('debrief:'+chapter.id)}>تأكيد قراءة التحديث (اختياري)</button>}{state.chapters[chapter.number]?.unlocked&&<button className="campaign-next" type="button" onClick={()=>setSelected(state.chapters[chapter.number].id)}>الفصل التالي ←</button>}</div>}</section>
  </div><aside className="campaign-aside"><section className="panel campaign-timeline"><div className="eyebrow"><Radio size={14}/> تسلسل الأحداث</div><h2>تسلسل القضية</h2><p>تظهر الأحداث بعد فتح الفصل أو إنجاز المهمة المعنية فقط.</p><ol>{state.timeline.map(e=><li key={e.id}><time dir="ltr">{e.time}</time><div><strong>{e.title}</strong><small>{e.detail}</small></div></li>)}</ol></section><section className="panel campaign-evidence"><div className="eyebrow"><FileText size={14}/> ملاحظات القضية</div><h2>ملاحظات الأدلة</h2><p>الاطلاع على هذه الملاحظات اختياري، ولا يغيّر اكتمال القضية.</p>{state.evidence.length?state.evidence.map(e=><details key={e.id} onToggle={event=>{if((event.currentTarget as HTMLDetailsElement).open&&!e.read)void mark('evidence:'+e.id)}}><summary>{e.title} · {e.read?'تمت المراجعة':'لم تُراجع (اختياري)'}</summary><p>{e.detail}</p></details>):<p>ستظهر الملاحظات هنا بعد إنهاء التحقيقات. لا تُعرض أدلة الفصول القادمة.</p>}</section><section className="panel campaign-team"><div className="eyebrow"><BookOpen size={14}/> فريق NexaCorp</div><h2>فريق القضية</h2>{state.campaign.people.map(p=><div key={p.id}><span className="campaign-avatar">{p.initial}</span><span><strong>{p.name}</strong><small>{p.role} · {p.department}</small></span></div>)}</section></aside></div>{error&&<p role="alert" className="error">{error}</p>}
  <footer className="campaign-footer"><a href="/missions">مركز المهمات</a><a href="/bosses">Boss Missions</a><a href="/skills">مهاراتي</a><ShieldCheck size={17}/> جميع بيئات التحقيق محاكاة تعليمية.</footer>
 </div>
}
