'use client';
import {CompletionProgressSummary} from '@/app/progression/view';
import {useEffect,useState} from 'react';
import {CoreFrame,CaseAccess,Knowledge,useCoreDraft,useCoreStep,useSavedCase} from '@/app/experience/core-ui';
import type {CoreBoardData} from '@/app/experience/core-types';
import {dynamicSteps,dynamicKnowledge} from '@/lib/dynamic-presentation';
import {relationshipLabels,relationshipTypes,type BoardDecision,type RelationshipType} from '@/lib/investigation-board';
type Investigation=CoreBoardData&{feedback:{observation:string;impact:string}|null;incident:{objective:string;guidance:string;difficulty:string;timeline:{time:string;summary:string}[]};review:{explanation:string;important:string[];distractors:string[]}|null};
const emptyDecision:BoardDecision={hypothesis:'',affected:[],evidenceIds:[],action:''};
const initial={field:'',from:'',to:'',relation:'OBSERVED_IN' as RelationshipType,reason:'',note:'',classification:'uncertain',decision:emptyDecision};
export default function DynamicWorkspace({id}:{id:string}){
 const api=useSavedCase<Investigation>('/api/investigations/'+id),[draft,setDraft]=useCoreDraft('dynamic-'+id,initial),[localFeedback,setFeedback]=useState('');
 const base='/investigations/'+id,closed=!!api.data&&api.data.workspace.status!=='open';
 const collected=api.data?.evidence.filter(e=>e.collectedAt).map(e=>e.evidenceId)||[];
 const [step,setStep]=useCoreStep<(typeof dynamicSteps)[number]>(base,dynamicSteps,api.ready&&!!api.data,s=>{if(closed)return 'result';if(s==='result')return 'observe';if(s==='connect'&&collected.length<2)return 'observe';if(s==='decide'&&!api.data?.links.length)return 'connect';return s});
 const patch=(part:Partial<typeof initial>)=>{setDraft(p=>({...p,...part}));setFeedback('')};
 useEffect(()=>{if(!api.data)return;const field=new URLSearchParams(location.search).get('field');if(field&&api.data.board.evidence.some(e=>e.id===field))patch({field});if(api.data.feedback)setFeedback(api.data.feedback.observation)},[api.ready]);
 useEffect(()=>{if(!api.ready)return;const url=new URL(location.href);if(draft.field)url.searchParams.set('field',draft.field);else url.searchParams.delete('field');history.replaceState(null,'',url.pathname+url.search)},[draft.field,api.ready]);
 const choice=draft.decision,decisionPatch=(part:Partial<BoardDecision>)=>patch({decision:{...choice,...part}}),toggle=(key:'affected'|'evidenceIds',value:string)=>decisionPatch({[key]:choice[key].includes(value)?choice[key].filter(v=>v!==value):[...choice[key],value]});
 const selected=api.data?.board.evidence.find(e=>e.id===draft.field),saved=api.data?.evidence.find(e=>e.evidenceId===draft.field);
 const visibleNodes=api.data?.board.nodes.filter(n=>!!n.companyRef||api.data?.board.evidence.some(e=>collected.includes(e.id)&&e.entities.includes(n.id))||n.kind==='evidence'&&collected.includes(n.id.slice(9)))||[];
 useEffect(()=>{if(!saved)return;setDraft(p=>({...p,note:saved.note,classification:saved.classification||'uncertain'}))},[draft.field,saved?.note,saved?.classification]);
 const knowledge=selected&&dynamicKnowledge[selected.type];
 useEffect(()=>{window.scrollTo(0,0)},[step]);
 async function review(){if(!selected)return;const d=await api.post({action:'review',evidenceId:selected.id});if(d){const e=d.evidence.find(e=>e.evidenceId===selected.id);patch({note:e?.note||'',classification:e?.classification||'uncertain'})}}
 async function decide(){const d=await api.post({action:'decide',decision:choice});if(!d)return;if(d.workspace.status!=='open'){setStep('result')}else setFeedback(d.feedback?.observation||'قارن الأدلة والعلاقات مع نطاق قرارك.')}
 if(!api.ready||!api.data)return <CoreFrame title="تحقيق التنبيه"><CaseAccess ready={api.ready} user={api.user} href={base} error={api.error}/></CoreFrame>;
 return <CoreFrame title="تحقيق التنبيه" error={api.error}><div className="dynamic-focus">{api.error&&<p className="pilot-error" role="alert">{api.error}</p>}<nav className="pilot-progress" aria-label="مراحل القضية">{dynamicSteps.map((s,i)=><span key={s} aria-current={step===s?'step':undefined}>{['التنبيه','الفحص','العلاقات','القرار','النتيجة'][i]}</span>)}</nav>
 {step==='brief'&&<section className="pilot-stage"><span className="pilot-kicker">تنبيه داخل NexaCorp</span><h1>{api.data.board.title}</h1><p className="pilot-lead">{api.data.board.subtitle}</p><dl className="response-context"><div><dt>الموظف والحساب</dt><dd>{api.data.board.nodes.find(n=>n.kind==='employee')?.label} · <bdi dir="ltr">{api.data.board.nodes.find(n=>n.kind==='account'&&n.companyRef?.id!=='backup')?.label}</bdi></dd></div><div><dt>الجهاز المعروف</dt><dd><bdi dir="ltr">{api.data.board.nodes.find(n=>n.kind==='device')?.label} · {api.data.board.nodes.find(n=>n.kind==='ip')?.label}</bdi></dd></div></dl><p>{api.data.incident.objective}</p><button className="primary-button" onClick={()=>setStep('observe')}>ابدأ فحص المصادر</button></section>}
 {step==='observe'&&<section className="pilot-stage"><span className="pilot-kicker">خزانة الأدلة</span><h1>ما الذي يثبته كل مصدر؟</h1>{api.data.incident.guidance&&<p>{api.data.incident.guidance}</p>}<label className="core-field">المصدر الذي تريد فحصه<select value={draft.field} disabled={api.busy} onChange={e=>patch({field:e.target.value})}><option value="">اختر مصدرًا</option>{api.data.board.evidence.map(e=><option key={e.id} value={e.id}>{e.title}{collected.includes(e.id)?' · محفوظ':''}</option>)}</select></label>
 {selected&&<article className="core-observation"><h2>{selected.title}</h2><p className="pilot-footnote">{selected.source} · <bdi dir="ltr">{selected.timestamp}</bdi></p>{saved?.reviewedAt&&<pre dir="ltr">{selected.raw}</pre>}{knowledge&&<Knowledge {...knowledge} returnTo={base+'?step=observe&field='+selected.id}/>}<div className="response-evidence-state">{saved?.reviewedAt?'تمت المراجعة':'لم تؤكد المراجعة بعد'} · {saved?.collectedAt?'محفوظ في الخزانة':'لم يُجمع'}</div>{saved?.reviewedAt&&<details className="pilot-secondary"><summary>تصنيفك وملاحظة المحلل</summary><form onSubmit={e=>{e.preventDefault();void api.post({action:'annotate',evidenceId:selected.id,note:draft.note,classification:draft.classification})}}><label className="core-field">التصنيف<select value={draft.classification} onChange={e=>patch({classification:e.target.value})}><option value="uncertain">غير محسوم</option><option value="relevant">مرتبط</option><option value="irrelevant">غير مرتبط</option></select></label><label className="core-field">ملاحظتك<textarea maxLength={1200} value={draft.note} onChange={e=>patch({note:e.target.value})}/></label><button className="secondary-button" disabled={api.busy}>احفظ الملاحظة</button></form></details>}</article>}
 <p className="pilot-footnote">الأدلة المحفوظة: {collected.length}. ليس كل مصدر إثباتًا للحادث؛ اجمع ما يسند فرضيتك.</p>
 {selected&&!saved?.reviewedAt?<button className="primary-button" disabled={api.busy} onClick={()=>void review()}>أكد مراجعة المصدر</button>:selected&&!saved?.collectedAt?<button className="primary-button" disabled={api.busy} onClick={()=>void api.post({action:'collect',evidenceId:selected.id})}>احفظ الدليل في الخزانة</button>:<button className="primary-button" disabled={collected.length<2||api.busy} onClick={()=>setStep('connect')}>اربط ما جمعته</button>}
 {selected&&(!saved?.collectedAt)&&collected.length>=2&&<button className="email-secondary-link" onClick={()=>setStep('connect')}>انتقل للعلاقات المحفوظة</button>}
 <details className="pilot-secondary"><summary>التسلسل الزمني والمصادر المحفوظة</summary><ol>{api.data.incident.timeline.map(e=><li key={e.time+e.summary}><bdi dir="ltr">{e.time}</bdi> · {e.summary}</li>)}</ol>{api.data.board.evidence.filter(e=>collected.includes(e.id)).map(e=><button className="email-secondary-link" key={e.id} onClick={()=>patch({field:e.id})}>{e.title}</button>)}</details></section>}
 {step==='connect'&&<section className="pilot-stage"><span className="pilot-kicker">لوحة التحقيق</span><h1>اربط كيانين بسبب تدعمه الأدلة</h1><form onSubmit={async e=>{e.preventDefault();if(await api.post({action:'link',fromId:draft.from,toId:draft.to,relation:draft.relation,reason:draft.reason})){patch({reason:''})}}}><div className="core-two-fields"><label className="core-field">من<select required value={draft.from} onChange={e=>patch({from:e.target.value})}><option value="">اختر كيانًا</option>{visibleNodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label className="core-field">إلى<select required value={draft.to} onChange={e=>patch({to:e.target.value})}><option value="">اختر كيانًا</option>{visibleNodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label></div><label className="core-field">العلاقة<select value={draft.relation} onChange={e=>patch({relation:e.target.value as RelationshipType})}>{relationshipTypes.map(r=><option key={r} value={r}>{relationshipLabels[r]} · {r}</option>)}</select></label><label className="core-field">ما الملاحظة التي تبرر الربط؟<textarea required minLength={8} maxLength={400} value={draft.reason} onChange={e=>patch({reason:e.target.value})}/></label><button className={api.data.links.length?'secondary-button':'primary-button'} disabled={api.busy}>احفظ العلاقة الموثقة</button></form>
 {api.data.incident.difficulty!=='advanced'&&<Knowledge {...dynamicKnowledge.links} returnTo={base+'?step=connect'}/>}<ol className="response-links">{api.data.links.map(l=><li key={l.fromId+l.relation+l.toId}><bdi>{api.data?.board.nodes.find(n=>n.id===l.fromId)?.label}</bdi> · {relationshipLabels[l.relation]} · <bdi>{api.data?.board.nodes.find(n=>n.id===l.toId)?.label}</bdi><p>{l.reason}</p><button className="email-secondary-link" disabled={api.busy} onClick={()=>void api.post({action:'unlink',fromId:l.fromId,toId:l.toId,relation:l.relation})}>راجع هذه العلاقة وأزلها</button></li>)}</ol>{api.data.links.length>0&&<button className="primary-button" onClick={()=>setStep('decide')}>ابنِ فرضيتك وحدد الاستجابة</button>}<button className="email-secondary-link" onClick={()=>setStep('observe')}>عد لمصدر الدليل</button></section>}
 {step==='decide'&&<section className="pilot-stage"><span className="pilot-kicker">الفرضية والقرار</span><h1>ما الذي تستطيع إثباته؟</h1><form onSubmit={e=>{e.preventDefault();void decide()}}><label className="core-field">تفسير الأحداث<select required value={choice.hypothesis} onChange={e=>decisionPatch({hypothesis:e.target.value})}><option value="">اختر فرضيتك</option>{api.data.board.hypotheses.map(h=><option key={h.id} value={h.id}>{h.label}</option>)}</select></label><fieldset className="pilot-choices"><legend>نطاق الحسابات أو الأصول محل التقييم</legend>{api.data.board.nodes.filter(n=>['employee','account','device','server'].includes(n.kind)).map(n=><label key={n.id}><input type="checkbox" checked={choice.affected.includes(n.id)} onChange={()=>toggle('affected',n.id)}/><bdi>{n.label}</bdi></label>)}</fieldset><fieldset className="pilot-choices"><legend>الأدلة التي تسند هذا الاستنتاج</legend>{api.data.board.evidence.filter(e=>collected.includes(e.id)).map(e=><label key={e.id}><input type="checkbox" checked={choice.evidenceIds.includes(e.id)} onChange={()=>toggle('evidenceIds',e.id)}/>{e.title}</label>)}</fieldset><label className="core-field">الإجراء المناسب<select required value={choice.action} onChange={e=>decisionPatch({action:e.target.value})}><option value="">اختر إجراءً</option>{api.data.board.actions.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label>{!localFeedback?<button className="primary-button" disabled={api.busy||!choice.affected.length||choice.evidenceIds.length<2}>احفظ القرار وشاهد أثره</button>:<div role="status" className="pilot-feedback"><p>{localFeedback}</p><p>{api.data.feedback?.impact}</p><button type="button" className="primary-button" onClick={()=>{setFeedback('');setStep('observe')}}>أعد الفحص دون فقد أدلتك</button></div>}<button type="button" className="email-secondary-link" onClick={()=>setStep('connect')}>راجع العلاقات قبل القرار</button></form></section>}
 {step==='result'&&closed&&<section className="pilot-stage pilot-result"><span className="pilot-kicker">القرار محفوظ</span><h1>الاستنتاج متوافق مع الأدلة</h1><p className="pilot-lead">{api.data.review?.explanation}</p><CompletionProgressSummary achievementId="investigator"/><details className="pilot-secondary"><summary>ما الذي ثبت، وما الذي لم يثبت؟</summary><h2>مصادر الاستنتاج</h2><ul>{api.data.review?.important.map(id=><li key={id}>{api.data?.board.evidence.find(e=>e.id===id)?.title}</li>)}</ul><h2>مصادر لا تثبت الحادث</h2><ul>{api.data.review?.distractors.map(id=><li key={id}>{api.data?.board.evidence.find(e=>e.id===id)?.title}</li>)}</ul><p>مارست جمع الأدلة، ربط الكيانات، تحديد النطاق، والاستجابة المتناسبة. حالتك محفوظة في التحقيق الحالي؛ لم تتغير مكافآت المحتوى القديم.</p></details><a className="primary-button" href="/incidents">اختر القضية التالية</a><details className="pilot-secondary"><summary>مراجعة نفس القضية</summary><button className="secondary-button" disabled={api.busy} onClick={async()=>{if(await api.post({action:'reopen'})){setStep('observe')}}}>أعد الفحص مع حفظ الأدلة ودون مكافآت</button></details></section>}
 </div></CoreFrame>;
}
