'use client';
import {CompletionProgressSummary} from '@/app/progression/view';
import {useState} from 'react';
import {relationshipLabels,relationshipTypes,type BoardDecision,type RelationshipType} from '@/lib/investigation-board';
import {coreJourney,boardSteps} from '@/lib/mission-first-core';
import {CaseAccess,CoreFrame,Knowledge,useCoreDraft,useCoreStep,useSavedCase} from '@/app/experience/core-ui';
import type {CoreBoardData} from '@/app/experience/core-types';
const initial={field:'',from:'',to:'',relation:'OBSERVED_IN' as RelationshipType,reason:'',note:'',classification:'uncertain',decision:{hypothesis:'',affected:[] as string[],evidenceIds:[] as string[],action:''} as BoardDecision};
export default function CoreInvestigation(){
 const api=useSavedCase<CoreBoardData>('/api/investigations/'+coreJourney.boardId),[draft,setDraft]=useCoreDraft('soc-board',initial),[feedback,setFeedback]=useState('');
 const closed=!!api.data&&api.data.workspace.status!=='open',required=api.data?.board.evidence.filter(e=>e.role==='required')||[];
 const collected=(id:string)=>!!api.data?.evidence.some(e=>e.evidenceId===id&&e.collectedAt),readyForLinks=required.length>0&&required.every(e=>collected(e.id));
 const [step,setStep]=useCoreStep(coreJourney.boardHref,boardSteps,api.ready&&!!api.data,s=>{if(closed)return 'result';if(s==='result')return 'locker';if(s!=='locker'&&!readyForLinks)return 'locker';if(s==='decision'&&!api.data?.links.length)return 'links';return s});
 const selected=api.data?.board.evidence.find(e=>e.id===draft.field),saved=api.data?.evidence.find(e=>e.evidenceId===draft.field);
 const patch=(part:Partial<typeof initial>)=>{setDraft(p=>({...p,...part}));setFeedback('')};
 const choice=draft.decision;
 const decisionPatch=(part:Partial<BoardDecision>)=>patch({decision:{...choice,...part}});
 const toggle=(key:'affected'|'evidenceIds',id:string)=>decisionPatch({[key]:choice[key].includes(id)?choice[key].filter(v=>v!==id):[...choice[key],id]});
 async function review(id:string){if(closed){patch({field:id});return}const d=await api.post({action:'review',evidenceId:id});if(d){const e=d.evidence.find(e=>e.evidenceId===id);patch({field:id,note:e?.note||'',classification:e?.classification||'uncertain'})}}
 async function decide(){const data=await api.post({action:'decide',decision:choice});if(!data)return;if(data.workspace.status!=='open')setStep('result');else setFeedback(choice.affected.includes('device:WKST-02')?'الدليل يصف متصفحًا غير مسجل في خدمة الهوية. أين الدليل الذي يثبت إصابة محطة WKST-02 نفسها؟':'قارن سجل الجلسات وبصمة الجهاز مع فرضيتك. هل تفسر الأدلة معًا، أم تعتمد على سياق البريد وحده؟');}
 return <CoreFrame title="تحقيق جلسة ليلى" error={api.error}>{!api.ready||!api.user||!api.data?<CaseAccess ready={api.ready} user={api.user} href={coreJourney.boardHref} error={api.error}/>:<>
 <nav className="pilot-progress" aria-label="مراحل لوحة التحقيق">{boardSteps.map((s,i)=><span key={s} aria-current={s===step?'step':undefined}>{['الأدلة','العلاقات','الفرضية','النتيجة'][i]}</span>)}</nav>
 {step==='locker'&&<section className="pilot-stage"><span className="pilot-kicker">خزانة الأدلة · Evidence Locker</span><h1>ما الذي جمعته، وما الذي ما زال فرضية؟</h1><p>هنا تحفظ المصادر التي جمعتها من التنبيه لتراجعها وتستند إليها في قرارك. الدليل الخام لا يتغير؛ تصنيفك وملاحظتك يعبّران عن تحليلك.</p><label className="core-field">الدليل<select value={draft.field} disabled={api.busy} onChange={e=>void review(e.target.value)}><option value="">اختر للمراجعة</option>{api.data.board.evidence.map(e=><option key={e.id} value={e.id}>{e.title} · {e.role==='required'?'مصدر حاسم':'داعم'}{collected(e.id)?' · محفوظ':''}</option>)}</select></label>
 {selected&&saved?.reviewedAt&&<article className="core-observation"><h2>{selected.title}</h2><pre dir="auto">{selected.raw}</pre>{!saved.collectedAt&&<button className="secondary-button" disabled={api.busy} onClick={()=>void api.post({action:'collect',evidenceId:selected.id})}>اجمع الدليل في الخزانة</button>}<details className="pilot-secondary"><summary>تصنيفك وملاحظة قصيرة</summary><form onSubmit={e=>{e.preventDefault();void api.post({action:'annotate',evidenceId:selected.id,note:draft.note,classification:draft.classification})}}><label className="core-field">تصنيفك<select value={draft.classification} onChange={e=>patch({classification:e.target.value})}><option value="relevant">مرتبط</option><option value="uncertain">غير محسوم</option><option value="irrelevant">غير مرتبط</option></select></label><label className="core-field">ملاحظتك<textarea maxLength={1200} value={draft.note} onChange={e=>patch({note:e.target.value})}/></label><button className="secondary-button" disabled={api.busy}>احفظ الملاحظة</button></form></details></article>}
 <p className="pilot-footnote">{required.filter(e=>collected(e.id)).length} من {required.length} مصادر حاسمة محفوظة. لا يلزم جمع كل الأدلة الداعمة.</p><button className="primary-button" disabled={api.busy||!readyForLinks} onClick={()=>setStep('links')}>اربط الكيانات التي تصفها الأدلة</button></section>}
 {step==='links'&&<section className="pilot-stage"><span className="pilot-kicker">لوحة التحقيق · Investigation Board</span><h1>لماذا يرتبط هذان الكيانان؟</h1><form onSubmit={async e=>{e.preventDefault();if(await api.post({action:'link',fromId:draft.from,toId:draft.to,relation:draft.relation,reason:draft.reason})){patch({reason:''});setStep('decision')}}}><div className="core-two-fields"><label className="core-field">من<select required value={draft.from} onChange={e=>patch({from:e.target.value})}><option value="">اختر كيانًا</option>{api.data.board.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label><label className="core-field">إلى<select required value={draft.to} onChange={e=>patch({to:e.target.value})}><option value="">اختر كيانًا</option>{api.data.board.nodes.map(n=><option key={n.id} value={n.id}>{n.label}</option>)}</select></label></div><label className="core-field">نوع العلاقة<select value={draft.relation} onChange={e=>patch({relation:e.target.value as RelationshipType})}>{relationshipTypes.map(r=><option key={r} value={r}>{relationshipLabels[r]} · {r}</option>)}</select></label><label className="core-field">ما الملاحظة التي تبررها؟<textarea required minLength={8} maxLength={400} value={draft.reason} onChange={e=>patch({reason:e.target.value})}/></label><button className="primary-button" disabled={api.busy}>احفظ العلاقة وابنِ الفرضية</button></form>
 <Knowledge title="العلاقة لا تعني السببية" text="USES يصف استخدامًا، وOBSERVED_IN يربط كيانًا بسجل أو دليل. اكتب الملاحظة التي تثبت العلاقة؛ عنوان خارجي لا يعني أنه عنوان جهاز الموظفة." lessonId="security-11" returnTo={coreJourney.boardHref+'&step=links'}/>
 {api.data.links.length>0&&<details className="pilot-secondary"><summary>العلاقات المحفوظة</summary>{api.data.links.map((l,i)=><p key={i}><bdi>{api.data?.board.nodes.find(n=>n.id===l.fromId)?.label}</bdi> · {relationshipLabels[l.relation]} · <bdi>{api.data?.board.nodes.find(n=>n.id===l.toId)?.label}</bdi><br/>{l.reason}</p>)}<button className="email-secondary-link" onClick={()=>setStep('decision')}>تابع فرضية التحليل المحفوظ</button></details>}<button className="email-secondary-link" onClick={()=>setStep('locker')}>راجع مصدر الدليل</button></section>}
 {step==='decision'&&<section className="pilot-stage"><h1>فرضية تدعمها الجلسة والجهاز</h1><form onSubmit={e=>{e.preventDefault();void decide()}}><label className="core-field">ماذا حدث؟<select required value={choice.hypothesis} onChange={e=>decisionPatch({hypothesis:e.target.value})}><option value="">اختر فرضيتك</option>{api.data.board.hypotheses.map(h=><option key={h.id} value={h.id}>{h.label}</option>)}</select></label><fieldset className="pilot-choices"><legend>الحسابات أو الأصول المتأثرة</legend>{api.data.board.nodes.filter(n=>['account','device','server','employee'].includes(n.kind)).map(n=><label key={n.id}><input type="checkbox" checked={choice.affected.includes(n.id)} onChange={()=>toggle('affected',n.id)}/><bdi>{n.label}</bdi></label>)}</fieldset><fieldset className="pilot-choices"><legend>الأدلة التي تسند الفرضية</legend>{api.data.board.evidence.filter(e=>collected(e.id)).map(e=><label key={e.id}><input type="checkbox" checked={choice.evidenceIds.includes(e.id)} onChange={()=>toggle('evidenceIds',e.id)}/>{e.title}</label>)}</fieldset><label className="core-field">الإجراء<select required value={choice.action} onChange={e=>decisionPatch({action:e.target.value})}><option value="">اختر الإجراء</option>{api.data.board.actions.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label>
 {!feedback?<button className="primary-button" disabled={api.busy||choice.evidenceIds.length<2||!choice.affected.length}>احفظ الفرضية والقرار</button>:<div className="pilot-feedback" role="status"><p>{feedback}</p><button className="primary-button" type="button" onClick={()=>{setFeedback('');setStep('locker')}}>أعد مراجعة المصدر</button></div>}<button className="email-secondary-link" type="button" onClick={()=>setStep('links')}>عدّل العلاقات</button></form></section>}
 {step==='result'&&closed&&<section className="pilot-stage pilot-result"><h1>تحليلك وعلاقاتك محفوظة</h1><p className="pilot-lead">عد إلى التنبيه لتسجيل تصنيفه والاستجابة وتسليم ملاحظة القضية. حفظ اللوحة لا يغلق التنبيه أو يمنح مكافأة إضافية.</p><CompletionProgressSummary achievementId="investigator"/><details className="pilot-secondary"><summary>راجع القرار والأدلة المحفوظة</summary><p>{api.data.board.hypotheses.find(h=>h.id===api.data?.workspace.decision?.hypothesis)?.label}</p><p>{api.data.board.actions.find(a=>a.id===api.data?.workspace.decision?.action)?.label}</p>{api.data.board.evidence.filter(e=>collected(e.id)).map(e=><details key={e.id}><summary>{e.title}</summary><pre dir="auto">{e.raw}</pre></details>)}</details><a className="primary-button" href={coreJourney.socHref+'&step=decision'}>عد للتنبيه وسجّل الاستجابة</a><details className="pilot-secondary"><summary>مراجعة إضافية</summary><a href="/investigations/soc-SOC-002">العرض الكامل للتحقيق</a><button className="secondary-button" disabled={api.busy} onClick={async()=>{if(await api.post({action:'reopen'}))setStep('locker')}}>أعد فتح اللوحة مع حفظ أدلتها</button></details></section>}
 </>}</CoreFrame>;
}
