'use client';
import DynamicWorkspace from './dynamic-workspace';
import LoadingState from '@/components/loading-state';
import {useEffect,useState} from 'react';
import {ArrowLeft,CheckCircle2,FileSearch,GitBranch,ShieldCheck} from 'lucide-react';
import {useProgress} from '@/app/shell';
import {relationshipLabels,relationshipTypes,type BoardDefinition,type BoardDecision,type BoardNode, type RelationshipType} from '@/lib/investigation-board';
import type {BoardAction} from '@/lib/investigation-storage';
type EvidenceState={evidenceId:string;reviewedAt:string|null;collectedAt:string|null;note:string;classification:string|null};
type LinkState={fromId:string;relation:RelationshipType;toId:string;reason:string;createdAt:string};
type State={board:Omit<BoardDefinition,'expected'|'allowedLinks'>;workspace:{status:string;decision:BoardDecision|null;closedAt:string|null};evidence:EvidenceState[];links:LinkState[];incident?:{instanceId:string;templateId:string;seed:number;difficulty:string;generationVersion?:2;guidance:string;timeline:{time:string;summary:string}[]}|null;review?:{explanation:string;evidence:Record<string,string>;important:string[];distractors:string[];correctLinks:{fromId:string;relation:RelationshipType;toId:string}[];missedEvidence:string[];missedLinks:{fromId:string;relation:RelationshipType;toId:string}[]}|null;message?:string;error?:string};
const kindLabels:Record<string,string>={employee:'موظف',account:'حساب',device:'جهاز',server:'خادم',ip:'عنوان IP',email:'بريد',process:'عملية',file:'ملف',connection:'اتصال',alert:'تنبيه',log:'حدث سجل',evidence:'دليل'};
const typeLabels:Record<string,string>={log:'سجل',email:'بريد',file:'ملف',process:'عملية',network:'اتصال شبكة',account:'حدث حساب',other:'أثر محاكى'};
const roleLabels={required:'مطلوب',supporting:'داعم',distractor:'للمقارنة',unclassified:'قيد التحليل'};
const blank:BoardDecision={hypothesis:'',affected:[],evidenceIds:[],action:''};
function nodeLabel(node:BoardNode){return `${kindLabels[node.kind]} · ${node.label}`}
export default function InvestigationView({id}:{id:string}){
 const {user}=useProgress(),[state,setState]=useState<State|null>(null),[decision,setDecision]=useState<BoardDecision>(blank),[from,setFrom]=useState(''),[to,setTo]=useState(''),[relation,setRelation]=useState<RelationshipType>('USES'),[reason,setReason]=useState(''),[notes,setNotes]=useState<Record<string,string>>({}),[classes,setClasses]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(!user)return;let live=true;fetch('/api/investigations/'+encodeURIComponent(id),{cache:'no-store'}).then(async r=>{const data=await r.json() as State;if(!r.ok)throw Error(data.error||'تعذر تحميل التحقيق.');if(live){setState(data);setDecision(data.workspace.decision||blank);setNotes(Object.fromEntries(data.evidence.map(e=>[e.evidenceId,e.note])));setClasses(Object.fromEntries(data.evidence.map(e=>[e.evidenceId,e.classification||'uncertain'])))}}).catch(e=>{if(live)setError(e instanceof Error?e.message:'تعذر الاتصال.')});return()=>{live=false}},[id,user]);
 async function act(action:BoardAction){if(busy)return;setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/investigations/'+encodeURIComponent(id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action)});const data=await response.json() as State;if(!response.ok)throw Error(data.error||'تعذر الحفظ.');setState(data);setMessage(data.message||'حُفظ التحقيق.');if(action.action==='link'){setReason('')}if(action.action==='decide')setDecision(data.workspace.decision||blank)}catch(e){setError(e instanceof Error?e.message:'تعذر الاتصال.')}finally{setBusy(false)}}
 if(!user)return <div className="reading-width ib-page"><h1>لوحة التحقيق</h1><p>سجّل الدخول لتجميع الأدلة وحفظ استنتاجك.</p><a className="primary-button" target="_top" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/investigations/'+id)}>تسجيل الدخول</a></div>;
 if(!state)return <div className="reading-width ib-page">{error?<div role="alert"><p>{error}</p><button className="secondary-button" onClick={()=>location.reload()}>إعادة المحاولة</button></div>:<LoadingState>جارٍ استعادة التحقيق…</LoadingState>}</div>;
 if(state.incident?.generationVersion===2)return <DynamicWorkspace id={id}/>;
 const {board,workspace}=state,closed=workspace.status!=='open',evidenceState=(eid:string)=>state.evidence.find(e=>e.evidenceId===eid),eligibleNodes=board.nodes.filter(n=>['employee','account','device','server'].includes(n.kind));
 const collected=state.evidence.filter(e=>e.collectedAt).length,reviewed=state.evidence.filter(e=>e.reviewedAt).length,review=state.review;
 const toggle=(key:'affected'|'evidenceIds',value:string)=>setDecision(previous=>({...previous,[key]:previous[key].includes(value)?previous[key].filter(item=>item!==value):[...previous[key],value]}));
 return <div className="reading-width ib-page"><a className="back-link" href={board.sourceKind==='campaign'?board.sourceHref+'?view=full':board.sourceHref}>← العودة إلى {board.sourceKind==='dynamic'?'الحوادث المتغيرة':board.sourceKind==='soc'?'التنبيه':board.sourceKind==='boss'?'التحقيق الأصلي':'First Signal'}</a>
 <header className="ib-header"><span className="eyebrow">NEXACORP / INVESTIGATION</span><h1>{board.title}</h1><p>{board.subtitle}</p><div className="ib-status"><span>{closed?'النتيجة محفوظة · '+(workspace.status==='contained'?'احتواء':workspace.status==='escalated'?'تصعيد':'إغلاق'):'قيد التحقيق'}</span><span>{reviewed} مراجعة · {collected} جمع · {state.links.length} روابط</span></div><p className="ib-caption">هذه مساحة تحليل مرتبطة بالمحتوى الأصلي، ولا تمنح XP أو Skill XP إضافيًا.</p></header>
 {state.incident&&<section className="ib-section di-context"><div><strong>قضية محفوظة</strong><span>{state.incident.difficulty==='beginner'?'مبتدئ':state.incident.difficulty==='intermediate'?'متوسط':'متقدم'}</span></div><p>{state.incident.guidance}</p><details><summary>التسلسل الزمني للمصادر المحاكية</summary><ol>{state.incident.timeline.map((event,i)=><li key={i}><time dir="ltr">{event.time.replace('T',' ').replace('Z',' UTC')}</time> · {event.summary}</li>)}</ol></details><p>الأدلة المختارة والنسخة نفسها محفوظة بعد التحديث والعودة للحساب. إعادة التحقيق نفسه تحتفظ بملاحظاتك؛ نسخة جديدة تبدأ من صفحة الحوادث.</p><div className="di-actions"><a className="secondary-button" href="/incidents">إعادة نفس النسخة أو بدء نسخة جديدة</a></div></section>}
 <nav className="ib-steps" aria-label="مراحل التحقيق"><a href="#ib-locker">1 · افحص الأدلة</a>{collected>0&&<a href="#ib-board">2 · اربط الكيانات</a>}{(state.links.length>0||closed)&&<a href="#ib-decision">3 · سجّل القرار</a>}</nav>
 <section className="ib-section" id="ib-locker"><div className="ib-title"><FileSearch size={21}/><div><h2>Evidence Locker · خزانة الأدلة</h2><p>راجع الدليل الخام، واجمع ما يفيدك، ثم أضف تصنيفك وملاحظتك. لا يمكن تعديل المصدر.</p></div></div><div className="ib-evidence-list">{!board.evidence.length&&<p>ستظهر أدلة هذه القضية بعد فتح فصولها وإكمال أنشطتها الأصلية.</p>}{board.evidence.map(e=>{const saved=evidenceState(e.id);return <article className="ib-evidence" key={e.id}><div className="ib-evidence-heading"><div><small><bdi dir="ltr">{e.id}</bdi> · {typeLabels[e.type]}</small><h3>{e.title}</h3></div><span className={'ib-role '+e.role}>{roleLabels[e.role]}</span></div><p className="ib-meta">{e.source} · <time dir="ltr" dateTime={e.timestamp}>{e.timestamp.replace('T',' ').replace('Z',' UTC')}</time></p><div className="ib-entities">{e.entities.map(entityId=><span key={entityId}><bdi>{board.nodes.find(n=>n.id===entityId)?.label||entityId}</bdi></span>)}</div><details><summary>عرض الدليل الخام (قراءة فقط)</summary><pre dir="auto">{e.raw}</pre></details><div className="ib-actions"><button className="secondary-button" type="button" disabled={closed||busy||!!saved?.reviewedAt} onClick={()=>void act({action:'review',evidenceId:e.id})}>{saved?.reviewedAt?'تمت المراجعة':'تأكيد المراجعة'}</button><button className="secondary-button" type="button" disabled={closed||busy||!saved?.reviewedAt||!!saved.collectedAt} onClick={()=>void act({action:'collect',evidenceId:e.id})}>{saved?.collectedAt?'محفوظ في الخزانة':'اجمع الدليل'}</button></div>{saved?.reviewedAt&&<form className="ib-annotation" onSubmit={event=>{event.preventDefault();void act({action:'annotate',evidenceId:e.id,note:notes[e.id]||'',classification:classes[e.id]||'uncertain'})}}><label>تصنيفك<select value={classes[e.id]||'uncertain'} disabled={closed||busy} onChange={event=>setClasses(p=>({...p,[e.id]:event.target.value}))}><option value="relevant">مرتبط</option><option value="uncertain">غير محسوم</option><option value="irrelevant">غير مرتبط</option></select></label><label>ملاحظة المحلل<textarea value={notes[e.id]||''} maxLength={1200} disabled={closed||busy} onChange={event=>setNotes(p=>({...p,[e.id]:event.target.value}))} placeholder="لماذا يفيد هذا الدليل؟"/></label><button className="secondary-button" disabled={closed||busy} type="submit">حفظ الملاحظة</button></form>}</article>})}</div></section>
 {(collected>0||closed)?<section className="ib-section" id="ib-board"><div className="ib-title"><GitBranch size={21}/><div><h2>Investigation Board · لوحة العلاقات</h2><p>اختر طرفَي العلاقة ونوعها، ثم وضّح سبب الربط. عناوين IP الخارجية لا تعني ملكية أجهزة الشركة.</p></div></div><div className="ib-node-list">{board.nodes.map(n=><div key={n.id} className="ib-node"><small>{kindLabels[n.kind]}</small><strong dir={['ip','email','account','device','server','file','process'].includes(n.kind)?'ltr':undefined}>{n.label}</strong>{n.companyRef&&<a href={'/operations/nexacorp#'+n.companyRef.kind+'-'+encodeURIComponent(n.companyRef.id)}>NexaCorp ←</a>}</div>)}</div><form className="ib-link-form" onSubmit={event=>{event.preventDefault();void act({action:'link',fromId:from,toId:to,relation,reason})}}><h3>أضف علاقة موثقة</h3><div className="ib-form-grid"><label>من<select required value={from} disabled={closed||busy} onChange={event=>setFrom(event.target.value)}><option value="">اختر كيانًا</option>{board.nodes.map(n=><option key={n.id} value={n.id}>{nodeLabel(n)}</option>)}</select></label><label>العلاقة<select value={relation} disabled={closed||busy} onChange={event=>setRelation(event.target.value as RelationshipType)}>{relationshipTypes.map(type=><option key={type} value={type}>{relationshipLabels[type]} · {type}</option>)}</select></label><label>إلى<select required value={to} disabled={closed||busy} onChange={event=>setTo(event.target.value)}><option value="">اختر كيانًا</option>{board.nodes.map(n=><option key={n.id} value={n.id}>{nodeLabel(n)}</option>)}</select></label></div><label>سبب العلاقة<textarea required minLength={8} maxLength={400} value={reason} disabled={closed||busy} onChange={event=>setReason(event.target.value)} placeholder="مثلًا: ظهر الحساب والعنوان في سجل المصادقة نفسه."/></label><button className={state.links.length?'secondary-button':'primary-button'} type="submit" disabled={closed||busy||!from||!to||reason.trim().length<8}>حفظ العلاقة</button></form><div className="ib-linked"><h3>العلاقات المحفوظة</h3>{state.links.length?<ol>{state.links.map(l=><li key={l.fromId+l.relation+l.toId}><div><strong><bdi>{board.nodes.find(n=>n.id===l.fromId)?.label}</bdi> ← {relationshipLabels[l.relation]} ← <bdi>{board.nodes.find(n=>n.id===l.toId)?.label}</bdi></strong><p>{l.reason}</p></div><button type="button" disabled={closed||busy} onClick={()=>void act({action:'unlink',fromId:l.fromId,toId:l.toId,relation:l.relation})}>إزالة</button></li>)}</ol>:<p>لم تُربط كيانات بعد.</p>}</div></section>:<section className="ib-section ib-next" id="ib-board"><h2>2 · اربط الكيانات</h2><p>راجع دليلًا واجمع ما يفيد التحقيق أولًا. ستظهر لوحة العلاقات هنا.</p></section>}
 {(state.links.length>0||closed)?<section className="ib-section" id="ib-decision"><div className="ib-title"><CheckCircle2 size={21}/><div><h2>الاستنتاج والإجراء</h2><p>حدّد ما حدث، وما الحسابات أو الأصول المتأثرة، والأدلة التي تسند قرارك.</p></div></div><form className="ib-decision" onSubmit={event=>{event.preventDefault();void act({action:'decide',decision})}}><label>ماذا حدث؟<select required disabled={closed||busy} value={decision.hypothesis} onChange={event=>setDecision(p=>({...p,hypothesis:event.target.value}))}><option value="">اختر استنتاجًا</option>{board.hypotheses.map(h=><option key={h.id} value={h.id}>{h.label}</option>)}</select></label><fieldset disabled={closed||busy}><legend>الحسابات والأصول المتأثرة</legend><div className="ib-checks">{eligibleNodes.map(n=><label key={n.id}><input type="checkbox" checked={decision.affected.includes(n.id)} onChange={()=>toggle('affected',n.id)}/>{nodeLabel(n)}</label>)}</div></fieldset><fieldset disabled={closed||busy}><legend>الأدلة التي تدعم الاستنتاج</legend><div className="ib-checks">{board.evidence.filter(e=>!!evidenceState(e.id)?.collectedAt).map(e=><label key={e.id}><input type="checkbox" checked={decision.evidenceIds.includes(e.id)} onChange={()=>toggle('evidenceIds',e.id)}/>{e.title} · {roleLabels[e.role]}</label>)}</div></fieldset><label>الإجراء الموصى به<select required disabled={closed||busy} value={decision.action} onChange={event=>setDecision(p=>({...p,action:event.target.value}))}><option value="">اختر إجراءً</option>{board.actions.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><button className="primary-button" type="submit" disabled={closed||busy||!decision.hypothesis||!decision.action||!decision.affected.length||!decision.evidenceIds.length}>حفظ القرار</button>{workspace.decision&&<p className="ib-result">الاستنتاج المحفوظ: {board.hypotheses.find(h=>h.id===workspace.decision?.hypothesis)?.label} · {board.actions.find(a=>a.id===workspace.decision?.action)?.label}</p>}{closed&&<button type="button" className="secondary-button" disabled={busy} onClick={()=>void act({action:'reopen'})}>{state.incident?'إعادة التحقيق في النسخة نفسها دون مكافآت':'إعادة فتح اللوحة للمراجعة دون مكافآت'}</button>}</form></section>:<section className="ib-section ib-next" id="ib-decision"><h2>3 · الاستنتاج والإجراء</h2><p>اجمع دليلًا واربط الكيانات التي تفسر الحدث. عندها سيظهر نموذج القرار.</p></section>}
 {review&&<section className="ib-section di-review" aria-label="مراجعة القرار"><h2>مراجعة التحقيق بعد القرار</h2><p>{review.explanation}</p><div className="di-grid"><div><h3>الأدلة المهمة</h3><ul>{review.important.map(key=><li key={key}>{board.evidence.find(e=>e.id===key)?.title||key}{review.missedEvidence.includes(key)?' · لم تستخدمه في استنتاجك':''}</li>)}</ul></div><div><h3>أدلة مضللة</h3><ul>{review.distractors.map(key=><li key={key}>{board.evidence.find(e=>e.id===key)?.title||key} · {review?.evidence[key]}</li>)}</ul></div><div><h3>العلاقات التي تثبت الاستنتاج</h3><ul>{review.correctLinks.map(l=><li key={l.fromId+l.relation+l.toId}>{board.nodes.find(n=>n.id===l.fromId)?.label} · {relationshipLabels[l.relation]} · {board.nodes.find(n=>n.id===l.toId)?.label}{review?.missedLinks.some(m=>m.fromId===l.fromId&&m.toId===l.toId&&m.relation===l.relation)?' · فاتتك':''}</li>)}</ul></div></div><p>{closed?'القرار متوافق مع الأدلة والعلاقات.':'القرار يحتاج مراجعة؛ تحقق من الأدلة والعلاقات والأصل المتأثر ثم أرسل تصحيحًا.'}</p></section>}
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status" className="mission-message">{message}</p>}<div className="safe-banner"><ShieldCheck size={19}/><p>الأدلة والكيانات محاكاة تدريبية. هذه اللوحة تحفظ تحليلك فقط؛ لا تغيّر اكتمال التحقيق الأصلي أو تقدمه.</p></div></div>;
}
