'use client';
import {careerTitles,skillTitles} from '@/lib/progression';
import LoadingState from '@/components/loading-state';
import {useEffect,useState} from 'react';
import {ArrowLeft,Check,LockKeyhole,Route} from 'lucide-react';
import {useProgress} from '@/app/shell';
import {isCyberHref} from '@/lib/content-scope';
import type {evaluateCareer} from '@/lib/career';
import {RankSummary} from '@/app/rank/experience';
type CareerView=ReturnType<typeof evaluateCareer>&{promotions:{stageId:string;achievedAt:string;requirements:unknown}[];newlyUnlocked:string[]};
export function useCareer(){const {user,items,loading:progressLoading}=useProgress(),[data,setData]=useState<CareerView|null>(null),[loading,setLoading]=useState(!!user),[error,setError]=useState('');
 useEffect(()=>{if(!user||progressLoading)return;let live=true;fetch('/api/career',{cache:'no-store'}).then(async r=>{const body=await r.json() as CareerView&{error?:string};if(!r.ok)throw Error(body.error||'تعذر تحميل المراحل.');if(live){setData(body);setError('')}}).catch(e=>{if(live)setError(e instanceof Error?e.message:'تعذر تحميل المراحل.')}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[user,items,progressLoading]);return {data,loading,error,user};}
 export function CareerCard(){const {data,loading,error,user}=useCareer();if(!user)return null;const next=data?.next;return <section className="panel career-card" aria-label="المرحلة المهنية التدريبية"><div className="career-card-heading"><span className="eyebrow">خطوتك نحو المرحلة المهنية التالية</span><Route size={21}/></div>{loading?<p role="status">جارٍ حساب جاهزيتك المهنية…</p>:error?<p role="alert">{error}</p>:data&&<>{data.newlyUnlocked.length>0&&<p className="career-unlocked" role="status">فُتحت مرحلة تدريبية · وصلت إلى {careerTitles[data.current.id]||data.current.title} ضمن تدريب CyberLab.</p>}<div className="career-card-grid"><div><small>مرحلتك الحالية</small><h2>{careerTitles[data.current.id]||data.current.title}</h2><p>مرحلة تدريب داخل CyberLab، وليست شهادة أو مسمى وظيفيًا معتمدًا.</p></div><div><small>المرحلة التالية</small><strong>{(next?careerTitles[next.id]||next.title:null)||'اكتمل المسار التأسيسي'}</strong><div className="career-readiness"><b>{next?.readiness??100}%</b><span>الجاهزية للمرحلة التالية</span></div></div></div>{next&&<div className="career-card-footer"><p>{next.requirementsState.filter(r=>!r.done&&isCyberHref(r.href)).slice(0,2).map(r=>r.label).join(' · ')||(next.requirementsState.every(r=>r.done)?'استوفيت متطلبات المرحلة التالية.':'بعض المتطلبات تخص المراحل القديمة؛ يمكنك مراجعتها في سجل المسار.')}</p>{data.careerPractice&&isCyberHref(data.careerPractice.href)&&<a href={data.careerPractice.href}>{data.careerPractice.title} <ArrowLeft size={15}/></a>}</div>}<a className="career-more" href="/career">عرض المسار والمتطلبات <ArrowLeft size={16}/></a></>}</section>}
export default function CareerPath(){const {data,loading,error,user}=useCareer(),{items,loading:progressLoading,error:progressError}=useProgress(),[selected,setSelected]=useState<string|null>(null);if(!user)return <div className="reading-width career-page"><h1>المسار المهني</h1><p>سجّل الدخول لعرض تقدمك التدريبي المحفوظ.</p><a className="primary-button" target="_top" href="/signin-with-chatgpt?return_to=%2Fcareer">تسجيل الدخول</a></div>;if(loading)return <LoadingState>جارٍ تحميل رحلتك المهنية التدريبية…</LoadingState>;if(error||!data)return <div className="reading-width" role="alert">{error||'تعذر تحميل الرحلة.'} <button onClick={()=>location.reload()}>إعادة المحاولة</button></div>;
 const stage=data.stages.find(s=>s.id===selected)||data.next||data.current,index=data.stages.findIndex(s=>s.id===stage.id),reached=index<=data.currentIndex,latest=data.promotions.find(p=>p.stageId===stage.id),prerequisite=index>data.currentIndex+1?data.stages[index-1]:null;
 return <div className="career-page"><header className="career-page-header"><div><span className="eyebrow">الجاهزية المهنية التدريبية</span><h1>رحلتك المهنية داخل CyberLab</h1><p>جاهزيتك تعتمد على نتائج التدريب والإتقان والإنجازات. كل مرحلة تقدم تدريبي داخل المنصة وليست شهادة أو ضمانًا لوظيفة.</p></div><div className="career-current-stat"><small>وصلت إلى</small><strong>{careerTitles[data.current.id]||data.current.title}</strong><span>{data.next?`التالي: ${careerTitles[data.next.id]||data.next.title} · ${data.next.readiness}% جاهزية`:'أكملت المراحل التأسيسية'}</span></div></header>{!progressLoading&&!progressError&&<RankSummary xp={items.reduce((sum,item)=>sum+item.xp,0)} variant="career"/>}
 {data.newlyUnlocked.length>0&&<p className="career-unlocked" role="status">مرحلة تدريبية مستوفاة · تم تسجيل {data.newlyUnlocked.map(id=>careerTitles[id]||data.stages.find(s=>s.id===id)?.title).join('، ')} ضمن تقدمك التدريبي.</p>}
 <div className="career-layout"><nav className="career-timeline" aria-label="مراحل المسار المهني">{data.stages.map((s,i)=><button type="button" key={s.id} onClick={()=>setSelected(s.id)} aria-current={s.id===stage.id?'step':undefined} className={'career-stop '+(i<data.currentIndex?'reached':i===data.currentIndex?'current':i===data.currentIndex+1?'next':'locked')+(stage.id===s.id?' selected':'')}><span className="career-node">{i<data.currentIndex?<Check size={18}/>:i>data.currentIndex+1?<LockKeyhole size={16}/>:String(i).padStart(2,'0')}</span><span className="career-stop-text"><small>المرحلة {String(i).padStart(2,'0')} · {i<data.currentIndex?'مكتملة':i===data.currentIndex?'حاليًا':i===data.currentIndex+1?'المرحلة التالية':'مقفلة'}</small><strong>{careerTitles[s.id]||s.title}</strong><span>{s.readiness}% من متطلبات المرحلة{i>data.currentIndex+1?' · أكمل المراحل السابقة':''}</span></span></button>)}</nav>
 <section className="panel career-detail" aria-live="polite"><div className="between"><span className="eyebrow">المرحلة {String(index).padStart(2,'0')} / {reached?'مستوفاة':'الجاهزية'}</span><span className="career-percent">{stage.readiness}%</span></div><h2>{careerTitles[stage.id]||stage.title}</h2><p>{stage.description}</p>{prerequisite&&<p className="career-prerequisite">هذه المرحلة مقفلة حتى تفتح {careerTitles[prerequisite.id]||prerequisite.title} أولًا، حتى لو اكتملت متطلبات هذه المرحلة منفردة.</p>}<div className="career-bar" role="progressbar" aria-label={'الجاهزية لمرحلة '+stage.title} aria-valuenow={stage.readiness} aria-valuemin={0} aria-valuemax={100}><span style={{width:stage.readiness+'%'}}/></div>{latest&&<p className="career-date">سُجل فتح هذه المرحلة في {new Date(latest.achievedAt).toLocaleDateString('ar-SA')}.</p>}
 <h3>المتطلبات {stage.requirementsState.length?`· ${stage.requirementsState.filter(r=>r.done).length} من ${stage.requirementsState.length}`:''}</h3>{stage.requirementsState.length?<ul className="career-requirements">{stage.requirementsState.map(r=><li key={r.kind+':'+r.id}><span className={r.done?'career-check done':'career-check'} aria-hidden="true">{r.done?<Check size={16}/>:''}</span><div><strong>{r.kind==='mastery'?`إتقان ${skillTitles[r.id]||r.id} ${r.minimum}%`:r.label}</strong>{r.current!==null&&<small>تقدمك الحالي: {r.current}{r.kind==='mastery'||r.kind==='subskill'?'%':''}</small>}</div>{!r.done&&<a href={r.href} aria-label={'ابدأ: '+r.label}>ابدأ <ArrowLeft size={14}/></a>}</li>)}</ul>:<p>تبدأ هذه المرحلة مع إنشاء حسابك، ولا تحتاج إلى متطلبات مسبقة.</p>}
 {stage.careerPractice&&<a className="career-practice" href={stage.careerPractice.href}><span><small>تدريب يخدم متطلبات المرحلة</small><strong>{stage.careerPractice.title}</strong><em>{stage.careerPractice.reason}</em></span><ArrowLeft size={19}/></a>}
 </section></div><section className="career-history"><h2>سجل التقدم التدريبي</h2><p>الترقيات المحفوظة مرتبطة بحسابك. تُسجل الإنجازات السابقة عند أول قراءة لهذه الصفحة دون مكافآت إضافية.</p><div>{data.promotions.map(p=><span key={p.stageId}>{careerTitles[p.stageId]||data.stages.find(s=>s.id===p.stageId)?.title} · {new Date(p.achievedAt).toLocaleDateString('ar-SA')}</span>)}</div></section></div>}
