'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowLeft,Check,X} from 'lucide-react';
import {rankTitles,points} from '@/lib/progression';
import {rankEvent,rankForXp,tiers,type RankEvent,type Tier} from '@/lib/ranks';

export function RankEmblem({tier,size='medium'}:{tier:Tier;size?:'small'|'medium'|'large'}){const {emblem}=tier;return <span className={'rank-emblem '+size} style={{'--rank-color':tier.color} as CSSProperties} role="img" aria-label={'شارة '+rankTitles[tier.id]}><svg viewBox="0 0 100 100" aria-hidden="true" focusable="false"><circle className="rank-halo" cx="50" cy="50" r="46"/><path className="rank-outline" d={emblem.outline}/><path className="rank-inset" d={emblem.outline} transform="translate(50 50) scale(.83) translate(-50 -50)"/><path className="rank-accent" d={emblem.accent}/><path className="rank-mark" d={emblem.mark}/>{Array.from({length:emblem.halo},(_,i)=><circle className="rank-node" key={i} cx={50+34*Math.cos(i*2*Math.PI/emblem.halo-Math.PI/2)} cy={50+34*Math.sin(i*2*Math.PI/emblem.halo-Math.PI/2)} r="1.6"/>)}</svg></span>}

export function RankSummary({xp,variant='dashboard'}:{xp:number;variant?:'dashboard'|'career'}){const r=rankForXp(xp);return <section className={'panel rank-summary '+variant} aria-label="الرتبة البصرية الحالية"><div className="rank-summary-main"><RankEmblem tier={r.tier} size="medium"/><div><span className="eyebrow">رتبتك</span><h2>{rankTitles[r.tier.id]}</h2><p>المستوى {r.level} · {r.xp} نقطة خبرة</p></div></div><div className="rank-summary-progress"><div className="between"><span>{r.next?'التالي · '+rankTitles[r.next.id]:'أعلى رتبة حالية'}</span><b>{r.next?points(r.remaining)+' متبقية':'مكتمل'}</b></div><div className="rank-meter" role="progressbar" aria-label={'التقدم إلى الرتبة التالية'} aria-valuenow={r.progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:r.progress+'%'}}/></div></div>{variant==='dashboard'&&<a href="/progress" className="rank-summary-link">المستوى والإنجازات والهدف التالي <ArrowLeft size={16}/></a>}</section>}

export function RankShowcase({xp,careerStage}:{xp:number;careerStage:string|null}){const r=rankForXp(xp);return <section id="ranks" className="rank-showcase" aria-label="عرض الرتب البصرية"><div className="rank-showcase-hero"><RankEmblem tier={r.tier} size="large"/><div><span className="eyebrow">رتبتك الحالية</span><h2>{rankTitles[r.tier.id]}</h2><p>الرتبة تعكس المستوى، وليست تأهيلًا مهنيًا.</p><strong>المستوى {r.level} · {r.xp} نقطة خبرة</strong><div className="rank-meter" role="progressbar" aria-label="التقدم للرتبة التالية" aria-valuenow={r.progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:r.progress+'%'}}/></div><small>{r.next?`${points(r.remaining)} حتى ${rankTitles[r.next.id]}`:'أعلى رتبة بصرية حاليًا'}</small><div className="rank-level-track"><span>تقدم المستوى {r.level}</span><strong>{points(200-r.xp%200)} خبرة إلى المستوى {r.level+1}</strong><div className="rank-meter" role="progressbar" aria-label="التقدم للمستوى الرقمي التالي" aria-valuenow={r.xp%200} aria-valuemin={0} aria-valuemax={200}><span style={{width:(r.xp%200)/2+'%'}}/></div></div></div></div><details className="progression-details"><summary>الرتب القادمة ومتطلباتها</summary><div className="rank-tier-grid">{tiers.map(t=><div className={'rank-tier-item '+(t.id===r.tier.id?'current':t.minLevel<r.tier.minLevel?'unlocked':'locked')} key={t.id}><RankEmblem tier={t} size="small"/><div><strong>{rankTitles[t.id]}</strong><small>المستويات {t.minLevel}{t.maxLevel?'–'+t.maxLevel:'+'} · {t.id===r.tier.id?'الحالية':t.minLevel<r.tier.minLevel?'فُتحت':'مقفلة'}</small></div>{t.minLevel<=r.level?<Check size={15} aria-hidden="true"/>:null}</div>)}</div></details><p className="rank-career-separation">المرحلة المهنية الحالية: <strong>{careerStage||'جارٍ حساب الجاهزية…'}</strong>. <a href="/career">عرض المتطلبات <ArrowLeft size={14}/></a></p></section>}

export function RankExperience({xp,ready,accountKey='default'}:{xp:number;ready:boolean;accountKey?:string}){const prior=useRef<number|null>(null),owner=useRef(accountKey),[event,setEvent]=useState<RankEvent|null>(null);
 useEffect(()=>{if(owner.current!==accountKey){owner.current=accountKey;prior.current=null;setEvent(null)}if(!ready)return;const next=rankEvent(prior.current,xp);prior.current=xp;if(next)setEvent(next)},[xp,ready,accountKey]);
 useEffect(()=>{if(!event)return;const timer=window.setTimeout(()=>setEvent(null),6500);return()=>window.clearTimeout(timer)},[event]);
 if(!event)return null;const current=rankForXp(event.xp);
 return <div className="rank-level-up" role="status"><span>تمت الترقية</span><strong>المستوى <b>{event.toLevel}</b></strong><small>{event.kind==='tier'?'محطة جديدة · '+rankTitles[current.tier.id]:`${current.xp} نقطة خبرة محفوظة`}</small><a href="/progress">هدفك التالي ←</a><button type="button" aria-label="إغلاق إشعار التقدم" onClick={()=>setEvent(null)}><X size={16}/></button></div>}
