'use client';
import {useEffect,useRef} from 'react';
import {completedLessonText} from '@/lib/progression';
import LoadingState from '@/components/loading-state';
import Link from '@/components/native-link';
import {UserRound} from 'lucide-react';
import {useProgress} from '../shell';
import {learningMetrics} from '@/lib/metrics';
import {lessons} from '@/lib/curriculum';
import {RankShowcase} from '@/app/rank/experience';
import {useProgression,ProgressionState,LevelProgressPath,AchievementPreview} from '@/app/progression/view';
export default function Profile(){const {user,items,learning,loading,error}=useProgress(),progression=useProgression(),ranksRef=useRef<HTMLDetailsElement>(null);useEffect(()=>{const reveal=()=>{if(window.location.hash==='#ranks'&&ranksRef.current){ranksRef.current.open=true;ranksRef.current.querySelector('#ranks')?.scrollIntoView({block:'start'})}};reveal();window.addEventListener('hashchange',reveal);return()=>window.removeEventListener('hashchange',reveal)},[loading,user,progression.data]);const m=learningMetrics(items,learning);return <div className="reading-width"><div className="page-heading"><div><h1>الملف الشخصي</h1></div><UserRound size={36}/></div>{!user?<div className="empty-state"><p>سجّل الدخول لعرض ملفك وتقدمك.</p><a className="primary-button" href="/signin-with-chatgpt?return_to=%2Fprofile" target="_top">تسجيل الدخول</a></div>:loading?<LoadingState>جارٍ تحميل ملفك المحفوظ…</LoadingState>:error?<p role="alert">تعذر تحميل الملف. أعد المحاولة من أعلى الصفحة.</p>:<><section className="panel"><h2>{user.name||'المتعلم'}</h2><p dir="ltr">{user.email}</p><div className="profile-stats"><span>{m.xp} نقطة خبرة</span><span>{completedLessonText(m.done.size)}</span><span>{Math.floor(m.totalSeconds/60)} دقيقة قراءة</span></div></section><LevelProgressPath xp={m.xp}/>{progression.error&&<ProgressionState api={progression}/>}{progression.data&&<AchievementPreview data={progression.data}/>}<details ref={ranksRef} className="progression-details"><summary>تفاصيل الرتبة والجاهزية المهنية</summary><RankShowcase xp={m.xp} careerStage={progression.data?.career.title||null}/></details><div className="button-row"><Link className="secondary-button" href="/achievements">مركز الإنجازات</Link><Link className="secondary-button" href="/history">سجل التعلم</Link><Link className="secondary-button" href="/settings">الإعدادات</Link></div><h2>دروس حفظتها</h2>{learning.bookmarks.length?<div className="lesson-list">{learning.bookmarks.map(b=><Link href={'/learn/'+b.id} className="lesson-row" key={b.id}>{lessons.find(l=>l.id===b.id)?.title||b.id} ←</Link>)}</div>:<div className="empty-state">لم تحفظ درسًا بعد. افتح درسًا واضغط حفظ في الإشارات.</div>}</>}</div>}
