'use client';
import {ChevronDown,Search} from 'lucide-react';
type Props={search:string;severity:string;status:string;type:string;types:string[];severityLabels:Record<string,string>;statusLabels:Record<string,string>;onSearch:(value:string)=>void;onSeverity:(value:string)=>void;onStatus:(value:string)=>void;onType:(value:string)=>void};
export default function SocFilters(p:Props){return <div className="soc-filters" role="search" aria-label="تصفية التنبيهات">
 <label className="soc-search" htmlFor="soc-search"><span className="soc-filter-label">البحث في التنبيهات</span><span className="soc-filter-control"><Search size={20} aria-hidden="true"/><input id="soc-search" type="search" value={p.search} onChange={e=>p.onSearch(e.target.value)} placeholder="عنوان التنبيه، المستخدم، IP أو الجهاز"/></span></label>
 <label htmlFor="soc-severity"><span className="soc-filter-label">مستوى الخطورة</span><span className="soc-filter-control soc-filter-select"><select id="soc-severity" value={p.severity} onChange={e=>p.onSeverity(e.target.value)}><option value="all">كل المستويات</option>{['Critical','High','Medium','Low'].map(s=><option key={s} value={s}>{p.severityLabels[s]}</option>)}</select><ChevronDown size={18} aria-hidden="true"/></span></label>
 <label htmlFor="soc-status"><span className="soc-filter-label">الحالة</span><span className="soc-filter-control soc-filter-select"><select id="soc-status" value={p.status} onChange={e=>p.onStatus(e.target.value)}><option value="all">كل الحالات</option>{Object.entries(p.statusLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><ChevronDown size={18} aria-hidden="true"/></span></label>
 <label htmlFor="soc-type"><span className="soc-filter-label">نوع التنبيه</span><span className="soc-filter-control soc-filter-select"><select id="soc-type" value={p.type} onChange={e=>p.onType(e.target.value)}><option value="all">كل الأنواع</option>{p.types.map(t=><option value={t} key={t}>{t}</option>)}</select><ChevronDown size={18} aria-hidden="true"/></span></label>
 </div>}
