'use client';
import {useEffect,useState} from 'react';
import {useProgress} from '@/app/shell';
import LoadingState from '@/components/loading-state';
import {CompletionProgressSummary} from '@/app/progression/view';
import {nexaCorp,companyEntityAnchor} from '@/lib/nexacorp';
import {offensiveCases,scopeCandidates,surfaceHypotheses,retestChoices,handoffChoices,type OffensiveCaseId} from '@/lib/offensive-expansion';
import {assessmentPages,assessmentTests,assessmentHypotheses,assessmentFindings,assessmentImpacts,assessmentFixes,assessmentKnowledge} from '@/lib/offensive-pilot';
import {surfaceServices,surfaceClasses,surfaceValidation,surfaceRetests,sessionTests,sessionHypotheses,minimumOptions,minimumKnowledge,offensiveTrackHref} from '@/lib/offensive-minimum';
import type {LabSession} from '@/lib/interactive-lab-engine';
import MinimumWorkspace from './minimum';
import OffensiveWorkspace from './offensive';
type State={completedAt:string|null;bestScore:number;session:LabSession};
type Detail={state:State|null;access:{locked:boolean;met:number;total:number;requirements:{label:string;href:string;done:boolean}[]}|null;error?:string};
type Trace={id:string;request:string;status:number;body:string;label?:string;policy?:string};
type Option={id:string;label:string};
const stageNames:Record<string,string>={scope:'نطاق الاختبار',authorize:'نطاق الاختبار',recon:'اكتشف السطح',login:'الدخول المحاكى',observe:'لاحظ السلوك',classify:'صنّف ما لاحظته',prioritize:'حدد أولوية التحقق',hypothesis:'ابنِ فرضية',test:'اختبر واجمع الأدلة',validate:'تحقق بالأدلة',impact:'حدد النتيجة والأثر',remediation:'المعالجة وإعادة الاختبار',result:'نتيجة التقييم'};
export default function ExpandedAssessment({id,track=false}:{id:OffensiveCaseId;track?:boolean}){
 const {user,error:progressError,refresh}=useProgress(),c=offensiveCases[id],access=id==='v2-access-control',surface=id==='v2-attack-surface',href='/labs/v2/'+id+(access&&track?'?track=offensive':''),api='/api/interactive-labs/'+id;
 const [detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selectedScope,setScope]=useState<string[]>([]),[accepted,setAccepted]=useState(false),[key,setKey]=useState(''),[value,setValue]=useState(''),[finding,setFinding]=useState(''),[impact,setImpact]=useState(''),[asset,setAsset]=useState(''),[proof,setProof]=useState<string[]>([]),[fix,setFix]=useState(''),[verdict,setVerdict]=useState(''),[handoff,setHandoff]=useState('');
 useEffect(()=>{let live=true;if(!user){setLoading(false);return}setLoading(true);fetch(api,{cache:'no-store'}).then(async r=>{const d=await r.json() as Detail;if(!r.ok)throw Error(d.error||'تعذر استعادة التقييم.');if(live){setDetail(d);const p=access?d.state?.session.assessment:d.state?.session.minimum;setScope(d.state?.session.offensive?.scope||[]);setFinding(p?.report.finding||'');setImpact(p?.report.impact||'');setProof(p?.report.evidence||[]);setAsset(d.state?.session.offensive?.affectedAsset||'');setFix(p?.patch||'')}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[api,user,access]);
 async function act(action:string,extra:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');try{
  const post=async(body:Record<string,unknown>)=>{const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as {state:State;error?:string};if(!r.ok)throw Error(d.error||'تعذر حفظ الخطوة.');return d.state as State};
  if(!detail?.state)await post({action:'start'});const state=await post({action,...extra});setDetail(d=>({...d!,state}));setKey('');setValue('');
  if(action==='assessment-upgrade'||action==='replay'){setScope([]);setAccepted(false);setFinding('');setImpact('');setProof([]);setAsset('');setFix('');setVerdict('');setHandoff('')}
  if(action==='submit'&&state.session.lastResult?.passed)await refresh();
 }catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ؛ يمكنك إعادة المحاولة.')}finally{setBusy(false)}}
 const s=detail?.state?.session,p=access?s?.assessment:s?.minimum,e=s?.offensive,step=p?.step||(access?'authorize':'scope'),disabled=busy||!!progressError;
 const button=(label:string,action:string,data:Record<string,unknown>={},off=false,primary=true)=><button className={primary?'primary-button':'assessment-secondary'} disabled={disabled||off} onClick={()=>void act(action,data)}>{label}</button>;
 const select=(label:string,v:string,set:(v:string)=>void,options:readonly Option[],technical=false)=><label className="core-field">{label}<select dir={technical?'ltr':undefined} value={v} disabled={disabled} onChange={ev=>set(ev.target.value)}><option value="">اختر…</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select>{options.find(o=>o.id===v)&&options.find(o=>o.id===v)!.label.length>32&&<small className="offensive-selected-choice" aria-hidden="true">الاختيار: {options.find(o=>o.id===v)!.label}</small>}</label>;
 const testOptions=access?assessmentTests:surface?surfaceValidation:sessionTests,retestOptions=surface?surfaceRetests:testOptions,observations=p?.observations||[],retests=p?.retests||[],tested=testOptions.every(t=>observations.some(o=>o.id===t.id)),collected=testOptions.every(t=>e?.collected.includes(t.id)),retested=retestOptions.every(t=>retests.some(o=>o.id===t.id));
 const options=access?{findings:assessmentFindings,impacts:assessmentImpacts,fixes:assessmentFixes}:surface?minimumOptions.surface:minimumOptions.session;
 const cards:Record<string,{title:string;text:string;lessonId:string}>=access?assessmentKnowledge:surface?minimumKnowledge.surface:minimumKnowledge.session,knowledge=cards[step];
 const traceList=(items:Trace[],collect=false)=><div className="offensive-evidence-list">{items.map(t=><details className="guided-disclosure assessment-trace" key={t.id}><summary>{t.label||assessmentTests.find(x=>x.id===t.id)?.label||t.id}{collect?(e?.collected.includes(t.id)?' · جُمع':' · لم يُجمع بعد'):''}</summary><pre dir="ltr">{t.request}</pre><p>الرد المحاكى: <bdi dir="ltr">{t.status}</bdi></p><pre dir="ltr">{t.body}</pre>{t.policy&&<p>{t.policy}</p>}{collect&&e&&!e.collected.includes(t.id)&&button('اجمع هذا الدليل','mark',{key:t.id},false,false)}</details>)}</div>;
 if(!user)return <div className="pilot-experience assessment" dir="rtl"><h1>{c.title}</h1><p>تقييم مصرح به داخل بيئة NexaCorp التدريبية فقط.</p><a className="primary-button" target="_top" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(href)}>سجّل الدخول لعرض متطلباتك</a></div>;
 if(loading)return <div className="pilot-experience"><LoadingState>جارٍ استعادة التقييم…</LoadingState></div>;
 if(!detail)return <div className="pilot-experience" role="alert"><p>{error||'تعذر استعادة التقييم.'}</p><button className="primary-button" onClick={()=>location.reload()}>إعادة المحاولة</button></div>;
 if(detail.access?.locked)return <div className="pilot-experience assessment" dir="rtl"><a className="back-link" href={offensiveTrackHref}>أساسيات التقييم الهجومي</a><section className="panel"><h1>{c.title}</h1><p>مقفل · {detail.access.met} من {detail.access.total} متطلبات مكتملة</p><ul>{detail.access.requirements.map(r=><li key={r.href}>{r.done?'مكتمل':'المتبقي'}: {r.label}</li>)}</ul>{detail.access.requirements.find(r=>!r.done)&&<a className="primary-button" href={detail.access.requirements.find(r=>!r.done)!.href}>أكمل المتطلب التالي</a>}</section></div>;
 // No silent transformation of saved attempts: old views continue to interpret old state.
 if(p&&!e)return <>{access?<OffensiveWorkspace track={track}/>:<MinimumWorkspace id={id}/>}<div className="pilot-experience assessment">{detail.state?.completedAt&&button('ابدأ التقييم الموسّع دون مكافأة جديدة','assessment-upgrade',{accepted:true},false,false)}{error&&<p role="alert">{error}</p>}</div></>;
 const scope=scopeCandidates(id),feedback=p?.feedback;
 return <div className="pilot-experience assessment minimum-assessment offensive-expanded" dir="rtl"><header className="assessment-header"><a className="back-link" href={offensiveTrackHref}>أساسيات التقييم الهجومي</a><span className="eyebrow">NexaCorp · تقييم مصرح به</span><h1>{c.title}</h1><p>بيئة تدريبية معزولة · طلبات وبيانات محاكاة فقط</p></header>
 <p className="offensive-stage" role="status">{e?.reportReady&&step==='remediation'?'تقرير النتيجة':stageNames[step]}</p>
 <section className="panel assessment-workspace">
 {!e?<><h2>تكليف التقييم</h2><p>{surface?'حدد الخدمات المتاحة، ثم تحقق هل يتوافق الوصول إليها مع سياسة الشركة.':access?'راجع حدود قراءة التقارير في التطبيق التدريبي.':'راجع دورة الدخول والخروج وثقة الخادم في جلسة التطبيق التدريبي.'}</p>{detail.state?.completedAt&&<p>إنجازك السابق محفوظ؛ هذه إعادة تقييم دون مكافأة إضافية.</p>}{button('راجع نطاق التكليف','assessment-upgrade',{accepted:true})}</>:<>
 {['scope','authorize'].includes(step)&&<><h2>حدد ما يسمح لك التكليف باختباره</h2><p>{surface?'سجل التفويض: TRAIN-PORTAL وTRAIN-METRICS وTRAIN-ADMIN. قراءة الردود والإعداد، ثم معالجة محاكاة.':access?'سجل التفويض: TRAIN-REPORTS؛ صفحتان وثلاثة طلبات قراءة للتقريرين R-104 وR-205 بهويات تدريبية.':'سجل التفويض: TRAIN-PROFILE؛ حالات الدخول والخروج والجلسة السابقة والحالية لملف سارة التدريبي.'}</p><p>لا تعديل أو حذف للبيانات، ولا اختبار بوابة الشركة أو أي هدف خارجي.</p>{!e.scopeApproved?<><fieldset className="assessment-evidence"><legend>الأصول داخل النطاق</legend>{scope.map(o=><label className="assessment-check" key={o.id}><input type="checkbox" checked={selectedScope.includes(o.id)} disabled={disabled} onChange={ev=>setScope(ev.target.checked?[...selectedScope,o.id]:selectedScope.filter(k=>k!==o.id))}/><span><bdi dir="ltr">{o.label}</bdi><small>{o.description}</small></span></label>)}</fieldset>{button('تحقق من نطاقي','scope-check',{scope:selectedScope},!selectedScope.length)}</>:<><p>النطاق المعتمد: <bdi dir="ltr">{e.scope.join(' · ')}</bdi></p><label className="assessment-check"><input type="checkbox" checked={accepted} disabled={disabled} onChange={ev=>setAccepted(ev.target.checked)}/>سأختبر هذه المحاكاة فقط ضمن التكليف.</label>{button('ابدأ التقييم المصرح به','authorize',{accepted:true},!accepted)}</>}</>}
 {step==='recon'&&surface&&<><h2>اكتشف أصلًا واحدًا</h2>{select('الأصل الذي تريد فحصه',key,setKey,surfaceServices.map(x=>({id:x.id,label:x.host})),true)}{p&&'inspected' in p&&p.inspected.map(k=>{const o=surfaceServices.find(x=>x.id===k)!;return <details className="guided-disclosure" key={k}><summary><bdi dir="ltr">{o.host}</bdi> · فُحص</summary><dl className="assessment-brief"><div><dt>الخدمة</dt><dd><bdi dir="ltr">{o.port} · {o.service}</bdi></dd></div><div><dt>الطلب والرد</dt><dd><bdi dir="ltr">{o.endpoint} · {o.response}</bdi></dd></div><div><dt>Banner محدود</dt><dd><bdi dir="ltr">{o.banner}</bdi></dd></div><div><dt>مكان الوصول</dt><dd>{o.exposure}</dd></div></dl></details>})}{p&&'inspected' in p&&p.inspected.length===3?button('ابنِ خريطة سطح الهجوم','classify-start'):button('افحص الأصل المحدد','inspect',{key},!key)}</>}
 {step==='recon'&&access&&<><h2>افحص الحساب والوظائف المتاحة</h2>{select('الصفحة التي تريد فحصها',key,setKey,assessmentPages)}{s?.assessment?.pages.includes('account')&&<details className="guided-disclosure"><summary>سارة · حساب الموظفة</summary><p><bdi dir="ltr">sara</bdi> · الموارد البشرية · قراءة تقارير الحساب نفسه فقط، بلا دور مراجع.</p><a className="assessment-secondary" href={companyEntityAnchor({kind:'employee',id:'sara'})}>هوية سارة في NexaCorp</a></details>}{s?.assessment?.pages.includes('reports')&&<details className="guided-disclosure"><summary>قائمة التقارير</summary><p><bdi dir="ltr">R-104</bdi> مملوك لسارة، ووظيفته القراءة. <bdi dir="ltr">R-205</bdi> مملوك لليلى، ولا يظهر في قائمة سارة؛ كلاهما في سجل التفويض.</p></details>}{s?.assessment?.pages.length===2?button('افحص الطلب الأول','observe'):button('افتح الصفحة المحددة','page',{key},!key)}</>}
 {step==='classify'&&s?.minimum&&<><h2>ما الذي تثبته الملاحظة الآن؟</h2><div className="surface-map">{surfaceServices.map(o=><article className="assessment-observation" key={o.id}><h3><bdi dir="ltr">{o.host}</bdi></h3><p><bdi dir="ltr">{o.response}</bdi></p><p>{surfaceClasses.find(x=>x.id===s.minimum?.classifications[o.id])?.label||'لم تصنّفه بعد'}</p></article>)}</div>{select('الأصل المراد تصنيفه',key,setKey,surfaceServices.map(x=>({id:x.id,label:x.host})),true)}{select('حدود ما ثبت',value,setValue,surfaceClasses)}{button('احفظ التصنيف','classify',{key,value},!key||!value,false)}{button('راجع الخريطة وحدد الأولوية','prioritize',{},!surfaceServices.every(x=>s.minimum?.classifications[x.id]))}</>}
 {step==='prioritize'&&<><h2>حدد ما يستحق التحقق أولًا</h2>{select('أولوية التحقق',key,setKey,surfaceServices.map(x=>({id:x.id,label:x.host})),true)}{button('تحقق من الأصل ذي الأولوية','priority',{key},!key)}</>}
 {step==='login'&&<><h2>ابدأ بهوية سارة التدريبية</h2><p>لا كلمات مرور حقيقية؛ لا يغيّر هذا تسجيل الدخول إلى CyberLab.</p>{button('سجّل الدخول إلى التطبيق المحاكى','login')}</>}
 {step==='observe'&&<><h2>لاحظ ما تغير</h2>{traceList(observations,access)}{access?button('كوّن فرضية قابلة للاختبار','hypothesis'):s?.minimum?.phase==='a'?button('سجّل الخروج من التطبيق المحاكى','logout'):s?.minimum?.phase==='out'?button('سجّل الدخول من جديد في المحاكاة','login-again'):button('كوّن فرضية قابلة للاختبار','hypothesis')}</>}
 {step==='hypothesis'&&<><h2>اختر تفسيرًا لتختبره</h2><details className="guided-disclosure"><summary>راجع الملاحظات السابقة</summary>{traceList(observations)}</details>{select('فرضيتك الحالية',key,setKey,access?assessmentHypotheses:sessionHypotheses)}{button('اختبر هذه الفرضية','choose',{key},!key)}</>}
 {['test','validate'].includes(step)&&<><h2>قارن مصادر مستقلة</h2><p>افتح كل رد يحتاجه استنتاجك، ثم اجمعه. مشاهدة الطلب وحدها لا تحفظه كدليل.</p>{select('الفحص المحاكى',key,setKey,testOptions)}{button('نفّذ الفحص المحدد','probe',{key},!key, !tested)}{traceList(observations.filter(o=>testOptions.some(t=>t.id===o.id)),true)}{surface&&tested&&<>{select('فرضية قابلة للاختبار',value,setValue,surfaceHypotheses)}{button('اعتمد فرضيتي للفحص','choose',{key:value},!value, !p?.hypothesis)}</>}{feedback?button('عد للملاحظات وأعد الفحص','recheck'):tested&&(!surface||p?.hypothesis)&&button('قارن الأدلة بفرضيتك','evaluate',{},!collected)}</>}
 {step==='impact'&&<><h2>ما الذي ثبت وما أثره؟</h2><details className="guided-disclosure"><summary>الأدلة التي جمعتها</summary>{traceList(observations.filter(o=>e.collected.includes(o.id)))}</details>{select('النتيجة المثبتة',finding,setFinding,options.findings)}{select('الأصل المتأثر',asset,setAsset,scope.map(o=>({id:o.id,label:o.label})),true)}{select('الأثر المدعوم بالأدلة',impact,setImpact,options.impacts)}<fieldset className="assessment-evidence"><legend>الأدلة التي تربط الملاحظات باستنتاجك</legend>{observations.filter(o=>e.collected.includes(o.id)).map(o=><label className="assessment-check" key={o.id}><input type="checkbox" disabled={disabled} checked={proof.includes(o.id)} onChange={ev=>setProof(ev.target.checked?[...proof,o.id]:proof.filter(k=>k!==o.id))}/>{('label' in o?o.label:'')||assessmentTests.find(t=>t.id===o.id)?.label||o.id}</label>)}</fieldset>{button('اعتمد النتيجة والأثر','report',{report:{finding,impact,evidence:proof,asset}},!finding||!impact||!asset||!proof.length)}{button('أعد الفحص','recheck',{},false,false)}</>}
 {step==='remediation'&&!e.reportReady&&<><h2>عالج ثم تحقق من السلوك</h2>{select('الإجراء التصحيحي',fix,setFix,options.fixes)}{button(p?.patch?'غيّر المعالجة وأعد الاختبار':'طبّق المعالجة في المحاكاة','patch',{key:fix},!fix,!p?.patch)}{p?.patch&&<>{select('طلب إعادة الاختبار',key,setKey,retestOptions)}{button('أعد اختبار الحالة المحددة','retest',{key},!key,!retested)}{traceList(retests)}{retested&&<>{select('حكمك على إعادة الاختبار',verdict,setVerdict,retestChoices)}{select('ما الذي تتابعه العمليات الأمنية بعد الإصلاح؟',handoff,setHandoff,handoffChoices)}{button('وثّق نتيجة إعادة الاختبار','finding-report',{key:verdict,value:handoff},!verdict||!handoff)}</>}</>}</>}
 {((step==='remediation'&&e.reportReady)||step==='result')&&<><h2>{step==='result'?'تقييم مكتمل':'راجع تقرير النتيجة'}</h2><dl className="offensive-finding-report"><div><dt>النتيجة المثبتة</dt><dd>{c.summary}</dd></div><div><dt>الأصل المتأثر</dt><dd><bdi dir="ltr">{e.affectedAsset}</bdi> · <a href={companyEntityAnchor({kind:'asset',id:c.assetId})}>{nexaCorp.importantAssets.find(a=>a.id===c.assetId)?.name}</a></dd></div><div><dt>الأثر</dt><dd>{options.impacts.find(o=>o.id===p?.report.impact)?.label}</dd></div><div><dt>المعالجة</dt><dd>{options.fixes.find(o=>o.id===p?.patch)?.label}</dd></div><div><dt>نتيجة إعادة الاختبار</dt><dd>منع السلوك غير المسموح مع استمرار الاستخدام المعتمد.</dd></div><div><dt>متابعة دفاعية</dt><dd>{c.defense}</dd></div></dl><details className="guided-disclosure"><summary>دليل التقرير: قبل المعالجة وبعدها</summary>{traceList(observations.filter(o=>p?.report.evidence.includes(o.id)))}<h3>بعد المعالجة</h3>{traceList(retests)}</details>{step==='result'?<><CompletionProgressSummary achievementId="offensive-foundations"/><p>أفضل نتيجة: {detail.state?.bestScore} من 100. {s?.lastResult?.xpGranted?'سُجلت المكافآت وفق قواعد الإنجاز الحالية.':'إنجازك محفوظ؛ لا مكافأة إضافية لإعادة التقييم.'}</p><a className="primary-button" href={c.next}>{c.nextLabel}</a>{button('أعد التقييم دون مكافأة جديدة','replay',{},false,false)}</>:button('احفظ التقرير وأنهِ التقييم','submit')}</>}
 </>}
 {feedback&&<p className="pilot-feedback" role="status">{feedback}</p>}
 </section>{knowledge&&e&&step!=='result'&&<details className="assessment-knowledge"><summary>معرفة عند الحاجة: {knowledge.title}</summary><p>{knowledge.text}</p><a href={'/learn/'+knowledge.lessonId+'?return_to='+encodeURIComponent(href)}>اقرأ الشرح الكامل ثم عد إلى هذا الموضع</a></details>}{error&&<p className="error" role="alert">{error}</p>}{progressError&&<p className="error" role="alert">{progressError}</p>}</div>;
}
