'use client';
import {CompletionProgressSummary} from '@/app/progression/view';
import LoadingState from '@/components/loading-state';
import {useEffect,useState} from 'react';
import {useProgress} from '@/app/shell';
import {nexaCorp} from '@/lib/nexacorp';
import {surfaceId,minimumHref,offensiveTrackHref,freshMinimum,surfaceSteps,sessionSteps,surfaceServices,surfaceClasses,surfaceValidation,surfaceRetests,sessionTests,sessionHypotheses,minimumOptions,minimumKnowledge,type MinimumState,type MinimumTrace} from '@/lib/offensive-minimum';
import type {LabSession} from '@/lib/interactive-lab-engine';
type Access={locked:boolean;met:number;total:number;requirements:{label:string;href:string;done:boolean}[]};
type State={completedAt:string|null;bestScore:number;session:LabSession};
type Detail={state:State|null;access:Access|null;error?:string};
const labels={scope:'النطاق',recon:'الاستكشاف',classify:'التصنيف',prioritize:'الأولوية',validate:'التحقق',login:'الدخول',observe:'الملاحظة',hypothesis:'الفرضية',test:'الاختبار',impact:'الأثر',remediation:'المعالجة وإعادة الاختبار',result:'النتيجة'};
function Traces({items}:{items:MinimumTrace[]}){return <div className="assessment-traces">{items.map(t=><article className="assessment-trace" key={t.id}><h3>{t.label}</h3><pre dir="ltr">{t.request}</pre><p>الحالة المحاكية: <bdi dir="ltr">{t.status}</bdi></p><pre dir="ltr">{t.body}</pre></article>)}</div>}
export default function MinimumWorkspace({id}:{id:string}){
 const {user,error:progressError,refresh}=useProgress();const [detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[accepted,setAccepted]=useState(false),[key,setKey]=useState(''),[classification,setClassification]=useState(''),[report,setReport]=useState<MinimumState['report']>(freshMinimum().report),[fix,setFix]=useState(''),[knowledgeOpen,setKnowledgeOpen]=useState(false);
 const surface=id===surfaceId,href=minimumHref(id),api='/api/interactive-labs/'+id,title=surface?'تقييم سطح الهجوم':'تقييم المصادقة والجلسة',options=surface?minimumOptions.surface:minimumOptions.session;
 useEffect(()=>{if(!user){setLoading(false);return}let live=true;fetch(api,{cache:'no-store'}).then(async r=>{const d=await r.json() as Detail;if(!r.ok)throw Error(d.error||'تعذر استعادة التقييم.');if(live){setDetail(d);setReport(d.state?.session.minimum?.report||freshMinimum().report);setFix(d.state?.session.minimum?.patch||'')}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[user,api]);
 async function post(body:Record<string,unknown>){const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as {state:State;error?:string};if(!r.ok)throw Error(d.error||'تعذر حفظ الخطوة.');return d.state}
 async function act(action:string,data:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');try{if(!detail?.state)await post({action:'start'});const state=await post({action,...data});setDetail(d=>({...d!,state}));setReport(state.session.minimum?.report||freshMinimum().report);setFix(state.session.minimum?.patch||'');setKnowledgeOpen(false);setKey('');setClassification('');if(action==='replay')setAccepted(false);if(action==='submit'&&state.session.lastResult?.passed)await refresh()}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ.')}finally{setBusy(false)}}
 const p=detail?.state?.session.minimum||freshMinimum(),step=p.step,disabled=busy||!!progressError,tests=surface?surfaceValidation:sessionTests,retests=surface?surfaceRetests:sessionTests,complete=tests.every(t=>p.observations.some(x=>x.id===t.id)),retested=retests.every(t=>p.retests.some(x=>x.id===t.id));
 const cards:Record<string,{title:string;text:string;lessonId:string}>=surface?minimumKnowledge.surface:minimumKnowledge.session,knowledge=cards[step];
 const select=(label:string,value:string,set:(v:string)=>void,items:readonly {id:string;label:string}[]) => <label className="core-field">{label}<select value={value} onChange={e=>set(e.target.value)} disabled={disabled}><option value="">اختر…</option>{items.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>;
 const button=(label:string,action:string,data:Record<string,unknown>={},off=false,primary=true)=><button className={primary?'primary-button':'assessment-secondary'} disabled={disabled||off} onClick={()=>void act(action,data)}>{label}</button>;
 if(!user)return <div className="pilot-experience assessment" dir="rtl"><a className="back-link" href={offensiveTrackHref}>أساسيات التقييم الهجومي</a><section className="panel"><h1>{title}</h1><p>تقييم مصرح به داخل محاكاة NexaCorp المعزولة.</p><a className="primary-button" target="_top" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(href)}>سجّل الدخول لعرض متطلباتك</a></section></div>;
 if(loading)return <div className="pilot-experience"><LoadingState>جارٍ استعادة التقييم…</LoadingState></div>;
 if(!detail)return <div className="pilot-experience" role="alert"><p>{error||'تعذر التحميل.'}</p><button className="primary-button" onClick={()=>location.reload()}>إعادة المحاولة</button></div>;
 if(detail.access?.locked)return <div className="pilot-experience assessment" dir="rtl"><a className="back-link" href={offensiveTrackHref}>أساسيات التقييم الهجومي</a><section className="panel"><span className="eyebrow">مقفل · المتطلبات</span><h1>{title}</h1><p>{surface?'فهم HTTP والتفويض يساعدك على قراءة رد الخدمة ضمن نطاق مصرح.':'اجمع أولًا مهارة تحديد السطح ومهارة اختبار صلاحية المورد؛ ثم اختبر عمر الجلسة دون خلطه بالتفويض.'}</p><p>{detail.access.met} من {detail.access.total} متطلبات مكتملة</p><ul>{detail.access.requirements.map(r=><li key={r.href}>{r.done?'مكتمل':'المتبقي'}: {r.label}</li>)}</ul>{detail.access.requirements.find(r=>!r.done)&&<a className="primary-button" href={detail.access.requirements.find(r=>!r.done)!.href}>أكمل المتطلب التالي</a>}</section></div>;
 return <div className="pilot-experience assessment minimum-assessment" dir="rtl"><header className="assessment-header"><a className="back-link" href={offensiveTrackHref}>أساسيات التقييم الهجومي</a><span className="eyebrow">NexaCorp · تكليف مصرح به</span><h1>{title}</h1><p>محاكاة معزولة · حالات محددة مسبقًا · بيانات وهمية</p></header><ol className="pilot-progress assessment-progress" aria-label="مراحل التقييم">{(surface?surfaceSteps:sessionSteps).map(s=><li key={s} aria-current={step===s?'step':undefined}>{labels[s]}</li>)}</ol>
 <section className="panel assessment-workspace" aria-labelledby="minimum-stage"><h2 id="minimum-stage">{labels[step]}</h2>
 {step==='scope'&&<><p>{surface?'كلّفتك NexaCorp برسم سطح بيئة التدريب وتحديد ما يستحق التحقق. لا تبحث عن Flag؛ ابنِ خريطة تعتمد على أدلة.':'كلّفتك NexaCorp بمراجعة الثقة في الجلسة داخل تطبيق ملف الموظف التدريبي. قارِن الدخول والخروج والدخول الجديد دون اختبار موارد حساب آخر.'}</p><dl className="assessment-brief"><div><dt>النطاق المصرح</dt><dd>{surface?'NexaCorp Training Environment: TRAIN-PORTAL وTRAIN-METRICS وTRAIN-ADMIN فقط.':'تطبيق ملف الموظف المعزول؛ تمثيل تدريبي لحساب '+nexaCorp.employees.find(e=>e.id==='sara')!.name+'.'}</dd></div><div><dt>الحدود</dt><dd>{surface?'قراءة سجلات ثلاثة أصول، مقارنة ردود محددة، ثم معالجة وإعادة اختبار محاكيان.':'حالات الدخول المحددة A وB وطلب دون جلسة، كلها لملف سارة الوهمي فقط. لا كلمات مرور أو Cookies حقيقية.'} لا فحص شبكة أو اتصال خارجي أو إدخال هدف.</dd></div></dl><label className="assessment-check"><input type="checkbox" checked={accepted} disabled={disabled} onChange={e=>setAccepted(e.target.checked)}/>قرأت التفويض وأوافق على حدود المحاكاة.</label>{button('ابدأ التقييم المصرح به','authorize',{accepted:true},!accepted)}</>}
 {surface&&step==='recon'&&<><p>افحص أصلًا واحدًا في كل مرة. قارِن الخدمة والمحتوى ومكان الوصول قبل التصنيف.</p>{select('الأصل الذي تريد فحصه',key,setKey,surfaceServices.map(x=>({id:x.id,label:x.host})))}{p.inspected.length<surfaceServices.length&&button('افحص الأصل المحدد','inspect',{key},!key)}{surfaceServices.filter(x=>p.inspected.includes(x.id)).map(x=><article className="assessment-observation" key={x.id}><h3><bdi dir="ltr">{x.host}</bdi></h3><dl className="assessment-brief"><div><dt>الخدمة والمنفذ</dt><dd><bdi dir="ltr">{x.service} · {x.port}</bdi></dd></div><div><dt>الرد المحاكى</dt><dd><bdi dir="ltr">{x.endpoint} · {x.response}</bdi></dd></div><div><dt>Banner محدود</dt><dd><bdi dir="ltr">{x.banner}</bdi></dd></div><div><dt>الوصول الملحوظ</dt><dd>{x.exposure}</dd></div></dl></article>)}{p.inspected.length===surfaceServices.length&&button('ابنِ خريطة سطح الهجوم','classify-start')}</>}
 {surface&&step==='classify'&&<><p>صنّف حدود ما ثبت حتى الآن. يمكنك تعديل التصنيف قبل اعتماده.</p><div className="surface-map">{surfaceServices.map(x=><article className="assessment-observation" key={x.id}><h3><bdi dir="ltr">{x.host} · {x.port} · {x.service}</bdi></h3><p><bdi dir="ltr">{x.response}</bdi></p><p>{surfaceClasses.find(c=>c.id===p.classifications[x.id])?.label||'لم يُصنّف بعد'}</p></article>)}</div>{select('الأصل المراد تصنيفه',key,setKey,surfaceServices.map(x=>({id:x.id,label:x.host})))}{select('التصنيف المبني على الدليل الحالي',classification,setClassification,surfaceClasses)}{button('احفظ التصنيف','classify',{key,value:classification},!key||!classification,false)}{p.feedback&&<p className="pilot-feedback" role="status">{p.feedback}</p>}{button('راجع الخريطة وحدد الأولوية','prioritize',{},!surfaceServices.every(x=>p.classifications[x.id]))}</>}
 {surface&&step==='prioritize'&&<><p>أي أصل يستحق مقارنة السياسة والسلوك أولًا؟ الأولوية ليست حكمًا بوجود ثغرة.</p>{select('أولوية التحقق',key,setKey,surfaceServices.map(x=>({id:x.id,label:x.host})))}{p.feedback&&<p className="pilot-feedback" role="status">{p.feedback}</p>}{button('تحقق من الأصل ذي الأولوية','priority',{key},!key)}</>}
 {!surface&&step==='login'&&<><p>استخدم هوية سارة التدريبية المحددة. لا تُدخل أي كلمة مرور؛ هذا ليس تسجيل الدخول إلى حساب CyberLab.</p>{button('سجّل الدخول إلى التطبيق المحاكى','login')}</>}
 {!surface&&step==='observe'&&<><p>راقب ما تغيّر في المتصفح، ثم ما ينتج من دخول جديد. لا تستنتج سبب المشكلة قبل اختبار مستقل.</p><Traces items={p.observations}/>{p.phase==='a'?button('سجّل الخروج من التطبيق المحاكى','logout'):p.phase==='out'?button('سجّل الدخول من جديد في المحاكاة','login-again'):button('كوّن فرضية قابلة للاختبار','hypothesis')}</>}
 {!surface&&step==='hypothesis'&&<><p>أي تفسير يستحق الاختبار؟ كل الطلبات التالية تخص ملف سارة نفسه.</p><details className="guided-disclosure"><summary>ملاحظات الدخول والخروج</summary><Traces items={p.observations.filter(t=>['login','logout','new-login'].includes(t.id))}/></details>{select('فرضيتك الحالية',key,setKey,sessionHypotheses)}{button('اختبر هذه الفرضية','choose',{key},!key)}</>}
 {(step==='validate'||step==='test')&&<><p>{surface?'قارِن السياسة والإعداد بطلبين من منطقتين مختلفتين. كلها ردود محددة داخل التدريب.':'قارِن الجلسة السابقة والجلسة الجديدة والطلب دون جلسة على المورد نفسه. A وB أسماء تدريبية وليستا رموز دخول حقيقية.'}</p>{select('الفحص المحاكى',key,setKey,tests)}{button('نفّذ الفحص المحدد','probe',{key},!key, !complete&&!p.feedback)}<Traces items={p.observations.filter(t=>tests.some(x=>x.id===t.id))}/>{p.feedback?<div className="pilot-feedback" role="status"><p>{p.feedback}</p>{button('عد للملاحظات وأعد الفحص','recheck')}</div>:complete&&button('قارن الأدلة واعتمد الاستنتاج','evaluate')}</>}
 {step==='impact'&&<><p>اجعل الاستنتاج والأثر في حدود الأدلة التي جمعتها.</p><details className="guided-disclosure"><summary>راجع الأدلة والخريطة</summary><Traces items={p.observations}/>{surface&&surfaceServices.map(x=><p key={x.id}><bdi dir="ltr">{x.host}</bdi>: {surfaceClasses.find(c=>c.id===p.classifications[x.id])?.label}</p>)}</details>{select('ما الذي ثبت فعليًا؟',report.finding,v=>setReport({...report,finding:v}),options.findings)}{select('الأثر الذي تدعمه الأدلة',report.impact,v=>setReport({...report,impact:v}),options.impacts)}<fieldset className="assessment-evidence"><legend>أدلة الاستنتاج</legend>{tests.map(t=><label className="assessment-check" key={t.id}><input type="checkbox" checked={report.evidence.includes(t.id)} disabled={disabled} onChange={e=>setReport({...report,evidence:e.target.checked?[...report.evidence,t.id]:report.evidence.filter(x=>x!==t.id)})}/>{t.label}</label>)}</fieldset>{p.feedback&&<p className="pilot-feedback" role="status">{p.feedback}</p>}{button('اعتمد الأثر وانتقل للمعالجة','report',{report},!report.finding||!report.impact||!report.evidence.length)}{button('أعد الفحص','recheck',{},false,false)}</>}
 {step==='remediation'&&<><p>اختر إجراءً، ثم أثبت أنه يمنع السلوك غير المقصود مع بقاء الاستخدام المسموح.</p>{select('الإجراء التصحيحي',fix,setFix,options.fixes)}{button(p.patch?'غيّر المعالجة وأعد الاختبار':'طبّق المعالجة في المحاكاة','patch',{key:fix},!fix,!p.patch)}{p.patch&&<>{select('طلب إعادة الاختبار',key,setKey,retests)}{button('أعد اختبار الحالة المحددة','retest',{key},!key,!retested)}<Traces items={p.retests}/>{p.feedback&&<p className="pilot-feedback" role="status">{p.feedback}</p>}{retested&&button('تحقق من المعالجة وأنهِ التقييم','submit')}</>}</>}
 {step==='result'&&<><span className="eyebrow">تقييم مكتمل</span><h3>استنتاج محدود بالأدلة ومعالجة جرى التحقق منها</h3><p>{surface?'بوابة HTTPS كانت خدمة مقصودة، وSSH مقيدًا داخليًا. خدمة القياس أعادت بيانات تشغيل لمنطقة لا تسمح بها السياسة؛ الإعداد وطلبا المقارنة أثبتا سوء التهيئة. المنفذ أو Banner وحده لم يثبت ثغرة برمجية.':'واجهة التطبيق أزالت الجلسة عند الخروج، لكن الخادم استمر في قبول A. مقارنة A وB وطلب دون جلسة أثبتت عدم إبطال الجلسة السابقة؛ لم تثبت تجاوز تفويض حساب آخر أو كشف كلمة مرور.'}</p><p>{surface?'حُصرت خدمة القياس في منطقة الإدارة: الخارجي 403، الداخلي 200، والبوابة 200. الأثر المثبت كشف بيانات تشغيل وهمية فقط.':'إبطال الجلسة في الخادم منع A برد 401، مع استمرار B برد 200 ورفض الطلب دون جلسة برد 401. الأثر هو استمرار قراءة ملف الحساب لمن يمتلك الجلسة السابقة.'}</p><p>مارست: فهم النطاق، بناء فرضية، مقارنة أدلة، تقدير أثر، معالجة وإعادة اختبار.</p><details className="guided-disclosure"><summary>تقرير الأدلة وإعادة الاختبار</summary><Traces items={p.observations}/><h3>بعد المعالجة</h3><Traces items={p.retests}/></details><CompletionProgressSummary achievementId="offensive-foundations"/><p className="assessment-reward">أفضل نتيجة: {detail.state?.bestScore} من 100. {detail.state?.session.lastResult?.xpGranted?'سُجلت مكافأة الإنجاز والمهارات مرة واحدة.':'مكافأة الإنجاز محفوظة؛ لا XP أو Skill XP إضافية.'}</p><a className="primary-button" href={surface?'/labs/v2/v2-access-control?track=offensive':offensiveTrackHref}>{surface?'الخطوة التالية: تقييم التحكم بالوصول':'راجع نتيجة أساسيات التقييم الهجومي'}</a>{button('أعد التقييم نفسه دون مكافأة جديدة','replay',{},false,false)}</>}
 </section>{knowledge&&<aside className="assessment-knowledge"><button className="assessment-secondary" aria-expanded={knowledgeOpen} onClick={()=>setKnowledgeOpen(v=>!v)}>معرفة عند الحاجة: {knowledge.title}</button>{knowledgeOpen&&<div><p>{knowledge.text}</p><a href={'/learn/'+knowledge.lessonId+'?return_to='+encodeURIComponent(href)}>اقرأ الشرح الكامل ثم عد إلى هذا الموضع</a></div>}</aside>}{error&&<p className="error" role="alert">{error}</p>}{progressError&&<p className="error" role="alert">{progressError}</p>}</div>;
}
