'use client';
import {CompletionProgressSummary} from '@/app/progression/view';
import LoadingState from '@/components/loading-state';
import {offensiveTrackHref} from '@/lib/offensive-minimum';
import {useEffect,useState} from 'react';
import {useProgress} from '@/app/shell';
import {nexaCorp} from '@/lib/nexacorp';
import {offensivePilot,assessmentSteps,assessmentPages,assessmentHypotheses,assessmentTests,assessmentFindings,assessmentImpacts,assessmentFixes,assessmentKnowledge,freshAssessment,type AssessmentState,type AssessmentTrace} from '@/lib/offensive-pilot';
import type {LabSession} from '@/lib/interactive-lab-engine';
type Access={locked:boolean;met:number;total:number;reasons:string[];requirements:{label:string;href:string;done:boolean}[]};
type State={completedAt:string|null;bestScore:number;session:LabSession};
type Detail={state:State|null;access:Access|null;error?:string};
const labels={authorize:'التفويض',recon:'الاستكشاف',observe:'الملاحظة',hypothesis:'الفرضية',test:'الاختبار',impact:'الأثر',remediation:'المعالجة',result:'النتيجة'};
const api='/api/interactive-labs/'+offensivePilot.id;
function Traces({traces}:{traces:AssessmentTrace[]}){return <div className="assessment-traces">{traces.map(t=><article className="assessment-trace" key={t.id}><h3>{assessmentTests.find(x=>x.id===t.id)?.label}</h3><pre dir="ltr">{t.request}</pre><p>الرد المحاكى: <bdi dir="ltr">{t.status}</bdi></p><pre dir="ltr">{t.body}</pre><p>{t.policy}</p></article>)}</div>}
export default function OffensiveWorkspace({track=false}:{track?:boolean}={}){
 const {user,refresh,error:progressError}=useProgress();const [detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[accepted,setAccepted]=useState(false),[page,setPage]=useState('account'),[hypothesis,setHypothesis]=useState(''),[test,setTest]=useState('guest'),[report,setReport]=useState<AssessmentState['report']>(freshAssessment().report),[fix,setFix]=useState(''),[showKnowledge,setShowKnowledge]=useState(false);
 useEffect(()=>{if(!user){setLoading(false);return}let live=true;fetch(api,{cache:'no-store'}).then(async r=>{const d=await r.json() as Detail;if(!r.ok)throw Error(d.error||'تعذر استعادة التقييم.');if(live){setDetail(d);setReport(d.state?.session.assessment?.report||freshAssessment().report);setHypothesis(d.state?.session.assessment?.hypothesis||'');setFix(d.state?.session.assessment?.patch||'')}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[user]);
 async function post(body:Record<string,unknown>){const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json() as {state:State;error?:string};if(!r.ok)throw Error(d.error||'تعذر حفظ الخطوة.');return d.state}
 async function act(action:string,data:Record<string,unknown>={}){if(busy)return;setBusy(true);setError('');try{if(!detail?.state)await post({action:'start'});const state=await post({action,...data});setDetail(prev=>({...prev!,state}));setReport(state.session.assessment?.report||freshAssessment().report);setShowKnowledge(false);if(action==='replay'){setAccepted(false);setHypothesis('');setFix('');setTest('guest')}if(action==='submit'&&state.session.lastResult?.passed)await refresh()}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ الخطوة؛ مدخلاتك ما زالت أمامك.')}finally{setBusy(false)}}
 const p=detail?.state?.session.assessment||freshAssessment(),step=p.step,testsComplete=assessmentTests.every(t=>p.observations.some(o=>o.id===t.id)),retestsComplete=assessmentTests.every(t=>p.retests.some(o=>o.id===t.id));
 const knowledge=step in assessmentKnowledge?assessmentKnowledge[step as keyof typeof assessmentKnowledge]:null;
 const employee=nexaCorp.employees.find(e=>e.id===offensivePilot.accountId)!,other=nexaCorp.employees.find(e=>e.id===offensivePilot.otherAccountId)!;
 const disabled=busy||!!progressError;
 const select=(label:string,value:string,onChange:(v:string)=>void,options:readonly {id:string;label:string}[]) => <label className="core-field">{label}<select value={value} disabled={busy} onChange={e=>onChange(e.target.value)}><option value="">اختر…</option>{options.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>;
 if(!user)return <div className="pilot-experience assessment"><a className="back-link" href={track?offensiveTrackHref:'/labs'}>{track?'أساسيات التقييم الهجومي':'المختبرات'}</a><section className="panel"><h1>تقييم الوصول إلى التقارير</h1><p>تقييم أمني مصرح به داخل محاكاة NexaCorp. يُفتح بعد مختبر HTTP ومرجع التفويض.</p><a className="primary-button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(offensivePilot.href+(track?'?track=offensive':''))} target="_top">سجّل الدخول لعرض متطلباتك</a></section></div>;
 if(loading)return <div className="pilot-experience"><LoadingState>جارٍ استعادة التقييم ومتطلباتك…</LoadingState></div>;
 if(!detail)return <div className="pilot-experience" role="alert"><p>{error||'تعذر الاستعادة.'}</p><button className="primary-button" onClick={()=>location.reload()}>إعادة المحاولة</button></div>;
 if(detail.access?.locked)return <div className="pilot-experience assessment"><a className="back-link" href={track?offensiveTrackHref:'/labs'}>{track?'أساسيات التقييم الهجومي':'المختبرات'}</a><section className="panel"><span className="eyebrow">مقفل · تدريب هجومي مصرح به</span><h1>تقييم الوصول إلى التقارير</h1><p>يلزم فهم الجلسة وطلبات HTTP وحدود التفويض قبل اختبار تطبيق.</p><p>{detail.access.met} من {detail.access.total} متطلبات مكتملة</p><ul>{detail.access.requirements.map(r=><li key={r.href}>{r.done?'مكتمل':'المتبقي'}: {r.label}</li>)}</ul>{detail.access.requirements.find(r=>!r.done)&&<a className="primary-button" href={detail.access.requirements.find(r=>!r.done)!.href}>أكمل المتطلب التالي</a>}</section></div>;
 return <div className="pilot-experience assessment" dir="rtl"><header className="assessment-header"><a className="back-link" href={track?offensiveTrackHref:'/labs'}>{track?'أساسيات التقييم الهجومي':'المختبرات'}</a><span className="eyebrow">NexaCorp · تقييم أمني مصرح به</span><h1>تقييم الوصول إلى التقارير</h1><p>تطبيق تدريبي معزول · بيانات وهمية · لا اتصال بأي هدف خارجي</p></header>
 <ol className="pilot-progress assessment-progress" aria-label="مراحل التقييم">{assessmentSteps.map(s=><li key={s} aria-current={step===s?'step':undefined}>{labels[s]}</li>)}</ol>
 <section className="panel assessment-workspace" aria-labelledby="assessment-stage">
 <h2 id="assessment-stage">{labels[step]}</h2>
 {step==='authorize'&&<><p>كلّفتك NexaCorp بفحص صلاحيات القراءة في تطبيق التقارير التدريبي. ابحث عن اختلاف بين الإذن المتوقع وسلوك التطبيق.</p><dl className="assessment-brief"><div><dt>الهدف المعتمد</dt><dd><bdi dir="ltr">access.training.nexacorp.example</bdi> — اسم داخل المحاكاة، وليس موقعًا يُفتح</dd></div><div><dt>النطاق</dt><dd>قراءة صفحتين ومقارنة ثلاثة طلبات GET للتقريرين R-104 وR-205 بحساب سارة أو زائر محاكى، ثم تجربة إصلاح محاكى.</dd></div><div><dt>حدود الإذن</dt><dd>لا تعديل أو حذف للتقارير، ولا اختبار حسابات أو أنظمة أخرى. الحسابات هنا تمثيل تدريبي لهويات الشركة؛ لا كلمات مرور حقيقية.</dd></div></dl><label className="assessment-check"><input type="checkbox" checked={accepted} disabled={busy} onChange={e=>setAccepted(e.target.checked)}/>قرأت التفويض وسأبقى داخل هذا النطاق المحاكى.</label><button className="primary-button" disabled={disabled||!accepted} onClick={()=>void act('authorize',{accepted:true})}>ابدأ التقييم المصرح به</button></>}
 {step==='recon'&&<><p>ابدأ بما يراه الموظف في التطبيق. لا تفترض أن وجود جلسة يعني صلاحية لكل تقرير.</p>{select('الصفحة التي تريد فحصها',page,setPage,assessmentPages)}{p.pages.length<2&&<button className="primary-button" disabled={disabled||!page} onClick={()=>void act('page',{key:page})}>افتح الصفحة المحددة</button>}
 {p.pages.includes('account')&&<article className="assessment-observation"><h3>حسابي</h3><p>{employee.name} · <bdi dir="ltr">{employee.accountId}</bdi> · {nexaCorp.departments.find(d=>d.id===employee.departmentId)?.name}</p><p>الدور التدريبي: موظفة عادية. السياسة: قراءة تقارير الحساب نفسه فقط؛ لا دور مراجع.</p></article>}
 {p.pages.includes('reports')&&<article className="assessment-observation"><h3>تقاريري</h3><p>تقرير R-104 · المالك: سارة. الوظيفة المتاحة: عرض التقرير. لا صلاحية تعديل أو حذف.</p><p>لا يظهر R-205 في قائمة سارة. سجل نطاق الاختبار يحدد مالك R-205: {other.name} · <bdi dir="ltr">{other.accountId}</bdi>.</p></article>}
 {p.pages.length===2&&<button className="primary-button" disabled={disabled} onClick={()=>void act('observe')}>افحص طلب التقرير الظاهر</button>}</>}
 {step==='observe'&&<><p>طلب قراءة التقرير المعروض وصل برد ناجح. قارِن الحساب والمالك؛ ما الذي تحتاج اختباره قبل الوثوق بحدود الوصول؟</p><Traces traces={p.observations.filter(t=>t.id==='own')}/><button className="primary-button" disabled={disabled} onClick={()=>void act('hypothesis')}>كوّن فرضية قابلة للاختبار</button></>}
 {step==='hypothesis'&&<><p>اختر تفسيرًا تريد اختباره. لن يُعتمد حتى تقارنه بطلبات وردود مستقلة.</p>{select('فرضيتك الحالية',hypothesis,setHypothesis,assessmentHypotheses)}<button className="primary-button" disabled={disabled||!hypothesis} onClick={()=>void act('choose',{key:hypothesis})}>اختبر هذه الفرضية</button></>}
 {step==='test'&&<><p>غيّر سياق الطلب ضمن الخيارات المعتمدة فقط. قارِن رد الخادم بالسياسة ومالك التقرير.</p>{select('الطلب المحاكى',test,setTest,assessmentTests)}<button className={testsComplete?'secondary-button':'primary-button'} disabled={disabled||!test} onClick={()=>void act('probe',{key:test})}>نفّذ الطلب داخل المحاكاة</button><Traces traces={p.observations}/>
 {p.feedback?<div className="pilot-feedback" role="status"><p>{p.feedback}</p><button className="primary-button" disabled={disabled} onClick={()=>void act('recheck')}>عد للملاحظات وأعد فرضيتك</button></div>:testsComplete&&<button className="primary-button" disabled={disabled} onClick={()=>void act('evaluate')}>قارن النتائج بفرضيتك</button>}</>}
 {step==='impact'&&<><p>النتائج أمامك؛ افصل ما ثبت عن الاحتمالات التي لم تختبرها.</p><details className="guided-disclosure"><summary>راجع الطلبات والردود</summary><Traces traces={p.observations}/></details>{select('ما الذي ثبت فعليًا؟',report.finding,v=>setReport({...report,finding:v}),assessmentFindings)}{select('الأثر الذي تدعمه الملاحظات',report.impact,v=>setReport({...report,impact:v}),assessmentImpacts)}<fieldset className="assessment-evidence"><legend>الأدلة التي تدعم استنتاجك</legend>{assessmentTests.map(t=><label className="assessment-check" key={t.id}><input type="checkbox" checked={report.evidence.includes(t.id)} disabled={busy} onChange={e=>setReport({...report,evidence:e.target.checked?[...report.evidence,t.id]:report.evidence.filter(id=>id!==t.id)})}/>{t.label}</label>)}</fieldset>{p.feedback&&<p className="pilot-feedback" role="status">{p.feedback}</p>}<button className="primary-button" disabled={disabled||!report.finding||!report.impact||report.evidence.length<2} onClick={()=>void act('report',{report})}>اعتمد الأثر وانتقل للمعالجة</button><button className="assessment-secondary" disabled={disabled} onClick={()=>void act('recheck')}>أعد الفحص</button></>}
 {step==='remediation'&&<><p>اقترح معالجة ثم أثبت أنها تمنع الوصول غير المصرح ولا تمنع المالك من عمله.</p>{select('الإجراء التصحيحي',fix,setFix,assessmentFixes)}<button className={p.patch?'secondary-button':'primary-button'} disabled={disabled||!fix} onClick={()=>void act('patch',{key:fix})}>{p.patch?'غيّر المعالجة وأعد الاختبار':'طبّق المعالجة على المحاكاة'}</button>{p.patch&&<>{select('طلب إعادة الاختبار',test,setTest,assessmentTests)}<button className={retestsComplete?'secondary-button':'primary-button'} disabled={disabled||!test} onClick={()=>void act('retest',{key:test})}>أعد اختبار الطلب</button><Traces traces={p.retests}/>{p.feedback&&<p className="pilot-feedback" role="status">{p.feedback}</p>}{retestsComplete&&<button className="primary-button" disabled={disabled} onClick={()=>void act('submit')}>تحقق من المعالجة وأنهِ التقييم</button>}</>}</>}
 {step==='result'&&<><span className="eyebrow">تقييم مكتمل</span><h3>أثبتّ الخلل وأعدت اختبار المعالجة</h3><p>جلسة سارة قرأت تقرير ليلى رغم أن السياسة تسمح بقراءة تقرير المالك فقط. مقارنة طلب المالك وطلب الزائر وطلب الحساب الآخر أثبتت أن الجلسة وحدها لم تكن تحققًا كافيًا من صلاحية المورد.</p><p>هذا خلل تفويض على مستوى المورد، يُعرف هنا بـBroken Object-Level Authorization / IDOR. تغيير المعرّف أو إخفاء الرابط إشارة للفحص، وليس إثباتًا وحده.</p><p>ثبت أثر على سرية التقرير المحاكى؛ لم تثبت تعديلًا أو حذفًا أو سيطرة على حساب. بعد فحص صلاحية المورد في الخادم: المالك <bdi dir="ltr">200</bdi>، الحساب الآخر <bdi dir="ltr">403</bdi>، والزائر <bdi dir="ltr">401</bdi>.</p><p>المهارة المثبتة: اختبار تفويض محدود، مقارنة أدلة، تقدير أثر دقيق، والتحقق من المعالجة.</p><details className="guided-disclosure"><summary>تقرير التقييم والدليل</summary><Traces traces={p.observations}/><h3>بعد المعالجة</h3><Traces traces={p.retests}/></details><CompletionProgressSummary achievementId="offensive-foundations"/><p className="assessment-reward">أفضل نتيجة: {detail.state?.bestScore} من 100. {detail.state?.session.lastResult?.xpGranted?'+75 XP · سُجلت مكافآت المهارات مرة واحدة.':'مكافأة الإنجاز محفوظة؛ لم تُمنح XP أو Skill XP إضافية.'}</p><a className="primary-button" href={track?offensiveTrackHref:'/progress'}>{track?'الخطوة التالية في التقييم الهجومي':'راجع تقدمك'}</a><button className="assessment-secondary" disabled={disabled} onClick={()=>void act('replay')}>أعد التقييم نفسه دون مكافأة جديدة</button></>}
 </section>
 {knowledge&&<aside className="assessment-knowledge"><button type="button" className="assessment-secondary" aria-expanded={showKnowledge} onClick={()=>setShowKnowledge(v=>!v)}>معرفة عند الحاجة: {knowledge.title}</button>{showKnowledge&&<div><p>{knowledge.text}</p><a href={'/learn/'+knowledge.lessonId+'?return_to='+encodeURIComponent(offensivePilot.href+(track?'?track=offensive':''))}>اقرأ الشرح الكامل ثم عد إلى هذا الموضع</a></div>}</aside>}
 {error&&<p className="error" role="alert">{error}</p>}{progressError&&<p className="error" role="alert">{progressError}</p>}
 </div>;
}
