import type {SkillId} from './skill-catalog';
export type LabKind='terminal'|'logs'|'email'|'network'|'http';
export type InteractiveLab={id:string;kind:LabKind;title:string;description:string;objective:string;difficulty:'مبتدئ'|'متوسط';skills:SkillId[];skillRewards:{skill:SkillId;points:number}[];hints:string[];relatedLessons:string[];relatedMissions:string[];relatedAlerts:string[];xpReward:number;completionConditions:string[];unlock?:{lessons:string[];labs:string[]}};
export type TerminalScenario={id:string;title:string;description:string;answerLabels:[string,string];examples:string;files:Record<string,string>;directories:string[];processes:string;network:{ip:string;ping:Record<string,string>;dns:Record<string,string>;route:Record<string,string>};requiredSteps:string[];acceptedAnswers:{path:string[];owner:string[]}};
export const terminalScenarios:TerminalScenario[]=[
 {id:'audit',title:'تعقب ملف الخدمة',description:'تتبع تقرير التدقيق والعملية التي تملكه.',answerLabels:['مسار التقرير','مالك الخدمة'],examples:'ls، cd /srv/audit، find /srv -name report.txt، cat report.txt، ps',files:{'/home/analyst/README.txt':'NexaCorp training system. Locate the audit report under /srv/audit and check the running account.','/home/analyst/notes.txt':'Only simulated files are accessible. No host shell or internet.','/srv/audit/report.txt':'report=nightly-audit\nowner=atlas\nstatus=review-required\nsource=APP-02','/srv/audit/archive.txt':'archived=true\nowner=backup-agent','/etc/resolv.conf':'nameserver 192.168.50.53'},directories:['/','/home','/home/analyst','/srv','/srv/audit','/etc'],processes:'PID USER COMMAND\n204 atlas audit-worker --report /srv/audit/report.txt\n218 analyst terminal-simulator',network:{ip:'Training LAN: 192.168.50.24/24 · gateway 192.168.50.1 · DNS 192.168.50.53',ping:{'192.168.50.1':'4/4 replies · simulated training route','portal.training':'4/4 replies · simulated training route'},dns:{'portal.training':'portal.training → 203.0.113.10 · simulated DNS'},route:{'portal.training':'1 192.168.50.1\n2 203.0.113.10 · simulated path'}},requiredSteps:['terminal:readme','terminal:find','terminal:report','terminal:ps'],acceptedAnswers:{path:['/srv/audit/report.txt','srv/audit/report.txt'],owner:['atlas']}},
 {id:'dns',title:'تشخيص DNS',description:'الشبكة تصل إلى خادم التدريب عبر IP لكن اسم البوابة لا يعمل. افحص إعداد المحلل واختبر الفرضية.',answerLabels:['سبب العطل (DNS أو resolver)','عنوان DNS الصحيح'],examples:'cat README.txt، cat /etc/resolv.conf، ip، ping 203.0.113.10، nslookup portal.training',files:{'/home/analyst/README.txt':'NexaCorp ticket: portal.training fails by name, but 203.0.113.10 is reachable. Inspect resolver configuration. Approved DNS is 192.168.50.53.','/home/analyst/notes.txt':'All commands and connections are simulated within the lesson.','/etc/resolv.conf':'nameserver 192.0.2.53\n# approved resolver: 192.168.50.53'},directories:['/','/home','/home/analyst','/etc'],processes:'PID USER COMMAND\n218 analyst terminal-simulator',network:{ip:'Training LAN: 192.168.50.24/24 · gateway 192.168.50.1 · DNS 192.0.2.53',ping:{'192.168.50.1':'4/4 replies · simulated gateway','203.0.113.10':'4/4 replies · simulated server','portal.training':'Name resolution failed · no packet sent'},dns:{'portal.training':'DNS server 192.0.2.53: timed out · no name resolution'},route:{'203.0.113.10':'1 192.168.50.1\n2 203.0.113.10 · simulated path'}},requiredSteps:['terminal:readme','terminal:resolver','terminal:ip','terminal:ping','terminal:nslookup'],acceptedAnswers:{path:['dns','resolver','dns misconfiguration','wrong dns','مشكلة dns','إعداد dns','محلل الأسماء'],owner:['192.168.50.53']}}
];
export const terminalScenarioById=(id:string)=>terminalScenarios.find(s=>s.id===id);
const reward=(skill:SkillId,points:number)=>({skill,points});
export const interactiveLabs:InteractiveLab[]=[
 {id:'v2-terminal',kind:'terminal',title:'طرفية NexaCorp',description:'سيناريوهات مستقلة لنظام ملفات افتراضي وتشخيص شبكة محاكية.',objective:'اختر سيناريو التحقيق، نفّذ سلسلة أوامر لفحص الأدلة ثم قدم استنتاجك.',difficulty:'متوسط',skills:['linux','troubleshooting'],skillRewards:[reward('linux',25),reward('troubleshooting',10)],hints:['ابدأ بـ pwd و ls ثم اقرأ README.txt.','افحص الملف المرتبط بالبلاغ، ثم اختبر الشبكة أو العملية بحسب السيناريو.'],relatedLessons:['linux-1','linux-2','net-2','it-10','it-11'],relatedMissions:['005','002'],relatedAlerts:[],xpReward:75,completionConditions:['قراءة التعليمات','فحص الملفات والأدوات المناسبة','تقديم استنتاج مبني على عدة خطوات']},
 {id:'v2-logs',kind:'logs',title:'تحقيق السجلات المترابطة',description:'اربط أحداث الهوية والجهاز واتصالات الشبكة لاكتشاف النمط.',objective:'رشّح السجلات، اجمع أدلة متعددة ثم اربط العملية على الجهاز باتصالاتها.',difficulty:'متوسط',skills:['logs','incident'],skillRewards:[reward('logs',25),reward('incident',10)],hints:['قارن حالات الفشل خلال دقائق مع النجاح الذي تلاها.','افحص علاقة Parent/Child وتوقيع العملية، ثم اربط الجهاز بوجهة الاتصال المتكرر.'],relatedLessons:['sec-2','security-9','soc-3','soc-4','response-6','soc-12'],relatedMissions:['004','boss-003'],relatedAlerts:['SOC-001','SOC-002','SOC-004','SOC-005'],xpReward:75,completionConditions:['ربط فشل الدخول بنجاحه','مقارنة عمليات الجهاز والتوقيع والعملية الأم','ربط اتصالات الشبكة المتكررة بسجل الجهاز']},
 {id:'v2-email',kind:'email',title:'صندوق بريد NexaCorp',description:'افحص ثلاث رسائل، بينها رسالة شرعية وأخرى مريبة ورسالة تصيّد.',objective:'قارن المرسل وReply-To والترويسات والروابط والمرفقات ثم صنّف الرسائل.',difficulty:'مبتدئ',skills:['phishing','cybersecurity'],skillRewards:[reward('phishing',25),reward('cybersecurity',10)],hints:['اسم المرسل الظاهر لا يكفي؛ افتح تفاصيل الترويسة والوجهة.','لاحظ عدم تطابق Reply-To وفشل SPF في الرسالة التي تطلب رمز التحقق.'],relatedLessons:['sec-1'],relatedMissions:['003','boss-002'],relatedAlerts:['SOC-006'],xpReward:75,completionConditions:['فحص الترويسة والرابط لكل رسالة','تحديد تصنيف الرسائل الثلاث','جمع مؤشري التصيّد']},
 {id:'v2-network',kind:'network',title:'مكتب الدعم الشبكي',description:'شخّص أجهزة المكتب، ثم تتبّع نقل البيانات والردود عبر شبكة محاكاة.',objective:'أصلح أعطال الأجهزة، واختر النقل وفق المتطلبات، ثم تتبّع العنوان والمنفذ ومسار الرد.',difficulty:'متوسط',skills:['networking','troubleshooting'],skillRewards:[reward('networking',25),reward('troubleshooting',10)],hints:['ابدأ من عنوان الجهاز والبوابة ثم اختبر البوابة قبل اسم الموقع.','قارن المسار حتى البوابة بجدول التوجيه وترجمة العناوين قبل تقرير السبب.'],relatedLessons:['net-1','net-2','net-3','network-7','network-10'],relatedMissions:['001','002','boss-001'],relatedAlerts:[],xpReward:75,completionConditions:['فحص وإصلاح الأجهزة الخمسة','اختيار النقل حسب متطلبات خمسة تطبيقات','تتبّع عودة الرد وتشخيص الترجمة والمسار']},
 {id:'v2-http',kind:'http',title:'تتبّع طلب الويب',description:'اقرأ طلبات وردود HTTP المحاكية وافهم جلسة الدخول ورموز الحالة.',objective:'قارن طلبًا غير مصادق وطلبًا يحمل Cookie واستخرج تأثيرهما على الرد.',difficulty:'مبتدئ',skills:['cybersecurity','logs'],skillRewards:[reward('cybersecurity',25),reward('logs',10)],hints:['افحص Request Headers ثم Response لكل تبادل.','401 للطلب دون جلسة، و200 عندما تُرفق Cookie تدريبية صالحة.'],relatedLessons:['web-1'],relatedMissions:[],relatedAlerts:[],xpReward:75,completionConditions:['فحص الطلب والرد لكل تبادل','تحديد الطريقة والحالة والفرق بين الردين']},
 {id:'v2-access-control',kind:'http',title:'تقييم الوصول إلى التقارير',description:'Web Access Control / Authorization · تكليف أمني مصرح به: افحص صلاحية قراءة التقارير داخل تطبيق NexaCorp تدريبي معزول.',objective:'استكشف الحساب والطلبات، اختبر فرضيتك، ثم أثبت الأثر والمعالجة داخل محاكاة.',difficulty:'متوسط',skills:['cybersecurity','logs'],skillRewards:[reward('cybersecurity',25),reward('logs',10)],hints:[],relatedLessons:['security-6','web-security-7','web-security-12'],relatedMissions:[],relatedAlerts:[],xpReward:75,completionConditions:['مراجعة التفويض والنطاق','مقارنة الحساب ومالك المورد وثلاثة طلبات','إثبات الأثر والمعالجة وإعادة الاختبار'],unlock:{lessons:['security-6'],labs:['v2-http']}},
 {id:'v2-attack-surface',kind:'http',title:'تقييم سطح الهجوم',description:'Attack Surface Assessment · ارسم خريطة ثلاثة أصول تدريبية، ثم قارِن الخدمة والتعرّض والإعداد بالسياسة.',objective:'حدد أولوية الفحص، أثبت الأثر المحدود، واقترح معالجة وأعد اختبارها.',difficulty:'متوسط',skills:['networking','cybersecurity'],skillRewards:[reward('networking',25),reward('cybersecurity',10)],hints:[],relatedLessons:['tools-1','net-3','network-security-1','web-7'],relatedMissions:[],relatedAlerts:[],xpReward:75,completionConditions:['تفويض ونطاق محددان','خريطة الأصول والتصنيف والأولوية','مقارنة السياسة بطلبين ثم معالجة وإعادة اختبار'],unlock:{lessons:['security-6'],labs:['v2-http']}},
 {id:'v2-auth-session',kind:'http',title:'تقييم المصادقة والجلسة',description:'Authentication & Session Assessment · قارِن الدخول والخروج والجلسة السابقة والحالية داخل تطبيق تدريبي معزول.',objective:'ابنِ فرضية واختبرها بالأدلة ثم حدد الأثر والمعالجة وأعد الاختبار.',difficulty:'متوسط',skills:['cybersecurity','logs'],skillRewards:[reward('cybersecurity',25),reward('logs',10)],hints:[],relatedLessons:['security-5','web-9','web-10','web-security-6'],relatedMissions:[],relatedAlerts:[],xpReward:75,completionConditions:['مقارنة الدخول والخروج والدخول الجديد','اختبار ثلاث حالات جلسة على المورد نفسه','إثبات أثر محدود ومعالجة وإعادة اختبار'],unlock:{lessons:[],labs:['v2-attack-surface','v2-access-control']}}
];
export const interactiveLabById=(id:string)=>interactiveLabs.find(l=>l.id===id);
export const labForLesson=(id:string)=>interactiveLabs.filter(l=>l.relatedLessons.includes(id));
export const labForMission=(id:string)=>interactiveLabs.filter(l=>l.relatedMissions.includes(id));
export const labForAlert=(id:string)=>interactiveLabs.filter(l=>l.relatedAlerts.includes(id));
export const logEvents=[
 {id:'L01',time:'2026-09-24T08:58:00Z',type:'Authentication',user:'layla',host:'WKST-02',ip:'192.0.2.42',severity:'Low',result:'success',message:'Office login confirmed'},
 {id:'L02',time:'2026-09-24T09:00:00Z',type:'Firewall',user:'service',host:'FW-01',ip:'203.0.113.7',severity:'Low',result:'allow',message:'Approved backup endpoint'},
 {id:'L03',time:'2026-09-24T09:01:00Z',type:'Web',user:'sara',host:'WEB-01',ip:'192.0.2.83',severity:'Low',result:'200',message:'GET /portal'},
 {id:'L04',time:'2026-09-24T09:02:10Z',type:'Authentication',user:'admin',host:'AUTH-01',ip:'198.51.100.24',severity:'Medium',result:'fail',message:'Invalid password'},
 {id:'L05',time:'2026-09-24T09:02:34Z',type:'Authentication',user:'admin',host:'AUTH-01',ip:'198.51.100.24',severity:'Medium',result:'fail',message:'Invalid password'},
 {id:'L06',time:'2026-09-24T09:02:55Z',type:'Endpoint',user:'admin',host:'WKST-01',ip:'192.0.2.10',severity:'Low',result:'ok',message:'Routine patch check'},
 {id:'L07',time:'2026-09-24T09:03:11Z',type:'Authentication',user:'admin',host:'AUTH-01',ip:'198.51.100.24',severity:'Medium',result:'fail',message:'Invalid password'},
 {id:'L08',time:'2026-09-24T09:03:49Z',type:'Authentication',user:'admin',host:'AUTH-01',ip:'198.51.100.24',severity:'High',result:'success',message:'New session from unrecognized address'},
 {id:'L09',time:'2026-09-24T09:04:00Z',type:'Firewall',user:'admin',host:'FW-01',ip:'198.51.100.24',severity:'Medium',result:'allow',message:'Identity service egress'},
 {id:'L10',time:'2026-09-24T09:05:00Z',type:'Authentication',user:'user1',host:'AUTH-01',ip:'203.0.113.18',severity:'Low',result:'fail',message:'Password mistyped'},
 {id:'L11',time:'2026-09-24T09:06:00Z',type:'Web',user:'layla',host:'WEB-01',ip:'192.0.2.42',severity:'Low',result:'200',message:'GET /help'},
 {id:'L12',time:'2026-09-24T09:08:00Z',type:'Endpoint',user:'sara',host:'WKST-03',ip:'192.0.2.83',severity:'Low',result:'ok',message:'Signed inventory task'},
 {id:'L13',time:'2026-09-24T09:12:00Z',type:'Endpoint',user:'atlas',host:'APP-02',ip:'192.168.50.25',severity:'Low',result:'ok',message:'PID 300 explorer.exe · signed NexaCorp · parent winlogon.exe'},
 {id:'L14',time:'2026-09-24T09:12:10Z',type:'Endpoint',user:'atlas',host:'APP-02',ip:'192.168.50.25',severity:'Medium',result:'start',message:'PID 412 report-viewer.exe · unsigned · parent explorer.exe · path /tmp/report-viewer.exe'},
 {id:'L15',time:'2026-09-24T09:12:14Z',type:'Endpoint',user:'atlas',host:'APP-02',ip:'192.168.50.25',severity:'Medium',result:'spawn',message:'PID 430 powershell.exe · signed Microsoft · parent PID 412 report-viewer.exe · -EncodedCommand'},
 {id:'L16',time:'2026-09-24T09:12:15Z',type:'Endpoint',user:'sara',host:'WKST-03',ip:'192.0.2.83',severity:'Low',result:'ok',message:'PID 217 updater.exe · signed NexaCorp · parent services.exe · approved maintenance'},
 {id:'L17',time:'2026-09-24T09:13:00Z',type:'Firewall',user:'atlas',host:'APP-02',ip:'203.0.113.77',severity:'Medium',result:'allow',message:'PID 430 → 203.0.113.77:443 · outbound 1/4'},
 {id:'L18',time:'2026-09-24T09:13:20Z',type:'Firewall',user:'atlas',host:'APP-02',ip:'203.0.113.77',severity:'Medium',result:'allow',message:'PID 430 → 203.0.113.77:443 · outbound 2/4'},
 {id:'L19',time:'2026-09-24T09:13:40Z',type:'Firewall',user:'atlas',host:'APP-02',ip:'203.0.113.77',severity:'Medium',result:'allow',message:'PID 430 → 203.0.113.77:443 · outbound 3/4'},
 {id:'L20',time:'2026-09-24T09:14:00Z',type:'Firewall',user:'backup',host:'FILE-01',ip:'203.0.113.7',severity:'Low',result:'allow',message:'PID 88 backup-agent → approved endpoint · scheduled backup 1/2'},
 {id:'L21',time:'2026-09-24T09:14:20Z',type:'Firewall',user:'backup',host:'FILE-01',ip:'203.0.113.7',severity:'Low',result:'allow',message:'PID 88 backup-agent → approved endpoint · scheduled backup 2/2'}
] as const;
export const logInvestigations=[
 {id:'endpoint-chain',title:'الجهاز بعد تسجيل الدخول',brief:'ظهرت عمليات متعددة بعد نشاط الهوية. أي سلسلة تستحق الفحص؟ قارِن التوقيع بالعملية الأم والابن.',required:['L14','L15'],host:'APP-02',indicator:'report-viewer.exe',decision:'investigate',feedback:'العملية غير الموقّعة بدأت PowerShell موقّعًا؛ توقيع الابن لا يجعل سلسلة التشغيل آمنة.'},
 {id:'network-chain',title:'اتصالات فترة الصباح',brief:'اتصالات متكررة من جهازين. اربط PID والجهاز والوجهة بسلسلة العمليات؛ هل هي صيانة مجدولة أم تحتاج احتواء؟',required:['L15','L17','L18'],host:'APP-02',indicator:'203.0.113.77',decision:'contain',feedback:'تكرار اتصال PID 430 من APP-02 إلى الوجهة نفسها يتصل بسلسلة التنفيذ؛ FILE-01 يتجه إلى خدمة النسخ المعتمدة.'}
] as const;
export const transportScenarios=[
 {id:'file-transfer',title:'تسليم ملف مالي',brief:'ملف 600 MB يجب أن يصل مطابقًا للأصل؛ فقدان جزء صغير يفسد الاستيراد، والتأخير مقبول.',trace:'فقدت المحاكاة القطعة 4/12؛ يجب استردادها قبل قبول الملف.',expected:'tcp',impact:'TCP يعيد إرسال الجزء المفقود ويحافظ على اكتمال الملف؛ قد يزيد التأخير.'},
 {id:'voice-call',title:'مكالمة فريق الدعم',brief:'الصوت الحي يجب أن يصل بأقل تأخير؛ فقدان جزء قصير مقبول إذا استمرت المكالمة.',trace:'تأخرت القطعة 4/12 بمقدار 900ms؛ إعادة إرسالها بعد وصول الصوت التالي لا تنفع.',expected:'udp',impact:'UDP يتيح التطبيق الاستمرار دون انتظار الحزمة القديمة؛ يحتاج التطبيق لمعالجة فقد الصوت.'},
 {id:'dns-query',title:'سؤال محلل الأسماء',brief:'استعلام صغير عن عنوان بوابة الشركة؛ مطلوب رد سريع، ويستطيع العميل إعادة الطلب عند انتهاء المهلة.',trace:'لم يصل الرد الأول؛ العميل قادر على إعادة الاستعلام بعد المهلة.',expected:'udp',impact:'UDP مناسب للاستعلام الصغير المعتاد مع إعادة المحاولة على مستوى التطبيق؛ بعض ردود DNS تستخدم TCP عند الحاجة.'},
 {id:'web-session',title:'جلسة بوابة الشركة',brief:'تحميل صفحة وتبادل بيانات جلسة حساسة؛ مطلوب تسليم البايتات بالترتيب داخل اتصال HTTPS تقليدي.',trace:'فُقد مقطع وسط الاستجابة قبل وصول آخر الصفحة.',expected:'tcp',impact:'الاتصال التقليدي HTTPS عبر TCP يعيد المقطع ويحافظ على ترتيب البيانات. توجد أيضًا تطبيقات HTTP/3 تستخدم QUIC فوق UDP.'},
 {id:'live-stream',title:'بث متابعة حي',brief:'بث منخفض التأخير عبر تطبيق مباشر مخصص؛ إطارات قديمة تصبح بلا فائدة بعد الإطار الجديد.',trace:'إطار قديم تأخر بينما وصلت ثلاثة إطارات أحدث.',expected:'udp',impact:'UDP يناسب هذا البث الحي المخصص حين يفضّل التطبيق زمن الوصول على استعادة الإطار القديم؛ كثير من بث الويب العادي يعمل عبر TCP.'}
] as const;
export const networkInvestigations=[
 {id:'return-flow',title:'طلب بوابة الشركة',brief:'جهاز داخلي فتح اتصالًا؛ تتبّع عنوان ومنفذ الرد الذي سيصل إلى الجهاز. اعتمد على جدول الجلسات بعد الفحص.',views:{device:'FIN-01 192.168.50.21:51514 → 203.0.113.10:443 · gateway 192.168.50.1 responds',gateway:'NAT table: 192.168.50.21:51514 ↔ 198.51.100.9:62001 · remote 203.0.113.10:443',route:'0.0.0.0/0 → WAN; remote reply 203.0.113.10:443 → 198.51.100.9:62001'},answer:'192.168.50.21:51514',reason:'translate',feedback:'الرد يصل إلى المنفذ العام 62001 ثم يعيده جدول NAT إلى 192.168.50.21:51514.'},
 {id:'missing-session',title:'بلاغ جهاز الاستقبال',brief:'البوابة والوجهة تردان من جهاز آخر، لكن طلب جهاز الاستقبال لا يتلقى ردًا. حدّد موضع انقطاع التدفق.',views:{device:'REC-03 192.168.50.23:51515 → 203.0.113.10:443 · gateway 192.168.50.1 responds; FIN-01 reaches remote',gateway:'NAT table: FIN-01 ↔ 198.51.100.9:62001; REC-03:51515 has no mapping · outbound policy denied',route:'0.0.0.0/0 → WAN active; 203.0.113.10 reachable from FIN-01'},answer:'mapping',reason:'policy',feedback:'المسار والبوابة يعملان؛ سياسة الخروج منعت إنشاء NAT mapping لهذا التدفق. راجع السياسة المصرّح بها ثم أعد الاختبار.'},
 {id:'branch-route',title:'زيارة شبكة الفرع',brief:'محطة IT-02 ترى بوابتها، لكنها لا تصل إلى خادم الفرع. قارِن فحص البوابة بجدول التوجيه.',views:{device:'IT-02 192.168.50.22/24 · gateway 192.168.50.1 · ping gateway succeeds · ping 10.42.0.20 fails',gateway:'Routing table: 192.168.50.0/24 local; 0.0.0.0/0 → WAN; no route to 10.42.0.0/24 via branch tunnel',route:'Branch tunnel 192.168.50.254 active · route to 10.42.0.0/24 absent on gateway'},answer:'route',reason:'add-route',feedback:'نجاح Ping إلى البوابة يستبعد خطأ بوابة الجهاز؛ أضف المسار المصرّح إلى 10.42.0.0/24 عبر نفق الفرع ثم اختبر.'}
] as const;
export const emails=[
 {id:'E01',subject:'تحديث جدول الصيانة',from:'it@nexacorp.example',replyTo:'it@nexacorp.example',domain:'nexacorp.example',url:'https://intranet.nexacorp.example/maintenance',attachment:'لا يوجد',headers:'SPF pass · DKIM pass · DMARC pass',body:'موعد الصيانة المجدولة يوم الخميس؛ التفاصيل في البوابة الداخلية. لا يُطلب تسجيل الدخول من الرسالة.'},
 {id:'E02',subject:'مراجعة فاتورة مورد',from:'billing@vendor-check.example',replyTo:'billing@vendor-check.example',domain:'vendor-check.example',url:'https://vendor-check.example/invoice',attachment:'invoice-042.pdf · PDF · 84 KB',headers:'SPF pass · DKIM none · DMARC none',body:'وصلت فاتورة جديدة للمراجعة. لا توجد مطالبة برمز دخول. تحقّق من المورد بقناة معروفة قبل التعامل مع المرفق.'},
 {id:'E03',subject:'رمز التحقق مطلوب الآن',from:'security@nexacorp.example',replyTo:'verify@account-review.example',domain:'account-review.example',url:'https://account-review.example/verify-code',attachment:'login-check.html · HTML · 19 KB',headers:'SPF fail · DKIM none · DMARC fail',body:'أرسل رمز التحقق خلال خمس دقائق لتجنّب إيقاف الحساب. هذه الرسالة مصطنعة للتدريب.'}
] as const;
export const networkCases=[
 {id:'wrong-ip',device:'Finance PC',host:'FIN-01',issue:'عنوان الجهاز',initial:{ip:'10.88.1.21',gateway:'192.168.50.1',dns:'192.168.50.53',dhcp:'on',port:'on'},fix:{field:'ip',value:'192.168.50.21'},target:'192.168.50.1'},
 {id:'wrong-gateway',device:'IT PC',host:'IT-02',issue:'البوابة',initial:{ip:'192.168.50.22',gateway:'192.168.51.1',dns:'192.168.50.53',dhcp:'on',port:'on'},fix:{field:'gateway',value:'192.168.50.1'},target:'203.0.113.10'},
 {id:'dhcp-failure',device:'Reception PC',host:'REC-03',issue:'خدمة العناوين',initial:{ip:'169.254.12.9',gateway:'-',dns:'-',dhcp:'off',port:'on'},fix:{field:'dhcp',value:'on'},target:'192.168.50.1'},
 {id:'dns-error',device:'Analyst PC',host:'SOC-04',issue:'أسماء النطاقات',initial:{ip:'192.168.50.24',gateway:'192.168.50.1',dns:'192.0.2.53',dhcp:'on',port:'on'},fix:{field:'dns',value:'192.168.50.53'},target:'portal.training'},
 {id:'isolated-host',device:'Server',host:'APP-05',issue:'عزل الجهاز',initial:{ip:'192.168.50.25',gateway:'192.168.50.1',dns:'192.168.50.53',dhcp:'on',port:'off'},fix:{field:'port',value:'on'},target:'192.168.50.1'}
] as const;
export const httpExchanges=[
 {id:'H01',label:'طلب دون جلسة',method:'GET',url:'https://portal.training/api/profile',requestHeaders:'Accept: application/json',requestBody:'(empty)',status:401,responseHeaders:'Content-Type: application/json\nWWW-Authenticate: Session',responseBody:'{"error":"Authentication required"}'},
 {id:'H02',label:'طلب مع جلسة',method:'GET',url:'https://portal.training/api/profile',requestHeaders:'Accept: application/json\nCookie: training_session=sample-valid',requestBody:'(empty)',status:200,responseHeaders:'Content-Type: application/json\nCache-Control: private',responseBody:'{"user":"trainee","role":"viewer"}'}
] as const;
