import type {OffensiveExtension} from './offensive-expansion';
import {isMinimumAssessment,surfaceId,surfaceSteps,sessionSteps,type MinimumState} from './offensive-minimum';
import {applyMinimum} from './offensive-minimum-actions';
import {offensivePilot,assessmentSteps,type AssessmentState} from './offensive-pilot';
import {applyAssessment} from './offensive-pilot-actions';
import {emails,httpExchanges,interactiveLabById,logEvents,logInvestigations,networkCases,networkInvestigations,transportScenarios,terminalScenarios,terminalScenarioById,type InteractiveLab} from './interactive-labs';
export type LabAction={action:string;[key:string]:unknown};
export type LabSession={offensive?:OffensiveExtension;minimum?:MinimumState;assessment?:AssessmentState;visited:string[];evidence:string[];filtered:boolean;filters:Record<string,string>;cwd:string;terminalScenarioId?:string;fileModes?:Record<string,string>;terminal:{input:string;output:string}[];networkIndex:number;networkInspected:boolean;networkTestedBefore:boolean;networkConfig:Record<string,string>|null;networkFixed:string[];networkOutput:string;transportSolved?:string[];networkSolved?:string[];logAuthSolved?:boolean;logSolved?:string[];verdicts:Record<string,string>;hintsUsed:number;mistakes:number;attempts:number;lastResult:{passed:boolean;score:number;feedback:string[];xpGranted?:boolean;skillGranted?:boolean}|null};
export const newLabSession=():LabSession=>({visited:[],evidence:[],filtered:false,filters:{},cwd:'/home/analyst',terminalScenarioId:'audit',fileModes:{},terminal:[],networkIndex:0,networkInspected:false,networkTestedBefore:false,networkConfig:null,networkFixed:[],networkOutput:'',transportSolved:[],networkSolved:[],logAuthSolved:false,logSolved:[],verdicts:{},hintsUsed:0,mistakes:0,attempts:0,lastResult:null});
export function publicLabData(lab:InteractiveLab){return {lab,terminalScenarios:lab.kind==='terminal'?terminalScenarios.map(({id,title,description,answerLabels,examples})=>({id,title,description,answerLabels,examples})):[],logs:lab.kind==='logs'?logEvents:[],logInvestigations:lab.kind==='logs'?logInvestigations.map(({id,title,brief})=>({id,title,brief})):[],emails:lab.kind==='email'?emails:[],network:lab.kind==='network'?networkCases.map(c=>({id:c.id,device:c.device,host:c.host,target:c.target,initial:c.initial})):[],transportScenarios:lab.kind==='network'?transportScenarios.map(({id,title,brief,trace})=>({id,title,brief,trace})):[],networkInvestigations:lab.kind==='network'?networkInvestigations.map(({id,title,brief,views})=>({id,title,brief,views})):[],http:lab.kind==='http'&&lab.id!==offensivePilot.id&&!isMinimumAssessment(lab.id)?httpExchanges:[]}}
const uniq=(a:string[],v:string)=>a.includes(v)?a:[...a,v];
const clean=(v:unknown,max=140)=>typeof v==='string'?v.trim().slice(0,max):'';
const normal=(v:string)=>v.toLowerCase().replace(/\s+/g,' ').trim();
function target(cwd:string,arg:string){const path=arg.startsWith('/')?arg:cwd+'/'+arg;const parts:string[]=[];for(const p of path.split('/')){if(p==='..')parts.pop();else if(p&&p!=='.')parts.push(p)}return '/'+parts.join('/')}
function executeTerminal(s:LabSession,input:string){if(input.length>160||/[;&|`$<>\\]/.test(input))return 'أمر غير مدعوم في هذه المحاكاة. استخدم help.';
 const scenario=terminalScenarioById(s.terminalScenarioId||'audit')||terminalScenarios[0],files=scenario.files,directories=scenario.directories;
 const [cmd,...args]=input.trim().split(/\s+/),arg=args.join(' '),path=target(s.cwd,args[0]||'.');
 switch(cmd){
  case 'help':return 'pwd, ls, cd, cat, grep, find, ps, chmod, ip, ping, nslookup, traceroute, tracert, netstat, ipconfig, whoami';
  case 'pwd':return s.cwd;
  case 'whoami':return 'analyst (simulated account)';
  case 'ls':{const detailed=args[0]==='-l';const dir=(detailed?args[1]:args[0])?target(s.cwd,detailed?args[1]||'.':args[0]):s.cwd;if(!directories.includes(dir))return 'المجلد غير موجود';return [...directories,...Object.keys(files)].filter(p=>p!==dir&&p.startsWith(dir==='/'?'/':dir+'/')&&!p.slice(dir==='/'?1:dir.length+1).includes('/')).map(p=>(detailed?(s.fileModes?.[p]||'644')+' ':'')+p.split('/').at(-1)+(directories.includes(p)?'/':'')).join('  ')||'(empty)'}
  case 'cd':if(!directories.includes(path))return 'المجلد غير موجود';s.cwd=path;return s.cwd;
  case 'cat':if(!files[path])return 'الملف غير موجود';if(path==='/home/analyst/README.txt')s.visited=uniq(s.visited,'terminal:readme');if(path==='/srv/audit/report.txt')s.visited=uniq(s.visited,'terminal:report');if(path==='/etc/resolv.conf')s.visited=uniq(s.visited,'terminal:resolver');return files[path];
  case 'find':if(!arg)return 'مثال: find /srv -name report.txt';{const matches=Object.keys(files).filter(p=>p.includes(args.at(-1)?.replaceAll('*','')||'report')&&p.startsWith(args[0]?.startsWith('/')?args[0]:s.cwd));if(matches.length)s.visited=uniq(s.visited,'terminal:find');return matches.join('\n')||'(no matches)'}
  case 'grep':{const needle=args[0],file=target(s.cwd,args[1]||'');if(!needle||!files[file])return 'مثال: grep owner /srv/audit/report.txt';if(file==='/srv/audit/report.txt')s.visited=uniq(s.visited,'terminal:report');return files[file].split('\n').filter(line=>line.toLowerCase().includes(needle.toLowerCase())).join('\n')||'(no matches)'}
  case 'ps':s.visited=uniq(s.visited,'terminal:ps');return scenario.processes;
  case 'chmod':if(args.length!==2||!['600','640','644'].includes(args[0])||!files[target(s.cwd,args[1])])return 'مثال آمن: chmod 640 /srv/audit/report.txt';s.fileModes={...s.fileModes,[target(s.cwd,args[1])]:args[0]};return 'وضع الملف الوهمي: '+args[0]+' (لا يغيّر ملفًا حقيقيًا)';
  case 'ip':case 'ipconfig':s.visited=uniq(s.visited,'terminal:ip');return scenario.network.ip;
  case 'ping':{const result=scenario.network.ping[arg];if(result)s.visited=uniq(s.visited,'terminal:ping');return !arg?'حدد وجهة تدريبية':result||'Unknown training destination · no packet sent'}
  case 'nslookup':{const result=scenario.network.dns[arg];if(result)s.visited=uniq(s.visited,'terminal:nslookup');return result||'No record in training scenario'}
  case 'traceroute':case 'tracert':return scenario.network.route[arg]||'No simulated path';
  case 'netstat':return 'tcp 127.0.0.1:8080 LISTEN · simulated only';
  default:return 'أمر غير مسموح. اكتب help لعرض الأوامر التعليمية.';
 }
}
export function filterLogs(filters:Record<string,string>){return logEvents.filter(e=>{
 const search=normal(filters.search||'');if(search&&!Object.values(e).some(v=>normal(String(v)).includes(search)))return false;
 for(const key of ['type','user','host','ip','severity'] as const)if(filters[key]&&normal(String(e[key]))!==normal(filters[key]))return false;
 if(filters.from&&e.time<filters.from)return false;if(filters.to&&e.time>filters.to)return false;
 return true;
})}
function grade(lab:InteractiveLab,s:LabSession,action:LabAction){const failures:string[]=[];const answer=(key:string)=>normal(clean(action[key]));
 if(lab.kind==='terminal'){const scenario=terminalScenarioById(s.terminalScenarioId||'audit')||terminalScenarios[0];if(!scenario.requiredSteps.every(id=>s.visited.includes(id)))failures.push('اجمع أدلة السيناريو عبر سلسلة فحوص قبل تقديم الاستنتاج.');if(!scenario.acceptedAnswers.path.includes(answer('path'))||!scenario.acceptedAnswers.owner.includes(answer('owner')))failures.push('راجع نتيجة الأوامر والملفات، ثم صحح الاستنتاج.');}
 if(lab.kind==='logs'){if(!s.logAuthSolved)failures.push('حلل تسلسل تسجيل الدخول بعد جمع الفشل والنجاح.');if((s.logSolved||[]).length!==logInvestigations.length)failures.push('اربط سلسلة العمليات وأحداث الاتصال بعد تسجيل الدخول.');}
 if(lab.kind==='email'){if(!emails.every(e=>s.visited.includes(e.id+':headers')&&s.visited.includes(e.id+':url')))failures.push('افحص ترويسة ووجهة الرابط لكل رسالة.');if(!['E03:replyTo','E03:headers'].every(e=>s.evidence.includes(e)))failures.push('اجمع مؤشرَي Reply-To ونتائج المصادقة للرسالة الخطرة.');if(s.verdicts.E01!=='legitimate'||s.verdicts.E02!=='suspicious'||s.verdicts.E03!=='phishing')failures.push('تحتاج إلى مراجعة تصنيف الرسائل الثلاث.');}
 if(lab.kind==='network'){if(s.networkFixed.length!==networkCases.length)failures.push('أكمل فحص وإصلاح واختبار جميع الأجهزة.');if((s.transportSolved||[]).length!==transportScenarios.length)failures.push('اختبر نقل البيانات في كل سياق واختر وفق المتطلبات.');if((s.networkSolved||[]).length!==networkInvestigations.length)failures.push('تتبّع تدفق الرد والمطابقة والمسار في السيناريوهات الثلاثة.');}
 if(lab.kind==='http'){if(!httpExchanges.every(e=>s.visited.includes(e.id+':request')&&s.visited.includes(e.id+':response')))failures.push('افحص الطلب والرد لكلا التبادلين.');if(answer('method')!=='get'||answer('unauthorized')!=='401'||answer('authorized')!=='200'||!['cookie','training_session','session cookie'].includes(answer('difference')))failures.push('قارن طريقة الطلب وحالتَي الرد وتأثير Cookie على الجلسة.');}
 const passed=failures.length===0;const score=passed?Math.max(60,100-s.hintsUsed*10-s.mistakes*5):Math.max(0,50-failures.length*15);return {passed,score,feedback:passed?['أكملت خطوات التحقيق واستندت إلى أدلة السيناريو.','أعد المختبر لتحسين نتيجتك من دون مكافأة أساسية جديدة.']:failures};}
export function applyLabAction(lab:InteractiveLab,old:LabSession,action:LabAction){if(isMinimumAssessment(lab.id))return applyMinimum(lab.id,old,action);if(lab.id===offensivePilot.id)return applyAssessment(old,action);const s:LabSession=structuredClone(old);const kind=lab.kind,key=clean(action.key,80),value=clean(action.value,250);let message='حُفظت الخطوة.';let submitted=false;
 if(s.lastResult?.passed&&action.action!=='replay')throw Error('أعد فتح المختبر لبدء محاولة جديدة.');
 switch(action.action){
 case 'scenario':if(kind!=='terminal'||s.terminal.length||s.visited.length||s.lastResult||!terminalScenarioById(key))throw Error('اختر سيناريو متاحًا قبل بدء الأوامر؛ يمكنك إكمال المختبر ثم إعادته.');s.terminalScenarioId=key;s.cwd='/home/analyst';s.fileModes={};message='تم اختيار سيناريو '+terminalScenarioById(key)!.title+'.';break;
 case 'hint':if(s.hintsUsed>=lab.hints.length)throw Error('ظهرت كل التلميحات.');message=lab.hints[s.hintsUsed++];break;
 case 'replay':{if(!s.lastResult?.passed)throw Error('أكمل المحاولة قبل إعادتها.');const fresh=newLabSession();fresh.attempts=s.attempts;return {session:fresh,message:'بدأت محاولة جديدة دون تكرار المكافآت.',submitted:false}}
 case 'inspect':if(kind==='email'&&emails.some(e=>e.id===key)&&['headers','url','attachment','sender','replyTo','body'].includes(value))s.visited=uniq(s.visited,key+':'+value);else if(kind==='http'&&httpExchanges.some(e=>e.id===key)&&['request','response'].includes(value))s.visited=uniq(s.visited,key+':'+value);else if(kind==='network'&&networkCases[s.networkIndex]?.id===key)s.networkInspected=true;else throw Error('عنصر غير موجود.');break;
 case 'filter':if(kind!=='logs'||typeof action.filters!=='object'||!action.filters)throw Error('مرشح غير صالح.');s.filters=Object.fromEntries(Object.entries(action.filters as Record<string,unknown>).filter(([k,v])=>['search','type','user','host','ip','severity','from','to'].includes(k)&&typeof v==='string'&&v.length<=100)) as Record<string,string>;s.filtered=Object.values(s.filters).some(Boolean);message=`عرض ${filterLogs(s.filters).length} أحداث. افحص النمط قبل جمع الأدلة.`;break;
 case 'mark':if(kind==='logs'&&s.filtered&&filterLogs(s.filters).some(e=>e.id===key))s.evidence=uniq(s.evidence,key);else if(kind==='email'&&key==='E03'&&['replyTo','headers'].includes(value)&&s.visited.includes(key+':'+value))s.evidence=uniq(s.evidence,key+':'+value);else throw Error('افحص الدليل في السياق أولًا.');break;
 case 'log-auth':{if(kind!=='logs')throw Error('إجراء غير مدعوم.');const marked=s.evidence.map(id=>logEvents.find(e=>e.id===id)).filter(Boolean);if(!s.filtered||!marked.some(e=>e?.result==='fail'&&e.ip==='198.51.100.24')||!marked.some(e=>e?.result==='success'&&e.ip==='198.51.100.24')||normal(clean(action.ip))!=='198.51.100.24'||normal(clean(action.user))!=='admin'){s.mistakes++;message='قارن فشل الدخول ونجاحه من المصدر والحساب نفسيهما ثم أعد المحاولة.';}else{s.logAuthSolved=true;message='صحيح: سلسلة الفشل والنجاح تشير إلى الحساب admin من 198.51.100.24. انتقل إلى أحداث الجهاز.';}break;}
 case 'correlate':{if(kind!=='logs'||!s.logAuthSolved)throw Error('أنهِ تحقيق الهوية أولًا.');const c=logInvestigations[(s.logSolved||[]).length];if(!c||c.id!==key)throw Error('افتح التحقيق الحالي.');if(!c.required.every(id=>s.evidence.includes(id))){s.mistakes++;message='اجمع الأحداث المترابطة من أنواع سجلات مختلفة قبل القرار.';break;}if(normal(clean(action.host))!==normal(c.host)||normal(clean(action.indicator))!==normal(c.indicator)||value!==c.decision){s.mistakes++;message=c.id==='endpoint-chain'?'افحص توقيع العملية الأم والابن؛ توقيع العملية وحده لا يكفي.':'اربط PID 430 بالجهاز والوجهة، وقارنه باتصالات النسخ المعتمدة.';break;}s.logSolved=uniq(s.logSolved||[],c.id);message=c.feedback;break;}
 case 'network-view':{if(kind!=='network'||s.networkFixed.length!==networkCases.length)throw Error('أكمل فحص أجهزة المكتب أولًا.');const c=networkInvestigations[(s.networkSolved||[]).length];if(!c||c.id!==key||!['device','gateway','route'].includes(value))throw Error('اختر فحصًا متاحًا.');s.visited=uniq(s.visited,`${key}:${value}`);message=c.views[value as keyof typeof c.views];break;}
 case 'transport':{if(kind!=='network'||s.networkFixed.length!==networkCases.length)throw Error('أكمل أجهزة المكتب أولًا.');const c=transportScenarios[(s.transportSolved||[]).length];if(!c||c.id!==key)throw Error('افتح سياق النقل الحالي.');if(!s.visited.includes(`${key}:trace`))throw Error('افحص أثر الفقد أو التأخير قبل اتخاذ القرار.');if(value!==c.expected){s.mistakes++;message=`هذا الاختيار لا يحقق متطلبات التطبيق. ${c.impact}`;break;}s.transportSolved=uniq(s.transportSolved||[],key);message=c.impact;break;}
 case 'transport-trace':{if(kind!=='network'||s.networkFixed.length!==networkCases.length||transportScenarios[(s.transportSolved||[]).length]?.id!==key)throw Error('اختر التطبيق الحالي.');s.visited=uniq(s.visited,`${key}:trace`);message=transportScenarios.find(c=>c.id===key)!.trace;break;}
 case 'network-resolve':{if(kind!=='network'||(s.transportSolved||[]).length!==transportScenarios.length)throw Error('أكمل قرارات النقل أولًا.');const c=networkInvestigations[(s.networkSolved||[]).length];if(!c||c.id!==key)throw Error('افتح التدفق الحالي.');if(!['device','gateway','route'].every(view=>s.visited.includes(`${key}:${view}`)))throw Error('افحص الجهاز والبوابة وجدول المسارات قبل الاستنتاج.');if(normal(clean(action.answer))!==normal(c.answer)||value!==c.reason){s.mistakes++;message='راجع القيم الفعلية للمنفذ والعنوان ومسار الرد؛ لا يكفي نجاح البوابة لتأكيد بقية الطريق.';break;}s.networkSolved=uniq(s.networkSolved||[],key);message=c.feedback;break;}
 case 'command':if(kind!=='terminal')throw Error('الأمر غير متاح لهذا المختبر.');{const input=clean(action.input,160);if(!input)throw Error('اكتب أمرًا.');const output=executeTerminal(s,input);s.terminal=[...s.terminal,{input,output}].slice(-30);message=output;break;}
 case 'classify':if(kind!=='email'||!emails.some(e=>e.id===key)||!['legitimate','suspicious','phishing'].includes(value)||!s.visited.includes(key+':headers')||!s.visited.includes(key+':url'))throw Error('افحص الترويسة والرابط قبل التصنيف.');s.verdicts[key]=value;break;
 case 'test':if(kind!=='network'||networkCases[s.networkIndex]?.id!==key)throw Error('اختر الجهاز الحالي.');if(!s.networkInspected)throw Error('افحص إعدادات الجهاز أولًا.');{const c=networkCases[s.networkIndex];const fixed=s.networkConfig?.[c.fix.field]===c.fix.value;if(!s.networkTestedBefore){s.networkTestedBefore=true;s.networkOutput=`${c.host} → ${c.target}: فشل الاتصال في المحاكاة. افحص الإعدادات.`;}else if(fixed){s.networkOutput=`${c.host} → ${c.target}: نجاح الاتصال بعد الإصلاح.`;s.networkFixed=uniq(s.networkFixed,c.id);s.networkIndex++;s.networkConfig=null;s.networkInspected=false;s.networkTestedBefore=false;}else s.networkOutput=`${c.host} → ${c.target}: ما زال الاتصال يفشل. أعد فحص الإعدادات.`;message=s.networkOutput;break;}
 case 'configure':if(kind!=='network'||networkCases[s.networkIndex]?.id!==key||!s.networkTestedBefore)throw Error('افحص الجهاز واختبر الاتصال قبل التعديل.');{const field=clean(action.field,30);if(!['ip','gateway','dns','dhcp','port'].includes(field)||!/^([0-9.]{1,15}|on|off|-)$/.test(value))throw Error('قيمة إعداد غير صالحة.');s.networkConfig={...networkCases[s.networkIndex].initial,...(s.networkConfig||{}),[field]:value};message='طُبق التعديل على الجهاز الوهمي. أعد اختبار الاتصال.';break;}
 case 'submit':submitted=true;s.attempts++;s.lastResult=grade(lab,s,action);if(!s.lastResult.passed)s.mistakes++;message=s.lastResult.passed?'أنجزت المختبر وحُفظ أفضل تقييم.':'لم تكتمل شروط المختبر؛ راجع الملاحظات.';break;
 default:throw Error('إجراء غير مدعوم.');
 }
 return {session:s,message,submitted};
}
export function progressOf(lab:InteractiveLab,s:LabSession){if(s.lastResult?.passed)return 100;if(isMinimumAssessment(lab.id))return Math.max(0,(lab.id===surfaceId?surfaceSteps:sessionSteps).findIndex(x=>x===(s.minimum?.step||'scope')))*12;if(lab.id===offensivePilot.id)return Math.max(0,assessmentSteps.indexOf(s.assessment?.step||'authorize'))*12;switch(lab.kind){case 'terminal':{const steps=(terminalScenarioById(s.terminalScenarioId||'audit')||terminalScenarios[0]).requiredSteps;return Math.round(steps.filter(v=>s.visited.includes(v)).length*80/steps.length)}case 'logs':return Math.min(95,(s.logAuthSolved?35:s.filtered?15:0)+(s.logSolved||[]).length*30);case 'email':return Math.min(90,(s.visited.length+s.evidence.length+Object.keys(s.verdicts).length)*6);case 'network':return Math.min(95,s.networkFixed.length*8+(s.transportSolved||[]).length*6+(s.networkSolved||[]).length*8);case 'http':return s.visited.length*20;}}
export function isInteractiveLab(id:string){return !!interactiveLabById(id)}
