import {defensiveBoards} from './soc-expansion';
import {nexaCorp,resolveCompanyEntity,type EntityRef} from './nexacorp';
import {socAlertById} from './soc-alerts';
import {bossMissions} from './boss-missions';
import {firstSignal} from './campaigns';

export type BoardNodeKind='employee'|'account'|'device'|'server'|'ip'|'email'|'process'|'file'|'connection'|'alert'|'log'|'evidence';
export type RelationshipType='USES'|'LOGGED_IN_TO'|'CONNECTED_TO'|'SPAWNED'|'SENT'|'RECEIVED'|'OBSERVED_IN'|'RELATED_TO';
export type EvidenceRole='required'|'supporting'|'distractor'|'unclassified';
export type BoardNode={id:string;kind:BoardNodeKind;label:string;detail?:string;companyRef?:EntityRef};
export type BoardEvidence={id:string;type:'log'|'email'|'file'|'process'|'network'|'account'|'other';title:string;source:string;timestamp:string;raw:string;role:EvidenceRole;entities:string[]};
export type BoardLink={fromId:string;relation:RelationshipType;toId:string};
export type BoardDefinition={id:string;title:string;subtitle:string;sourceHref:string;sourceKind:'soc'|'boss'|'campaign'|'dynamic';sourceId:string;nodes:BoardNode[];evidence:BoardEvidence[];hypotheses:{id:string;label:string}[];actions:{id:string;label:string}[];expected:{hypothesis:string;actions:string[];affected:string[];requiredLinks?:BoardLink[];requiredEvidenceIds?:string[]};allowedLinks?:BoardLink[]};
export type BoardDecision={hypothesis:string;affected:string[];evidenceIds:string[];action:string};
const node=(kind:BoardNodeKind,id:string,label:string,detail?:string,companyRef?:EntityRef):BoardNode=>({id:`${kind}:${id}`,kind,label,detail,companyRef});
const core=[node('employee','layla','ليلى حداد','المالية',{kind:'employee',id:'layla'}),node('account','layla','layla','حساب ليلى',{kind:'account',id:'layla'}),node('device','WKST-02','WKST-02','جهاز ليلى في سجلات المكتب · 192.0.2.42؛ لا يثبت أنه جهاز الجلسة المريبة.',{kind:'device',id:'WKST-02'}),node('server','IDP-01','IDP-01','خدمة الهوية',{kind:'device',id:'IDP-01'}),node('ip','198.51.100.77','198.51.100.77','مصدر الجلسة غير المعتادة؛ ليس عنوان WKST-02.'),node('alert','SOC-002','SOC-002','Impossible travel login'),node('email','phishing','رسالة التحقق','مصدر محاكاة لا يُفتح خارج التطبيق.'),node('connection','unfamiliar-session','جلسة متصفح غير معروف','جلسة حساب ليلى من 198.51.100.77')];
const evidenceNodes=(ids:string[])=>ids.map(id=>node('evidence',id,id));
const soc=socAlertById('SOC-002')!;
const boss=bossMissions.find(m=>m.id==='boss-002')!;
const campaignTimes:Record<string,string>={'network-settings':'08:42','email-domains':'10:16','admin-ip':'13:12','layla-session':'10:41','service-owner':'20:34','soc-trace':'02:51'};
export const investigationBoards:BoardDefinition[]=[
 ...defensiveBoards,
 {id:'soc-SOC-002',title:'تحقيق جلسة ليلى',subtitle:'SOC-002 · ربط حساب الموظفة وجلسة الهوية وتنبيه المصادقة.',sourceHref:'/soc/alerts/SOC-002',sourceKind:'soc',sourceId:'SOC-002',
  nodes:[...core,node('log','soc-sessions','سجل الجلسات'),node('log','soc-device','أحداث الجهاز'),...evidenceNodes(soc.evidence.map(e=>e.id))],
  evidence:soc.evidence.map(e=>({id:e.id,type:e.kind==='auth'?'account':e.kind==='endpoint'?'process':e.kind==='email'?'email':'other',title:e.title,source:`SOC-002 · ${e.kind}`,timestamp:`2026-09-24T${e.time}:00Z`,raw:e.content,role:e.id==='email'?'supporting':'required',entities:e.id==='sessions'?['account:layla','ip:198.51.100.77','log:soc-sessions','alert:SOC-002']:e.id==='device'?['server:IDP-01','log:soc-device','connection:unfamiliar-session']:['email:phishing','account:layla']})),
  hypotheses:[{id:'compromised',label:'جلسة غير مألوفة عقب تفاعل البريد وتحتاج احتواء'},{id:'normal',label:'جلسة الموظفة المعتادة دون مؤشرات إضافية'},{id:'uncertain',label:'المؤشرات غير كافية بعد للحسم'}],actions:[{id:'contain',label:'إنهاء الجلسة والتحقق من الحساب'},{id:'escalate',label:'تصعيد لفريق الاستجابة'},{id:'monitor',label:'توثيق ومراقبة'}],expected:{hypothesis:'compromised',actions:['contain','escalate'],affected:['account:layla']}},
 {id:'boss-boss-002',title:'تحقيق رسالة التصيد',subtitle:'The Phishing Incident · الترويسة ونشاط ليلى والدخول غير المعتاد.',sourceHref:'/bosses/boss-002',sourceKind:'boss',sourceId:'boss-002',
  nodes:[...core,node('device','HR-07','HR-07','جهاز ظهر في لقطة Boss-002؛ لا تساوه تلقائيًا بـWKST-02.'),node('process','browser','عملية المتصفح','فتح رابط الرسالة في المحاكاة'),node('log','boss-auth','سجل المصادقة'),node('file','response-plan','خطة الاستجابة'),...evidenceNodes(boss.evidence.map(e=>e.id))],
  evidence:boss.evidence.map(e=>({id:e.id,type:e.id==='email'?'email':e.id==='auth-log'?'account':e.id==='activity'?'log':'file',title:e.title,source:`boss-002 · ${e.id}`,timestamp:`2026-09-24T${e.occurredAt}:00Z`,raw:e.content,role:e.id==='email'||e.id==='auth-log'?'required':'supporting',entities:e.id==='email'?['email:phishing','account:layla']:e.id==='activity'?['employee:layla','device:HR-07']:e.id==='auth-log'?['account:layla','ip:198.51.100.77','log:boss-auth']:['file:response-plan']})),
  hypotheses:[{id:'phishing',label:'رسالة تصيد تبعها استخدام غير معتاد للحساب'},{id:'legitimate',label:'رسالة وتسجيل دخول معتادان'},{id:'uncertain',label:'نحتاج أدلة إضافية قبل الحكم'}],actions:[{id:'contain',label:'إنهاء جلسات الحساب والتحقق من بيانات الدخول'},{id:'escalate',label:'تصعيد الأدلة للأمن'},{id:'monitor',label:'توثيق ومراقبة'}],expected:{hypothesis:'phishing',actions:['contain','escalate'],affected:['account:layla']}},
 {id:'campaign-first-signal',title:'قضية ليلى في First Signal',subtitle:'ملف الحملة · مؤشرات البريد والجلسة ومحاولات admin المنفصلة.',sourceHref:'/campaigns/first-signal',sourceKind:'campaign',sourceId:'first-signal',
  nodes:[...core,node('account','admin','admin','حساب منفصل عن layla',{kind:'account',id:'admin'}),node('ip','198.51.100.24','198.51.100.24','مصدر محاولات admin، ليس مصدر جلسة ليلى.'),...evidenceNodes(firstSignal.evidence.map(e=>e.id))],
  evidence:firstSignal.evidence.map(e=>({id:e.id,type:e.id==='email-domains'?'email':e.id==='layla-session'||e.id==='admin-ip'?'account':'other',title:e.title,source:`First Signal · ${e.sourceMission}`,timestamp:`2026-09-24T${campaignTimes[e.id]}:00Z`,raw:e.detail,role:e.id==='email-domains'||e.id==='layla-session'?'required':e.id==='network-settings'?'supporting':'distractor',entities:e.id==='email-domains'?['email:phishing','account:layla']:e.id==='layla-session'?['account:layla','ip:198.51.100.77']:e.id==='admin-ip'?['account:admin','ip:198.51.100.24']:[]})),
  hypotheses:[{id:'distinct',label:'جلسة ليلى ومحاولات admin مؤشران منفصلان يحتاجان تقييمًا مستقلًا'},{id:'same-source',label:'العنوان نفسه تسبب في الحادثين'},{id:'uncertain',label:'العلاقة بين المؤشرات غير محسومة'}],actions:[{id:'escalate',label:'تصعيد سياق جلسة ليلى مع إبقاء المؤشرين منفصلين'},{id:'contain',label:'احتواء حساب ليلى بناء على تحقيق الجلسة'},{id:'monitor',label:'توثيق المؤشرات ومراقبتها'}],expected:{hypothesis:'distinct',actions:['escalate','contain'],affected:['account:layla']}}
];
export const investigationBoardById=(id:string)=>investigationBoards.find(b=>b.id===id);
export {relationshipTypes,relationshipLabels} from './investigation-relationships';
const allowed:Record<RelationshipType,[BoardNodeKind[],BoardNodeKind[]]>={
 USES:[['employee','account'],['device','server','account']],LOGGED_IN_TO:[['account'],['device','server']],CONNECTED_TO:[['device','server','process','connection'],['ip','device','server','connection']],SPAWNED:[['process'],['process']],SENT:[['account','employee','email'],['email','account','ip']],RECEIVED:[['account','employee'],['email']],OBSERVED_IN:[['employee','account','device','server','ip','email','process','file','connection'],['alert','log','evidence']],RELATED_TO:[['employee','account','device','server','ip','email','process','file','connection','alert','log','evidence'],['employee','account','device','server','ip','email','process','file','connection','alert','log','evidence']]
};
export function validRelationship(board:BoardDefinition,fromId:string,relation:RelationshipType,toId:string){const from=board.nodes.find(n=>n.id===fromId),to=board.nodes.find(n=>n.id===toId);return !!from&&!!to&&fromId!==toId&&!!allowed[relation]?.[0].includes(from.kind)&&!!allowed[relation]?.[1].includes(to.kind)&&(!board.allowedLinks||board.allowedLinks.some(l=>l.fromId===fromId&&l.toId===toId&&l.relation===relation))}
export function validBoardDefinition(board:BoardDefinition){return board.nodes.every(n=>!n.companyRef||!!resolveCompanyEntity(n.companyRef))&&board.evidence.every(e=>e.entities.every(id=>board.nodes.some(n=>n.id===id))&&board.nodes.some(n=>n.id==='evidence:'+e.id))&&new Set(board.nodes.map(n=>n.id)).size===board.nodes.length&&new Set(board.evidence.map(e=>e.id)).size===board.evidence.length&&nexaCorp.id==='nexacorp'}
