import {expansionAction} from './offensive-expansion-actions';
import {freshOffensiveExtension,surfaceHypotheses,type OffensiveCaseId} from './offensive-expansion';
import {surfaceId,isMinimumAssessment,freshMinimum,surfaceServices,surfaceClasses,surfaceValidation,surfaceRetests,sessionTests,sessionHypotheses,minimumOptions,type MinimumTrace} from './offensive-minimum';
import type {LabSession,LabAction} from './interactive-lab-engine';
function surfaceTrace(id:string,patch=''):MinimumTrace{
 if(id==='policy')return {id,label:'سجل النطاق والإعداد',request:'TRAIN-METRICS / approved inventory / configuration snapshot',status:200,body:'Approved: management zone only; /metrics contains training operational data.\nObserved setting: allow_zone=all\nPortal 443: approved for external training zone.\nAdmin 22: management zone only.'};
 if(id==='portal')return {id,label:'بوابة التدريب',request:'External simulated zone → TRAIN-PORTAL:443 /login',status:patch==='close'?503:200,body:patch==='close'?'Portal unavailable':'Training login page; no account data'};
 if(id==='external'||id==='internal'){const denied=patch==='close'||id==='external'&&patch==='restrict';return {id,label:id==='external'?'منطقة خارجية محاكية':'منطقة إدارة داخلية محاكية',request:(id==='external'?'External':'Management')+' simulated zone → TRAIN-METRICS:8080 /metrics',status:denied?403:200,body:denied?'Denied by simulated zone policy':'queue=4; worker=training-only; build=simulated; no credentials'};}
 throw Error('الفحص خارج نطاق التدريب.');
}
function sessionTrace(id:string,patch=''):MinimumTrace{const allowed=id==='current'||id==='old'&&patch!=='revoke';return {id,label:sessionTests.find(t=>t.id===id)?.label||id,request:'GET /training/my-profile\nSimulated Sara session: '+(id==='old'?'A (logout already requested)':id==='current'?'B (new login)':'none'),status:allowed?200:401,body:allowed?'owner=sara; display=training-profile; role=employee; no other account resources':'Session not accepted; login required'};}
export function applyMinimum(id:string,old:LabSession,action:LabAction){
 if(!isMinimumAssessment(id))throw Error('تقييم غير معروف.');
 if(['url','ip','domain','target','input','credentials'].some(k=>k in action))throw Error('لا تقبل المحاكاة أهدافًا أو بيانات دخول أو أوامر خارج نطاقها.');
 const s=structuredClone(old),p=s.minimum||freshMinimum();s.minimum=p;const surface=id===surfaceId,options=surface?minimumOptions.surface:minimumOptions.session;let submitted=false;const key=typeof action.key==='string'?action.key:'';
 const expect=(...steps:string[])=>{if(!steps.includes(p.step))throw Error('أكمل خطوة التقييم الحالية أولًا.');};
 const listed=(items:readonly {id:string}[])=>{if(!items.some(x=>x.id===key))throw Error('اختر عنصرًا من النطاق المحاكى.');};
 const add=(t:MinimumTrace)=>{if(!p.observations.some(x=>x.id===t.id))p.observations.push(t)};
 const fail=(msg:string)=>{p.feedback=msg;s.mistakes++;};
 const tests=surface?surfaceValidation:sessionTests;
 const expanded=expansionAction(id as OffensiveCaseId,s,action);if(expanded!==null)return {session:s,submitted:false,message:expanded};
 if(s.lastResult?.passed&&action.action!=='replay')throw Error('ابدأ إعادة التقييم قبل محاولة جديدة.');
 switch(action.action){
 case 'replay':if(!s.lastResult?.passed)throw Error('أكمل التقييم قبل إعادته.');s.minimum=freshMinimum();if(s.offensive)s.offensive=freshOffensiveExtension();s.visited=[];s.evidence=[];s.mistakes=0;s.hintsUsed=0;s.lastResult=null;return {session:s,submitted:false,message:'بدأت إعادة المحاكاة نفسها دون مكافأة جديدة.'};
 case 'authorize':expect('scope');if(action.accepted!==true)throw Error('راجع التفويض والنطاق أولًا.');p.authorized=true;p.step=surface?'recon':'login';break;
 case 'inspect':if(!surface)throw Error('الفحص غير متاح.');expect('recon');listed(surfaceServices);if(!p.inspected.includes(key))p.inspected.push(key);break;
 case 'classify-start':if(!surface)throw Error('إجراء غير متاح.');expect('recon');if(p.inspected.length!==surfaceServices.length)throw Error('افحص الأصول الثلاثة قبل المقارنة.');p.step='classify';break;
 case 'classify':if(!surface)throw Error('إجراء غير متاح.');expect('classify');listed(surfaceServices);if(!surfaceClasses.some(x=>x.id===action.value))throw Error('تصنيف غير صالح.');p.classifications[key]=action.value as string;break;
 case 'prioritize':if(!surface)throw Error('إجراء غير متاح.');expect('classify');if(!surfaceServices.every(x=>p.classifications[x.id]))throw Error('صنّف كل أصل أولًا.');if(p.classifications.portal!=='present'||p.classifications.admin!=='present'||p.classifications.metrics!=='review'){fail('رد صفحة الدخول لا يعرض بيانات حساب؛ والمنفذ 22 مرفوض من المنطقة الخارجية. رد /metrics يعرض بيانات تشغيل، لكنك لم تقارنه بعد بالسياسة والإعداد. ما حدود الدليل الآن؟');break;}p.feedback='';p.step='prioritize';break;
 case 'priority':if(!surface)throw Error('إجراء غير متاح.');expect('prioritize');listed(surfaceServices);p.priority=key;if(key!=='metrics'){fail(key==='portal'?'استجابة البوابة صفحة دخول فقط. قارِنها بالأصل الذي أعاد بيانات تشغيل قبل ترتيب أولوية التحقق.':'خدمة الإدارة مرفوضة من المنطقة الخارجية. أي أصل آخر أعاد محتوى يحتاج مراجعة؟');break;}p.step='validate';p.feedback='';break;
 case 'login':if(surface)throw Error('إجراء غير متاح.');expect('login');if(p.phase!=='none')throw Error('الجلسة التدريبية بدأت بالفعل.');p.phase='a';add({id:'login',label:'تسجيل دخول محاكى لسارة',request:'Predefined training identity Sara → Login',status:200,body:'Session A created; browser attached A; GET own profile: 200'});p.step='observe';break;
 case 'logout':if(surface)throw Error('إجراء غير متاح.');expect('observe');if(p.phase!=='a')throw Error('قارن حالة الجلسة الحالية.');p.phase='out';add({id:'logout',label:'تسجيل الخروج في التطبيق التدريبي',request:'POST /training/logout (session A)',status:200,body:'Browser removed A; UI: signed out; subsequent browser request without session: 401. Policy: logout must end the previous session.'});break;
 case 'login-again':if(surface)throw Error('إجراء غير متاح.');expect('observe');if(p.phase!=='out')throw Error('افحص الخروج قبل الدخول الجديد.');p.phase='b';add({id:'new-login',label:'تسجيل دخول جديد',request:'Predefined training identity Sara → Login again',status:200,body:'Session B created; browser attached B; same own profile: 200. Saved test alias A remains available for authorized comparison.'});break;
 case 'hypothesis':if(surface)throw Error('إجراء غير متاح.');expect('observe');if(p.phase!=='b')throw Error('قارن الدخول والخروج والدخول الجديد أولًا.');p.step='hypothesis';break;
 case 'choose':if(surface&&s.offensive){expect('validate');listed(surfaceHypotheses);p.hypothesis=key;p.feedback='';break;}if(surface)throw Error('إجراء غير متاح.');expect('hypothesis');listed(sessionHypotheses);p.hypothesis=key;p.feedback='';p.step='test';break;
 case 'probe':expect(surface?'validate':'test');listed(tests);add(surface?surfaceTrace(key):sessionTrace(key));break;
 case 'evaluate':expect(surface?'validate':'test');if(s.offensive){if(!tests.every(t=>s.offensive!.collected.includes(t.id)))throw Error('اجمع المقارنات الثلاث قبل اعتماد الفرضية.');if(surface&&p.hypothesis!=='zone'){fail('رد الخدمة وحده لا يثبت خللًا برمجيًا، والبوابة المقصودة متاحة أيضًا. قارِن منطقة الطلب بالسياسة والإعداد ثم أعد فرضيتك.');break;}}if(!tests.every(t=>p.observations.some(x=>x.id===t.id)))throw Error('اجمع المقارنة من المصادر الثلاثة أولًا.');if(!surface&&p.hypothesis!=='revocation'){fail(p.hypothesis==='browser'?'المتصفح أزال A وأعاد 401 دون جلسة، لكن الطلب المحفوظ باستخدام A أعاد 200. قارِن الواجهة بقرار الخادم.':'كل الطلبات تستهدف ملف سارة نفسه؛ لا يوجد طلب لمورد حساب آخر. قارِن زمن الخروج وقبول A وB والطلب بلا جلسة.');break;}if(surface)p.classifications.metrics='misconfiguration';p.feedback='';p.step='impact';break;
 case 'recheck':expect(surface?'validate':'test','impact');p.feedback='';p.step=surface?'validate':'hypothesis';break;
 case 'report':expect('impact');{const r=action.report as typeof p.report|undefined;if(!r||!options.findings.some(x=>x.id===r.finding)||!options.impacts.some(x=>x.id===r.impact)||!Array.isArray(r.evidence)||r.evidence.some(x=>typeof x!=='string'||!tests.some(t=>t.id===x))||new Set(r.evidence).size!==r.evidence.length)throw Error('اختر أثرًا واستنتاجًا وأدلة صحيحة دون تكرار.');p.report={finding:r.finding,impact:r.impact,evidence:[...r.evidence]};if(r.finding!==(surface?'config':'revocation')||r.impact!==(surface?'metadata':'continued')){fail(surface?'الدليل يقارن سياسة التعرّض بإعداد وردّ خدمة القياس. لم تثبت ثغرة برمجية أو سيطرة على جهاز.':'الطلب أعاد بيانات سارة بجلسة سارة السابقة؛ لا دليل على كلمة مرور أو صلاحيات إدارة أو مورد حساب آخر.');break;}if(!tests.every(t=>r.evidence.includes(t.id))){fail('الاستنتاج يحتاج المقارنة كاملة؛ دليل واحد لا يميز التفسير عن البدائل.');break;}p.feedback='';p.step='remediation';break;}
 case 'patch':expect('remediation');listed(options.fixes);p.patch=key;p.retests=[];p.feedback='';break;
 case 'retest':expect('remediation');listed(surface?surfaceRetests:sessionTests);if(!p.patch)throw Error('اختر المعالجة قبل إعادة الاختبار.');if(!p.retests.some(t=>t.id===key))p.retests.push(surface?surfaceTrace(key,p.patch):sessionTrace(key,p.patch));break;
 case 'submit':expect('remediation');submitted=true;s.attempts++;if(p.patch!==(surface?'restrict':'revoke')||!(surface?surfaceRetests:sessionTests).every(t=>p.retests.some(x=>x.id===t.id))){fail(surface?'قارِن الرد الخارجي والاستخدام الداخلي والبوابة بعد التغيير؛ يجب حصر التعرّض مع بقاء الوظائف المعتمدة.':'قارِن A بعد الخروج، وB الحالية، والطلب بلا جلسة؛ تغير الواجهة أو إذن الملف وحده لا يثبت انتهاء A.');s.lastResult={passed:false,score:40,feedback:[p.feedback]};break;}p.step='result';p.feedback='';s.lastResult={passed:true,score:Math.max(60,100-s.mistakes*5),feedback:[surface?'أثبتّ إعداد تعرّض مخالفًا للسياسة، دون ادعاء ثغرة من رقم منفذ.':'أثبتّ استمرار قبول الجلسة بعد الخروج بمقارنة ثلاث حالات.', 'تحققت من منع السلوك غير المقصود وبقاء الاستخدام المسموح بعد المعالجة.']};break;
 default:throw Error('إجراء غير متاح في هذا التقييم المحدود.');
 }
 s.visited=[...p.inspected];s.evidence=s.offensive?[...s.offensive.collected]:p.observations.map(x=>x.id);return {session:s,submitted,message:p.feedback||'حُفظت خطوة التقييم.'};
}
