/** Fictional NexaCorp telemetry. No command, IP, hash or URL is executed or contacted. */
export type Severity='Low'|'Medium'|'High'|'Critical';
export type Verdict='true_positive'|'false_positive'|'benign_suspicious';
export type ResponseAction='contain'|'escalate'|'monitor'|'dismiss';
export type EvidenceKind='auth'|'endpoint'|'network'|'user'|'email'|'file'|'ip';
export type SocEvidence={id:string;kind:EvidenceKind;time:string;title:string;content:string};
export type SocTool={id:string;label:string;description:string;output:string};
export type SocAlert={id:string;title:string;severity:Severity;timestamp:string;user:string;host:string;sourceIp:string;type:string;summary:string;scenario:string;evidence:SocEvidence[];tools:SocTool[];requiredEvidence:string[];truth:Verdict;responses:ResponseAction[];caseId?:string;feedback:string;skillRewards:{skill:string;points:number}[]};
export type SocCaseTemplate={id:string;title:string;description:string;severity:Severity;relatedAlertIds:string[]};

const skills={logs:[{skill:'logs',points:30},{skill:'incident',points:20}],phish:[{skill:'phishing',points:30},{skill:'incident',points:20}],fund:[{skill:'cybersecurity',points:25},{skill:'logs',points:20}],endpoint:[{skill:'incident',points:30},{skill:'cybersecurity',points:20}]} as const;
export const socAlerts:SocAlert[]=[
 {id:'SOC-001',title:'Multiple failed logins',severity:'High',timestamp:'2026-09-24T13:12:00Z',user:'admin',host:'AUTH-01',sourceIp:'198.51.100.24',type:'Authentication',summary:'محاولات دخول متكررة إلى admin خلال دقيقة واحدة.',scenario:'تلقّى فريق NexaCorp تنبيهًا من بوابة الهوية. حدد هل نمط الفشل يستحق التصعيد بعد مراجعة السجلات ونشاط الحساب.',truth:'true_positive',responses:['escalate','contain'],caseId:'case-admin',requiredEvidence:['auth','owner'],skillRewards:[...skills.logs],feedback:'ثلاث محاولات متقاربة من 198.51.100.24 على admin بلا اختبار معلن؛ هذا نشاط حقيقي يستدعي تقييد المصدر والتحقق من الحساب، لكن السجل لا يثبت نجاح دخول.',
 evidence:[{id:'auth',kind:'auth',time:'13:12',title:'Authentication Logs',content:'13:12:02 admin · 198.51.100.24 · failed\n13:12:15 admin · 198.51.100.24 · failed\n13:12:38 admin · 198.51.100.24 · failed\n13:12:52 user1 · 203.0.113.18 · success'}, {id:'owner',kind:'user',time:'13:14',title:'تأكيد مالك الحساب',content:'آدم، مسؤول الأنظمة: لا يوجد اختبار دخول مصرح به على admin بين 13:00 و13:20.'},{id:'network',kind:'ip',time:'13:16',title:'IP inspection',content:'198.51.100.24 عنوان تدريب خارجي في هذه المحاكاة؛ ظهر في ثلاث محاولات فاشلة فقط، ولا يوجد نجاح مثبت.'}],
 tools:[{id:'failures',label:'Log Viewer · عرض الفشل',description:'ترشيح فشل الدخول من السجل.',output:'admin / 198.51.100.24 → 3 failed within 50 seconds\nuser1 / 203.0.113.18 → 0 failed'}, {id:'correlate',label:'ربط نشاط الحساب',description:'قارن التنبيه بنشاط admin.',output:'admin: 3 failed · 0 successful sessions in alert window · no approved test.'}]},
 {id:'SOC-002',title:'Impossible travel login',severity:'Critical',timestamp:'2026-09-24T10:41:00Z',user:'layla',host:'IDP-01',sourceIp:'198.51.100.77',type:'Identity',summary:'جلسة ليلى الجديدة ظهرت بعد موقع مختلف خلال دقائق.',scenario:'الحساب ظهر في تحقيق The Phishing Incident. راجع توقيت الجلسات، ومعلومات الجهاز، وتقاطعها مع بلاغ البريد قبل اتخاذ قرار.',truth:'true_positive',responses:['contain','escalate'],caseId:'case-layla',requiredEvidence:['sessions','device'],skillRewards:[...skills.logs],feedback:'جلسة 198.51.100.77 على جهاز غير معروف تلت تفاعل البريد. اعزل الجلسة وحقق في الحساب؛ اختلاف المواقع وحده لا يكفي دون قرائن الجهاز والتوقيت.',
 evidence:[{id:'sessions',kind:'auth',time:'10:41',title:'Authentication Logs',content:'10:36 layla · office workstation · 192.0.2.31 · success\n10:41 layla · unfamiliar browser · 198.51.100.77 · success\nSession overlap: 4 min'}, {id:'device',kind:'endpoint',time:'10:42',title:'Endpoint Events',content:'IDP-01: new browser fingerprint for layla. No registered device record for second session.'},{id:'email',kind:'email',time:'10:16',title:'Email information',content:'بلاغ سابق: Return-Path verify@account-review.example، وجهة login-check.example. رسالة التحقيق الموسع تعرض cyberlab-help.example؛ لا تفترض أن النطاقين واحد.'}],
 tools:[{id:'timeline',label:'ربط الجلسات زمنيًا',description:'قارن البصمات والوقت.',output:'10:16 mail report → 10:36 office session → 10:41 unknown browser session · overlapping identities'}, {id:'ip',label:'IP inspection',description:'افحص المصدرين في المحاكاة.',output:'192.0.2.31: office test network; 198.51.100.77: external test range, unfamiliar for layla.'}]},
 {id:'SOC-003',title:'Suspicious PowerShell',severity:'Medium',timestamp:'2026-09-24T15:25:00Z',user:'adam',host:'WIN-07',sourceIp:'192.0.2.48',type:'Endpoint',summary:'PowerShell بوسيط مشفّر شغّله مسؤول الأنظمة.',scenario:'سطر الأمر مثير للريبة. راجع توقيع السكربت وتذكرة التغيير وسلسلة التنفيذ قبل الحكم على النية.',truth:'benign_suspicious',responses:['monitor'],requiredEvidence:['process','change'],skillRewards:[...skills.endpoint],feedback:'السلوك يستحق المراجعة، لكن السكربت موقع ويرتبط بتذكرة تحديث مصرح بها. لا يوجد دليل كافٍ على اختراق؛ وثّق وراقب بدل عزل الجهاز.',
 evidence:[{id:'process',kind:'endpoint',time:'15:25',title:'Process tree',content:'WIN-07 · adam · powershell.exe -EncodedCommand [simulated payload]\nParent: approved updater.exe · signature: NexaCorp IT valid'}, {id:'change',kind:'user',time:'15:20',title:'Change ticket',content:'CHG-184 · نافذة تحديث عميل الأجهزة 15:20–16:00 · معتمد من آدم · 14 جهازًا.'},{id:'network',kind:'network',time:'15:27',title:'Network Events',content:'WIN-07 → internal update server 192.0.2.20 only. No external destinations observed.'}],
 tools:[{id:'decode',label:'فك ملخص الأمر',description:'عرض معنى الحمولة الوهمية فقط.',output:'Simulated decoded action: install signed endpoint-agent update. No execution.'},{id:'fleet',label:'مقارنة الأجهزة',description:'قارن مع بقية أسطول التحديث.',output:'14 managed hosts ran the same signed update in approved window.'}]},
 {id:'SOC-004',title:'Malware detection on APP-02',severity:'Critical',timestamp:'2026-09-25T02:51:00Z',user:'maya',host:'APP-02',sourceIp:'203.0.113.86',type:'Malware',summary:'رُصد ملف خبيث تدريبي على خادم التطبيق.',scenario:'تنبيه Endpoint ضمن التحقيق الليلي. تأكد من حالة الملف والأثر على APP-02 قبل اختيار الاحتواء أو التصعيد.',truth:'true_positive',responses:['contain','escalate'],caseId:'case-midnight',requiredEvidence:['hash','process'],skillRewards:[...skills.endpoint],feedback:'بصمة الملف التدريبية مع عملية غير مصرح بها وارتباط جلسة maya تشير إلى حادث حقيقي. الحجر على الملف وحده لا يغلق احتمال نشاط الحساب أو الاتصال الخارجي.',
 evidence:[{id:'hash',kind:'file',time:'02:51',title:'File hash and verdict',content:'Path: /tmp/agent-update.bin (simulation)\nSHA-256: 9d5f8c4216b0e7a324a199cb025fe66d41a8b297c03e6f104a12b59c79d4860\nVerdict: malicious training signature · file quarantined'}, {id:'process',kind:'endpoint',time:'02:48',title:'Endpoint Events',content:'APP-02 · unexpected process launched from /tmp by maya session. Child attempted access to service config.'},{id:'auth',kind:'auth',time:'02:37',title:'Login Logs',content:'maya · 203.0.113.86 · unusual successful login to APP-02 at 02:37.'}],
 tools:[{id:'process-tree',label:'Host activity',description:'أظهر سلسلة العمليات.',output:'login maya → /tmp/agent-update.bin → config access attempt · isolated sample'}, {id:'correlation',label:'تنبيهات مترابطة',description:'قارن تنبيه الملفات بالشبكة.',output:'SOC-005: unusual outbound traffic from APP-02 at 02:53. Investigate both in the same case.'}]},
 {id:'SOC-005',title:'Unusual outbound traffic',severity:'Critical',timestamp:'2026-09-25T02:53:00Z',user:'maya',host:'APP-02',sourceIp:'203.0.113.86',type:'Network',summary:'اتصالات خارجية متكررة من APP-02 بعد تنبيه Endpoint.',scenario:'افصل بين حركة الخدمة الاعتيادية والاتصال المريب باستخدام NetFlow وسلسلة العمليات.',truth:'true_positive',responses:['contain','escalate'],caseId:'case-midnight',requiredEvidence:['flow','process'],skillRewards:[...skills.logs],feedback:'أرسل APP-02 اتصالات دورية غير مبررة بعد تشغيل العملية غير المصرح بها. اربط النشاط بـSOC-004 واحتوِ المضيف أو صعّد القضية.',
 evidence:[{id:'flow',kind:'network',time:'02:53',title:'Network Events',content:'APP-02 → 203.0.113.86 · 02:53, 02:55, 02:57 · 32 KB each\nBaseline: no outbound connections to this source in prior 24 h.'},{id:'process',kind:'endpoint',time:'02:52',title:'Process correlation',content:'Socket owner: simulated /tmp/agent-update.bin · alert SOC-004. No approved job associated.'},{id:'file',kind:'file',time:'02:56',title:'File access',content:'FILE-01 was referenced in the midnight investigation. NetFlow alone does not prove file exfiltration; no file contents are transmitted in this simulation.'}],
 tools:[{id:'baseline',label:'Network baseline',description:'قارن الوجهة بالنمط السابق.',output:'203.0.113.86: first seen at 02:53 · three periodic flows · not in approved destinations.'},{id:'correlate',label:'Host activity',description:'اربط المنفذ بسلسلة العملية.',output:'Process owner: /tmp/agent-update.bin · simulated malicious signature · host APP-02.'}]},
 {id:'SOC-006',title:'Phishing report from Finance',severity:'High',timestamp:'2026-09-24T10:16:00Z',user:'layla',host:'MAIL-01',sourceIp:'192.0.2.38',type:'Email',summary:'أبلغت ليلى عن رسالة تحقق غير معتادة.',scenario:'افحص نطاق الرد والرابط والتفاعل مع الرسالة. قد يقترن هذا التنبيه بجلسة غير مألوفة لنفس الحساب.',truth:'true_positive',responses:['contain','escalate'],caseId:'case-layla',requiredEvidence:['headers','interaction'],skillRewards:[...skills.phish],feedback:'فشل SPF واختلاف Return-Path والرابط مع تفاعل ليلى يدعم تصنيف التصيّد. اربط الحالة بـSOC-002 وتحقق من الجلسة دون زيارة الرابط.',
 evidence:[{id:'headers',kind:'email',time:'10:16',title:'Email headers',content:'From: support@cyberlab.example\nReturn-Path: verify@account-review.example\nSPF: fail · DKIM: none\nDisplay link: account review → login-check.example (fictional)'},{id:'interaction',kind:'user',time:'10:41',title:'User activity',content:'ليلى فتحت رسالة التدريب، ثم سُجلت جلسة جديدة من 198.51.100.77. لا تعرض الرسالة أي رمز حقيقي.'},{id:'ip',kind:'ip',time:'10:42',title:'IP information',content:'198.51.100.77 نطاق توثيقي في المحاكاة، وليس وجهة حية. ظهر في SOC-002 أيضًا.'}],
 tools:[{id:'headers',label:'تحليل الترويسة',description:'قارن العنوان الظاهر بالمصدر.',output:'Return-Path differs from visible From; SPF fail; DKIM absent.'},{id:'correlate',label:'ربط هوية المستخدم',description:'تحقق من الجلسة اللاحقة.',output:'10:16 email → 10:41 unfamiliar login SOC-002 · same user layla.'}]},
 {id:'SOC-007',title:'New administrator account',severity:'High',timestamp:'2026-09-24T16:03:00Z',user:'adam',host:'DC-01',sourceIp:'192.0.2.12',type:'Identity',summary:'أُنشئ حساب بصلاحيات مرتفعة خلال نافذة التغيير.',scenario:'تغيير الصلاحيات عالي الحساسية. تحقق من الطلب والموافقة ومنشئ الحساب قبل افتراض الاختراق.',truth:'false_positive',responses:['dismiss'],requiredEvidence:['audit','ticket'],skillRewards:[...skills.fund],feedback:'الحساب المؤقت موثق في تغيير معتمد وبصلاحية انتهاء محددة ومنشئ معروف. أغلق التنبيه كإنذار كاذب موثق، مع بقاء مراجعة الصلاحيات الدورية.',
 evidence:[{id:'audit',kind:'auth',time:'16:03',title:'Directory audit',content:'Created: svc-deploy-temp · creator: adam · privilege: scoped admin · expires 18:00.'},{id:'ticket',kind:'user',time:'15:50',title:'Approved change',content:'CHG-191 · اعتماد مدير الأنظمة وSOC lead · حساب نشر مؤقت 16:00–18:00.'},{id:'network',kind:'network',time:'16:05',title:'Session locations',content:'192.0.2.12 internal deployment station · no unknown logins.'}],
 tools:[{id:'audit',label:'مراجعة الموافقة',description:'قارن التذكرة بسجل الدليل.',output:'CHG-191 matches creator adam, account svc-deploy-temp, expiry 18:00.'},{id:'permissions',label:'فحص الصلاحية',description:'تأكد من النطاق والمدة.',output:'Scoped deployment role · expires in two hours · no persistent global admin.'}]},
 {id:'SOC-008',title:'Large file transfer',severity:'High',timestamp:'2026-09-25T01:05:00Z',user:'backup',host:'FILE-01',sourceIp:'192.0.2.70',type:'Network',summary:'نقل 8 GB من FILE-01 خلال الليل.',scenario:'الحجم وحده لا يثبت تسريبًا. افحص الوجهة والجدولة ومنشأ العملية، وقارن هذا الحدث بتنبيه APP-02 المنفصل.',truth:'false_positive',responses:['dismiss'],requiredEvidence:['flow','schedule'],skillRewards:[...skills.logs],feedback:'الوجهة خادم نسخ داخلي مع جدول وتذكرة متطابقين. لا تخلط هذا النقل بإنذار APP-02 الخارجي؛ أغلقه كإنذار كاذب موثق.',
 evidence:[{id:'flow',kind:'network',time:'01:05',title:'Transfer log',content:'FILE-01 → 192.0.2.70 · 8 GB · backup protocol · internal segment.'},{id:'schedule',kind:'user',time:'01:00',title:'Backup schedule',content:'JOB-BK-12 · incremental backup daily 01:00–01:20 · approved destination 192.0.2.70.'},{id:'process',kind:'endpoint',time:'01:06',title:'Endpoint Events',content:'Signed backup-agent launched transfer; no interactive user session.'}],
 tools:[{id:'destination',label:'IP inspection',description:'حدد موقع الوجهة.',output:'192.0.2.70: internal simulated backup appliance; not 203.0.113.86.'},{id:'baseline',label:'مقارنة الحجم',description:'افحص آخر سبعة أيام.',output:'Daily 01:00 backup volumes 7.4–8.3 GB · current 8.0 GB.'}]},
 {id:'SOC-009',title:'Unknown USB device event',severity:'Medium',timestamp:'2026-09-24T19:11:00Z',user:'maya',host:'WKST-05',sourceIp:'192.0.2.145',type:'Endpoint',summary:'جهاز USB غير مألوف وُصل بمحطة عمل.',scenario:'الحدث يحتاج توثيقًا ولا يثبت تسريبًا. راجع فئة الجهاز ونشاط الملفات وصاحب الجهاز قبل الإغلاق.',truth:'benign_suspicious',responses:['monitor'],requiredEvidence:['device','files'],skillRewards:[...skills.endpoint],feedback:'الجهاز لوحة مفاتيح مؤقتة غير مسجلة، ولم يُرصد نسخ ملفات. وثّق التحقق واطلب تسجيل الجهاز ومراقبته بدل اتهام المستخدم.',
 evidence:[{id:'device',kind:'endpoint',time:'19:11',title:'USB enumeration',content:'VID/PID fictional 1234:0042 · device class HID keyboard · no mass-storage interface.'},{id:'files',kind:'file',time:'19:12',title:'File activity',content:'No removable drive mounted. No file copy events in 19:00–19:20.'},{id:'owner',kind:'user',time:'19:16',title:'Owner confirmation',content:'أبلغت مايا الدعم باستبدال لوحة مفاتيح معطلة. التذكرة لم تُغلق بعد.'}],
 tools:[{id:'usb',label:'Host activity',description:'افحص نوع الجهاز.',output:'HID keyboard only · no storage volume · no execution event.'},{id:'files',label:'File activity',description:'ابحث عن عمليات نسخ.',output:'No read/write to removable storage. Await hardware registration.'}]},
 {id:'SOC-010',title:'Scheduled task anomaly',severity:'Low',timestamp:'2026-09-24T22:00:00Z',user:'system',host:'APP-01',sourceIp:'192.0.2.21',type:'Endpoint',summary:'مهمة مجدولة شغّلت سكربتًا في غير ساعات الدوام.',scenario:'اسم المهمة يشبه نشاط الاستطلاع، لكن زمن التشغيل ثابت. تحقق من المنشئ والتوقيع وجدول التغيير.',truth:'false_positive',responses:['dismiss'],requiredEvidence:['task','change'],skillRewards:[...skills.fund],feedback:'مهمة inventory-check موقعة وتعمل يوميًا من حساب الخدمة وفق CHG-170. أغلق التنبيه كإنذار كاذب بعد توثيق الأدلة.',
 evidence:[{id:'task',kind:'endpoint',time:'22:00',title:'Task definition',content:'inventory-check · 22:00 daily · creator: system · signed /opt/nexa/inventory-check.sh'}, {id:'change',kind:'user',time:'17:00',title:'Change record',content:'CHG-170 · جرد الأصول الليلي · معتمد لمدة 30 يومًا.'},{id:'network',kind:'network',time:'22:01',title:'Network Events',content:'APP-01 → internal asset inventory 192.0.2.22 only.'}],
 tools:[{id:'history',label:'Task history',description:'قارن وقت التشغيل.',output:'Task ran at 22:00 for seven consecutive days with identical signature.'},{id:'signature',label:'توقيع السكربت',description:'تحقق من المصدر.',output:'Signed by NexaCorp IT training issuer · matches approved CHG-170.'}]}
];
export const socCases:SocCaseTemplate[]=[
 {id:'case-admin',title:'Admin authentication probing',description:'سلسلة محاولات دخول فاشلة على الحساب الإداري.',severity:'High',relatedAlertIds:['SOC-001']},
 {id:'case-layla',title:'Finance phishing incident',description:'بلاغ بريد وجلسة هوية غير مألوفة لحساب ليلى.',severity:'Critical',relatedAlertIds:['SOC-006','SOC-002']},
 {id:'case-midnight',title:'Midnight APP-02 investigation',description:'تنبيه ملف واتصال خارجي من جهاز التطبيق في نوبة SOC.',severity:'Critical',relatedAlertIds:['SOC-004','SOC-005']}
];
export function socAlertById(id:string){return socAlerts.find(a=>a.id===id)}
export function socCaseById(id:string){return socCases.find(c=>c.id===id)}
