'use client';
import {skillTitles} from '@/lib/progression';
import LoadingState from '@/components/loading-state';
import {useEffect,useState} from 'react';
import {ArrowLeft,ChartNoAxesCombined} from 'lucide-react';
import {useProgress} from '@/app/shell';
import {MasteryIntro,SkillMastery,useAdaptive} from '@/app/adaptive/overview';
export type SkillState={id:string;name:string;description:string;xp:number;level:number;progress:number;lastUpdated:string|null;contributions:{kind:'lesson'|'mission'|'boss'|'soc'|'lab';id:string;title:string;xp:number;at:string}[]};
export function useSkills(){const {user}=useProgress(),[skills,setSkills]=useState<SkillState[]>([]),[loading,setLoading]=useState(!!user),[error,setError]=useState('');
 useEffect(()=>{if(!user)return;let active=true;fetch('/api/skills',{cache:'no-store'}).then(async r=>{const result=await r.json() as {skills?:SkillState[];error?:string};if(!r.ok)throw Error(result.error||'تعذر التحميل');if(active)setSkills(result.skills||[])}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user]);return {skills,loading,error,user}}
export function SkillSummary(){const {skills,loading,error,user}=useSkills();if(!user)return null;const ranked=[...skills].sort((a,b)=>b.xp-a.xp),strong=ranked.filter(s=>s.xp>0).slice(0,3),toDevelop=[...skills].sort((a,b)=>a.xp-b.xp).slice(0,3);
 return <section className="panel skill-summary"><div className="between"><div><span className="eyebrow">المهارات والتقدم</span><h2>مهاراتك</h2></div><a href="/skills">كل المهارات <ArrowLeft size={16}/></a></div>{loading?<p role="status">جارٍ تحميل مهاراتك…</p>:error?<p role="alert">{error}</p>:<div className="skill-summary-grid"><div><h3>أقوى المهارات</h3>{strong.length?strong.map(s=><p key={s.id}>{skillTitles[s.id]||s.name} <b>{s.xp} نقطة مهارة · مستوى {s.level}</b></p>):<p>ستظهر بعد إكمال درس أو مهمة أو تحقيق SOC.</p>}</div><div><h3>مهارات تحتاج تطويرًا</h3>{toDevelop.map(s=><p key={s.id}>{skillTitles[s.id]||s.name} <b>{s.xp} نقطة مهارة</b></p>)}</div></div>}</section>}
export default function SkillsPage(){const {skills,loading,error,user}=useSkills(),adaptive=useAdaptive();return <div className="reading-width skills-page"><div className="page-heading"><div><div className="eyebrow">المهارات والإتقان</div><h1>مهاراتك</h1><p>نقاط المهارات تسجل ممارستك؛ والإتقان يقدّر جودة أدائك من نتائج التدريب.</p></div><ChartNoAxesCombined size={36}/></div>{!user?<div className="panel"><p>سجّل الدخول لعرض مهارات حسابك.</p><a className="primary-button" target="_top" href="/signin-with-chatgpt?return_to=%2Fskills">تسجيل الدخول</a></div>:loading?<LoadingState>جارٍ تحميل المهارات…</LoadingState>:error?<div role="alert" className="error"><p>{error}</p><button className="secondary-button" onClick={()=>location.reload()}>إعادة المحاولة</button></div>:<><MasteryIntro/>{adaptive.error&&<p role="alert" className="error">{adaptive.error}</p>}<div className="skill-grid">{skills.map(s=><section className="panel skill-card" key={s.id}><div className="between"><h2>{skillTitles[s.id]||s.name}</h2><strong>مستوى المهارة {s.level}</strong></div><p>{s.description}</p><div className="between"><strong>{s.xp} نقطة مهارة</strong><span>{s.progress}% للمستوى التالي</span></div><div className="mission-meter" role="progressbar" aria-label={'تقدم نقطة مهارة في '+s.name} aria-valuenow={s.progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:s.progress+'%'}}/></div>{!adaptive.error&&<SkillMastery skill={adaptive.data?.mastery.find(m=>m.id===s.id)}/>}<details><summary>الإنجازات المساهمة ({s.contributions.length})</summary>{s.contributions.length?<ul>{s.contributions.map(c=><li key={c.kind+':'+c.id}><a href={(c.kind==='lesson'?'/learn/':c.kind==='boss'?'/bosses/':c.kind==='soc'?'/soc/alerts/':c.kind==='lab'?'/labs/v2/':'/missions/')+c.id}>{c.title}</a><span>+{c.xp} · {c.kind==='lesson'?'درس':c.kind==='boss'?'مهمة مركبة':c.kind==='soc'?'تحقيق SOC':c.kind==='lab'?'مختبر عملي':'مهمة'}</span></li>)}</ul>:<p>لم تحصل على نقاط لهذه المهارة بعد.</p>}</details>{s.lastUpdated&&<small>آخر تحديث: {new Date(s.lastUpdated).toLocaleDateString('ar-SA')}</small>}</section>)}</div></>}</div>}
