'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,Terminal,Lightbulb,CheckCircle2} from 'lucide-react';
import {useProgress} from '@/app/shell';
import type {Mission} from '@/lib/missions';
import {objectiveDone,objectiveReady,type MissionAction,type MissionSession} from '@/lib/mission-engine';
import {skillName} from '@/lib/skill-catalog';
import LabBridge from '@/app/labs/v2/lab-bridge';
import CompanyContext from '@/components/company-context';
import TaskBrief from '@/components/task-brief';
import {missionBriefs} from '@/lib/practical-training';
type State={id:string;completedAt:string|null;score:number;stars:number;progress:number;session:MissionSession};
export default function BossWorkspace({mission,campaign=false}:{mission:Mission;campaign?:boolean}){
 const {user,refresh}=useProgress(),[state,setState]=useState<State|null>(null),[loading,setLoading]=useState(!!user),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[opened,setOpened]=useState(''),[command,setCommand]=useState(''),[responses,setResponses]=useState<Record<string,string>>({}),[answers,setAnswers]=useState<Record<string,string>>({});
 useEffect(()=>{if(!user)return;let active=true;fetch('/api/missions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:mission.id,action:'start'})}).then(async r=>{const data=await r.json() as {error?:string;state:State};if(!r.ok)throw Error(data.error||'تعذر فتح التحقيق.');if(active)setState(data.state)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'تعذر الاتصال.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user,mission.id]);
 async function act(action:Omit<MissionAction,'id'>){if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/missions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:mission.id,...action})});const data=await r.json() as {error?:string;state:State;message:string};if(!r.ok)throw Error(data.error||'تعذر حفظ التحقيق.');setState(data.state);setMessage(data.message);if(action.action==='solve'&&data.state.session.lastResult)await refresh();if(action.action==='replay'){setAnswers({});setResponses({});setOpened('');setCommand('')}}catch(e){setError(e instanceof Error?e.message:'تعذر الاتصال.')}finally{setBusy(false)}}
 const session=state?.session,finished=!!state?.completedAt&&!session?.replaying,report=finished?session?.lastResult?.report:undefined;
 const ready=(id:string)=>!!session&&objectiveReady(mission,session,id);
 const objectiveFor=(kind:'evidence'|'tool'|'decision',target:string)=>mission.objectives.find(o=>o.kind===kind&&o.target===target);
 function runCommand(e:React.FormEvent){e.preventDefault();const normalized=command.trim().replace(/\s+/g,' ');if(!normalized)return;void act({action:'tool',toolId:mission.tools.find(t=>t.command===normalized)?.id,command:normalized});setCommand('')}
 return <div className="reading-width mission-workspace boss-workspace"><a className="back-link" href={campaign?'/campaigns/first-signal?view=full':'/bosses'}>← {campaign?'ملف First Signal':'التحقيقات المتقدمة'}</a><CompanyContext kind="boss" id={mission.id}/>{mission.id==='boss-002'&&<a className="ib-entry" href="/investigations/boss-boss-002">افتح خزانة الأدلة ولوحة العلاقات لهذا التحقيق ←</a>}<div className="page-heading"><div><div className="eyebrow">تحقيق متقدم</div><h1>{mission.title}</h1><p>{mission.description}</p></div></div>
 <section className="mission-brief boss-intro"><div><span className="eyebrow">INVESTIGATION BRIEF</span><p>{mission.scenario}</p><TaskBrief brief={missionBriefs[mission.id]}/><div className="mission-tags">{mission.requiredSkills.map(s=><span key={s}>{s}</span>)}</div></div><strong>+{mission.xpReward} XP</strong></section><div className="safe-banner"><ShieldCheck size={20}/><p>الأوامر والشبكات والسجلات محاكاة محلية داخل التطبيق. الأدلة والخطوات محفوظة لحسابك.</p></div>
 {!user?<div className="panel"><p>سجّل الدخول لبدء التحقيق والعودة إلى هذه الصفحة.</p><a className="primary-button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/bosses/'+mission.id+(campaign?'?campaign=first-signal':''))} target="_top">تسجيل الدخول</a></div>:loading?<p role="status">جارٍ استعادة التحقيق…</p>:error&&!state?<div className="panel" role="alert"><p>{error}</p><a href="/bosses">عرض متطلبات الفتح</a></div>:state&&<>
 <section className="panel mission-objectives"><div className="between"><h2>أهداف التحقيق</h2><strong>{state.progress}%</strong></div><div className="mission-meter" role="progressbar" aria-label="تقدم التحقيق" aria-valuenow={state.progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:state.progress+'%'}}/></div><ol>{mission.objectives.map(o=>{const done=objectiveDone(mission,session!,finished,o.id),unlocked=ready(o.id);return <li className={done?'done':''} key={o.id}>{done?'✓':unlocked?'○':'🔒'} {o.label}{!done&&!unlocked&&<small> · بعد الأهداف السابقة</small>}</li>})}</ol></section>
 {finished&&report?<section className="panel mission-result boss-report" aria-live="polite"><CheckCircle2 size={32}/><div className="eyebrow">تقرير التحقيق</div><h2>اكتمل التحقيق</h2><div className="mission-result-stats"><strong>{session!.lastResult!.stars} من 3 ★</strong><strong>نتيجة المحاولة {session!.lastResult!.score} من 100</strong><strong>أفضل نتيجة {state.score} من 100 · {state.stars} ★</strong><strong>{session!.lastResult!.xpGranted?'+'+mission.xpReward+' XP':'XP سبق منحها'}</strong></div><div className="boss-report-grid"><div><h3>الأهداف المكتملة</h3><ul>{report.objectives.map(o=><li key={o}>{o}</li>)}</ul></div><div><h3>الأدلة المكتشفة</h3><ul>{report.evidence.map(e=><li key={e}>{e}</li>)}</ul></div><div><h3>القرارات الصحيحة</h3><ul>{report.decisions.map(d=><li key={d}>{d}</li>)}</ul></div><div><h3>الأخطاء والتلميحات</h3><p>{report.hintsUsed} تلميحات · {report.mistakes.length} أخطاء</p><ul>{report.mistakes.map((m,i)=><li key={i}>{m}</li>)}</ul></div></div><h3>المهارات التي طورتها</h3><p>{mission.skillRewards.map(r=>skillName(r.skill)+' · '+r.points+' Skill XP').join(' · ')}{!session!.lastResult!.xpGranted&&' · مكافآتها الأساسية سُجلت سابقًا'}</p><h3>مهارات تحتاج ممارسة</h3><p>{report.skillsNeedingPractice.length?report.skillsNeedingPractice.join(' · '):'لم تُرصد أخطاء أو تلميحات في هذه المحاولة.'}</p><div className="button-row"><button className="secondary-button" type="button" disabled={busy} onClick={()=>void act({action:'replay'})}>إعادة التحقيق لتحسين النتيجة</button><a href={campaign?'/campaigns/first-signal?view=full':'/bosses'} className="primary-button">{campaign?'العودة للحملة':'العودة إلى المركز'}</a></div></section>:<>
 {mission.networkView&&<section className="panel boss-network"><h2>Network View · شبكة المكتب</h2><div className="boss-network-grid">{mission.networkView.map(node=><div key={node.id}><strong>{node.label}</strong><small>{node.description}</small></div>)}</div></section>}
 <div className="mission-layout"><section className="panel mission-evidence"><h2>ملف الأدلة</h2><p>افتح الأدلة وافحص الوقت والمصدر. لا يُعدّ الدليل مكتشفًا حتى تفتحه.</p>{mission.evidence.map(e=>{const o=objectiveFor('evidence',e.id),locked=!!o&&!ready(o.id);return <div className="mission-evidence-item" key={e.id}><button type="button" disabled={busy||locked} aria-expanded={opened===e.id} onClick={()=>{setOpened(e.id);void act({action:'inspect',evidenceId:e.id})}}>{e.title} <small>{e.occurredAt}</small> {session?.inspected.includes(e.id)?'✓':locked?'🔒':'←'}</button>{opened===e.id&&<pre dir="auto">{e.content}</pre>}</div>})}</section>
 <section className="panel mission-tools"><h2>أدوات التحقيق</h2><div className="terminal-title"><Terminal size={16}/> طرفية وتحليل محاكاة · الأوامر المدرجة فقط</div><div className="mission-tool-list">{mission.tools.map(t=>{const o=objectiveFor('tool',t.id);return <button type="button" key={t.id} disabled={busy||!!o&&!ready(o.id)} onClick={()=>void act({action:'tool',toolId:t.id,command:t.command})}>{t.command?<code dir="ltr">{t.command}</code>:t.label} {session?.usedTools.includes(t.id)?'✓':''}</button>})}</div>{mission.tools.some(t=>t.command)&&<form onSubmit={runCommand} className="mission-command"><label htmlFor="boss-command">أو اكتب أمرًا من القائمة</label><div><input id="boss-command" dir="ltr" value={command} maxLength={120} autoComplete="off" onChange={e=>setCommand(e.target.value)} placeholder="command"/><button type="submit" disabled={busy||!command.trim()}>تشغيل</button></div></form>}<div className="mission-transcript" aria-live="polite">{session?.transcript.length?session.transcript.map((line,i)=><div key={i}><span dir="auto">$ {line.input}</span><pre dir="auto">{line.output}</pre></div>):<p>ستظهر نتائج الفحص هنا.</p>}</div></section></div>
 <section className="panel boss-timeline"><h2>Investigation Timeline · التسلسل الزمني</h2><p>تظهر أوقات وقوع الأدلة داخل الحادث بعد فحصها، ثم خطوات تحقيقك المحفوظة على الحساب.</p><h3>تسلسل الحادث</h3>{session?.inspected.length?<ol>{mission.evidence.filter(e=>session.inspected.includes(e.id)&&e.occurredAt).sort((a,b)=>a.occurredAt!.localeCompare(b.occurredAt!)).map(e=><li key={e.id}><time>{e.occurredAt}</time><span>{e.title}</span><small>دليل</small></li>)}</ol>:<p>افتح دليلًا ليظهر وقته في تسلسل الحادث.</p>}<h3>سجل التحقيق</h3>{session?.timeline.length?<ol>{session.timeline.map((event,i)=><li key={i}><time>{new Date(event.at).toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}</time><span>{event.label}</span><small>{event.kind}</small></li>)}</ol>:<p>لم تُسجل خطوات بعد.</p>}</section>
 <section className="panel boss-decisions"><h2>قرارات الاستجابة</h2><p>اكتب الإجراء المناسب وفق الأدلة. تُحفظ القرارات الصحيحة وتؤثر القرارات المبكرة والخاطئة في التقييم.</p>{mission.decisions?.map(d=>{const o=objectiveFor('decision',d.id),locked=!!o&&!ready(o.id),done=session?.decisions.includes(d.id);return <form key={d.id} onSubmit={e=>{e.preventDefault();void act({action:'decide',decisionId:d.id,response:responses[d.id]})}}><h3>{done?'✓ ':''}{d.label}</h3><label>{d.prompt}<input dir="auto" value={responses[d.id]||''} onChange={e=>setResponses(p=>({...p,[d.id]:e.target.value}))} disabled={busy||locked||done} maxLength={200} required placeholder={locked?'استكمل أهداف التحقيق السابقة':'اكتب القرار هنا'}/></label><button type="submit" className="secondary-button" disabled={busy||locked||done||!responses[d.id]?.trim()}>{done?'سُجل القرار':'تسجيل القرار'}</button></form>})}</section>
 <section className="panel mission-hints"><div className="between"><h2><Lightbulb size={18}/> التلميحات</h2><button className="secondary-button" type="button" disabled={busy||session!.hintsUsed>=mission.hints.length} onClick={()=>void act({action:'hint'})}>طلب تلميح ({session!.hintsUsed} من {mission.hints.length})</button></div>{mission.hints.slice(0,session!.hintsUsed).map((h,i)=><p key={i}>{i+1}. {h}</p>)}</section>
 <form className="panel mission-solve" onSubmit={e=>{e.preventDefault();void act({action:'solve',answers})}}><h2>الاستنتاج النهائي</h2><p>التقرير يربط ما حدث بالأدلة والقرارات. أكمل الأهداف أولًا.</p><div className="mission-fields">{mission.answerFields.map(f=><label key={f.id}>{f.label}<input dir="auto" value={answers[f.id]||''} onChange={e=>setAnswers(a=>({...a,[f.id]:e.target.value}))} placeholder={f.placeholder} required maxLength={160}/></label>)}</div><button className="primary-button" type="submit" disabled={busy||!ready(mission.objectives.find(o=>o.kind==='solve')?.id||'')}>إرسال تقرير التحقيق</button></form>
 </>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="mission-message">{message}</p>}</>}
 <LabBridge missionId={mission.id}/><div className="mission-related"><h2>دروس مرتبطة</h2>{mission.relatedLessons.map(id=><a key={id} href={'/learn/'+id}>{id} ←</a>)}</div></div>
}
