'use client';
import {CompletionProgressSummary} from '@/app/progression/view';
/* eslint-disable @next/next/no-html-link-for-pages */
import {useEffect,useState} from 'react';
import {ArrowRight,ShieldCheck,Lightbulb,Terminal,CheckCircle2} from 'lucide-react';
import {useProgress} from '@/app/shell';
import type {Mission} from '@/lib/missions';
import {skillName} from '@/lib/skill-catalog';
import LabBridge from '@/app/labs/v2/lab-bridge';
import CompanyContext from '@/components/company-context';
import TaskBrief from '@/components/task-brief';
import {missionBriefs} from '@/lib/practical-training';
import type {MissionAction,MissionSession} from '@/lib/mission-engine';
type State={id:string;startedAt:string;updatedAt:string;completedAt:string|null;score:number;stars:number;hintsUsed:number;attempts:number;session:MissionSession;progress:number};
export default function MissionWorkspace({mission,campaign=false}:{mission:Mission;campaign?:boolean}){
 const {user,refresh}=useProgress(),[state,setState]=useState<State|null>(null),[loading,setLoading]=useState(!!user),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[openEvidence,setOpenEvidence]=useState(''),[command,setCommand]=useState(''),[answers,setAnswers]=useState<Record<string,string>>({});
 useEffect(()=>{if(!user)return;let active=true;fetch('/api/missions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:mission.id,action:'start'})}).then(async r=>{const data=await r.json() as {error?:string;state:State};if(!r.ok)throw Error(data.error||'تعذر بدء المهمة.');if(active)setState(data.state)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[user,mission.id]);
 async function act(action:Omit<MissionAction,'id'>){if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/missions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:mission.id,...action})});const data=await r.json() as {error?:string;state:State;message:string};if(!r.ok)throw Error(data.error||'تعذر حفظ الخطوة.');setState(data.state);setMessage(data.message);if(action.action==='solve'&&data.state.session.lastResult)await refresh();if(action.action==='replay'){setAnswers({});setOpenEvidence('');setCommand('')}}catch(e){setError(e instanceof Error?e.message:'تعذر الاتصال.')}finally{setBusy(false)}}
 const session=state?.session,finished=!!state?.completedAt&&!session?.replaying;
 function runCommand(e:React.FormEvent){e.preventDefault();const normalized=command.trim().replace(/\s+/g,' ');if(!normalized)return;const tool=mission.tools.find(t=>t.command===normalized);void act({action:'tool',toolId:tool?.id,command:normalized});setCommand('')}
 return <div className="reading-width mission-workspace"><a className="back-link" href={campaign?'/campaigns/first-signal?view=full':'/missions'}><ArrowRight size={17}/>{campaign?'العودة لملف First Signal':'مركز المهمات'}</a><div className="page-heading"><div><div className="eyebrow">MISSION {mission.id} / {mission.difficulty}</div><h1>{mission.title}</h1><p>{mission.description}</p></div></div>
 {mission.id==='003'&&!campaign&&<div className="pilot-return"><span>حقق في هذه الرسالة خطوة بخطوة مع نفس التقدم المحفوظ.</span><a href="/experience/nexacorp-email">افتح التحقيق الموجّه</a></div>}<CompanyContext kind="mission" id={mission.id}/><div className="mission-brief"><div><span className="eyebrow">THE BRIEF</span><p>{mission.scenario}</p><TaskBrief brief={missionBriefs[mission.id]}/><div className="mission-tags">{mission.requiredSkills.map(s=><span key={s}>{s}</span>)}</div></div><strong>+{mission.xpReward} XP</strong></div>
 <div className="safe-banner"><ShieldCheck size={20}/><p>جميع الأوامر والسجلات والروابط تمثيلية داخل التطبيق. لا يوجد اتصال بنظام تشغيل أو شبكة حقيقية.</p></div>
 {!user?<div className="panel mission-empty"><p>سجّل الدخول لبدء المهمة وحفظ خطوات التحقيق.</p><a className="primary-button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/missions/'+mission.id+(campaign?'?campaign=first-signal':''))} target="_top">تسجيل الدخول والعودة لهذه المهمة</a></div>:loading?<p role="status">جارٍ استعادة المهمة…</p>:error&&!state?<div role="alert" className="error">{error}<button type="button" onClick={()=>location.reload()}>إعادة المحاولة</button></div>:state&&<>
 <section className="panel mission-objectives"><div className="between"><h2>خطوات التحقيق</h2><span>{state.progress}%</span></div><div className="mission-meter" role="progressbar" aria-label="تقدم المهمة" aria-valuenow={state.progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:state.progress+'%'}}/></div><ol>{mission.objectives.map(o=>{const done=o.kind==='solve'?finished:o.kind==='tool'?session?.usedTools.includes(o.target):session?.inspected.includes(o.target);return <li key={o.id} className={done?'done':''}>{done?'✓':'○'} {o.label}</li>})}</ol></section>
 {session?.lastResult&&!session.replaying?<section className="panel mission-result" aria-live="polite"><CheckCircle2 size={28}/><div className="eyebrow">مهمة مكتملة</div><h2>أُنجزت المهمة</h2><div className="mission-result-stats"><strong>{session.lastResult.stars} من 3 ★</strong><strong>{session.lastResult.score} من 100</strong><strong>{session.lastResult.xpGranted?'+'+mission.xpReward+' XP':'XP سبق منحها'}</strong></div><h3>{session.lastResult.xpGranted?'مهارات تحسنت':'مهارات سبق احتسابها'}</h3><p>{mission.skillRewards.map(s=>skillName(s.skill)+(session.lastResult?.xpGranted?' +':' · ')+s.points+' Skill XP').join(' · ')}</p><CompletionProgressSummary/><h3>مراجعة المحاولة</h3><p>التلميحات المستخدمة: {session.lastResult.hintsUsed} · الأخطاء: {session.lastResult.mistakes.length}</p>{session.lastResult.mistakes.length>0&&<ul>{session.lastResult.mistakes.map((m,i)=><li key={i}>{m}</li>)}</ul>}<div className="button-row"><button type="button" className="secondary-button" disabled={busy} onClick={()=>void act({action:'replay'})}>إعادة المهمة دون XP إضافية</button><a className="primary-button" href={campaign?'/campaigns/first-signal?view=full':'/missions'}>{campaign?'العودة للحملة':'العودة للمركز'}</a></div></section>:<>
 <div className="mission-layout"><section className="panel mission-evidence"><h2>الأدلة</h2><p>افتح العناصر لفحص تفاصيلها. تُحفظ الأدلة التي فحصتها.</p>{mission.evidence.map(e=><div className="mission-evidence-item" key={e.id}><button type="button" disabled={busy} aria-expanded={openEvidence===e.id} onClick={()=>{setOpenEvidence(e.id);void act({action:'inspect',evidenceId:e.id})}}>{e.title} {session?.inspected.includes(e.id)?'✓':'←'}</button>{openEvidence===e.id&&<pre dir="auto">{e.content}</pre>}</div>)}</section>
 <section className="panel mission-tools"><h2>أدوات التحقيق</h2>{mission.tools.some(t=>t.command)?<><div className="terminal-title"><Terminal size={16}/> طرفية محاكاة · الأوامر المتاحة فقط</div><div className="mission-tool-list">{mission.tools.filter(t=>t.command).map(t=><button type="button" key={t.id} disabled={busy} onClick={()=>void act({action:'tool',toolId:t.id,command:t.command})}><code dir="ltr">{t.command}</code>{session?.usedTools.includes(t.id)?' ✓':''}</button>)}</div><form onSubmit={runCommand} className="mission-command"><label htmlFor="mission-command">اكتب أمرًا من القائمة</label><div><input id="mission-command" dir="ltr" value={command} onChange={e=>setCommand(e.target.value)} maxLength={120} placeholder="command" autoComplete="off"/><button type="submit" disabled={busy||!command.trim()}>تشغيل</button></div></form></>:<div className="mission-tool-list">{mission.tools.map(t=><button type="button" key={t.id} disabled={busy} onClick={()=>void act({action:'tool',toolId:t.id})}>{t.label}{session?.usedTools.includes(t.id)?' ✓':''}</button>)}</div>}
 <div className="mission-transcript" aria-label="نتائج أدوات المحاكاة" aria-live="polite">{session?.transcript.length?session.transcript.map((line,i)=><div key={i}><span dir="auto">$ {line.input}</span><pre dir="auto">{line.output}</pre></div>):<p>ستظهر نتائج الأدوات هنا بعد استخدامها.</p>}</div></section></div>
 <section className="panel mission-hints"><div className="between"><h2><Lightbulb size={18}/> التلميحات</h2><button type="button" className="secondary-button" disabled={busy||!!session&&session.hintsUsed>=mission.hints.length} onClick={()=>void act({action:'hint'})}>طلب تلميح ({session?.hintsUsed||0} من {mission.hints.length})</button></div>{mission.hints.slice(0,session?.hintsUsed||0).map((h,i)=><p key={i}>{i+1}. {h}</p>)}</section>
 <form className="panel mission-solve" onSubmit={e=>{e.preventDefault();void act({action:'solve',answers})}}><h2>قدّم حلّك</h2><p>اكتب ما استنتجته من الأدلة والتجارب. لا تُقبل الإجابة قبل استكمال التحقيق.</p><div className="mission-fields">{mission.answerFields.map(f=><label key={f.id}>{f.label}<input value={answers[f.id]||''} onChange={e=>setAnswers(a=>({...a,[f.id]:e.target.value}))} placeholder={f.placeholder} maxLength={160} required dir="auto"/></label>)}</div><button className="primary-button" type="submit" disabled={busy}>تحقق من الحل واحفظ النتيجة</button></form>
 </>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status" className="mission-message">{message}</p>}</>}
 <LabBridge missionId={mission.id}/><div className="mission-related"><h2>دروس تساعدك</h2>{mission.relatedLessons.map(id=><a href={'/learn/'+id} key={id}>{id} ←</a>)}</div></div>;
}
