'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,Search,Radio,GitBranch,Mail,ScanLine,Layers,Target,Flag,BookOpen,LockKeyhole,Check,ChevronLeft} from 'lucide-react';
import Link from '@/components/native-link';
import LoadingState from '@/components/loading-state';
import {useProgress} from '@/app/shell';
import {clientJson} from '@/lib/client-json';
import {RankEmblem} from '@/app/rank/experience';
import {rankTitles,skillTitles,levelPath,points,progressionCopy,type AchievementState,type ProgressionData} from '@/lib/progression';

export function useProgression(){const {user,loading,items,learning}=useProgress(),[data,setData]=useState<ProgressionData|null>(null),[owner,setOwner]=useState(''),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;const controller=new AbortController();setData(null);setError('');if(!user||loading)return;clientJson<ProgressionData>('/api/progression',{signal:controller.signal},{message:'تعذر استعادة المستوى والإنجازات. أعد المحاولة.'}).then(d=>{if(!d||!Array.isArray(d.mastery)||!Array.isArray(d.achievements)||!d.goal||!d.career||!Number.isFinite(d.xp))throw Error('تعذر قراءة بيانات المستوى والإنجازات. أعد المحاولة.');if(live){setOwner(user.email);setData(d)}}).catch(e=>{if(live)setError(e instanceof Error?e.message:'تعذر استعادة التقدم.')});return()=>{live=false;controller.abort()}},[user,loading,items,learning,revision]);return {data:user&&owner===user.email?data:null,error,guest:!user,retry:()=>setRevision(r=>r+1)};}
export function ProgressionState({api}:{api:ReturnType<typeof useProgression>}){return api.guest?<div className="empty-state"><h2>تقدمك يبدأ من أول قضية</h2><a className="primary-button" href="/signin-with-chatgpt?return_to=%2Fprogress" target="_top">سجّل الدخول لحفظ تقدمك</a></div>:api.error?<div className="empty-state" role="alert"><p>{api.error}</p><button className="secondary-button" onClick={api.retry}>أعد المحاولة</button></div>:<LoadingState>جارٍ استعادة المستوى والإنجازات المحفوظة…</LoadingState>}
export function LevelProgressPath({xp,compact=false}:{xp:number;compact?:boolean}){const r=levelPath(xp);return <section className={'level-path '+(compact?'compact':'')} aria-label="مسار المستوى"><div className="level-path-head"><div><span className="eyebrow">تقدمك العام</span><h2>المستوى <b>{r.level}</b></h2><p>رتبة <strong>{rankTitles[r.tier.id]}</strong></p></div><RankEmblem tier={r.tier} size={compact?'medium':'large'}/></div><div className="level-balance"><span>رصيد الخبرة <b><bdi>{r.xp.toLocaleString('ar')}</bdi> نقطة</b></span><span>المستوى التالي <b>{r.nextLevel}</b></span></div><div className="level-meter" role="progressbar" aria-label="التقدم للمستوى التالي" aria-valuenow={r.within} aria-valuemin={0} aria-valuemax={200}><span style={{width:r.percent+'%'}}/></div><div className="level-progress-copy"><span>{r.within} من {r.required} نقطة · <bdi dir="ltr">{r.percent}%</bdi></span><strong>بقي {points(r.toNext)}</strong></div>{!compact&&<><ol className="level-stations" aria-label="مستويات ومحطات قريبة">{r.path.map(p=><li key={p.level} aria-current={p.current?'step':undefined} className={p.current?'current':p.level<r.level?'passed':p.milestone?'milestone':''}><span>{p.milestone?<Flag size={14}/>:null}<b>{p.level}</b></span><small>{p.current?'أنت هنا':p.milestone?rankTitles[p.milestone.id]:p.level<r.level?'أكملته':'التالي'}</small></li>)}</ol><details className="progression-details"><summary>{r.next?'المحطة التالية · '+rankTitles[r.next.id]:'ماذا تعني هذه الأرقام؟'}</summary><p>{r.next?`رتبة ${rankTitles[r.next.id]} تبدأ عند المستوى ${r.next.minLevel}. بقي ${r.remaining} نقطة لهذه المحطة.`:'بلغت أعلى رتبة بصرية حالية، ويمكنك مواصلة رفع مستواك وإتقانك.'}</p><p>فتح المحتوى المتقدم يعتمد على متطلبات التعلم، لا على النقاط وحدها.</p><Link href="/roadmap">اعرض متطلبات المحتوى القادم <ChevronLeft size={15}/></Link></details></>}</section>}
export function NextGoal({data}:{data:ProgressionData}){return <section className="progression-goal" aria-label="هدفك التالي"><span className="eyebrow">هدفك التالي</span><h2>{data.goal.title}</h2><p>{progressionCopy(data.goal.detail)}</p><Link href={data.goal.href} className="primary-button">{data.goal.action}<ChevronLeft size={17}/></Link></section>}
const badgeIcons={mission:ShieldCheck,investigation:Search,soc:Radio,correlation:GitBranch,phishing:Mail,offensive:ScanLine,chain:Layers,mastery:Target,level:Flag,legacy:BookOpen};
export function AchievementBadge({achievement:a}:{achievement:AchievementState}){const Icon=badgeIcons[a.icon];return <span className={'achievement-insignia '+(a.earnedTier?'earned':'')+' tier-'+Math.min(a.earnedTier,3)} aria-hidden="true"><Icon size={25} strokeWidth={1.5}/>{a.earnedTier>0&&<span className="badge-cert"><Check size={11}/></span>}</span>}
export function AchievementCard({achievement:a}:{achievement:AchievementState}){const tierNames=a.thresholds.length===3?['برونزي','فضي','ذهبي']:a.id==='level-milestone'?a.thresholds.map(n=>'المستوى '+n):a.thresholds.map((_,i)=>'المرحلة '+(i+1));return <article className={'achievement-card '+a.state}><div className="achievement-card-head"><AchievementBadge achievement={a}/><span className="achievement-state">{a.earnedTier?<><Check size={14}/> تم تحقيقه{a.thresholds.length>1?' · '+tierNames[a.earnedTier-1]:''}</>:a.value>0?'قيد التقدم':<><LockKeyhole size={14}/> لم يُحقق بعد</>}</span></div><h3>{a.title}</h3><p>{a.description}</p><div className="achievement-count"><strong>{Math.min(a.value,a.target)} من {a.target}</strong><span>{a.complete?'اكتملت جميع المراحل':a.earnedTier?'نحو المرحلة التالية':'نحو تحقيق الإنجاز'}</span></div><div className="level-meter" role="progressbar" aria-label={'التقدم في '+a.title} aria-valuemin={0} aria-valuemax={a.target} aria-valuenow={Math.min(a.value,a.target)}><span style={{width:a.percent+'%'}}/></div>{a.earnedAt&&<small>محفوظ في سجلك · {new Date(a.earnedAt).toLocaleDateString('ar',{year:'numeric',month:'short',day:'numeric'})}</small>}</article>}
export function AchievementOverview({data}:{data:ProgressionData}){const all=data.achievements.filter(a=>!a.legacy),earned=all.filter(a=>a.earnedTier>0),complete=earned.filter(a=>a.complete),developing=earned.length-complete.length;return <p className="progression-muted">حققت {earned.length} من {all.length} إنجازات أمنية.{earned.length>0&&<> {complete.length} مكتملة بجميع مراحلها{developing>0?`، و${developing} قابلة للتطوير.`:'.'}</>} الإنجازات لا تضيف نقاط خبرة.</p>}
export function AchievementPreview({data}:{data:ProgressionData}){const meaningful=data.achievements.filter(a=>!a.legacy),next=meaningful.find(a=>!a.complete&&a.value>0)||meaningful.find(a=>!a.complete),recent=meaningful.filter(a=>a.earnedTier&&a.id!==next?.id).sort((a,b)=>(b.earnedAt||'').localeCompare(a.earnedAt||''))[0];return <section className="progression-achievement-preview"><div className="between"><h2>إنجازاتك والخطوة القادمة</h2><Link href="/achievements">مركز الإنجازات <ChevronLeft size={16}/></Link></div><div className="achievement-preview-grid">{recent&&<div><p className="achievement-preview-label">من إنجازاتك المحققة</p><AchievementCard achievement={recent}/></div>}{next&&<div><p className="achievement-preview-label">إنجازك القادم{next.earnedTier?' · المرحلة التالية':''}</p><AchievementCard achievement={next}/></div>}</div><AchievementOverview data={data}/></section>}
export function ProgressionCompact({xp}:{xp:number}){return <div className="progression-compact"><LevelProgressPath xp={xp} compact/><Link href="/progress">المستوى والإنجازات والهدف التالي <ChevronLeft size={16}/></Link></div>}
export function CompletionProgressSummary({achievementId}:{achievementId?:string}){const api=useProgression();if(api.guest)return null;return <details className="progression-completion"><summary>{api.data?`تقدمك محفوظ · المستوى ${api.data.level.level} · إنجازاتك ومهاراتك`:'أثر هذه الخطوة على تقدمك'}</summary>{!api.data?<ProgressionState api={api}/>:<><LevelProgressPath xp={api.data.xp} compact/><p>الإنجازات لا تضيف نقاطًا، وإعادة النشاط لا تكرر مكافأة الإكمال.</p><div className="completion-achievements">{api.data.achievements.filter(a=>!a.legacy&&a.earnedTier).sort((a,b)=>Number(b.id===achievementId)-Number(a.id===achievementId)).slice(0,3).map(a=><span key={a.id}><AchievementBadge achievement={a}/>{a.title} · محفوظ</span>)}</div><details className="progression-details"><summary>المهارات والإتقان والجاهزية</summary><p>نقاط المهارة تسجل الممارسة؛ الإتقان يقيس الأداء عبر أدلة متعددة.</p><ul>{api.data.mastery.filter(s=>s.xp>0||s.samples>0).map(s=><li key={s.id}>{skillTitles[s.id]} · {s.xp} نقطة مهارة · {s.mastery===null?'إتقان لم يُقيّم بعد':'إتقان '+s.mastery+'%'}</li>)}</ul><p>مرحلتك المهنية: {api.data.career.title}.</p></details><Link href="/progress">راجع تقدمك والهدف التالي <ChevronLeft size={16}/></Link></>}</details>}
