'use client';
import {useState} from 'react';
import Link from '@/components/native-link';
import {ShieldCheck,Terminal} from 'lucide-react';
import {challenges} from '@/lib/extra-labs';
import {useProgress} from '@/app/shell';
export default function Challenge({id,backHref="/labs",backLabel="المختبرات"}:{id:string;backHref?:string;backLabel?:string}){const lab=challenges.find(c=>c.id===id)!;const [answer,setAnswer]=useState<number|null>(null),[result,setResult]=useState<{passed:boolean;message:string;guest:boolean}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const [command,setCommand]=useState(''),[cwd,setCwd]=useState('/home/student'),[terminal,setTerminal]=useState<string[]>(['مرحبًا في الطرفية التدريبية. اكتب help.']);const {refresh}=useProgress();function run(){const c=command.trim();let output='أمر غير متاح في هذه المحاكاة. اكتب help.';if(c==='help')output='pwd | ls | cd logs | cat incident.log | help';else if(c==='pwd')output=cwd;else if(c==='ls')output=cwd==='/home/student'?'logs  README.txt':'incident.log';else if(c==='cd logs'){setCwd('/home/student/logs');output='انتقلت إلى /home/student/logs'}else if(c==='cat incident.log')output=cwd.endsWith('/logs')?'08:10 fail\n08:11 fail\n08:12 success':'انتقل أولًا إلى logs';setTerminal(v=>[...v,'$ '+c,output].slice(-14));setCommand('')}
 async function submit(){setBusy(true);setError('');try{const r=await fetch('/api/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'lab',id,input:{answer}})});const d=await r.json() as {passed:boolean;message:string;guest:boolean;error?:string};if(!r.ok)throw Error(d.error);setResult(d);await refresh()}catch(e){setError(e instanceof Error?e.message:'تعذر التحقق.')}finally{setBusy(false)}}
 return <div className="reading-width"><Link className="back-link" href={backHref}>← {backLabel}</Link><div className="page-heading"><div><div className="eyebrow">{lab.tag} / SAFE LAB</div><h1>{lab.title}</h1><p>{lab.description}</p></div></div><div className="safe-banner"><ShieldCheck size={20}/><p>محاكاة على بيانات اصطناعية داخل المنصة؛ لا اتصال بأجهزة أو خدمات حقيقية.</p></div><section className="panel lab-panel"><h2>المشهد التدريبي</h2><pre className="scenario" dir="auto">{lab.scenario}</pre>{id==='terminal'&&<div className="terminal-box"><div><Terminal size={16}/> طرفية افتراضية</div><pre dir="ltr">{terminal.join('\n')}</pre><form onSubmit={e=>{e.preventDefault();run()}}><label htmlFor="command">أمر التدريب</label><input id="command" dir="ltr" value={command} onChange={e=>setCommand(e.target.value)} placeholder="help" maxLength={60}/><button type="submit" className="secondary-button">نفذ في المحاكاة</button></form></div>}<h3>{lab.prompt}</h3>{lab.options.map((o,i)=><label className={'answer-option '+(result&&i===lab.answer?'correct':'')} key={i}><input type="radio" name="lab-answer" checked={answer===i} onChange={()=>{setAnswer(i);setResult(null)}}/>{o}</label>)}{answer===null&&<p className="muted" id="answer-help">اختر إجابة لتفعيل التحقق.</p>}<button className="primary-button" aria-describedby={answer===null?'answer-help':undefined} disabled={answer===null||busy} onClick={()=>void submit()}>{busy?'جارٍ التحقق…':'تحقق من الحل'}</button>{error&&<p className="error" role="alert">{error}</p>}{result&&<div className="result-panel" aria-live="polite"><h2>{result.passed?'أنجزت المختبر':'حاول مرة أخرى'}</h2><p>{result.message}</p><p>{result.guest?'سجّل الدخول ثم أعد الحل لحفظ الإنجاز.':result.passed?'حُفظ الإنجاز واحتسبت نقاطه مرة واحدة.':'راجع المشهد وعدّل اختيارك.'}</p>{result.guest&&<a className="secondary-button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/labs/'+id+'?start=1')} target="_top">تسجيل الدخول لحفظ التقدم</a>}<Link className="secondary-button" href={backHref}>{backLabel} ←</Link></div>}</section></div>}
