'use client';
import {useEffect,useState} from 'react';
import {useProgress} from '@/app/shell';
import {offensiveOrder,minimumHref,offensiveTrackHref} from '@/lib/offensive-minimum';
type Lab={id:string;title:string;state:{completedAt:string|null}|null;access:{locked:boolean;met:number;total:number;reasons:string[]}|null};
const descriptions=['اعرف ما يوجد وما يستحق التحقق؛ الخدمة ليست ثغرة بمجرد وجودها.','اختبر هل يقرأ الحساب الموارد التي يحق له الوصول إليها فقط.','قارِن الهوية والجلسة والتفويض، ثم اختبر انتهاء الثقة وأعد اختبار المعالجة.'];
export default function OffensiveMinimumTrack(){const {user}=useProgress(),[labs,setLabs]=useState<Lab[]|null>(null),[error,setError]=useState('');useEffect(()=>{let live=true;fetch('/api/interactive-labs',{cache:'no-store'}).then(async r=>{const d=await r.json() as {labs:Lab[];error?:string};if(!r.ok)throw Error(d.error||'تعذر استعادة المسار.');if(live)setLabs(d.labs)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[user]);
 const ordered=offensiveOrder.map(id=>labs?.find(l=>l.id===id)),done=ordered.filter(l=>l?.state?.completedAt).length,next=ordered.find(l=>l&&!l.state?.completedAt),allDone=done===3;
 return <div className="pilot-experience assessment offensive-track" dir="rtl"><a className="back-link" href="/labs">المختبرات</a><header className="assessment-header"><span className="eyebrow">NexaCorp · تدريب أمني مصرح به</span><h1>أساسيات التقييم الهجومي</h1><p>ثلاث تجارب فقط: استكشف، اختبر بالأدلة، وافهم الأثر ثم تحقق من المعالجة. جميعها محاكاة معزولة ببيانات محددة.</p></header>{error?<div role="alert"><p>{error}</p><button className="primary-button" onClick={()=>location.reload()}>إعادة المحاولة</button></div>:!labs?<p role="status">جارٍ استعادة المسار…</p>:<><p>{done} من 3 تجارب مكتملة</p><ol className="offensive-track-list">{ordered.map((lab,i)=>lab&&<li key={lab.id}><h2>{i+1} — {lab.title}</h2><p>{descriptions[i]}</p><p>{lab.state?.completedAt?'مكتمل':lab.access?.locked?'مقفل · '+lab.access.met+' من '+lab.access.total+' متطلبات مكتملة':'متاح الآن'}</p>{lab.access?.locked&&<p>{lab.access.reasons.join(' · ')}</p>}<a className="assessment-secondary" href={minimumHref(lab.id)+(lab.id==='v2-access-control'?'?track=offensive':'')}>{lab.access?.locked?'عرض متطلبات الفتح':lab.state?.completedAt?'راجع التقييم المكتمل':'عرض التقييم'}</a></li>)}</ol>{!user?<a className="primary-button" href={'/signin-with-chatgpt?return_to='+encodeURIComponent(offensiveTrackHref)} target="_top">سجّل الدخول لحفظ التقييم</a>:allDone?<section className="panel"><span className="eyebrow" dir="ltr">Offensive Foundations Completed</span><h2>أكملت أساسيات التقييم الهجومي</h2><p>مارست فهم النطاق، الاستكشاف، بناء الفرضيات، اختبارًا مبنيًا على الأدلة، تقدير الأثر، المعالجة وإعادة الاختبار.</p><p>هذا إنجاز تأسيسي؛ ليس شهادة أو ادعاء جاهزية للعمل كمختبر اختراق. لا توجد مكافأة إضافية لجمع التجارب الثلاث.</p><a className="primary-button" href="/progress">راجع تقدمك</a></section>:next&&<a className="primary-button" href={minimumHref(next.id)+(next.id==='v2-access-control'?'?track=offensive':'')}>{next.access?.locked?'خطوتك التالية: عرض متطلبات الفتح':'تابع التقييم التالي'}</a>}<p>ترتيب التدريب مقترح. يظل Access Control السابق متاحًا بشروطه الأصلية؛ تقييم الجلسة يتطلب إكمال التجربتين.</p></>}</div>;
}
